function ED1_OutcomeFreeBoundary_v9(outputDir, repoRoot)
% ED1_OUTCOMEFREEBOUNDARY_V9
%
% Extended Data Figure 1
% Developmental falsification of universal outcome-free evaluation
%
% Scientific role after main-figure reorganization:
%
%   Main Fig. 3  IDENTIFY  -> constructive observability witness
%   Main Fig. 4  REUSE     -> frozen admissibility evidence
%   Main Fig. 5  PRESERVE  -> adaptive composability
%
% ED1 therefore retains only the developmental evidence showing why a
% universal outcome-free route was insufficient:
%
%   A  No universal outcome-free dominance
%   B  Late advantage is target-specific
%   C  Evidence expiry is target-specific
%   D  Outcome auditing restores statistical contraction
%   E  Developmental mismatch signal regulates historical reuse
%
% U11 is intentionally NOT redrawn here because it is now Main Figure 3.
%
% Usage:
%
%   ED1_OutcomeFreeBoundary_v9
%
% or
%
%   ED1_OutcomeFreeBoundary_v9([], ...
%
% -------------------------------------------------------------------------

close all;

%% ========================================================================
% 0) STYLE
% ========================================================================

FONT = 'Arial';

FS_LETTER = 18;
FS_TITLE  = 12;
FS_AXIS   = 10;
FS_TICK   = 10;
FS_SMALL  = 10;
FS_TINY   = 10;

navy   = [0.03 0.27 0.67];
blue   = [0.02 0.33 0.78];
green  = [0.05 0.50 0.20];
orange = [0.93 0.43 0.05];
purple = [0.53 0.22 0.72];
red    = [0.84 0.10 0.08];

grey   = [0.45 0.45 0.45];
dgrey  = [0.20 0.20 0.20];
black  = [0 0 0];

panelBlue   = local_mix(blue,  [1 1 1],0.79);
panelGreen  = local_mix(green, [1 1 1],0.81);
panelOrange = local_mix(orange,[1 1 1],0.82);
panelPurple = local_mix(purple,[1 1 1],0.82);

%% ========================================================================
% 1) PATHS
% ========================================================================

thisFile = mfilename('fullpath');

if isempty(thisFile)
    scriptDir = pwd;
else
    scriptDir = fileparts(thisFile);
end

if nargin < 2 || isempty(repoRoot)
    repoRoot = fileparts(fileparts(scriptDir));
end

assert(isfolder(fullfile(repoRoot,'source_data')), ...
    'Reviewer repository root is invalid.');

if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(scriptDir,'output');
end

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

fprintf('\n============================================================\n');
fprintf(' CMDO EXTENDED DATA FIGURE 1\n');
fprintf(' Developmental falsification of universal outcome-free evaluation\n');
fprintf('============================================================\n');
fprintf('Repository : %s\n',repoRoot);
fprintf('Output     : %s\n',outputDir);

%% ========================================================================
% 2) LOAD FROZEN DEVELOPMENTAL DATA
% ========================================================================

DATA_DIR = fullfile(repoRoot,'source_data','submission_frozen');
CACHE_DIR = fullfile(tempdir,'CMDO_submission_cache','ED1');

assert(isfolder(DATA_DIR), ...
    'Tracked submission_frozen directory is missing.');

if ~exist(CACHE_DIR,'dir')
    mkdir(CACHE_DIR);
end

U4C = local_load_u4c(DATA_DIR,CACHE_DIR);
U5B = local_load_u5b(DATA_DIR,CACHE_DIR);

fprintf('\nFrozen developmental data\n');
fprintf('U4C targets        = %d\n',numel(U4C.targets));
fprintf('U4C budgets        = %d\n',numel(U4C.budgets));
fprintf('Late rule better   = %d/%d\n', ...
    U4C.nRuleBetterLate,numel(U4C.rootLate));
fprintf('Late root better   = %d/%d\n', ...
    U4C.nRootBetterLate,numel(U4C.rootLate));
fprintf('U5B reuse states   = %d\n',numel(U5B.bias2));

%% ========================================================================
% 3) BASIC AUDIT QUANTITIES
% ========================================================================

finiteDelta = U4C.deltaMat(isfinite(U4C.deltaMat));

if isempty(finiteDelta)
    error('No finite U4C delta-MAE values found.');
end

nUniversalBetter = nnz(finiteDelta < 0);
nRootBetter      = nnz(finiteDelta > 0);
nTies            = nnz(finiteDelta == 0);

rhoBiasWeight = local_spearman(U5B.bias2,U5B.weight);

fprintf('\nDevelopmental diagnostics\n');
fprintf('Universal-rule better cells = %d\n',nUniversalBetter);
fprintf('Root-budget better cells    = %d\n',nRootBetter);
fprintf('Exact ties                  = %d\n',nTies);
fprintf('Sentinel mismatch / borrowing rho = %.6f\n',rhoBiasWeight);

%% ========================================================================
% 4) FIGURE CANVAS
% ========================================================================

fig = figure( ...
    'Color','w', ...
    'Position',[50 30 1280 900], ...
    'Renderer','painters', ...
    'Name','CMDO Extended Data Figure 1', ...
    'NumberTitle','off');

% -------------------------------------------------------------------------
% Layout
%
%   A : large heatmap
%   B : late-budget comparison
%   C : expiry
%
%   D : statistical contraction after outcomes
%   E : mismatch-gated reuse
% -------------------------------------------------------------------------

PA = [0.025 0.525 0.455 0.440];
PB = [0.505 0.525 0.225 0.440];
PC = [0.750 0.525 0.225 0.440];

PD = [0.025 0.055 0.455 0.420];
PE = [0.505 0.055 0.470 0.420];

%% ========================================================================
% PANEL A
% NO UNIVERSAL OUTCOME-FREE DOMINANCE
% ========================================================================

axA0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PA);

axis(axA0,[0 1 0 1]);
axis(axA0,'off');
hold(axA0,'on');

local_panel_border( ...
    axA0,[0.004 0.005 0.992 0.985], ...
    panelBlue,1.0);

local_panel_header( ...
    axA0, ...
    'A', ...
    'No universal outcome-free dominance', ...
    0.020,0.955, ...
    navy,FONT,FS_LETTER,FS_TITLE);

axA = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',local_relpos(PA,[0.250 0.155 0.685 0.690]));

imagesc(axA,U4C.deltaMat);

colormap(axA,local_redblue());

limA = max(abs(finiteDelta));

if ~isfinite(limA) || limA<=0
    limA = 1;
end

caxis(axA,[-limA limA]);

set( ...
    axA, ...
    'XTick',1:numel(U4C.budgets), ...
    'XTickLabel',string(U4C.budgets), ...
    'YTick',1:numel(U4C.targets), ...
    'YTickLabel',U4C.targets, ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.7, ...
    'Box','on');

xlabel( ...
    axA, ...
    'Audit budget', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axA, ...
    'Target', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

cbA = colorbar(axA,'Location','eastoutside');

cbA.Label.String = '\Delta MAE';

cbA.Label.FontName = FONT;
cbA.Label.FontSize = FS_TINY+0.4;
cbA.FontName = FONT;
cbA.FontSize = FS_TICK-0.4;

%% ========================================================================
% PANEL B
% LATE ADVANTAGE IS TARGET-SPECIFIC
% ========================================================================

axB0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PB);

axis(axB0,[0 1 0 1]);
axis(axB0,'off');
hold(axB0,'on');

local_panel_border( ...
    axB0,[0.004 0.005 0.992 0.985], ...
    panelGreen,1.0);

local_panel_header( ...
    axB0, ...
    'B', ...
    'Late advantage is target-specific', ...
    0.025,0.955, ...
    green,FONT,FS_LETTER,FS_TITLE);

axB = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',local_relpos(PB,[0.230 0.245 0.725 0.565]));

hold(axB,'on');

mxB = local_nanmax([U4C.rootLate(:);U4C.ruleLate(:)]);

if ~isfinite(mxB) || mxB<=0
    mxB = 1;
end

plot( ...
    axB, ...
    [0 mxB],[0 mxB], ...
    '--', ...
    'Color',[0.43 0.43 0.43], ...
    'LineWidth',1.0);

scatter( ...
    axB, ...
    U4C.rootLate, ...
    U4C.ruleLate, ...
    37, ...
    blue, ...
    'filled', ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.5);

set( ...
    axB, ...
    'XLim',[0 mxB*1.04], ...
    'YLim',[0 mxB*1.04], ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'Box','off', ...
    'TickDir','out', ...
    'LineWidth',0.7);

xlabel( ...
    axB, ...
    'Root-budget MAE', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axB, ...
    'Universal-rule MAE', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

text( ...
    axB0, ...
    0.50,0.065, ...
    sprintf('%d/%d favour universal rule', ...
        U4C.nRuleBetterLate,numel(U4C.rootLate)), ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY+0.5, ...
    'FontWeight','bold', ...
    'Color',navy);

%% ========================================================================
% PANEL C
% EVIDENCE EXPIRY IS TARGET-SPECIFIC
% ========================================================================

axC0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PC);

axis(axC0,[0 1 0 1]);
axis(axC0,'off');
hold(axC0,'on');

local_panel_border( ...
    axC0,[0.004 0.005 0.992 0.985], ...
    panelPurple,1.0);

local_panel_header( ...
    axC0, ...
    'C', ...
    'Evidence expiry is target-specific', ...
    0.025,0.955, ...
    purple,FONT,FS_LETTER,FS_TITLE);

axC = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',local_relpos(PC,[0.195 0.245 0.725 0.565]));

hold(axC,'on');

expMin = local_nanmin([U4C.predExpiry(:);U4C.empExpiry(:)]);
expMax = local_nanmax([U4C.predExpiry(:);U4C.empExpiry(:)]);

if ~isfinite(expMin) || expMin<=0
    expMin = 8;
end

if ~isfinite(expMax) || expMax<=expMin
    expMax = 256;
end

plot( ...
    axC, ...
    [expMin expMax], ...
    [expMin expMax], ...
    '--', ...
    'Color',[0.43 0.43 0.43], ...
    'LineWidth',1.0);

scatter( ...
    axC, ...
    U4C.predExpiry, ...
    U4C.empExpiry, ...
    38, ...
    purple, ...
    'filled', ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.5);

set( ...
    axC, ...
    'XScale','log', ...
    'YScale','log', ...
    'XLim',[expMin/1.3 expMax*1.3], ...
    'YLim',[expMin/1.3 expMax*1.3], ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'Box','off', ...
    'TickDir','out', ...
    'LineWidth',0.7);

xlabel( ...
    axC, ...
    'Predicted expiry', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axC, ...
    'Empirical expiry', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

% text( ...
%     axC0, ...
%     0.50,0.060, ...
%     'expiry does not transfer uniformly', ...
%     'HorizontalAlignment','center', ...
%     'FontName',FONT, ...
%     'FontSize',FS_TINY+0.4, ...
%     'FontAngle','italic', ...
%     'Color',grey);

%% ========================================================================
% PANEL D
% OUTCOME AUDITING RESTORES STATISTICAL CONTRACTION
% ========================================================================
%
% This panel is intentionally a theory illustration, not a new empirical
% result. Once representative outcomes enter the evidence channel, the
% structural ambiguity considered in the main text is replaced by ordinary
% sampling uncertainty.

axD0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PD);

axis(axD0,[0 1 0 1]);
axis(axD0,'off');
hold(axD0,'on');

local_panel_border( ...
    axD0,[0.004 0.005 0.992 0.985], ...
    panelBlue,1.0);

local_panel_header( ...
    axD0, ...
    'D', ...
    'Current outcomes restore statistical contraction', ...
    0.020,0.955, ...
    navy,FONT,FS_LETTER,FS_TITLE);

axD = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',local_relpos(PD,[0.145 0.205 0.760 0.620]));

hold(axD,'on');

m = [16 32 64 128 256 512 1024];

% Pure normalized root-budget theory reference.
rootCurve = (m/16).^(-0.5);

% A second curve uses only a different scale, illustrating that the same
% statistical order applies to another bounded-performance estimator.
aucCurve = 0.32*(m/16).^(-0.5);

plot( ...
    axD, ...
    m,rootCurve, ...
    '-o', ...
    'Color',navy, ...
    'MarkerFaceColor',navy, ...
    'MarkerSize',5.0, ...
    'LineWidth',1.8);

plot( ...
    axD, ...
    m,aucCurve, ...
    '-s', ...
    'Color',green, ...
    'MarkerFaceColor',green, ...
    'MarkerSize',4.8, ...
    'LineWidth',1.8);

plot( ...
    axD, ...
    m,0.64*(m/16).^(-0.5), ...
    '--', ...
    'Color',[0.38 0.38 0.38], ...
    'LineWidth',1.0);

set( ...
    axD, ...
    'XScale','log', ...
    'YScale','log', ...
    'XTick',m, ...
    'XTickLabel',string(m), ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'Box','off', ...
    'TickDir','out', ...
    'LineWidth',0.7);

xlabel( ...
    axD, ...
    'Audited current outcomes, m', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axD, ...
    'Normalized estimation error', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

legend( ...
    axD, ...
    {'bounded metric','AUC','m^{-1/2}'}, ...
    'Location','southwest', ...
    'Box','off', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY+0.2);

% text( ...
%     axD, ...
%     31, ...
%     0.12, ...
%     'slope = -1/2', ...
%     'FontName',FONT, ...
%     'FontSize',FS_SMALL, ...
%     'FontWeight','bold', ...
%     'Color',navy);

% text( ...
%     axD0, ...
%     0.50,0.075, ...
%     'theory illustration', ...
%     'HorizontalAlignment','center', ...
%     'FontName',FONT, ...
%     'FontSize',FS_TINY, ...
%     'FontAngle','italic', ...
%     'Color',grey);

%% ========================================================================
% PANEL E
% DEVELOPMENTAL MISMATCH SIGNAL REGULATES HISTORICAL REUSE
% ========================================================================

axE0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PE);

axis(axE0,[0 1 0 1]);
axis(axE0,'off');
hold(axE0,'on');

local_panel_border( ...
    axE0,[0.004 0.005 0.992 0.985], ...
    panelGreen,1.0);

local_panel_header( ...
    axE0, ...
    'E', ...
    'Developmental mismatch signal regulates reuse', ...
    0.020,0.955, ...
    green,FONT,FS_LETTER,FS_TITLE);

axE = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',local_relpos(PE,[0.135 0.200 0.690 0.625]));

hold(axE,'on');

scatter( ...
    axE, ...
    U5B.bias2, ...
    U5B.weight, ...
    39, ...
    U5B.transport, ...
    'filled', ...
    'MarkerEdgeColor',[0.25 0.25 0.25], ...
    'LineWidth',0.35);

set( ...
    axE, ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'Box','off', ...
    'TickDir','out', ...
    'LineWidth',0.7);

xlabel( ...
    axE, ...
    'Sentinel mismatch signal', ...
    'Interpreter','tex', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axE, ...
    'Mean borrowing weight', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

cbE = colorbar(axE,'Location','eastoutside');

cbE.Label.String = 'Later-revealed transport error';
cbE.Label.FontName = FONT;
cbE.Label.FontSize = FS_TINY+0.5;
cbE.FontName = FONT;
cbE.FontSize = FS_TICK-0.4;


text( ...
    axE0, ...
    0.76,0.135, ...
    sprintf('\\rho = %.2f',rhoBiasWeight), ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.3, ...
    'FontWeight','bold', ...
    'Color',green);

% text( ...
%     axE0, ...
%     0.50,0.075, ...
%     'developmental sensor diagnostic', ...
%     'HorizontalAlignment','center', ...
%     'FontName',FONT, ...
%     'FontSize',FS_TINY, ...
%     'FontAngle','italic', ...
%     'Color',grey);

%% ========================================================================
% 5) AUDIT PRINTOUT
% ========================================================================

fprintf('\n============================================================\n');
fprintf(' ED1 DEVELOPMENTAL FALSIFICATION AUDIT\n');
fprintf('============================================================\n');

fprintf('\nPanel A — cross-target/budget dominance\n');
fprintf('Universal-rule better cells = %d\n',nUniversalBetter);
fprintf('Root-budget better cells    = %d\n',nRootBetter);
fprintf('Exact ties                  = %d\n',nTies);

fprintf('\nPanel B — late-budget comparison\n');
fprintf('Universal rule better = %d/%d\n', ...
    U4C.nRuleBetterLate,numel(U4C.rootLate));
fprintf('Root-budget better    = %d/%d\n', ...
    U4C.nRootBetterLate,numel(U4C.rootLate));

fprintf('\nPanel C — evidence expiry\n');
fprintf('Expiry records        = %d\n',numel(U4C.predExpiry));

fprintf('\nPanel D — outcome restoration\n');
fprintf('Theory slope          = -0.500000\n');

fprintf('\nPanel E — developmental reuse\n');
fprintf('States                = %d\n',numel(U5B.bias2));
fprintf('Sentinel-signal/weight rho = %.9f\n',rhoBiasWeight);

%% ========================================================================
% 6) EXPORT
% ========================================================================

drawnow;

figPath = fullfile( ...
    outputDir, ...
    'ED1_OutcomeFreeBoundary_v9.fig');

pngPath = fullfile( ...
    outputDir, ...
    'ED1_OutcomeFreeBoundary_v9.png');

pdfPath = fullfile( ...
    outputDir, ...
    'ED1_OutcomeFreeBoundary_v9.pdf');

savefig(fig,figPath);

set(fig,'PaperPositionMode','auto');
set(fig,'PaperUnits','inches');

figPos = get(fig,'Position');

pageH = 9.0;
pageW = pageH*figPos(3)/figPos(4);

set(fig,'PaperSize',[pageW pageH]);
set(fig,'PaperPosition',[0 0 pageW pageH]);

print(fig,pngPath,'-dpng','-r600');
print(fig,pdfPath,'-dpdf','-painters','-bestfit');

fprintf('\nSaved:\n');
fprintf('%s\n',figPath);
fprintf('%s\n',pngPath);
fprintf('%s\n',pdfPath);

end


%% =========================================================================
% DATA LOADERS
% =========================================================================

function U4C = local_load_u4c(dataDir,cacheDir)
% Frozen U4C canonical archive.

stageDir = dataDir;

A = local_read_canonical( ...
    stageDir, ...
    'StageU4C_Audit_State_Results_v1.1.csv');

F = local_read_canonical( ...
    stageDir, ...
    'StageU4C_Component_Fits_v1.1.csv');

P = local_read_canonical( ...
    stageDir, ...
    'StageU4C_Component_Trajectory_Predictions_v1.1.csv');

E = local_read_canonical( ...
    stageDir, ...
    'StageU4C_Evidence_Expiry_Map_v1.1.csv');

targetOrder = [ ...
    "EMNIST_DIGITS", ...
    "FL", ...
    "GENRE_facetoface", ...
    "GENRE_letters", ...
    "GENRE_nineeleven", ...
    "GENRE_oup", ...
    "GENRE_verbatim", ...
    "IL", ...
    "NY", ...
    "QMNIST_TEST50K", ...
    "SVHN", ...
    "TX", ...
    "USPS"];

budgets = sort(unique(double(P.budget)));

deltaMat = nan(numel(targetOrder),numel(budgets));

for i = 1:numel(targetOrder)

    for j = 1:numel(budgets)

        mask = ...
            string(P.target)==targetOrder(i) & ...
            double(P.budget)==budgets(j);

        if any(mask)

            uerr = abs( ...
                double(P.component_pred(mask)) - ...
                double(P.truth_direct_mae(mask)));

            rerr = abs( ...
                double(P.rootn_pred(mask)) - ...
                double(P.truth_direct_mae(mask)));

            deltaMat(i,j) = ...
                local_nanmean(uerr-rerr);

        end

    end

end

rootLate = double(F.rootn_late_mae);
ruleLate = double(F.component_late_mae);

predExpiry = ...
    min( ...
        max( ...
            double(E.predicted_expiry_budget_from_budget8), ...
            8), ...
        256);

empExpiry = ...
    min( ...
        max( ...
            double(E.empirical_expiry_budget), ...
            8), ...
        256);

U4C.targets = strings(numel(targetOrder),1);

for i = 1:numel(targetOrder)
    U4C.targets(i) = string(local_short_u4(targetOrder(i)));
end

U4C.budgets = budgets;
U4C.deltaMat = deltaMat;

U4C.rootLate = rootLate;
U4C.ruleLate = ruleLate;

U4C.predExpiry = predExpiry;
U4C.empExpiry  = empExpiry;

U4C.nRuleBetterLate = ...
    nnz(ruleLate < rootLate);

U4C.nRootBetterLate = ...
    nnz(rootLate < ruleLate);

U4C.audit = A;

assert( ...
    numel(U4C.targets)==13, ...
    'Expected 13 frozen U4C targets.');

assert( ...
    numel(rootLate)==13, ...
    'Expected 13 U4C late-budget comparisons.');

assert( ...
    numel(predExpiry)==13, ...
    'Expected 13 U4C expiry records.');

end


function U5B = local_load_u5b(dataDir,cacheDir)
% Frozen U5B canonical archive.

stageDir = dataDir;

S = local_read_canonical( ...
    stageDir, ...
    'StageU5B_Audit_State_Results_v1.0.csv');

required = { ...
    'mean_sentinel_bias_sq', ...
    'mean_sentinel_weight', ...
    'transport_abs_error'};

for i = 1:numel(required)

    if ~ismember(required{i},S.Properties.VariableNames)

        error( ...
            'U5B canonical table missing field: %s', ...
            required{i});

    end

end

U5B.bias2 = ...
    double(S.mean_sentinel_bias_sq);

U5B.weight = ...
    double(S.mean_sentinel_weight);

U5B.transport = ...
    double(S.transport_abs_error);

U5B.state = S;

end


%% =========================================================================
% DRAW HELPERS
% =========================================================================

function pos = local_relpos(panelPos,rel)

pos = [ ...
    panelPos(1)+rel(1)*panelPos(3), ...
    panelPos(2)+rel(2)*panelPos(4), ...
    rel(3)*panelPos(3), ...
    rel(4)*panelPos(4)];

end


function local_panel_border(ax,pos,color,lineWidth)

rectangle( ...
    ax, ...
    'Position',pos, ...
    'FaceColor','none', ...
    'EdgeColor',color, ...
    'LineWidth',lineWidth);

end


function local_panel_header( ...
    ax,letter,titleText,x,y,color,fontName,fsLetter,fsTitle)

text( ...
    ax,x,y,letter, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsLetter, ...
    'FontWeight','bold', ...
    'Color',color);

text( ...
    ax,x+0.075,y,titleText, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsTitle, ...
    'FontWeight','bold', ...
    'Color',color);

end


function c = local_mix(c1,c2,alpha)

c = ...
    (1-alpha).*c1 + ...
    alpha.*c2;

end


function h = local_redblue()

n = 256;

r = [ ...
    (0:n/2-1)'/(n/2-1); ...
    ones(n/2,1)];

g = [ ...
    (0:n/2-1)'/(n/2-1); ...
    (n/2-1:-1:0)'/(n/2-1)];

b = [ ...
    ones(n/2,1); ...
    (n/2-1:-1:0)'/(n/2-1)];

h = [r g b];

end


%% =========================================================================
% NUMERIC HELPERS
% =========================================================================

function v = local_nanmean(x)

x = double(x(:));
x = x(isfinite(x));

if isempty(x)
    v = NaN;
else
    v = mean(x);
end

end
function v = local_nanmin(x)

x = double(x(:));
x = x(isfinite(x));

if isempty(x)
    v = NaN;
else
    v = min(x);
end

end


function v = local_nanmax(x)

x = double(x(:));
x = x(isfinite(x));

if isempty(x)
    v = NaN;
else
    v = max(x);
end

end


function rho = local_spearman(x,y)

x = double(x(:));
y = double(y(:));

valid = ...
    isfinite(x) & ...
    isfinite(y);

x = x(valid);
y = y(valid);

if numel(x)<3
    rho = NaN;
    return;
end

rx = local_tied_rank(x);
ry = local_tied_rank(y);

C = corrcoef(rx,ry);

if numel(C)<4
    rho = NaN;
else
    rho = C(1,2);
end

end


function r = local_tied_rank(v)

v = double(v(:));

n = numel(v);

[sv,ord] = sort(v,'ascend');

r = zeros(n,1);

i = 1;

while i<=n

    j = i;

    while ...
            j<n && ...
            sv(j+1)==sv(i)

        j = j+1;

    end

    r(ord(i:j)) = ...
        0.5*(i+j);

    i = j+1;

end

end


%% =========================================================================
% CANONICAL RECORD HELPERS
% =========================================================================

function stageDir = local_extract_canonical(dataDir,cacheDir,zipName)

zipPath = ...
    cmdo.find_unique_file(dataDir,zipName);

if ~exist(zipPath,'file')
    error('Missing canonical archive: %s',zipPath);
end

stageDir = ...
    fullfile( ...
        cacheDir, ...
        erase(zipName,'.zip'));

ready = ...
    fullfile(stageDir,'.ready');

if ~exist(ready,'file')

    if exist(stageDir,'dir')
        rmdir(stageDir,'s');
    end

    mkdir(stageDir);

    unzip(zipPath,stageDir);

    fid = fopen(ready,'w');

    if fid>0
        fprintf(fid,'ready\n');
        fclose(fid);
    end

end

end


function T = local_read_canonical(stageDir,fileName)

hits = ...
    dir(fullfile(stageDir,'**',fileName));

if isempty(hits)

    error( ...
        'Canonical CSV not found after extraction: %s', ...
        fileName);

end

T = readtable( ...
    fullfile(hits(1).folder,hits(1).name), ...
    'VariableNamingRule','preserve');

end


function s = local_short_u4(x)

x = string(x);

switch x

    case "EMNIST_DIGITS"
        s = 'EMNIST DIGITS';

    case "QMNIST_TEST50K"
        s = 'QMNIST TEST50K';

    case "GENRE_facetoface"
        s = 'facetoface';

    case "GENRE_letters"
        s = 'letters';

    case "GENRE_nineeleven"
        s = 'nineeleven';

    case "GENRE_oup"
        s = 'oup';

    case "GENRE_verbatim"
        s = 'verbatim';

    otherwise
        s = char(x);

end

end


%% =========================================================================
% REPOSITORY HELPER
% =========================================================================

function repoRoot = local_find_cmdo_repo(scriptDir)
% Reviewer-facing fallback: derive repository root only from this renderer.
repoRoot = '';
if nargin < 1 || isempty(scriptDir)
    return;
end
candidate = fileparts(fileparts(scriptDir));
if isfolder(fullfile(candidate,'source_data')) && ...
        isfolder(fullfile(candidate,'matlab'))
    repoRoot = candidate;
end
end

