function Figure2_IDENTIFY_Validation(outputDir, repoRoot)
% FIGURE2_IDENTIFY_VALIDATION
% CMDO Figure 2 — IDENTIFY validation:
% identical monitored evidence can conceal opposite performance.
%
% Scientific role
%   A) Observed model scores in two external ECG cohorts
%   B) Georgia: same observed outputs, opposite compatible performance
%   C) CPSC 2018: same observed outputs, opposite compatible performance
%   D) Frozen U6/U7 direct-audit error versus audit budget, compared with
%      the root-budget prediction for finite-sample uncertainty
%
% IMPORTANT
%   - Panels A-C use frozen U11 score channels and constructed outcome worlds.
%   - Panels A-C do NOT access true U10 target outcomes.
%   - Panels A-C do NOT imply either constructed world is the real clinical world.
%   - Panel D uses frozen U6/U7 current-audit records; it is not a seeded
%     toy simulation and does not use the U11 constructed worlds.
%
% Usage
%   Figure2_IDENTIFY_Validation(outputDir, repoRoot)
close all;

%% ------------------------------------------------------------------------
% 0. STYLE
% -------------------------------------------------------------------------

FONT = 'Arial';

FS_LETTER = 22;
FS_TITLE  = 11.5;
FS_AXIS   = 9.5;
FS_TICK   = 9.0;
FS_SMALL  = 9.2;
FS_TINY   = 8.2;

navy  = [0.02 0.24 0.63];
blue  = [0.02 0.29 0.70];

red   = [0.82 0.05 0.04];
green = [0.02 0.48 0.20];

grey  = [0.42 0.42 0.42];
dgrey = [0.22 0.22 0.22];
lgrey = [0.82 0.82 0.82];

panelBlue = local_mix(blue,[1 1 1],0.72);

%% ------------------------------------------------------------------------
% 1. OUTPUT
% -------------------------------------------------------------------------

thisFile = mfilename('fullpath');

if isempty(thisFile)
    scriptDir = pwd;
else
    scriptDir = fileparts(thisFile);
end

if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(scriptDir,'output');
end

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

%% ------------------------------------------------------------------------
% 2. LOCATE CMDO REPOSITORY
% -------------------------------------------------------------------------

if nargin < 2 || isempty(repoRoot)
    repoRoot = fileparts(fileparts(scriptDir));
end

assert(isfolder(fullfile(repoRoot,'source_data')), ...
    'Reviewer repository root is invalid.');

fprintf('\n============================================================\n');
fprintf(' CMDO FIGURE 2 — IDENTIFY\n');
fprintf(' Same monitoring, opposite compatible performance\n');
fprintf('============================================================\n');
fprintf('Repository : %s\n',repoRoot);
fprintf('Output     : %s\n',outputDir);

% Reviewer-facing frozen tables are tracked directly in source_data.
addpath(scriptDir);
D = cmdo_submission_load(repoRoot);

%% ------------------------------------------------------------------------
% 3. LOAD FROZEN U11 INFORMATION-CLOSURE WORLDS
% -------------------------------------------------------------------------

U11 = local_load_u11(repoRoot);

% Explicit frozen checks.
assert(U11.georgia.scoreResidual == 0, ...
    'Georgia WORLD+ and WORLD- scores differ.');

assert(U11.cpsc.scoreResidual == 0, ...
    'CPSC WORLD+ and WORLD- scores differ.');

assert(U11.georgia.predictionIdentity, ...
    'Georgia prediction channels differ.');

assert(U11.cpsc.predictionIdentity, ...
    'CPSC prediction channels differ.');

assert(abs(U11.georgia.prevalencePlus - ...
           U11.georgia.prevalenceMinus) < 1e-12, ...
    'Georgia prevalence is not matched.');

assert(abs(U11.cpsc.prevalencePlus - ...
           U11.cpsc.prevalenceMinus) < 1e-12, ...
    'CPSC prevalence is not matched.');

%% ------------------------------------------------------------------------
% 4. FROZEN CURRENT-AUDIT CONVERGENCE
% -------------------------------------------------------------------------
%
% Once representative current outcomes are available, IDENTIFY predicts
% ordinary finite-sample uncertainty.  For bounded performance quantities
% (including balanced AUC), the expected direct-estimation error should
% contract at the root-budget order m^{-1/2}.
%
% Here we test that consequence on the frozen U6/U7 audit records rather
% than on the seeded Figure-2 mechanism simulation.
%

local_require_vars( ...
    D.u6_state, ...
    {'budget','direct_mae'}, ...
    'U6 state table');

metricCol7S = ...
    local_find_var(D.u7_state,{'metric'});

if isempty(metricCol7S)

    error('U7 state table missing metric.');

end

S7AUC = ...
    D.u7_state( ...
    string(D.u7_state.(metricCol7S))=="AUC",:);

local_require_vars( ...
    S7AUC, ...
    {'budget','direct_mae'}, ...
    'U7 AUC state table');

bud6 = ...
    sort(unique(double(D.u6_state.budget)))';

bud7 = ...
    sort(unique(double(S7AUC.budget)))';

u6MeanDirect = nan(size(bud6));
u6LoDirect   = nan(size(bud6));
u6HiDirect   = nan(size(bud6));

u7MeanDirect = nan(size(bud7));
u7LoDirect   = nan(size(bud7));
u7HiDirect   = nan(size(bud7));

for i = 1:numel(bud6)

    v = double( ...
        D.u6_state.direct_mae( ...
        double(D.u6_state.budget)==bud6(i)));

    v = v(isfinite(v));

    u6MeanDirect(i) = mean(v,'omitnan');
    u6LoDirect(i)   = local_quantile(v,0.10);
    u6HiDirect(i)   = local_quantile(v,0.90);

end

for i = 1:numel(bud7)

    v = double( ...
        S7AUC.direct_mae( ...
        double(S7AUC.budget)==bud7(i)));

    v = v(isfinite(v));

    u7MeanDirect(i) = mean(v,'omitnan');
    u7LoDirect(i)   = local_quantile(v,0.10);
    u7HiDirect(i)   = local_quantile(v,0.90);

end

m6fit = ...
    isfinite(bud6) & ...
    isfinite(u6MeanDirect) & ...
    bud6>0 & ...
    u6MeanDirect>0;

m7fit = ...
    isfinite(bud7) & ...
    isfinite(u7MeanDirect) & ...
    bud7>0 & ...
    u7MeanDirect>0;

assert(nnz(m6fit)>=3, ...
    'Insufficient U6 budgets for log-log slope.');

assert(nnz(m7fit)>=3, ...
    'Insufficient U7 budgets for log-log slope.');

p6 = polyfit( ...
    log10(bud6(m6fit)), ...
    log10(u6MeanDirect(m6fit)), ...
    1);

p7 = polyfit( ...
    log10(bud7(m7fit)), ...
    log10(u7MeanDirect(m7fit)), ...
    1);

u6Slope = p6(1);
u7Slope = p7(1);

% Root-budget theory lines, anchored to each empirical curve at its
% smallest evaluated audit budget.  These are rate references, not fits.
u6RootRef = ...
    u6MeanDirect(find(m6fit,1,'first')) .* ...
    (bud6 ./ bud6(find(m6fit,1,'first'))).^(-0.5);

u7RootRef = ...
    u7MeanDirect(find(m7fit,1,'first')) .* ...
    (bud7 ./ bud7(find(m7fit,1,'first'))).^(-0.5);

fprintf('\n--- IDENTIFY FROZEN AUDIT-CONVERGENCE ---\n');
fprintf('U6 direct-audit slope = %.6f\n',u6Slope);
fprintf('U7 direct-audit slope = %.6f\n',u7Slope);

%% ------------------------------------------------------------------------
% 5. CANVAS
% -------------------------------------------------------------------------

fig = figure( ...
    'Color','w', ...
    'Position',[55 35 1000 960], ...
    'Renderer','painters', ...
    'Name','CMDO Figure 2 — IDENTIFY', ...
    'NumberTitle','off');

% One wide monitoring panel, two compatible-world panels,
% and one wide empirical audit-convergence panel.
PA = [0.025 0.705 0.950 0.265];

PB = [0.025 0.360 0.460 0.315];

PC = [0.515 0.360 0.460 0.315];

PD = [0.025 0.050 0.950 0.270];

%% ========================================================================
% PANEL A — SAME MONITORED EVIDENCE
% ========================================================================

axA0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PA);

axis(axA0,[0 1 0 1]);
axis(axA0,'off');
hold(axA0,'on');

local_panel_border( ...
    axA0, ...
    [0.005 0.005 0.99 0.99], ...
    panelBlue, ...
    1.05);

local_panel_header( ...
    axA0, ...
    'A', ...
    'Identical outcome-free evidence', ...
    0.020, ...
    0.955, ...
    navy, ...
    FONT, ...
    FS_LETTER, ...
    FS_TITLE);

% -------------------------------------------------------------------------
% Georgia score stream
% -------------------------------------------------------------------------

axA1 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PA,[0.080 0.235 0.385 0.515]));

local_score_stream( ...
    axA1, ...
    U11.georgia.scoreRaw, ...
    grey, ...
    FONT, ...
    FS_AXIS);

title( ...
    axA1, ...
    sprintf('Georgia   n = %s', ...
    local_comma_integer(U11.georgia.n)), ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',dgrey);

ylabel( ...
    axA1, ...
    'Model score', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

% -------------------------------------------------------------------------
% CPSC 2018 score stream
% -------------------------------------------------------------------------

axA2 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PA,[0.535 0.235 0.385 0.515]));

local_score_stream( ...
    axA2, ...
    U11.cpsc.scoreRaw, ...
    grey, ...
    FONT, ...
    FS_AXIS);

title( ...
    axA2, ...
    sprintf('CPSC 2018   n = %s', ...
    local_comma_integer(U11.cpsc.n)), ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',dgrey);

ylabel( ...
    axA2, ...
    'Model score', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);



%% ========================================================================
% PANEL B — GEORGIA
% ========================================================================

axB0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PB);

axis(axB0,[0 1 0 1]);
axis(axB0,'off');
hold(axB0,'on');

local_panel_border( ...
    axB0, ...
    [0.005 0.005 0.99 0.99], ...
    panelBlue, ...
    1.05);

local_panel_header( ...
    axB0, ...
    'B', ...
    'Georgia: same evidence, opposite performance', ...
    0.025, ...
    0.955, ...
    navy, ...
    FONT, ...
    FS_LETTER, ...
    FS_TITLE);

text( ...
    axB0, ...
    0.50, ...
    0.855, ...
    sprintf('matched prevalence = %.6f', ...
    U11.georgia.prevalencePlus), ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY, ...
    'Color',grey);

% WORLD+
axB1 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PB,[0.160 0.555 0.610 0.185]));

local_world_strip( ...
    axB1, ...
    U11.georgia.yPlus, ...
    green, ...
    FONT, ...
    FS_AXIS, ...
    false);

text( ...
    axB0, ...
    0.120, ...
    0.650, ...
    'WORLD+', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',green);

text( ...
    axB0, ...
    0.805, ...
    0.650, ...
    sprintf('AUC = %.2f',U11.georgia.aucPlus), ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',green);

% WORLD-
axB2 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PB,[0.160 0.285 0.610 0.185]));

local_world_strip( ...
    axB2, ...
    U11.georgia.yMinus, ...
    red, ...
    FONT, ...
    FS_AXIS, ...
    true);

text( ...
    axB0, ...
    0.120, ...
    0.370, ...
    'WORLD-', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',red);

text( ...
    axB0, ...
    0.805, ...
    0.370, ...
    sprintf('AUC = %.2f',U11.georgia.aucMinus), ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',red);

% Delta_E
text( ...
    axB0, ...
    0.50, ...
    0.105, ...
    sprintf('$\\Delta_{\\mathcal{E}} = %.2f$', ...
    U11.georgia.aucGap), ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'Color',blue);

%% ========================================================================
% PANEL C — CPSC 2018
% ========================================================================

axC0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PC);

axis(axC0,[0 1 0 1]);
axis(axC0,'off');
hold(axC0,'on');

local_panel_border( ...
    axC0, ...
    [0.005 0.005 0.99 0.99], ...
    panelBlue, ...
    1.05);

local_panel_header( ...
    axC0, ...
    'C', ...
    'CPSC 2018: same evidence, opposite performance', ...
    0.025, ...
    0.955, ...
    navy, ...
    FONT, ...
    FS_LETTER, ...
    FS_TITLE);

text( ...
    axC0, ...
    0.50, ...
    0.855, ...
    sprintf('matched prevalence = %.6f', ...
    U11.cpsc.prevalencePlus), ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY, ...
    'Color',grey);

% WORLD+
axC1 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PC,[0.160 0.555 0.610 0.185]));

local_world_strip( ...
    axC1, ...
    U11.cpsc.yPlus, ...
    green, ...
    FONT, ...
    FS_AXIS, ...
    false);

text( ...
    axC0, ...
    0.120, ...
    0.650, ...
    'WORLD+', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',green);

text( ...
    axC0, ...
    0.805, ...
    0.650, ...
    sprintf('AUC = %.2f',U11.cpsc.aucPlus), ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',green);

% WORLD-
axC2 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PC,[0.160 0.285 0.610 0.185]));

local_world_strip( ...
    axC2, ...
    U11.cpsc.yMinus, ...
    red, ...
    FONT, ...
    FS_AXIS, ...
    true);

text( ...
    axC0, ...
    0.120, ...
    0.370, ...
    'WORLD-', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',red);

text( ...
    axC0, ...
    0.805, ...
    0.370, ...
    sprintf('AUC = %.2f',U11.cpsc.aucMinus), ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',red);

% Delta_E
text( ...
    axC0, ...
    0.50, ...
    0.105, ...
    sprintf('$\\Delta_{\\mathcal{E}} = %.2f$', ...
    U11.cpsc.aucGap), ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'Color',blue);

%% ========================================================================
% PANEL D — FROZEN AUDIT ERROR VERSUS ROOT-BUDGET THEORY
% ========================================================================

axD0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PD);

axis(axD0,[0 1 0 1]);
axis(axD0,'off');
hold(axD0,'on');

local_panel_border( ...
    axD0, ...
    [0.005 0.005 0.99 0.99], ...
    panelBlue, ...
    1.05);

local_panel_header( ...
    axD0, ...
    'D', ...
    'Representative outcomes restore root-budget estimation', ...
    0.020, ...
    0.955, ...
    navy, ...
    FONT, ...
    FS_LETTER, ...
    FS_TITLE);

% -------------------------------------------------------------------------
% D1 — U6 cross-domain
% -------------------------------------------------------------------------

axD1 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PD,[0.090 0.205 0.380 0.570]));

hold(axD1,'on');

fill( ...
    axD1, ...
    [bud6 fliplr(bud6)], ...
    [u6LoDirect fliplr(u6HiDirect)], ...
    local_mix(blue,[1 1 1],0.76), ...
    'EdgeColor','none', ...
    'FaceAlpha',0.35, ...
    'HandleVisibility','off');

hU6 = plot( ...
    axD1, ...
    bud6, ...
    u6MeanDirect, ...
    '-o', ...
    'Color',blue, ...
    'MarkerFaceColor',blue, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',1.8, ...
    'MarkerSize',5.6, ...
    'DisplayName','Frozen audit error');

hR6 = plot( ...
    axD1, ...
    bud6, ...
    u6RootRef, ...
    '--', ...
    'Color',[0.25 0.25 0.25], ...
    'LineWidth',1.0, ...
    'DisplayName','Root-budget theory');

set( ...
    axD1, ...
    'XScale','log', ...
    'YScale','log', ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'LineWidth',0.75, ...
    'TickDir','out', ...
    'Box','off');

xlim(axD1,[0.88*min(bud6) 1.14*max(bud6)]);

xticks(axD1,bud6);
xticklabels(axD1,cellstr(string(bud6)));

grid(axD1,'on');
axD1.GridAlpha = 0.08;

xlabel( ...
    axD1, ...
    'Current-outcome audit budget, m', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axD1, ...
    'Direct-estimation MAE', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

title( ...
    axD1, ...
    'Cross-domain', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.4, ...
    'FontWeight','bold');

text( ...
    axD1, ...
    0.055,0.12, ...
    sprintf('observed slope = %.2f',u6Slope), ...
    'Units','normalized', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',blue);

legend( ...
    axD1, ...
    [hU6 hR6], ...
    'Location','northeast', ...
    'Box','off', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY-0.4);

% -------------------------------------------------------------------------
% D2 — U7 clinical AUC
% -------------------------------------------------------------------------

axD2 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PD,[0.560 0.205 0.380 0.570]));

hold(axD2,'on');

fill( ...
    axD2, ...
    [bud7 fliplr(bud7)], ...
    [u7LoDirect fliplr(u7HiDirect)], ...
    local_mix(green,[1 1 1],0.78), ...
    'EdgeColor','none', ...
    'FaceAlpha',0.35, ...
    'HandleVisibility','off');

hU7 = plot( ...
    axD2, ...
    bud7, ...
    u7MeanDirect, ...
    '-s', ...
    'Color',green, ...
    'MarkerFaceColor',green, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',1.8, ...
    'MarkerSize',5.6, ...
    'DisplayName','Frozen audit error');

hR7 = plot( ...
    axD2, ...
    bud7, ...
    u7RootRef, ...
    '--', ...
    'Color',[0.25 0.25 0.25], ...
    'LineWidth',1.0, ...
    'DisplayName','Root-budget theory');

set( ...
    axD2, ...
    'XScale','log', ...
    'YScale','log', ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'LineWidth',0.75, ...
    'TickDir','out', ...
    'Box','off');

xlim(axD2,[0.88*min(bud7) 1.14*max(bud7)]);

xticks(axD2,bud7);
xticklabels(axD2,cellstr(string(bud7)));

grid(axD2,'on');
axD2.GridAlpha = 0.08;

xlabel( ...
    axD2, ...
    'Audited outcomes, m', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axD2, ...
    'Direct-estimation MAE', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

title( ...
    axD2, ...
    'Clinical AUC', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.4, ...
    'FontWeight','bold');

text( ...
    axD2, ...
    0.055,0.12, ...
    sprintf('observed slope = %.2f',u7Slope), ...
    'Units','normalized', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',green);

legend( ...
    axD2, ...
    [hU7 hR7], ...
    'Location','northeast', ...
    'Box','off', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY-0.4);

%% ------------------------------------------------------------------------
% 6. AUDIT PRINTOUT
% -------------------------------------------------------------------------

fprintf('\n--- U11 IDENTIFY AUDIT ---\n');

fprintf(['Georgia : n=%d | prevalence=%.12f | ' ...
    'AUC+=%.12f | AUC-=%.12f | Delta_E=%.12f\n'], ...
    U11.georgia.n, ...
    U11.georgia.prevalencePlus, ...
    U11.georgia.aucPlus, ...
    U11.georgia.aucMinus, ...
    U11.georgia.aucGap);

fprintf(['CPSC    : n=%d | prevalence=%.12f | ' ...
    'AUC+=%.12f | AUC-=%.12f | Delta_E=%.12f\n'], ...
    U11.cpsc.n, ...
    U11.cpsc.prevalencePlus, ...
    U11.cpsc.aucPlus, ...
    U11.cpsc.aucMinus, ...
    U11.cpsc.aucGap);

fprintf('Georgia score identity residual : %.3e\n', ...
    U11.georgia.scoreResidual);

fprintf('CPSC score identity residual    : %.3e\n', ...
    U11.cpsc.scoreResidual);

fprintf('Georgia prediction identity     : %d\n', ...
    U11.georgia.predictionIdentity);

fprintf('CPSC prediction identity        : %d\n', ...
    U11.cpsc.predictionIdentity);

fprintf('U6 frozen direct-audit slope  : %.6f\n',u6Slope);
fprintf('U7 frozen direct-audit slope  : %.6f\n',u7Slope);

%% ------------------------------------------------------------------------
% 7. EXPORT
% -------------------------------------------------------------------------

drawnow;

% Keep current basename for compatibility with the existing runner.
baseName = 'Figure2_IDENTIFY_Validation';

figPath = fullfile(outputDir,[baseName '.fig']);
pngPath = fullfile(outputDir,[baseName '.png']);
pdfPath = fullfile(outputDir,[baseName '.pdf']);

savefig(fig,figPath);

set(fig,'PaperPositionMode','auto');
set(fig,'PaperUnits','inches');

figPos = get(fig,'Position');

pageH = 9.0;
pageW = pageH * figPos(3) / figPos(4);

set(fig,'PaperSize',[pageW pageH]);
set(fig,'PaperPosition',[0 0 pageW pageH]);

try

    exportgraphics( ...
        fig, ...
        pngPath, ...
        'Resolution',600, ...
        'BackgroundColor','white');

    exportgraphics( ...
        fig, ...
        pdfPath, ...
        'ContentType','vector', ...
        'BackgroundColor','white');

catch ME

    warning( ...
        'Figure3 exportgraphics failed (%s). Falling back to print.', ...
        ME.message);

    print(fig,pngPath,'-dpng','-r600');
    print(fig,pdfPath,'-dpdf','-painters','-bestfit');

end

fprintf('\nSaved:\n%s\n%s\n%s\n', ...
    figPath,pngPath,pdfPath);

end

%% =========================================================================
% HELPERS
% =========================================================================

function U11 = local_load_u11(repoRoot)

paths.gp = fullfile( ...
    repoRoot, ...
    'U11_Information_Closure', ...
    '01_Result', ...
    'U11_WORLD_PLUS_georgia_v0.1.csv');

paths.gm = fullfile( ...
    repoRoot, ...
    'U11_Information_Closure', ...
    '01_Result', ...
    'U11_WORLD_MINUS_georgia_v0.1.csv');

paths.cp = fullfile( ...
    repoRoot, ...
    'U11_Information_Closure', ...
    '01_Result', ...
    'U11_WORLD_PLUS_cpsc_2018_v0.1.csv');

paths.cm = fullfile( ...
    repoRoot, ...
    'U11_Information_Closure', ...
    '01_Result', ...
    'U11_WORLD_MINUS_cpsc_2018_v0.1.csv');

f = fieldnames(paths);
for i = 1:numel(f)

    if ~isfile(paths.(f{i}))
        error( ...
            'Missing U11 world file:\n%s', ...
            paths.(f{i}));
    end

end

Tgp = readtable(paths.gp);
Tgm = readtable(paths.gm);

Tcp = readtable(paths.cp);
Tcm = readtable(paths.cm);

U11.georgia = local_parse_u11_pair( ...
    Tgp,Tgm,'Georgia');

U11.cpsc = local_parse_u11_pair( ...
    Tcp,Tcm,'CPSC 2018');

end

function S = local_parse_u11_pair(Tp,Tm,nameStr)

local_require_vars( ...
    Tp, ...
    {'score_af','predicted_af','synthetic_outcome'}, ...
    [nameStr ' WORLD+']);

local_require_vars( ...
    Tm, ...
    {'score_af','predicted_af','synthetic_outcome'}, ...
    [nameStr ' WORLD-']);

sp = double(Tp.score_af(:));
sm = double(Tm.score_af(:));

pp = double(Tp.predicted_af(:));
pm = double(Tm.predicted_af(:));

ypRaw = double(Tp.synthetic_outcome(:));
ymRaw = double(Tm.synthetic_outcome(:));

assert( ...
    numel(sp)==numel(sm), ...
    'U11 paired worlds have different lengths.');

% If record IDs are available, verify that those channels also match.
if ismember('record_id',Tp.Properties.VariableNames) && ...
        ismember('record_id',Tm.Properties.VariableNames)

    ridP = string(Tp.record_id);
    ridM = string(Tm.record_id);

    assert( ...
        isequal(ridP,ridM), ...
        'U11 record_id channels differ.');

end

scoreResidual = max(abs(sp-sm),[],'omitnan');

predictionIdentity = isequal(pp,pm);

% Preserve original frozen ordering for the monitoring-stream panel.
S.scoreRaw = sp;

% Sort only for the compatible-world visualization.
[scoreSorted,ord] = sort(sp,'ascend');

yp = ypRaw(ord);
ym = ymRaw(ord);

S.name = nameStr;

S.n = numel(sp);

S.score = scoreSorted;

S.yPlus = yp;
S.yMinus = ym;

S.prevalencePlus = mean(ypRaw,'omitnan');
S.prevalenceMinus = mean(ymRaw,'omitnan');

S.aucPlus = local_auc_rank(sp,ypRaw);
S.aucMinus = local_auc_rank(sm,ymRaw);

S.aucGap = abs( ...
    S.aucPlus - S.aucMinus);

S.scoreResidual = scoreResidual;

S.predictionIdentity = predictionIdentity;

end

function local_score_stream(ax,score,color,FONT,FS_AXIS)

score = double(score(:));

score = score(isfinite(score));

Nshow = min(240,numel(score));

idx = unique( ...
    round( ...
    linspace(1,numel(score),Nshow)));

s = score(idx);

x = 1:numel(s);

hold(ax,'on');

% Light vertical score stems.
h = stem( ...
    ax, ...
    x, ...
    s, ...
    'Marker','none', ...
    'Color',color, ...
    'LineWidth',0.55);

try
    h.BaseLine.Visible = 'off';
catch
end

scatter( ...
    ax, ...
    x, ...
    s, ...
    10, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor',color, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.25);

xlim(ax,[1 numel(x)]);

scoreMin = min(s,[],'omitnan');
scoreMax = max(s,[],'omitnan');

lo = min(0,scoreMin);
hi = max(1,scoreMax);

span = hi-lo;

if span<=0 || ~isfinite(span)
    span = 1;
end

ylim(ax,[lo-0.03*span hi+0.04*span]);

set( ...
    ax, ...
    'XTick',[1 round(numel(x)/2) numel(x)], ...
    'XTickLabel',{'1','n/2','n'}, ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

xlabel( ...
    ax, ...
    'Record order', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

end

function local_world_strip(ax,y,color,FONT,FS_AXIS,showXLabel)

y = double(y(:));

Nshow = min(320,numel(y));

idx = unique( ...
    round( ...
    linspace(1,numel(y),Nshow)));

yy = y(idx);

x = 1:numel(yy);

hold(ax,'on');

% Light guides first.
plot( ...
    ax, ...
    [1 numel(yy)], ...
    [0 0], ...
    '-', ...
    'Color',[0.86 0.86 0.86], ...
    'LineWidth',0.65);

plot( ...
    ax, ...
    [1 numel(yy)], ...
    [1 1], ...
    '-', ...
    'Color',[0.86 0.86 0.86], ...
    'LineWidth',0.65);

% Actual constructed outcome world.
stairs( ...
    ax, ...
    x, ...
    yy, ...
    '-', ...
    'Color',color, ...
    'LineWidth',1.80);

step = max(1,round(numel(yy)/34));

markerIdx = 1:step:numel(yy);

scatter( ...
    ax, ...
    x(markerIdx), ...
    yy(markerIdx), ...
    20, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor',color, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.30);

xlim(ax,[1 numel(yy)]);
ylim(ax,[-0.10 1.10]);

set( ...
    ax, ...
    'YTick',[0 1], ...
    'YTickLabel',{'0','1'}, ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS-1, ...
    'TickDir','out', ...
    'LineWidth',0.70, ...
    'Box','off');

if showXLabel

    set( ...
        ax, ...
        'XTick',[1 numel(yy)], ...
        'XTickLabel',{'low','high'});

    xlabel( ...
        ax, ...
        'Model-score rank', ...
        'FontName',FONT, ...
        'FontSize',FS_AXIS);

else

    set(ax,'XTick',[]);

end

end

function auc = local_auc_rank(score,y)

score = double(score(:));
y = double(y(:));

m = isfinite(score) & isfinite(y);

score = score(m);
y = y(m);

n1 = nnz(y==1);
n0 = nnz(y==0);

if n1==0 || n0==0

    auc = NaN;
    return;

end

r = local_tied_rank(score);

sumR1 = sum(r(y==1));

auc = ...
    (sumR1 - n1*(n1+1)/2) / ...
    (n1*n0);

end

function r = local_tied_rank(v)

v = double(v(:));

n = numel(v);

[sv,ord] = sort(v,'ascend');

r = zeros(n,1);

i = 1;

while i<=n

    j = i;

    while j<n && sv(j+1)==sv(i)
        j = j+1;
    end

    r(ord(i:j)) = 0.5*(i+j);

    i = j+1;

end

end

function name = local_find_var(T,candidates)

name = '';

vars = string(T.Properties.VariableNames);

for i = 1:numel(candidates)

    j = find( ...
        strcmpi(vars,candidates{i}), ...
        1,'first');

    if ~isempty(j)

        name = char(vars(j));
        return;

    end

end

end

function q = local_quantile(values,p)

values = sort(double(values(:)));
values = values(isfinite(values));

if isempty(values)

    q = NaN;
    return;

end

idx = ...
    1 + ...
    (numel(values)-1) .* ...
    min(max(p,0),1);

lo = floor(idx);
hi = ceil(idx);

a = idx-lo;

q = ...
    (1-a).*values(lo) + ...
    a.*values(hi);

end

function local_require_vars(T,vars,sourceName)

missing = strings(0,1);

for i = 1:numel(vars)

    if ~ismember(vars{i},T.Properties.VariableNames)

        missing(end+1,1) = string(vars{i}); %#ok<AGROW>

    end

end

if ~isempty(missing)

    error( ...
        '%s missing variables: %s', ...
        sourceName, ...
        strjoin(cellstr(missing),', '));

end

end

function local_panel_border(ax,pos,color,lineWidth)

rectangle( ...
    ax, ...
    'Position',pos, ...
    'Curvature',0.018, ...
    'FaceColor','none', ...
    'EdgeColor',color, ...
    'LineWidth',lineWidth);

end

function local_panel_header( ...
    ax,letter,titleText,x,y,color,fontName,fsLetter,fsTitle)

text( ...
    ax, ...
    x,y, ...
    letter, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsLetter, ...
    'FontWeight','bold', ...
    'Color',color);

text( ...
    ax, ...
    x+0.050, ...
    y, ...
    titleText, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsTitle, ...
    'FontWeight','bold', ...
    'Color',color);

end

function pos = local_relpos(panelPos,rel)

pos = [ ...
    panelPos(1) + rel(1)*panelPos(3), ...
    panelPos(2) + rel(2)*panelPos(4), ...
    rel(3)*panelPos(3), ...
    rel(4)*panelPos(4)];

end

function c = local_mix(c1,c2,alpha)

c = ...
    (1-alpha).*c1 + ...
    alpha.*c2;

end

function repoRoot = local_find_cmdo_repo(scriptDir)
% Reviewer-facing fallback: derive repository root only from this renderer.
repoRoot = '';
if nargin < 1 || isempty(scriptDir)
    return;
end
candidate = fileparts(fileparts(scriptDir));
if isfolder(fullfile(candidate,'source_data')) && ...
        isfolder(fullfile(candidate,'matlab'))
    repoRoot = candidate;
end
end

function s = local_comma_integer(n)

s = sprintf('%d',round(n));

k = length(s)-3;

while k>0

    s = [s(1:k) ',' s(k+1:end)]; %#ok<AGROW>

    k = k-3;

end

end
