function Figure4_PRESERVE_Refined(outputDir, repoRoot)
% ============================================================
% FIGURE 4 — PRESERVE
% Evidence value must survive adaptation
%
% A | Adaptation can consume fixed-use value
% B | Adaptation is worthwhile only when H > A + C
%
% Panel B deliberately shows:
%   1) all eight U10 statewise contributions,
%   2) the 8-state aggregate frontier location,
%   3) the post-completion pairing-disruption shift.
%
% Individual state labels are intentionally omitted to avoid clutter.
% Cohort identity is encoded by marker shape; each cohort contributes
% the four frozen budgets 128, 256, 512 and 1024.
% ============================================================

close all;

%% OUTPUT
thisFile = mfilename('fullpath');
if isempty(thisFile)
    scriptDir = pwd;
else
    scriptDir = fileparts(thisFile);
end

if nargin < 2 || isempty(repoRoot)
    repoRoot = local_find_cmdo_repo(scriptDir);
end

if isempty(repoRoot)
    error(['Could not locate CMDO-Reproducibility.' newline ...
           'Run with an explicit repository path.']);
end

if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(scriptDir,'output');
end

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

%% STYLE
FONT = 'Arial';

FS_AXIS  = 11.2;
FS_TICK  = 9.8;

DARK   = [0.18 0.18 0.18];
GREY   = [0.45 0.45 0.45];
GREEN  = [0.00 0.50 0.18];
RED    = [0.88 0.07 0.06];
PURPLE = [0.45 0.18 0.78];

% Slightly softened colours for the eight statewise points.
GREEN_STATE = 0.72*GREEN + 0.28*[1 1 1];
RED_STATE   = 0.72*RED   + 0.28*[1 1 1];

BORDER_RED    = [0.96 0.77 0.77];
BORDER_PURPLE = [0.88 0.80 0.96];

%% DATA
budgets = [128 256 512 1024];

% ============================================================
% U9B: matched-fixed versus adaptive risk
% ============================================================
u9bPath = fullfile( ...
    repoRoot, ...
    'source_data', ...
    'figure6_admissibility', ...
    'U9B_external_composability_decomposition.csv');

if ~isfile(u9bPath)
    error('Missing U9B decomposition:\n%s',u9bPath);
end

U9B = readtable(u9bPath);

needU9B = {'budget','scalar_gain_pct','observed_gain_pct'};
local_require_vars(U9B,needU9B,'U9B decomposition');

[~,oU9B] = sort(double(U9B.budget),'ascend');
U9B = U9B(oU9B,:);

riskFixed_u9b = 1 - double(U9B.scalar_gain_pct(:))'    ./ 100;
riskAdapt_u9b = 1 - double(U9B.observed_gain_pct(:))' ./ 100;

% ============================================================
% U10: external ECG composability records
% ============================================================
u10Path = fullfile( ...
    repoRoot, ...
    'U10_Prospective_ECG', ...
    '02_Posthoc_Diagnostics', ...
    'U10_DEPENDENCE_DECOMPOSITION.csv');

if ~isfile(u10Path)
    error('Missing U10 decomposition:\n%s',u10Path);
end

U10 = readtable(u10Path);

needU10 = { ...
    'dataset', ...
    'budget', ...
    'shared_adaptive_gain_pct', ...
    'shared_constant_mean_gain_pct', ...
    'B', ...
    'direct_mse', ...
    'shared_constant_mean_weight', ...
    'shared_adaptive_mse', ...
    'shared_constant_mean_mse', ...
    'shared_permuted_weight_mse', ...
    'shared_tax_weight_heterogeneity'};

local_require_vars(U10,needU10,'U10 dependence decomposition');

dataset = lower(string(U10.dataset));
budget  = double(U10.budget);

idxGa = find(dataset == "georgia");
[~,oGa] = sort(budget(idxGa),'ascend');
idxGa = idxGa(oGa);

idxCp = find(dataset == "cpsc_2018");
[~,oCp] = sort(budget(idxCp),'ascend');
idxCp = idxCp(oCp);

assert(numel(idxGa)==4 && numel(idxCp)==4, ...
    'Expected four Georgia and four CPSC 2018 states.');

assert(isequal(budget(idxGa(:))',budgets), ...
    'Unexpected Georgia budget sequence.');

assert(isequal(budget(idxCp(:))',budgets), ...
    'Unexpected CPSC 2018 budget sequence.');

% ============================================================
% Panel A statewise composability summary
% ============================================================
riskFixed_ga = ...
    1 - double(U10.shared_constant_mean_gain_pct(idxGa))' ./ 100;
riskAdapt_ga = ...
    1 - double(U10.shared_adaptive_gain_pct(idxGa))' ./ 100;

riskFixed_cp = ...
    1 - double(U10.shared_constant_mean_gain_pct(idxCp))' ./ 100;
riskAdapt_cp = ...
    1 - double(U10.shared_adaptive_gain_pct(idxCp))' ./ 100;

riskFixed = [riskFixed_u9b riskFixed_ga riskFixed_cp];
riskAdapt = [riskAdapt_u9b riskAdapt_ga riskAdapt_cp];

x1 = 1:4;
x2 = 6:9;
x3 = 11:14;
xAll = [x1 x2 x3];

adaptiveWorse = nnz(riskAdapt > riskFixed);
benefitToHarm = nnz((riskFixed < 1) & (riskAdapt > 1));

assert(adaptiveWorse == 12, ...
    'Expected adaptive risk to exceed matched fixed risk in 12/12 states.');

assert(benefitToHarm == 7, ...
    'Expected fixed-benefit to adaptive-harm transition in 7/12 states.');

% ============================================================
% Panel B: empirical Eq. (4) adaptation frontier
% ============================================================

u10B        = double(U10.B);
u10V        = double(U10.direct_mse);
u10MeanW    = double(U10.shared_constant_mean_weight);
u10FixedMSE = double(U10.shared_constant_mean_mse);

% ------------------------------------------------------------
% Common empirical fixed-risk measure
%
% r_emp(w) =
% (1-w)^2 + Lambda*w^2 + 2*w*(1-w)*q
%
% where
% Lambda = B^2/V
% q      = B*mu/V
%
% mu is the empirical mean error of the direct estimator.
%
% Recover q exactly from the already-frozen matched-fixed MSE
% at the observed mean borrowing weight.
% ------------------------------------------------------------

u10Lambda = (u10B.^2) ./ u10V;

fixedRiskAtMean = ...
    u10FixedMSE ./ u10V;

denQ = ...
    2 .* u10MeanW .* (1-u10MeanW);

assert( ...
    all(abs(denQ) > 1e-12), ...
    'Cannot reconstruct empirical cross-term from mean-weight risk.');

u10Q = ...
    ( fixedRiskAtMean ...
    - (1-u10MeanW).^2 ...
    - u10Lambda .* u10MeanW.^2 ) ...
    ./ denQ;

% ------------------------------------------------------------
% Empirical quadratic curvature and optima
% ------------------------------------------------------------

quadTerm = ...
    1 + u10Lambda - 2*u10Q;

linearGain = ...
    1 - u10Q;

assert( ...
    all(isfinite(quadTerm) & quadTerm > 0), ...
    'Empirical fixed-risk quadratic is not convex in all U10 states.');

% State-specific fixed optimum over w in [0,1].
u10Wstar = ...
    linearGain ./ quadTerm;

u10Wstar = ...
    min(1,max(0,u10Wstar));

% Best single fixed weight across all eight states,
% minimizing mean normalized empirical risk.
wGlobal = ...
    mean(linearGain,'omitnan') ./ ...
    mean(quadTerm,'omitnan');

wGlobal = ...
    min(1,max(0,wGlobal));

% ------------------------------------------------------------
% Common empirical normalized fixed-risk function
% ------------------------------------------------------------

riskEmp = @(w) ...
    (1-w).^2 ...
    + u10Lambda .* w.^2 ...
    + 2 .* w .* (1-w) .* u10Q;

riskStar = ...
    riskEmp(u10Wstar);

riskGlobal = ...
    riskEmp(wGlobal .* ones(size(u10MeanW)));

riskMeanW = ...
    riskEmp(u10MeanW);

% Exact reconstruction check at each state's observed mean weight.
reconstructionResidual = ...
    max(abs(riskMeanW-fixedRiskAtMean),[],'omitnan');

assert( ...
    reconstructionResidual < 1e-10, ...
    'Empirical matched-fixed risk reconstruction failed.');

% ------------------------------------------------------------
% Eq. (4) statewise terms
% ------------------------------------------------------------

% H: opportunity from allowing state-specific fixed optima
% instead of one global fixed weight.
Hi = ...
    riskGlobal - riskStar;

% A: allocation error from the adaptive rule's mean weight
% relative to the state-specific fixed optimum.
Ai = ...
    riskMeanW - riskStar;

% C: composition excess risk relative to the matched fixed rule.
XiShared = ...
    (double(U10.shared_adaptive_mse) - ...
     u10FixedMSE) ./ u10V;

% Post-completion pairing-disruption diagnostic.
XiPerm = ...
    (double(U10.shared_permuted_weight_mse) - ...
     u10FixedMSE) ./ u10V;

% Role-separated composition diagnostic.
XiRole = ...
    double(U10.shared_tax_weight_heterogeneity) ./ u10V;

% ------------------------------------------------------------
% Aggregate Eq. (4) quantities
% ------------------------------------------------------------

H = mean(Hi,'omitnan');
A = mean(Ai,'omitnan');

Cshared = mean(XiShared,'omitnan');
Cperm   = mean(XiPerm,'omitnan');
Crole   = mean(XiRole,'omitnan');

costShared = A + Cshared;
costPerm   = A + Cperm;
costRole   = A + Crole;

marginShared = H - costShared;
marginPerm   = H - costPerm;
marginRole   = H - costRole;

% Statewise contributions plotted in Panel B.
stateOpp  = Hi;
stateCost = Ai + XiShared;

% ------------------------------------------------------------
% State-to-aggregate closure
% ------------------------------------------------------------

assert( ...
    abs(mean(stateOpp,'omitnan') - H) < 1e-12, ...
    'Statewise opportunity contributions do not close to H.');

assert( ...
    abs(mean(stateCost,'omitnan') - costShared) < 1e-12, ...
    'Statewise cost contributions do not close to A+C.');

% ------------------------------------------------------------
% Corrected empirical fingerprints
% ------------------------------------------------------------

assert(abs(H - 0.082867) < 5e-6, ...
    'Corrected empirical H fingerprint mismatch.');

assert(abs(A - 0.015085) < 5e-6, ...
    'Corrected empirical A fingerprint mismatch.');

assert(abs(Cshared - 0.21760208) < 5e-7, ...
    'Shared C fingerprint mismatch.');

assert(abs(Cperm - 0.03214915) < 5e-7, ...
    'Permutation C fingerprint mismatch.');

assert(abs(marginShared - (-0.149820)) < 5e-6, ...
    'Corrected shared margin fingerprint mismatch.');

assert(abs(marginPerm - 0.035633) < 5e-6, ...
    'Corrected permutation margin fingerprint mismatch.');

%% FIGURE
fig = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[45 45 1080 430], ...
    'Renderer','painters', ...
    'Name','CMDO Figure 4 — PRESERVE', ...
    'NumberTitle','off');

annotation(fig,'textbox',[0.22 0.944 0.56 0.045], ...
    'String','Evidence value must survive adaptation', ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',20, ...
    'FontWeight','bold', ...
    'Color',DARK);

panelA = [0.018 0.055 0.590 0.855];
panelB = [0.615 0.055 0.374 0.855];

annotation(fig,'rectangle',panelA, ...
    'Color',BORDER_RED, ...
    'LineWidth',1.2);

annotation(fig,'rectangle',panelB, ...
    'Color',BORDER_PURPLE, ...
    'LineWidth',1.2);

annotation(fig,'textbox',[0.038 0.823 0.045 0.075], ...
    'String','A', ...
    'EdgeColor','none', ...
    'FontName',FONT, ...
    'FontSize',28, ...
    'FontWeight','bold', ...
    'Color',RED);

annotation(fig,'textbox',[0.080 0.835 0.42 0.055], ...
    'String','Adaptation can consume fixed-use value', ...
    'EdgeColor','none', ...
    'FontName',FONT, ...
    'FontSize',14.5, ...
    'FontWeight','bold', ...
    'Color',RED);

annotation(fig,'textbox',[0.620 0.823 0.045 0.075], ...
    'String','B', ...
    'EdgeColor','none', ...
    'FontName',FONT, ...
    'FontSize',28, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

annotation(fig,'textbox',[0.670 0.812 0.305 0.085], ...
    'String',{'Adaptation improves on best fixed only','when H > A + C'}, ...
    'EdgeColor','none', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',13.6, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

%% PANEL A
axA = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',[0.070 0.175 0.520 0.575]);

hold(axA,'on');
box(axA,'off');
hideToolbarSafe(axA);

yline(axA,1,'--', ...
    'Color',[0.42 0.42 0.42], ...
    'LineWidth',1.0, ...
    'HandleVisibility','off');

xline(axA,5,'-', ...
    'Color',[0.89 0.89 0.89], ...
    'LineWidth',0.85, ...
    'HandleVisibility','off');

xline(axA,10,'-', ...
    'Color',[0.89 0.89 0.89], ...
    'LineWidth',0.85, ...
    'HandleVisibility','off');

for i = 1:numel(xAll)
    plot(axA, ...
        [xAll(i) xAll(i)], ...
        [riskFixed(i) riskAdapt(i)], ...
        '-', ...
        'Color',[0.70 0.70 0.70], ...
        'LineWidth',1.55, ...
        'HandleVisibility','off');
end

hFixed = scatter(axA, ...
    xAll,riskFixed, ...
    58,'s','filled', ...
    'MarkerFaceColor',GREEN, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.75);

hAdapt = scatter(axA, ...
    xAll,riskAdapt, ...
    65,'o','filled', ...
    'MarkerFaceColor',RED, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.75);

text(axA,mean(x1),1.263,'External system (U9B)', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',10.0, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

text(axA,mean(x2),1.263,'Georgia', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',10.0, ...
    'FontWeight','bold', ...
    'Color',GREEN);

text(axA,mean(x3),1.263,'CPSC 2018', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',10.0, ...
    'FontWeight','bold', ...
    'Color',RED);

text(axA,6,1.012,'Direct baseline, R/V = 1', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontName',FONT, ...
    'FontSize',9.1, ...
    'Color',GREY);

text(axA,13.65,0.615, ...
    sprintf('adaptive worse: %d/12 states',adaptiveWorse), ...
    'HorizontalAlignment','right', ...
    'FontName',FONT, ...
    'FontSize',10.0, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

text(axA,13.65,0.565, ...
    sprintf('fixed benefit \\rightarrow adaptive harm: %d/12',benefitToHarm), ...
    'Interpreter','tex', ...
    'HorizontalAlignment','right', ...
    'FontName',FONT, ...
    'FontSize',10.0, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

set(axA, ...
    'XLim',[0.45 14.55], ...
    'YLim',[0.50 1.30], ...
    'XTick',xAll, ...
    'XTickLabel',string([budgets budgets budgets]), ...
    'YTick',0.5:0.1:1.3, ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.95);

xtickangle(axA,0);

xlabel(axA, ...
    'Audited outcomes, m', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel(axA, ...
    'Normalized risk, R/V', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

legend(axA,[hFixed hAdapt], ...
    {'Matched fixed reuse','Adaptive reuse'}, ...
    'Location','southwest', ...
    'Box','off', ...
    'FontName',FONT, ...
    'FontSize',9.0);

%% PANEL B — ADAPTATION FRONTIER
axB = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',[0.685 0.190 0.245 0.545]);

hold(axB,'on');
box(axB,'off');
hideToolbarSafe(axB);

% Dynamic square range, rounded to the next 0.05.
allFrontierVals = [ ...
    stateCost(:); ...
    stateOpp(:); ...
    costShared; ...
    costPerm; ...
    H];

limB = max(0.35, ...
    ceil(1.08*max(allFrontierVals,[],'omitnan')/0.05)*0.05);

% H = A + C frontier.
plot(axB,[0 limB],[0 limB],'--', ...
    'Color',[0.42 0.42 0.42], ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

% Eight frozen statewise contributions.
hGaState = scatter(axB, ...
    stateCost(idxGa), ...
    stateOpp(idxGa), ...
    45,'s','filled', ...
    'MarkerFaceColor',GREEN_STATE, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.75);

hCpState = scatter(axB, ...
    stateCost(idxCp), ...
    stateOpp(idxCp), ...
    60,'o','filled', ...
    'MarkerFaceColor',RED_STATE, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.75);

% Aggregate Eq. (4) location.
% Use an open triangle so an underlying state point remains visible.
hMean = scatter(axB, ...
    costShared,H, ...
    145,'^', ...
    'MarkerFaceColor','none', ...
    'MarkerEdgeColor',DARK, ...
    'LineWidth',1.8);

% Pairing-disruption diagnostic.
hPerm = scatter(axB, ...
    costPerm,H, ...
    92,'d','filled', ...
    'MarkerFaceColor',PURPLE, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.85);

% Horizontal shift caused by reducing composition cost.
quiver(axB, ...
    costShared,H, ...
    costPerm-costShared,0, ...
    0, ...
    'Color',PURPLE, ...
    'LineWidth',2.0, ...
    'MaxHeadSize',0.30, ...
    'HandleVisibility','off');

% Minimal direct labels only for the two aggregate locations.
text(axB, ...
    costShared+0.014,H-0.014, ...
    '8-state mean', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',FONT, ...
    'FontSize',8.8, ...
    'FontWeight','bold', ...
    'Color',DARK);

text(axB, ...
    costPerm+0.010,H+0.012, ...
    'pairing disrupted', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'FontName',FONT, ...
    'FontSize',8.6, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

% Frontier label.
frontierX = 0.54*limB;
text(axB, ...
    frontierX,frontierX+0.012, ...
    'H = A + C', ...
    'Rotation',45, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontName',FONT, ...
    'FontSize',8.4, ...
    'FontWeight','bold', ...
    'Color',GREY);

% Compact cohort legend placed above the axes, not on top of the data.
lgB = legend(axB,[hGaState hCpState], ...
    {'Georgia: 4 budgets','CPSC 2018: 4 budgets'}, ...
    'Orientation','horizontal', ...
    'Box','off', ...
    'FontName',FONT, ...
    'FontSize',8.1);

set(lgB, ...
    'Units','normalized', ...
    'Position',[0.685 0.742 0.255 0.030]);

set(axB, ...
    'XLim',[0 limB], ...
    'YLim',[0 limB], ...
    'XTick',0:0.05:limB, ...
    'YTick',0:0.05:limB, ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.95);

axis(axB,'square');

xlabel(axB, ...
    'Cost contribution (A + C)', ...
    'FontName',FONT, ...
    'FontSize',10.2);

ylabel(axB, ...
    'Opportunity contribution (H)', ...
    'FontName',FONT, ...
    'FontSize',10.2);

%% EXPORT
drawnow;

pngPath = fullfile(outputDir,'Figure4_PRESERVE_Refined.png');
pdfPath = fullfile(outputDir,'Figure4_PRESERVE_Refined.pdf');
figPath = fullfile(outputDir,'Figure4_PRESERVE_Refined.fig');

savefig(fig,figPath);

exportgraphics(fig,pngPath, ...
    'Resolution',300, ...
    'BackgroundColor','white');

exportgraphics(fig,pdfPath, ...
    'ContentType','vector', ...
    'BackgroundColor','white');

fprintf('\n============================================================\n');
fprintf('FIGURE 4 — PRESERVE REFINED\n');
fprintf('============================================================\n');

fprintf('Adaptive worse than matched fixed : %d/12\n',adaptiveWorse);
fprintf('Fixed benefit -> adaptive harm    : %d/12\n',benefitToHarm);

fprintf('\nAdaptation frontier\n');
fprintf('H                  : %.8f\n',H);
fprintf('A                  : %.8f\n',A);
fprintf('C shared           : %.8f\n',Cshared);
fprintf('C pairing-disrupt  : %.8f\n',Cperm);
fprintf('C role-separated   : %.8f\n',Crole);

fprintf('\nMargins H-(A+C)\n');
fprintf('Shared adaptive    : %.8f\n',marginShared);
fprintf('Pairing disrupted  : %.8f\n',marginPerm);
fprintf('Role separated     : %.8f\n',marginRole);

fprintf('\nPanel B state-to-aggregate closure\n');
fprintf('mean(state opportunity) : %.8f\n',mean(stateOpp,'omitnan'));
fprintf('mean(state cost)        : %.8f\n',mean(stateCost,'omitnan'));

fprintf('\nSaved\n');
fprintf('PNG : %s\n',pngPath);
fprintf('PDF : %s\n',pdfPath);
fprintf('FIG : %s\n',figPath);

fprintf('============================================================\n\n');

end

%% ========================================================================
% HELPERS
% ========================================================================

function hideToolbarSafe(ax)
try
    ax.Toolbar.Visible = 'off';
catch
    try
        axtoolbar(ax,{});
    catch
    end
end
end

function repoRoot = local_find_cmdo_repo(startDir)

repoRoot = '';
p = startDir;

for k = 1:8

    candidate = fullfile(p,'U10_Prospective_ECG');

    if isfolder(candidate)
        repoRoot = p;
        return;
    end

    parent = fileparts(p);

    if isempty(parent) || strcmp(parent,p)
        break;
    end

    p = parent;
end

end

function local_require_vars(T,vars,label)

missing = vars(~ismember(vars,T.Properties.VariableNames));

if ~isempty(missing)
    error('%s missing variables: %s', ...
        label, ...
        strjoin(missing,', '));
end

end
