function Figure4_PRESERVE_Refined(outputDir)
% ============================================================
% FIGURE 4 — PRESERVE
% Evidence value must survive adaptation
%
% A | Adaptation can erase fixed-use gains
% B | Theory tracks observed adaptive value
% ============================================================

close all;

%% OUTPUT
thisFile = mfilename('fullpath');
if isempty(thisFile)
    scriptDir = pwd;
else
    scriptDir = fileparts(thisFile);
end
if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(scriptDir,'output');
end
if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

%% STYLE
FONT = 'Arial';
FS_AXIS  = 11.5;
FS_TICK  = 10.0;
FS_SMALL = 8.8;

DARK   = [0.18 0.18 0.18];
GREY   = [0.45 0.45 0.45];
GREEN  = [0.00 0.50 0.18];
RED    = [0.88 0.07 0.06];
PURPLE = [0.45 0.18 0.78];

BORDER_RED    = [0.96 0.77 0.77];
BORDER_PURPLE = [0.88 0.80 0.96];

%% DATA
budgets = [128 256 512 1024];

riskFixed_u9b = [0.920 0.975 1.007 1.026];
riskAdapt_u9b = [1.019 1.091 1.078 1.156];

riskFixed_ga  = [0.545 0.678 0.850 0.849];
riskAdapt_ga  = [0.690 0.848 1.113 1.105];

riskFixed_cp  = [0.667 0.788 0.954 0.890];
riskAdapt_cp  = [0.899 1.084 1.193 1.033];

riskFixed = [riskFixed_u9b riskFixed_ga riskFixed_cp];
riskAdapt = [riskAdapt_u9b riskAdapt_ga riskAdapt_cp];

x1 = 1:4;
x2 = 6:9;
x3 = 11:14;
xAll = [x1 x2 x3];

adaptiveWorse = nnz(riskAdapt > riskFixed);
benefitToHarm = nnz((riskFixed < 1) & (riskAdapt > 1));

assert(adaptiveWorse == 12);
assert(benefitToHarm == 7);

pred_ga = [0.065953 -0.046493 -0.259004 -0.256578];
obs_ga  = [0.079285 -0.047034 -0.265122 -0.253994];

pred_cp = [-0.148460 -0.297085 -0.233287 0.010954];
obs_cp  = [-0.121781 -0.278424 -0.232492 -0.069003];

predAll = [pred_ga pred_cp];
obsAll  = [obs_ga obs_cp];

winnerAgreement = nnz(sign(predAll) == sign(obsAll));
rmseClosure = sqrt(mean((predAll-obsAll).^2));

assert(winnerAgreement == 7);

%% FIGURE
fig = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',[45 45 1000 400], ...
    'Renderer','painters', ...
    'Name','CMDO Figure 4 — PRESERVE', ...
    'NumberTitle','off');

annotation(fig,'textbox',[0.22 0.944 0.56 0.045], ...
    'String','Evidence value must survive adaptation', ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',21, ...
    'FontWeight','bold', ...
    'Color',DARK);

panelA = [0.018 0.055 0.590 0.855];
panelB = [0.615 0.055 0.374 0.855];

annotation(fig,'rectangle',panelA, ...
    'Color',BORDER_RED, ...
    'LineWidth',1.2);

annotation(fig,'rectangle',panelB, ...
    'Color',BORDER_PURPLE, ...
    'LineWidth',1.2);

annotation(fig,'textbox',[0.038 0.825 0.045 0.07], ...
    'String','A', ...
    'EdgeColor','none', ...
    'FontName',FONT, ...
    'FontSize',29, ...
    'FontWeight','bold', ...
    'Color',RED);

annotation(fig,'textbox',[0.080 0.835 0.42 0.055], ...
    'String','Adaptation can erase fixed-use gains', ...
    'EdgeColor','none', ...
    'FontName',FONT, ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'Color',RED);

annotation(fig,'textbox',[0.620 0.825 0.045 0.07], ...
    'String','B', ...
    'EdgeColor','none', ...
    'FontName',FONT, ...
    'FontSize',29, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

annotation(fig,'textbox',[0.670 0.828 0.32 0.065], ...
    'String','Adaptation frontier predicts strategy advantage', ...
    'EdgeColor','none', ...
    'FontName',FONT, ...
    'FontSize',14.2, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

%% PANEL A
axA = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',[0.070 0.170 0.520 0.590]);

hold(axA,'on');
box(axA,'off');
hideToolbarSafe(axA);

yline(axA,1,'--', ...
    'Color',[0.42 0.42 0.42], ...
    'LineWidth',1.0, ...
    'HandleVisibility','off');

xline(axA,5,'-', ...
    'Color',[0.89 0.89 0.89], ...
    'LineWidth',0.85, ...
    'HandleVisibility','off');

xline(axA,10,'-', ...
    'Color',[0.89 0.89 0.89], ...
    'LineWidth',0.85, ...
    'HandleVisibility','off');

for i = 1:numel(xAll)
    plot(axA, ...
        [xAll(i) xAll(i)], ...
        [riskFixed(i) riskAdapt(i)], ...
        '-', ...
        'Color',[0.70 0.70 0.70], ...
        'LineWidth',1.55, ...
        'HandleVisibility','off');
end

hFixed = scatter(axA, ...
    xAll,riskFixed, ...
    58,'s','filled', ...
    'MarkerFaceColor',GREEN, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.75);

hAdapt = scatter(axA, ...
    xAll,riskAdapt, ...
    65,'o','filled', ...
    'MarkerFaceColor',RED, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.75);

text(axA,mean(x1),1.263,'External system (U9B)', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',10.2, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

text(axA,mean(x2),1.263,'Georgia', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',10.2, ...
    'FontWeight','bold', ...
    'Color',GREEN);

text(axA,mean(x3),1.263,'CPSC 2018', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',10.2, ...
    'FontWeight','bold', ...
    'Color',RED);

text(axA,7.65,1.012,'Direct baseline, R/V = 1', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontName',FONT, ...
    'FontSize',9.3, ...
    'Color',GREY);

text(axA,13.65,0.615, ...
    sprintf('adaptive worse: %d/12 states',adaptiveWorse), ...
    'HorizontalAlignment','right', ...
    'FontName',FONT, ...
    'FontSize',10.2, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

text(axA,13.65,0.565, ...
    sprintf('fixed benefit \\rightarrow adaptive harm: %d/12',benefitToHarm), ...
    'Interpreter','tex', ...
    'HorizontalAlignment','right', ...
    'FontName',FONT, ...
    'FontSize',10.2, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

set(axA, ...
    'XLim',[0.45 14.55], ...
    'YLim',[0.50 1.30], ...
    'XTick',xAll, ...
    'XTickLabel',string([budgets budgets budgets]), ...
    'YTick',0.5:0.1:1.3, ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.95);

xtickangle(axA,0);

xlabel(axA, ...
    'Audited outcomes, m', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel(axA, ...
    'Normalized risk, R/V', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

legend(axA,[hFixed hAdapt], ...
    {'Matched fixed reuse','Adaptive reuse'}, ...
    'Location','southwest', ...
    'Box','off', ...
    'FontName',FONT, ...
    'FontSize',9.2);

%% PANEL B
axB = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',[0.680 0.175 0.225 0.585]);

hold(axB,'on');
box(axB,'off');
hideToolbarSafe(axB);

lims = [-0.33 0.11];

xline(axB,0,'-', ...
    'Color',[0.88 0.88 0.88], ...
    'LineWidth',0.9, ...
    'HandleVisibility','off');

yline(axB,0,'-', ...
    'Color',[0.88 0.88 0.88], ...
    'LineWidth',0.9, ...
    'HandleVisibility','off');

plot(axB,lims,lims,'--', ...
    'Color',[0.40 0.40 0.40], ...
    'LineWidth',1.15, ...
    'HandleVisibility','off');

hGa = scatter(axB, ...
    pred_ga,obs_ga, ...
    64,'s','filled', ...
    'MarkerFaceColor',GREEN, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.75);

hCp = scatter(axB, ...
    pred_cp,obs_cp, ...
    64,'o','filled', ...
    'MarkerFaceColor',RED, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.75);

gLabels = {'G128','G256','G512','G1024'};
cLabels = {'C128','C256','C512','C1024'};

gDx = [0.010 0.010 0.010 0.012];
gDy = [0.006 0.010 -0.012 -0.005];

cDx = [-0.032 0.010 0.010 0.010];
cDy = [0.020 -0.015 -0.005 -0.014];

for k = 1:4

    text(axB, ...
        pred_ga(k)+gDx(k), ...
        obs_ga(k)+gDy(k), ...
        gLabels{k}, ...
        'FontName',FONT, ...
        'FontSize',8.5, ...
        'FontWeight','bold', ...
        'Color',GREEN);

    text(axB, ...
        pred_cp(k)+cDx(k), ...
        obs_cp(k)+cDy(k), ...
        cLabels{k}, ...
        'FontName',FONT, ...
        'FontSize',8.5, ...
        'FontWeight','bold', ...
        'Color',RED);

end

set(axB, ...
    'XLim',lims, ...
    'YLim',lims, ...
    'XTick',[-0.3 -0.2 -0.1 0 0.1], ...
    'YTick',[-0.3 -0.25 -0.2 -0.15 -0.1 -0.05 0 0.05 0.1], ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.95);

axis(axB,'square');

xlabel(axB, ...
    'Predicted adaptive advantage, H - A - C', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel(axB, ...
    'Observed adaptive advantage', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

legend(axB,[hGa hCp], ...
    {'Georgia','CPSC 2018'}, ...
    'Location','northwest', ...
    'Box','off', ...
    'FontName',FONT, ...
    'FontSize',9.1);

text(axB,0.96,0.055, ...
    sprintf('sign agreement: %d/8',winnerAgreement), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'FontName',FONT, ...
    'FontSize',9.7, ...
    'FontWeight','bold', ...
    'Color',PURPLE);

%% EXPORT
drawnow;

pngPath = fullfile(outputDir,'Figure4_PRESERVE_Refined.png');
pdfPath = fullfile(outputDir,'Figure4_PRESERVE_Refined.pdf');
figPath = fullfile(outputDir,'Figure4_PRESERVE_Refined.fig');

savefig(fig,figPath);

exportgraphics(fig,pngPath, ...
    'Resolution',300, ...
    'BackgroundColor','white');

exportgraphics(fig,pdfPath, ...
    'ContentType','vector', ...
    'BackgroundColor','white');

fprintf('\n============================================================\n');
fprintf('FIGURE 4 — PRESERVE REFINED\n');
fprintf('============================================================\n');
fprintf('Adaptive worse than matched fixed : %d/12\n',adaptiveWorse);
fprintf('Fixed benefit -> adaptive harm    : %d/12\n',benefitToHarm);
fprintf('Winner agreement                  : %d/8\n',winnerAgreement);
fprintf('Closure RMSE                      : %.6f\n',rmseClosure);
fprintf('PNG : %s\n',pngPath);
fprintf('PDF : %s\n',pdfPath);
fprintf('FIG : %s\n',figPath);
fprintf('============================================================\n\n');

end

function hideToolbarSafe(ax)
try
    ax.Toolbar.Visible = 'off';
catch
    try
        axtoolbar(ax,{});
    catch
    end
end
end
