function Figure3_REUSE_Validation(outputDir, repoRoot)
% FIGURE3_REUSE_VALIDATION
% CMDO Figure 3 — REUSE validation
%
% Final scientific role:
%   A) Frozen confirmation in cross-domain and clinical settings
%   B) Current-audit discrepancy tracks later-revealed historical mismatch |B|
%   C) The REUSE admissibility boundary separates observed benefit from harm
%   D) Predicted fixed-use risk is compared directly with observed risk
%
% Usage:
%   Figure3_REUSE_Validation(outputDir, repoRoot)
close all;

%% ------------------------------------------------------------------------
% 0. STYLE
% -------------------------------------------------------------------------

FONT = 'Arial';

FS_LETTER = 21;
FS_TITLE  = 10.5;
FS_AXIS   = 9.0;
FS_TICK   = 8.6;
FS_SMALL  = 8.5;
FS_TINY   = 7.6;

navy   = [0.02 0.24 0.63];
blue   = [0.02 0.29 0.70];

green  = [0.02 0.48 0.20];
teal   = [0.02 0.45 0.38];

orange = [0.93 0.27 0.08];
red    = [0.82 0.05 0.04];
purple = [0.43 0.17 0.70];

grey   = [0.42 0.42 0.42];
dgrey  = [0.22 0.22 0.22];

panelGreen = local_mix(green,[1 1 1],0.74);

clinicalColor = [0.05 0.52 0.20];

stageOrder = ["U6","U7","U8","U9A","U9B"];

stageLabels = { ...
    'Cross-domain', ...
    'Clinical', ...
    'Temporal', ...
    'External bridge', ...
    'External system'};

stageColors = [ ...
    0.02 0.29 0.70; ...
    0.02 0.48 0.20; ...
    0.43 0.17 0.70; ...
    0.93 0.45 0.08; ...
    0.82 0.05 0.04];

stageMarkers = {'o','s','d','^','p'};

familyOrder = [ ...
    "ACS_PUBLIC_COVERAGE_2024", ...
    "MEDICAL_DERMOSCOPY", ...
    "NATURAL_IMAGE"];

familyColors = [ ...
    0.1216 0.4667 0.7059; ...
    1.0000 0.4980 0.0549; ...
    0.8392 0.1529 0.1569];

%% ------------------------------------------------------------------------
% 1. OUTPUT / REPOSITORY
% -------------------------------------------------------------------------

thisFile = mfilename('fullpath');

if isempty(thisFile)
    scriptDir = pwd;
else
    scriptDir = fileparts(thisFile);
end

if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(scriptDir,'output');
end

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

if nargin < 2 || isempty(repoRoot)
    repoRoot = fileparts(fileparts(scriptDir));
end

assert(isfolder(fullfile(repoRoot,'source_data')), ...
    'Reviewer repository root is invalid.');

addpath(scriptDir);

fprintf('\n============================================================\n');
fprintf(' CMDO FIGURE 3 — REUSE\n');
fprintf(' REUSE theory tested against frozen deployment states\n');
fprintf('============================================================\n');
fprintf('Repository : %s\n',repoRoot);
fprintf('Output     : %s\n',outputDir);

%% ------------------------------------------------------------------------
% 2. LOAD FROZEN U6 / U7 TABLES
% -------------------------------------------------------------------------

D = cmdo_submission_load(repoRoot);

%% ------------------------------------------------------------------------
% 3. U6 CROSS-DOMAIN CONFIRMATION
% -------------------------------------------------------------------------

U6raw = D.u6_target;

u6Observer = double(U6raw.mae);
u6Direct   = double(U6raw.direct_mae);

u6RelGain = ...
    100 .* double(U6raw.gain_vs_full_direct) ./ u6Direct;

u6PooledObserver = ...
    mean(double(D.u6_state.mae),'omitnan');

u6PooledDirect = ...
    mean(double(D.u6_state.direct_mae),'omitnan');

u6PooledGain = ...
    100 .* ...
    (u6PooledDirect-u6PooledObserver) ./ ...
    u6PooledDirect;

% Sort only for display.
[u6DisplayGain,~] = ...
    sort(u6RelGain,'descend');

%% ------------------------------------------------------------------------
% 4. U7 CLINICAL CONFIRMATION
% -------------------------------------------------------------------------

metricCol7T = ...
    local_find_var(D.u7_target,{'metric'});

if isempty(metricCol7T)
    error('U7 target table missing metric.');
end

U7 = ...
    D.u7_target( ...
    string(D.u7_target.(metricCol7T))=="AUC",:);

u7RelGain = ...
    100 .* double(U7.gain) ./ ...
    double(U7.direct_mae);

[u7DisplayGain,~] = ...
    sort(u7RelGain,'descend');

metricCol7M = ...
    local_find_var(D.u7_metric,{'metric'});

rowAUC = ...
    find( ...
    string(D.u7_metric.(metricCol7M))=="AUC", ...
    1,'first');

if isempty(rowAUC)
    error('AUC row absent in U7 metric table.');
end

u7PooledGain = ...
    100 .* double( ...
    D.u7_metric.relative_gain(rowAUC));

metricCol7S = ...
    local_find_var(D.u7_state,{'metric'});

S7AUC = ...
    D.u7_state( ...
    string(D.u7_state.(metricCol7S))=="AUC",:);

%% ------------------------------------------------------------------------
% 5. AUDIT-MISMATCH / HISTORICAL-ERROR RELATION
% -------------------------------------------------------------------------

maxBudget6 = ...
    max(double(D.u6_state.budget),[],'omitnan');

M6 = ...
    D.u6_state( ...
    double(D.u6_state.budget)==maxBudget6,:);

x6 = double(M6.mean_sensor_abs_gap);
y6 = double(M6.transport_abs_error);
fam6 = string(M6.family);

rho6 = local_spearman(x6,y6);

maxBudget7 = ...
    max(double(S7AUC.budget),[],'omitnan');

M7 = ...
    S7AUC( ...
    double(S7AUC.budget)==maxBudget7,:);

x7 = double(M7.mean_sensor_gap);
y7 = double(M7.transport_abs_error);

rho7 = local_spearman(x7,y7);

%% ------------------------------------------------------------------------
% 6. 185-STATE EVIDENCE-ADMISSIBILITY SYNTHESIS
% -------------------------------------------------------------------------

statePath = ...
    fullfile( ...
    repoRoot, ...
    'source_data', ...
    'figure6_admissibility', ...
    'CMDO_Admissibility_State_MSE_Audit.csv');

if ~isfile(statePath)

    error( ...
        'Missing 185-state synthesis file:\n%s', ...
        statePath);

end

T = readtable(statePath);

local_require_vars( ...
    T, ...
    {'stage', ...
     'mean_weight', ...
     'lambda_ean', ...
     'mse_gain_pct', ...
     'scalar_risk_ratio_at_meanweight'}, ...
    '185-state synthesis');

stageName = string(T.stage);

wState = ...
    double(T.mean_weight);

lambdaState = ...
    double(T.lambda_ean);

gObserved = ...
    double(T.mse_gain_pct);

riskReconstructed = ...
    (1-wState).^2 + ...
    lambdaState .* wState.^2;

gPredicted = ...
    100 .* (1-riskReconstructed);

% Express the observed statewise MSE in the same normalized-risk
% coordinates as Eq. (2): R/V = 1 - gain/100.
riskObserved = ...
    1 - gObserved./100;

storedRatio = ...
    double(T.scalar_risk_ratio_at_meanweight);

ratioResidual = ...
    max( ...
    abs( ...
    riskReconstructed-storedRatio), ...
    [],'omitnan');

assert( ...
    height(T)==185, ...
    'Expected 185 frozen states.');

assert( ...
    ratioResidual < 1e-10, ...
    '185-state scalar-risk reconstruction mismatch.');

signConcordant = ...
    local_sign_concordance( ...
    gPredicted,gObserved);

signN = nnz(signConcordant);

rho185 = ...
    local_spearman( ...
    gPredicted,gObserved);

stageMedPred = ...
    nan(numel(stageOrder),1);

stageMedObs = ...
    nan(numel(stageOrder),1);

for s = 1:numel(stageOrder)

    m = ...
        stageName==stageOrder(s);

    stageMedPred(s) = ...
        median(gPredicted(m),'omitnan');

    stageMedObs(s) = ...
        median(gObserved(m),'omitnan');

end

% The affine conversion preserves the stage medians exactly.
stageMedPredRisk = ...
    1 - stageMedPred./100;

stageMedObsRisk = ...
    1 - stageMedObs./100;

%% ------------------------------------------------------------------------
% 7. FIGURE CANVAS
% -------------------------------------------------------------------------

fig = figure( ...
    'Color','w', ...
    'Position',[60 45 1000 800], ...
    'Renderer','painters', ...
    'Name','CMDO Figure 3 — REUSE', ...
    'NumberTitle','off');

pA = uipanel( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.025 0.515 0.465 0.460], ...
    'BackgroundColor','w', ...
    'BorderType','none');

pB = uipanel( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.510 0.515 0.465 0.460], ...
    'BackgroundColor','w', ...
    'BorderType','none');

pC = uipanel( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.025 0.040 0.465 0.445], ...
    'BackgroundColor','w', ...
    'BorderType','none');

pD = uipanel( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.510 0.040 0.465 0.445], ...
    'BackgroundColor','w', ...
    'BorderType','none');

%% ========================================================================
% PANEL A — FROZEN CONFIRMATION
% ========================================================================

axA0 = axes( ...
    'Parent',pA, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);

axis(axA0,[0 1 0 1]);
axis(axA0,'off');
hold(axA0,'on');

local_panel_border( ...
    axA0, ...
    [0.005 0.005 0.99 0.99], ...
    panelGreen, ...
    1.05);

local_panel_header( ...
    axA0, ...
    'A', ...
    'Frozen confirmation', ...
    0.025,0.955, ...
    green,FONT, ...
    FS_LETTER,FS_TITLE);

% Shared y limits for direct comparison.
allConfirmationGain = ...
    [u6DisplayGain(:);u7DisplayGain(:)];

% Cross-version-safe finite-value handling
validConfirmationGain = ...
    allConfirmationGain(isfinite(allConfirmationGain));

if isempty(validConfirmationGain)
    error('No finite confirmation-gain values were found.');
end

yMinA = ...
    min(0,min(validConfirmationGain));

yMaxA = ...
    max(validConfirmationGain);

ySpanA = ...
    max(yMaxA-yMinA,1);

yLimA = [ ...
    yMinA-0.08*ySpanA, ...
    yMaxA+0.18*ySpanA];

% U6
axA1 = axes( ...
    'Parent',pA, ...
    'Units','normalized', ...
    'Position',[0.120 0.205 0.365 0.610]);

hold(axA1,'on');

plot( ...
    axA1, ...
    [0.5 16.5], ...
    [0 0], ...
    '--', ...
    'Color',[0.45 0.45 0.45], ...
    'LineWidth',0.8);

scatter( ...
    axA1, ...
    1:16, ...
    u6DisplayGain, ...
    42, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor',blue, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.5);

set( ...
    axA1, ...
    'XLim',[0.5 16.5], ...
    'YLim',yLimA, ...
    'XTick',[1 8 16], ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

xlabel( ...
    axA1, ...
    'Target', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axA1, ...
    'Relative MAE gain vs direct (%)', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

title( ...
    axA1, ...
    'Cross-domain', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.4, ...
    'FontWeight','bold');

text( ...
    axA1, ...
    0.96,0.95, ...
    sprintf('16/16\n+%.2f%%',u6PooledGain), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',blue);

% U7
axA2 = axes( ...
    'Parent',pA, ...
    'Units','normalized', ...
    'Position',[0.585 0.205 0.365 0.610]);

hold(axA2,'on');

plot( ...
    axA2, ...
    [0.5 16.5], ...
    [0 0], ...
    '--', ...
    'Color',[0.45 0.45 0.45], ...
    'LineWidth',0.8);

scatter( ...
    axA2, ...
    1:16, ...
    u7DisplayGain, ...
    42, ...
    's', ...
    'filled', ...
    'MarkerFaceColor',clinicalColor, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.5);

set( ...
    axA2, ...
    'XLim',[0.5 16.5], ...
    'YLim',yLimA, ...
    'XTick',[1 8 16], ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

xlabel( ...
    axA2, ...
    'Clinical stratum', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);
ylabel( ...
    axA2, ...
    'MAE improvement vs direct (%)', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

title( ...
    axA2, ...
    'Clinical transition', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.4, ...
    'FontWeight','bold');

text( ...
    axA2, ...
    0.96,0.95, ...
    sprintf('16/16\n+%.2f%%',u7PooledGain), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',clinicalColor);

%% ========================================================================
% PANEL B — AUDIT DISCREPANCY TRACKS HISTORICAL MISMATCH |B|
% ========================================================================

axB0 = axes( ...
    'Parent',pB, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);

axis(axB0,[0 1 0 1]);
axis(axB0,'off');
hold(axB0,'on');

local_panel_border( ...
    axB0, ...
    [0.005 0.005 0.99 0.99], ...
    panelGreen, ...
    1.05);

local_panel_header( ...
    axB0, ...
    'B', ...
    'Current audit tracks historical mismatch', ...
    0.025,0.955, ...
    green,FONT, ...
    FS_LETTER,FS_TITLE);

% U6
axB1 = axes( ...
    'Parent',pB, ...
    'Units','normalized', ...
    'Position',[0.115 0.205 0.365 0.610]);

hold(axB1,'on');

local_fit_band(axB1,x6,y6);

familyLabels = { ...
    'ACS 2024', ...
    'Dermoscopy', ...
    'Natural image'};

hFam = gobjects(numel(familyOrder),1);

for f = 1:numel(familyOrder)

    m = fam6==familyOrder(f);

    hFam(f) = scatter( ...
        axB1, ...
        x6(m), ...
        y6(m), ...
        30, ...
        'o', ...
        'filled', ...
        'MarkerFaceColor',familyColors(f,:), ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.45, ...
        'DisplayName',familyLabels{f});

end

set( ...
    axB1, ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

xlabel( ...
    axB1, ...
    'Current-audit discrepancy, \delta_{audit}', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axB1, ...
    'Historical mismatch, |B|', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

title( ...
    axB1, ...
    sprintf('Cross-domain   \\rho = %.2f',rho6), ...
    'Interpreter','tex', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold');

legend( ...
    axB1, ...
    hFam, ...
    familyLabels, ...
    'Location','southeast', ...
    'Box','off', ...
    'FontName',FONT, ...
    'FontSize',6.3);

% U7
axB2 = axes( ...
    'Parent',pB, ...
    'Units','normalized', ...
    'Position',[0.600 0.205 0.350 0.610]);

hold(axB2,'on');

local_fit_band(axB2,x7,y7);

scatter( ...
    axB2, ...
    x7,y7, ...
    32, ...
    's', ...
    'filled', ...
    'MarkerFaceColor',clinicalColor, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.45);

set( ...
    axB2, ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

xlabel( ...
    axB2, ...
    'Current-audit discrepancy, \delta_{audit}', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axB2, ...
    'Historical mismatch, |B|', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

title( ...
    axB2, ...
    sprintf('Clinical   \\rho = %.2f',rho7), ...
    'Interpreter','tex', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold');

%% ========================================================================
% PANEL C — THEORY BOUNDARY VERSUS OBSERVED BENEFIT / HARM
% ========================================================================

axC0 = axes( ...
    'Parent',pC, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);

axis(axC0,[0 1 0 1]);
axis(axC0,'off');
hold(axC0,'on');

local_panel_border( ...
    axC0, ...
    [0.005 0.005 0.99 0.99], ...
    panelGreen, ...
    1.05);

local_panel_header( ...
    axC0, ...
    'C', ...
    'Admissibility geometry separates benefit from harm', ...
    0.025,0.955, ...
    green,FONT, ...
    FS_LETTER,FS_TITLE);

axC = axes( ...
    'Parent',pC, ...
    'Units','normalized', ...
    'Position',[0.175 0.205 0.755 0.615]);

hold(axC,'on');

% -------------------------------------------------------------------------
% Theory boundary
%
% Eq. (2) gives beneficial fixed reuse when
%   (1-w)^2 + Lambda*w^2 < 1,
% i.e. for w>0:
%   w < 2/(1+Lambda).
%
% The equation itself is kept out of the artwork and belongs in the caption.
% -------------------------------------------------------------------------

validGeom = ...
    isfinite(lambdaState) & ...
    lambdaState>0 & ...
    isfinite(wState) & ...
    wState>=0 & ...
    wState<=1 & ...
    isfinite(gObserved);

lambdaValid = ...
    lambdaState(validGeom);

if isempty(lambdaValid)
    error('No finite positive Lambda values are available for Panel C.');
end

logMinC = floor(log10(min(lambdaValid)));
logMaxC = ceil(log10(max(lambdaValid)));

if logMinC==logMaxC
    logMinC = logMinC-1;
    logMaxC = logMaxC+1;
end

xMinC = 10.^logMinC;
xMaxC = 10.^logMaxC;

lambdaLine = ...
    logspace(logMinC,logMaxC,600);

wBoundary = ...
    min(2./(1+lambdaLine),1);

% Theory-predicted beneficial region.
patch( ...
    axC, ...
    [lambdaLine fliplr(lambdaLine)], ...
    [zeros(size(wBoundary)) fliplr(wBoundary)], ...
    local_mix(green,[1 1 1],0.87), ...
    'EdgeColor','none', ...
    'FaceAlpha',0.92, ...
    'HandleVisibility','off');

% Theory-predicted harmful region.
patch( ...
    axC, ...
    [lambdaLine fliplr(lambdaLine)], ...
    [wBoundary fliplr(ones(size(wBoundary)))], ...
    local_mix(red,[1 1 1],0.91), ...
    'EdgeColor','none', ...
    'FaceAlpha',0.92, ...
    'HandleVisibility','off');

plot( ...
    axC, ...
    lambdaLine,wBoundary, ...
    '--', ...
    'Color',[0.18 0.18 0.18], ...
    'LineWidth',1.20, ...
    'HandleVisibility','off');

% -------------------------------------------------------------------------
% Actual observed outcome:
% green = reuse empirically helped;
% red   = reuse empirically hurt.
% -------------------------------------------------------------------------

obsBenefit = ...
    validGeom & ...
    gObserved>0;

obsHarm = ...
    validGeom & ...
    gObserved<0;

obsNeutral = ...
    validGeom & ...
    gObserved==0;

hBenefit = scatter( ...
    axC, ...
    lambdaState(obsBenefit), ...
    wState(obsBenefit), ...
    24, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor',green, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.35, ...
    'DisplayName','Observed benefit');

hHarm = scatter( ...
    axC, ...
    lambdaState(obsHarm), ...
    wState(obsHarm), ...
    26, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor',red, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.35, ...
    'DisplayName','Observed harm');

if any(obsNeutral)

    hNeutral = scatter( ...
        axC, ...
        lambdaState(obsNeutral), ...
        wState(obsNeutral), ...
        24, ...
        'o', ...
        'filled', ...
        'MarkerFaceColor',grey, ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.35, ...
        'DisplayName','Observed neutral');

else

    hNeutral = gobjects(0);

end

% Outline the states for which the theory and observed benefit direction
% disagree. The 185-state frozen synthesis gives four such states.
misMask = ...
    validGeom & ...
    ~signConcordant;

if any(misMask)

    scatter( ...
        axC, ...
        lambdaState(misMask), ...
        wState(misMask), ...
        68, ...
        'o', ...
        'MarkerFaceColor','none', ...
        'MarkerEdgeColor',dgrey, ...
        'LineWidth',1.15, ...
        'HandleVisibility','off');

end

set( ...
    axC, ...
    'XScale','log', ...
    'XLim',[xMinC xMaxC], ...
    'YLim',[0 1], ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

axC.XTickLabelRotation = 0;

xlabel( ...
    axC, ...
    'Evidence-admissibility coordinate, \Lambda', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axC, ...
    'Borrowing weight, w', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);
ylim([0 0.2]);

text( ...
    axC, ...
    0.04,0.91, ...
    'reuse predicted to help', ...
    'Units','normalized', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY, ...
    'FontWeight','bold', ...
    'Color',green);

text( ...
    axC, ...
    0.98,0.91, ...
    {'reuse predicted' ...
    ' to hurt'}, ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY, ...
    'FontWeight','bold', ...
    'Color',red);

text( ...
    axC, ...
    0.96,1.05, ...
    sprintf('sign agreement: %d/185',signN), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',green, ...
    'BackgroundColor','w');

if isempty(hNeutral)

    legend( ...
        axC, ...
        [hBenefit hHarm], ...
        {'Observed benefit','Observed harm'}, ...
        'Location','southwest', ...
        'Box','off', ...
        'FontName',FONT, ...
        'FontSize',6.8);

else

    legend( ...
        axC, ...
        [hBenefit hHarm hNeutral], ...
        {'Observed benefit','Observed harm','Observed neutral'}, ...
        'Location','southwest', ...
        'Box','off', ...
        'FontName',FONT, ...
        'FontSize',6.8);

end

%% ========================================================================
% PANEL D — THEORY VERSUS OBSERVED FIXED-USE RISK
% ========================================================================

axD0 = axes( ...
    'Parent',pD, ...
    'Units','normalized', ...
    'Position',[0 0 1 1]);

axis(axD0,[0 1 0 1]);
axis(axD0,'off');
hold(axD0,'on');

local_panel_border( ...
    axD0, ...
    [0.005 0.005 0.99 0.99], ...
    panelGreen, ...
    1.05);

local_panel_header( ...
    axD0, ...
    'D', ...
    'Predicted and observed fixed-use risk', ...
    0.025,0.955, ...
    green,FONT, ...
    FS_LETTER,FS_TITLE);

axD = axes( ...
    'Parent',pD, ...
    'Units','normalized', ...
    'Position',[0.155 0.205 0.735 0.620]);

hold(axD,'on');

allXY = ...
    [riskReconstructed(:); ...
     riskObserved(:); ...
     1];

xyMin = min(allXY,[],'omitnan');
xyMax = max(allXY,[],'omitnan');

xySpan = xyMax-xyMin;

if ~isfinite(xySpan) || xySpan<=0
    xySpan = 1;
end

xyLim = [ ...
    xyMin-0.07*xySpan, ...
    xyMax+0.07*xySpan];

% Identity line: exact agreement between predicted and observed risk.
plot( ...
    axD, ...
    xyLim,xyLim, ...
    '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.0, ...
    'HandleVisibility','off');

% Direct-evaluation reference: normalized risk = 1.
plot( ...
    axD, ...
    [1 1],xyLim, ...
    ':', ...
    'Color',[0.68 0.68 0.68], ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');

plot( ...
    axD, ...
    xyLim,[1 1], ...
    ':', ...
    'Color',[0.68 0.68 0.68], ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');

hStage = gobjects(numel(stageOrder),1);

for s = 1:numel(stageOrder)

    m = ...
        stageName==stageOrder(s);

    hStage(s) = ...
        scatter( ...
        axD, ...
        riskReconstructed(m), ...
        riskObserved(m), ...
        25, ...
        stageMarkers{s}, ...
        'filled', ...
        'MarkerFaceColor',stageColors(s,:), ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.35, ...
        'DisplayName',stageLabels{s});

    % Stage median.
    scatter( ...
        axD, ...
        stageMedPredRisk(s), ...
        stageMedObsRisk(s), ...
        74, ...
        stageMarkers{s}, ...
        'filled', ...
        'MarkerFaceColor',stageColors(s,:), ...
        'MarkerEdgeColor',dgrey, ...
        'LineWidth',0.9, ...
        'HandleVisibility','off');

end

set( ...
    axD, ...
    'XLim',xyLim, ...
    'YLim',xyLim, ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

axis(axD,'square');

xlabel( ...
    axD, ...
    'Predicted normalized risk, R(w)/V', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axD, ...
    'Observed normalized risk, R/V', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

grid(axD,'on');
axD.GridAlpha = 0.08;

% Direction agreement is already shown in Panel C.
% Panel D therefore reports only the magnitude association.
text( ...
    axD, ...
    0.97,0.07, ...
    sprintf('\\rho = %.3f',rho185), ...
    'Units','normalized', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',green, ...
    'BackgroundColor','w');

legend( ...
    axD, ...
    hStage, ...
    'Location','northwest', ...
    'Box','off', ...
    'FontName',FONT, ...
    'FontSize',6.8);

%% ------------------------------------------------------------------------
% 8. AUDIT PRINTOUT
% -------------------------------------------------------------------------

fprintf('\n============================================================\n');
fprintf(' FIGURE 3 REUSE AUDIT\n');
fprintf('============================================================\n');

fprintf( ...
    'U6 improved = %d/16 | pooled gain = %.6f%%\n', ...
    nnz(u6RelGain>0),u6PooledGain);

fprintf( ...
    'U7 improved = %d/16 | pooled gain = %.6f%%\n', ...
    nnz(u7RelGain>0),u7PooledGain);

fprintf( ...
    'U6 mismatch/error rho = %.9f\n',rho6);

fprintf( ...
    'U7 mismatch/error rho = %.9f\n',rho7);

fprintf( ...
    '185-state sign concordance = %d/185 = %.3f%%\n', ...
    signN,100*signN/185);

fprintf( ...
    '185-state predicted/observed rho = %.9f\n', ...
    rho185);

fprintf( ...
    '185-state scalar reconstruction residual = %.3e\n', ...
    ratioResidual);

%% ------------------------------------------------------------------------
% 9. EXPORT
% -------------------------------------------------------------------------

drawnow;

figPath = ...
    fullfile( ...
    outputDir, ...
    'Figure3_REUSE_Validation.fig');

pngPath = ...
    fullfile( ...
    outputDir, ...
    'Figure3_REUSE_Validation.png');

pdfPath = ...
    fullfile( ...
    outputDir, ...
    'Figure3_REUSE_Validation.pdf');

savefig(fig,figPath);

set(fig,'PaperPositionMode','auto');
set(fig,'PaperUnits','inches');

figPos = get(fig,'Position');

pageH = 8.0;

pageW = ...
    pageH * ...
    figPos(3) / ...
    figPos(4);

set(fig,'PaperSize',[pageW pageH]);
set(fig,'PaperPosition',[0 0 pageW pageH]);

print( ...
    fig,pngPath, ...
    '-dpng','-r600');

print( ...
    fig,pdfPath, ...
    '-dpdf','-painters','-bestfit');

fprintf('\nSaved:\n%s\n%s\n%s\n', ...
    figPath,pngPath,pdfPath);

end

%% =========================================================================
% HELPERS
% =========================================================================

function c = local_mix(c1,c2,alpha)

c = ...
    (1-alpha).*c1 + ...
    alpha.*c2;

end

function local_panel_border(ax,pos,color,lineWidth)

rectangle( ...
    ax, ...
    'Position',pos, ...
    'Curvature',0.018, ...
    'FaceColor','none', ...
    'EdgeColor',color, ...
    'LineWidth',lineWidth);

end

function local_panel_header( ...
    ax,letter,titleText,x,y,color,fontName,fsLetter,fsTitle)

text( ...
    ax,x,y,letter, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsLetter, ...
    'FontWeight','bold', ...
    'Color',color);

text( ...
    ax,x+0.055,y,titleText, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsTitle, ...
    'FontWeight','bold', ...
    'Color',color);

end

function local_fit_band(ax,x,y)

x = double(x(:));
y = double(y(:));

m = ...
    isfinite(x) & ...
    isfinite(y);

x = x(m);
y = y(m);

n = numel(x);

if n < 3
    return;
end

X = [ones(n,1),x];

beta = X\y;

xg = ...
    linspace( ...
    min(x),max(x),180)';

yg = ...
    beta(1) + ...
    beta(2).*xg;

res = ...
    y-X*beta;

df = ...
    max(n-2,1);

s2 = ...
    sum(res.^2)./df;

xm = mean(x);

sxx = ...
    sum((x-xm).^2);

if ~isfinite(sxx) || sxx<=0
    sxx = eps;
end

se = ...
    sqrt( ...
    s2 .* ...
    (1/n + ...
    (xg-xm).^2./sxx));

tc = ...
    local_tcritical95(df);

lo = yg-tc.*se;
hi = yg+tc.*se;

fill( ...
    ax, ...
    [xg;flipud(xg)], ...
    [lo;flipud(hi)], ...
    [0.72 0.72 0.72], ...
    'FaceAlpha',0.20, ...
    'EdgeColor','none', ...
    'HandleVisibility','off');

plot( ...
    ax,xg,yg, ...
    'k-', ...
    'LineWidth',1.15, ...
    'HandleVisibility','off');

end

function tcrit = local_tcritical95(df)

if df<=0
    tcrit = 1.96;
    return;
end

b = ...
    betaincinv( ...
    0.05, ...
    df/2, ...
    0.5);

tcrit = ...
    sqrt( ...
    df.*(1-b)./b);

end

function name = local_find_var(T,candidates)

name = '';

vars = ...
    string( ...
    T.Properties.VariableNames);

for i = 1:numel(candidates)

    j = ...
        find( ...
        strcmpi(vars,candidates{i}), ...
        1,'first');

    if ~isempty(j)

        name = ...
            char(vars(j));

        return;

    end

end

end

function local_require_vars(T,vars,sourceName)

missing = strings(0,1);

for i = 1:numel(vars)

    if ~ismember( ...
            vars{i}, ...
            T.Properties.VariableNames)

        missing(end+1,1) = ...
            string(vars{i}); %#ok<AGROW>

    end

end

if ~isempty(missing)

    error( ...
        '%s missing variables: %s', ...
        sourceName, ...
        strjoin( ...
        cellstr(missing), ...
        ', '));

end

end

function tf = local_sign_concordance(a,b)

a = double(a(:));
b = double(b(:));

tf = false(size(a));

for i = 1:numel(a)

    if ~isfinite(a(i)) || ...
            ~isfinite(b(i))

        tf(i) = false;

    elseif a(i)==0 && b(i)==0

        tf(i) = true;

    elseif a(i)>0 && b(i)>0

        tf(i) = true;

    elseif a(i)<0 && b(i)<0

        tf(i) = true;

    end

end

end

function rho = local_spearman(x,y)

x = double(x(:));
y = double(y(:));

m = ...
    isfinite(x) & ...
    isfinite(y);

x = x(m);
y = y(m);

rx = local_tied_rank(x);
ry = local_tied_rank(y);

rx = rx-mean(rx);
ry = ry-mean(ry);

den = ...
    sqrt( ...
    sum(rx.^2) .* ...
    sum(ry.^2));

if den<=0

    rho = NaN;

else

    rho = ...
        sum(rx.*ry) ./ den;

end

end

function r = local_tied_rank(v)

v = double(v(:));

n = numel(v);

[sv,ord] = ...
    sort(v,'ascend');

r = zeros(n,1);

i = 1;

while i<=n

    j = i;

    while j<n && ...
            sv(j+1)==sv(i)

        j = j+1;

    end

    r(ord(i:j)) = ...
        0.5*(i+j);

    i = j+1;

end

end

function repoRoot = local_find_cmdo_repo(scriptDir)
% Reviewer-facing fallback: derive repository root only from this renderer.
repoRoot = '';
if nargin < 1 || isempty(scriptDir)
    return;
end
candidate = fileparts(fileparts(scriptDir));
if isfolder(fullfile(candidate,'source_data')) && ...
        isfolder(fullfile(candidate,'matlab'))
    repoRoot = candidate;
end
end

