function Figure1_Evidential_Order_PCC(outputDir, repoRoot)
% FIGURE1_IDA_REALDATA_FINAL
% CMDO Figure 1 — four-layer evidential order
%
% A  Monitoring need not establish performance
% B  IDENTIFY -> REUSE -> CERTIFY -> PRESERVE
% C  Information roles and protected-evaluation structure
%
% Design principle:
%   - Keep the old Panel A
%   - Keep the old Panel B
%   - Add a compact Panel C only for structure
%
% Scientific mapping:
%   IDENTIFY  = Performance observability   (Delta_E)
%   REUSE     = Evidence admissibility      (Lambda)
%   CERTIFY   = Prospective composability certificate
%   PRESERVE  = Adaptive composability      (Xi)

clc;
close all;

thisFile = mfilename('fullpath');
if isempty(thisFile), scriptDir=pwd; else, scriptDir=fileparts(thisFile); end
if nargin < 2 || isempty(repoRoot)
    repoRoot = fullfile(getenv('USERPROFILE'),'CMDO-Reproducibility');
end
assert(isfolder(repoRoot),'CMDO repository not found: %s',repoRoot);
if nargin < 1 || isempty(outputDir), outputDir=fullfile(scriptDir,'output'); end
if ~isfolder(outputDir), mkdir(outputDir); end

%% ========================================================================
% USER-ADJUSTABLE DISPLAY CONTROLS
% ========================================================================
FONT_SCALE = 1.10;
CANVAS = [30 30 1080 980];

%% ========================================================================
% LOAD FROZEN REAL ASSETS
% ========================================================================
[A, assetPath] = load_frozen_assets(repoRoot);

assert(isfield(A,'images') && numel(A.images) >= 4, ...
    'Need >=4 frozen image assets.');
assert(isfield(A,'tables') && numel(A.tables) >= 1, ...
    'Need >=1 frozen table asset.');
assert(isfield(A,'witnesses') && numel(A.witnesses) >= 2, ...
    'Need >=2 frozen U11 witnesses.');

W  = A.witnesses(1);
W2 = A.witnesses(2);

requiredWitnessFields = { ...
    'score','success_outcome','failure_outcome', ...
    'auc_success','auc_failure','name'};

for k = 1:numel(requiredWitnessFields)
    assert(isfield(W,requiredWitnessFields{k}), ...
        'Witness field missing: %s', requiredWitnessFields{k});
end

fprintf('\n============================================================\n');
fprintf(' CMDO FIGURE 1 — EVIDENTIAL ORDER + STRUCTURE\n');
fprintf('============================================================\n');
fprintf('Frozen asset package:\n  %s\n', assetPath);
fprintf('Primary U11 witness : %s | AUC %.2f <-> %.2f\n', ...
    char(string(W.name)), double(W.auc_success), double(W.auc_failure));
fprintf('Replication witness : %s | AUC %.2f <-> %.2f\n', ...
    char(string(W2.name)), double(W2.auc_success), double(W2.auc_failure));

%% ========================================================================
% STYLE / CANVAS
% ========================================================================
S = style_spec(FONT_SCALE);

fig = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',CANVAS, ...
    'Renderer','painters', ...
    'InvertHardcopy','off');

%% ========================================================================
% GLOBAL GEOMETRY
% ========================================================================
x0 = 0.018;
right = 0.985;

Apos = [x0 0.700 right-x0 0.275];
Bpos = [x0 0.360 right-x0 0.300];
Cpos = [x0 0.075 right-x0 0.235];

axA = panel_axes( ...
    fig, Apos, S, 'A', ...
    'Monitoring need not determine current performance', S.blue);

axB = panel_axes( ...
    fig, Bpos, S, 'B', ...
    'Four evidential questions in post-deployment evaluation', S.purple);

axC = panel_axes( ...
    fig, Cpos, S, 'C', ...
    'Information roles for licensed reuse', S.teal);

%% ========================================================================
% PANEL A — THE PROBLEM
% Keep previous composition unchanged
% ========================================================================
inputX = 0.020;
inputW = 0.300;

draw_real_image_triplet( ...
    fig, axA, A.images, [2 3 4], ...
    [inputX 0.505 inputW 0.300], S);

draw_real_table_snippet( ...
    axA, A.tables(1), ...
    [inputX 0.275 inputW 0.180], S);

arrow_norm(axA,[0.335 0.565],[0.382 0.565],S.axis,1.6);
draw_model_box(axA,[0.392 0.355 0.090 0.380],S);
arrow_norm(axA,[0.488 0.565],[0.545 0.565],S.axis,1.6);

draw_score_stream( ...
    fig, axA, W, ...
    [0.560 0.410 0.185 0.310], S, false);

arrow_norm(axA,[0.750 0.565],[0.792 0.565],S.axis,1.6);

text(axA,0.815,0.575,'?', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,31), ...
    'FontWeight','bold', ...
    'Color',S.red);

arrow_norm(axA,[0.837 0.565],[0.875 0.565],S.axis,1.6);

draw_hidden_gauge(axA,[0.885 0.410 0.085 0.300],S);

text(axA,0.985,0.360,{'current';'performance'}, ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.2), ...
    'Color',S.text);

text(axA,0.50,0.115, ...
    {'Without outcome-linking assumptions,'; ...
     'outcome-free monitoring need not identify performance'}, ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,9.2), ...
    'FontWeight','bold', ...
    'Color',S.red);

%% ========================================================================
% PANEL B — FOUR LINKED EVIDENTIAL QUESTIONS
% IDENTIFY -> REUSE -> CERTIFY -> PRESERVE
% ========================================================================
cardY = 0.105; cardH = 0.720; cardW = 0.222;
xCard = [0.012 0.257 0.502 0.747];
accent = {S.blue,S.green,S.purple,S.red};
fillc = {[0.992 0.996 1.000],[0.992 1.000 0.994],[0.997 0.993 1.000],[1.000 0.994 0.992]};
for k=1:4
    round_box(axB,[xCard(k) cardY cardW cardH],fillc{k},0.72*[1 1 1]+0.28*accent{k},0.8);
end
for k=1:3
    arrow_norm(axB,[xCard(k)+cardW+0.004 0.785],[xCard(k+1)-0.006 0.785],S.axis,1.35);
end

% IDENTIFY
xc=xCard(1)+cardW/2;
text(axB,xc,0.790,'IDENTIFY','HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,8.9),'FontWeight','bold','Color',S.blue);
text(axB,xc,0.735,'Is current performance determined?','HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,5.8),'Color',S.blue);
draw_score_stream(fig,axB,W,[xCard(1)+0.032 0.535 cardW-0.064 0.115],S,true);
round_box(axB,[xCard(1)+0.030 0.315 cardW-0.060 0.135],S.bluePale,S.blue,0.9);
text(axB,xc,0.382,{'same monitored evidence';'AUC 1  \leftrightarrow  0'},'Interpreter','tex','HorizontalAlignment','center','VerticalAlignment','middle','FontName',S.font,'FontSize',F(S,6.1),'FontWeight','bold','Color',S.text);

% REUSE
xc=xCard(2)+cardW/2;
text(axB,xc,0.790,'REUSE','HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,8.9),'FontWeight','bold','Color',S.green);
text(axB,xc,0.735,'Does fixed historical evidence reduce risk?','HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,5.6),'Color',S.green);
draw_current_audit(axB,[xCard(2)+0.025 0.535 0.075 0.100],S);
draw_history_evidence(axB,[xCard(2)+0.120 0.535 0.075 0.100],S);
arrow_norm(axB,[xc 0.520],[xc 0.455],S.muted,1.0);
round_box(axB,[xCard(2)+0.030 0.335 cardW-0.060 0.105],S.greenPale,S.green,0.95);
text(axB,xc,0.387,{'fixed-use risk';'B^2 versus V'},'Interpreter','tex','HorizontalAlignment','center','VerticalAlignment','middle','FontName',S.font,'FontSize',F(S,6.2),'FontWeight','bold','Color',S.green);

% CERTIFY
xc=xCard(3)+cardW/2;
text(axB,xc,0.790,'CERTIFY','HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,8.9),'FontWeight','bold','Color',S.purple);
text(axB,xc,0.735,'Can reuse be licensed before evaluation?','HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,5.6),'Color',S.purple);
round_box(axB,[xCard(3)+0.035 0.535 cardW-0.070 0.100],[0.985 0.978 1.000],S.purple,0.95);
text(axB,xc,0.585,{'pre-audit current';'outcome information'},'HorizontalAlignment','center','VerticalAlignment','middle','FontName',S.font,'FontSize',F(S,5.8),'FontWeight','bold','Color',S.purple);
arrow_norm(axB,[xc 0.520],[xc 0.455],S.purple,1.0);
round_box(axB,[xCard(3)+0.028 0.340 cardW-0.056 0.105],[0.992 0.986 1.000],S.purple,1.0);
text(axB,xc,0.392,'$\mathcal{W}_\delta=[0,\widehat{s}]$','Interpreter','latex','HorizontalAlignment','center','VerticalAlignment','middle','FontName',S.font,'FontSize',F(S,7.0),'FontWeight','bold','Color',S.purple);
text(axB,xc,0.275,'$C^*_{\delta,\beta}$: certification cost  $C^*_{\delta,\beta}$','Interpreter','latex','HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,5.7),'Color',S.muted);

% PRESERVE
xc=xCard(4)+cardW/2;
text(axB,xc,0.790,'PRESERVE','HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,8.9),'FontWeight','bold','Color',S.red);
text(axB,xc,0.735,'Does adaptation preserve licensed value?','HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,5.6),'Color',S.red);
draw_composition_case(axB,[xCard(4)+0.025 0.480 cardW-0.050 0.135],S,'preserved',true);
draw_composition_case(axB,[xCard(4)+0.025 0.300 cardW-0.050 0.135],S,'consumed',false);

%% ========================================================================
% PANEL C — INFORMATION ROLES AND PROTECTED EVALUATION
% ========================================================================
% Main nodes
x=[0.020 0.235 0.425 0.615 0.805];
round_box(axC,[x(1) 0.400 0.150 0.330],[0.985 0.990 1.000],S.blue,0.9);
text(axC,x(1)+0.075,0.650,'Deployment evidence','HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,6.6),'FontWeight','bold','Color',S.blue);
text(axC,x(1)+0.075,0.525,{'inputs / scores';'predictions / telemetry'},'HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,5.4),'Color',S.text);

labels={'IDENTIFY','REUSE','CERTIFY','PRESERVE'};
cols={S.blue,S.green,S.purple,S.red};
subs={'','','',''};
for k=1:4
    rectangle(axC,'Position',[x(k+1) 0.475 0.135 0.180],'Curvature',[1 1], ...
        'FaceColor',0.93*[1 1 1]+0.07*cols{k},'EdgeColor',cols{k},'LineWidth',1.2);
    text(axC,x(k+1)+0.0675,0.585,labels{k},'HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,8.0),'FontWeight','bold','Color',cols{k});
end
for k=1:4
    arrow_norm(axC,[x(k)+0.150 0.565],[x(k+1)-0.008 0.565],S.axis,1.1);
end

% Current outcomes restore identification / direct estimate
round_box(axC,[0.215 0.175 0.180 0.105],S.greenPale,S.green,0.85);
text(axC,0.305,0.228,{'Representative current';'outcomes'},'HorizontalAlignment','center','VerticalAlignment','middle','FontName',S.font,'FontSize',F(S,5.8),'FontWeight','bold','Color',S.green);
arrow_norm(axC,[0.305 0.285],[0.302 0.465],S.green,0.9);

% Historical evidence enters reuse
round_box(axC,[0.405 0.770 0.170 0.105],[0.990 0.985 1.000],S.purple,0.8);
text(axC,0.490,0.823,'Historical evidence','HorizontalAlignment','center','VerticalAlignment','middle','FontName',S.font,'FontSize',F(S,5.8),'FontWeight','bold','Color',S.purple);
arrow_norm(axC,[0.490 0.765],[0.493 0.665],S.purple,0.9);

% Independent certification information enters CERTIFY
round_box(axC,[0.590 0.175 0.190 0.105],[0.990 0.985 1.000],S.purple,0.8);
text(axC,0.685,0.228,{'Independent pre-audit';'certification outcomes'},'HorizontalAlignment','center','VerticalAlignment','middle','FontName',S.font,'FontSize',F(S,5.6),'FontWeight','bold','Color',S.purple);
arrow_norm(axC,[0.685 0.285],[0.682 0.465],S.purple,0.9);

% Locked action between CERTIFY and PRESERVE
text(axC,0.792,0.690,'locked reuse action','HorizontalAlignment','center','FontName',S.font,'FontSize',F(S,5.2),'FontWeight','bold','Color',S.purple);

%% ========================================================================
% EXPORT
% ========================================================================
pngPath = fullfile(outputDir,'Figure1_Evidential_Order_PCC.png');
pdfPath = fullfile(outputDir,'Figure1_Evidential_Order_PCC.pdf');
exportgraphics(fig,pngPath,'Resolution',300);
exportgraphics(fig,pdfPath,'ContentType','vector');
fprintf('\nFigure 1 written:\n%s\n%s\n',pngPath,pdfPath);
end

%% ========================================================================
% LOAD FROZEN ASSETS — ROBUST PATH SEARCH
% ========================================================================
function [A, matPath] = load_frozen_assets(repoRoot)
thisFile = mfilename('fullpath');
if isempty(thisFile)
    scriptDir = pwd;
else
    scriptDir = fileparts(thisFile);
end

if nargin < 1 || isempty(repoRoot), repoRoot = fileparts(fileparts(scriptDir)); end
matPath = fullfile( ...
    repoRoot, ...
    'source_data', ...
    'figure1_assets', ...
    'Figure1_assets_selected_v1.mat');

assert(isfile(matPath), ...
    ['Missing tracked Figure 1 frozen asset:' newline matPath]);

q = whos('-file',matPath);
vars = string({q.name});
assert(any(vars=="Assets"), ...
    'Figure 1 MAT does not contain variable Assets.');

Q = load(matPath,'Assets');
A = Q.Assets;

assert(isfield(A,'images') && numel(A.images)>=4, ...
    'Assets.images is incomplete.');
assert(isfield(A,'tables') && numel(A.tables)>=1, ...
    'Assets.tables is incomplete.');
assert(isfield(A,'witnesses') && numel(A.witnesses)>=2, ...
    'Assets.witnesses is incomplete.');

fprintf('\n============================================================\n');
fprintf(' FIGURE 1 TRACKED FROZEN ASSET\n');
fprintf('============================================================\n');
fprintf('%s\n',matPath);
fprintf('============================================================\n\n');
end

function S = style_spec(fontScale)

S.font  = 'Arial';
S.scale = fontScale;

% Text / axes
S.text  = [0.08 0.10 0.14];
S.axis  = [0.22 0.24 0.28];
S.muted = [0.42 0.44 0.49];
S.line  = [0.76 0.78 0.82];

% Scientific colours
S.blue   = [0.04 0.25 0.66];
S.green  = [0.02 0.42 0.18];
S.red    = [0.80 0.08 0.07];
S.purple = [0.34 0.22 0.58];
S.teal   = [0.02 0.47 0.42];

% Pale fills
S.bluePale  = [0.965 0.980 1.000];
S.greenPale = [0.965 0.995 0.972];
S.redPale   = [1.000 0.972 0.965];
S.purplePale = [0.985 0.978 1.000];

end

function v = F(S,x)
v = S.scale*x;
end

%% ========================================================================
% PANEL FRAME / GEOMETRY
% ========================================================================
function ax = panel_axes(fig,pos,S,letter,ttl,accent)

ax = axes(fig,'Position',pos);
axis(ax,[0 1 0 1]);
axis(ax,'off');
hold(ax,'on');
turn_off_toolbar(ax);

rectangle( ...
    ax, ...
    'Position',[0.003 0.003 0.994 0.994], ...
    'Curvature',[0.018 0.018], ...
    'FaceColor','w', ...
    'EdgeColor',0.70*[1 1 1] + 0.30*accent, ...
    'LineWidth',1.0);

text(ax,0.022,0.947,letter, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,11.8), ...
    'FontWeight','bold', ...
    'Color',accent);

text(ax,0.085,0.947,ttl, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,8.9), ...
    'FontWeight','bold', ...
    'Color',accent);

end

function round_box(ax,p,face,edge,lw)
rectangle( ...
    ax, ...
    'Position',p, ...
    'Curvature',[0.04 0.04], ...
    'FaceColor',face, ...
    'EdgeColor',edge, ...
    'LineWidth',lw);
end

function arrow_norm(ax,p1,p2,c,lw)
quiver( ...
    ax, ...
    p1(1), p1(2), ...
    p2(1)-p1(1), p2(2)-p1(2), ...
    0, ...
    'Color',c, ...
    'LineWidth',lw, ...
    'MaxHeadSize',0.85);
end

function p = relpos(parentPos,r)
p = [ ...
    parentPos(1) + r(1)*parentPos(3), ...
    parentPos(2) + r(2)*parentPos(4), ...
    r(3)*parentPos(3), ...
    r(4)*parentPos(4)];
end

function turn_off_toolbar(ax)
try
    ax.Toolbar.Visible = 'off';
catch
end

try
    disableDefaultInteractivity(ax);
catch
end
end

%% ========================================================================
% A — REAL IMAGES
% ========================================================================
function draw_real_image_triplet(fig,ax,images,idx,r,S)

P = ax.Position;

labels = { ...
    'Dermoscopy', ...
    'Breast ultrasound', ...
    'Retinal fundus'};

gap = 0.010;
tw = (r(3)-2*gap)/3;

for k = 1:3
    rr = [ ...
        r(1)+(k-1)*(tw+gap), ...
        r(2), ...
        tw, ...
        r(4)];

    a = axes(fig,'Position',relpos(P,[ ...
        rr(1), ...
        rr(2)+0.11*rr(4), ...
        rr(3), ...
        0.72*rr(4)]));
    turn_off_toolbar(a);

    I = images(idx(k)).image;
    image(a,I);
    axis(a,'image');
    axis(a,'off');
    set(a,'YDir','reverse');

    rectangle(a, ...
        'Position',[0.5 0.5 size(I,2)-1 size(I,1)-1], ...
        'EdgeColor',[0.72 0.72 0.72], ...
        'LineWidth',0.7);

    text(ax,rr(1)+rr(3)/2,rr(2)+0.98*rr(4),labels{k}, ...
        'HorizontalAlignment','center', ...
        'FontName',S.font, ...
        'FontSize',F(S,6.6), ...
        'Color',S.text);
end

end

%% ========================================================================
% A — REAL TABLE PREVIEW
% ========================================================================
function draw_real_table_snippet(ax,T,p,S)

round_box(ax,p,[0.997 0.998 1.000],[0.55 0.58 0.63],0.8);

M = double(T.preview);
names = string(T.varNames);

nr = min(3,size(M,1));
nc = min(4,size(M,2));

M = M(1:nr,1:nc);
names = names(1:nc);

x0 = p(1)+0.014;
y0 = p(2)+0.025;
W  = p(3)-0.028;
H  = p(4)-0.050;

rowH = H/(nr+1);
colW = W/nc;

rectangle(ax, ...
    'Position',[x0 y0+nr*rowH W rowH], ...
    'FaceColor',[0.92 0.95 0.98], ...
    'EdgeColor','none');

for rr = 0:(nr+1)
    yy = y0 + rr*rowH;
    plot(ax,[x0 x0+W],[yy yy],'-', ...
        'Color',[0.68 0.70 0.74], ...
        'LineWidth',0.55);
end

for cc = 0:nc
    xx = x0 + cc*colW;
    plot(ax,[xx xx],[y0 y0+H],'-', ...
        'Color',[0.68 0.70 0.74], ...
        'LineWidth',0.55);
end

for c = 1:nc
    nm = short_name(names(c),5);
    text(ax,x0+(c-0.5)*colW,y0+(nr+0.5)*rowH,char(nm), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontName',S.font, ...
        'FontSize',F(S,5.2), ...
        'FontWeight','bold', ...
        'Color',S.text);
end

for r0 = 1:nr
    for c = 1:nc
        text(ax,x0+(c-0.5)*colW,y0+(nr-r0+0.5)*rowH, ...
            sprintf('%.2f',M(r0,c)), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontName',S.font, ...
            'FontSize',F(S,5.0), ...
            'Color',S.text);
    end
end

text(ax,p(1)+p(3)/2,p(2)+p(4)+0.025,'Tabular input', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.2), ...
    'FontWeight','bold', ...
    'Color',S.text);

end

function s = short_name(x,maxLen)
s = char(string(x));
s = strrep(s,'_','');
if numel(s) > maxLen
    s = s(1:maxLen);
end
s = string(s);
end

%% ========================================================================
% A — MODEL ICON
% ========================================================================
function draw_model_box(ax,p,S)

round_box(ax,p,[0.975 0.985 1.000],S.blue,0.9);

pts = [ ...
    0.18 0.25; ...
    0.18 0.50; ...
    0.18 0.75; ...
    0.50 0.18; ...
    0.50 0.40; ...
    0.50 0.62; ...
    0.50 0.82; ...
    0.82 0.30; ...
    0.82 0.55; ...
    0.82 0.75];

pts(:,1) = p(1) + p(3)*pts(:,1);
pts(:,2) = p(2) + p(4)*(0.23 + 0.55*pts(:,2));

for i = 1:3
    for j = 4:7
        plot(ax,[pts(i,1) pts(j,1)],[pts(i,2) pts(j,2)],'-', ...
            'Color',[0.55 0.62 0.72], ...
            'LineWidth',0.45);
    end
end

for i = 4:7
    for j = 8:10
        plot(ax,[pts(i,1) pts(j,1)],[pts(i,2) pts(j,2)],'-', ...
            'Color',[0.55 0.62 0.72], ...
            'LineWidth',0.45);
    end
end

scatter(ax,pts(:,1),pts(:,2),28, ...
    'MarkerFaceColor',[0.65 0.78 0.95], ...
    'MarkerEdgeColor',S.blue, ...
    'LineWidth',0.7);

text(ax,p(1)+p(3)/2,p(2)+0.075*p(4),'AI model', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.0), ...
    'FontWeight','bold', ...
    'Color',S.text);

end

%% ========================================================================
% A/B — FROZEN SCORE STREAM
% ========================================================================
function draw_score_stream(fig,ax,W,r,S,withTitle)

P = ax.Position;

a = axes(fig,'Position',relpos(P,r));
turn_off_toolbar(a);
hold(a,'on');

s = double(W.score(:));
n = numel(s);

take = unique(round(linspace(1,n,min(260,n))));
xx = 1:numel(take);
ss = s(take);

plot(a,xx,ss,'-', ...
    'Color',[0.48 0.48 0.48], ...
    'LineWidth',0.55);

scatter(a,xx,ss,7, ...
    'MarkerFaceColor',[0.36 0.36 0.36], ...
    'MarkerEdgeColor','none');

ylim(a,[0 1]);
xlim(a,[1 max(2,numel(xx))]);

set(a, ...
    'FontName',S.font, ...
    'FontSize',F(S,5.4), ...
    'Box','off', ...
    'TickDir','out', ...
    'XColor',S.axis, ...
    'YColor',S.axis, ...
    'YTick',[0 0.5 1]);

if withTitle
    title(a,'Observed model scores', ...
        'FontName',S.font, ...
        'FontSize',F(S,7.2), ...
        'FontWeight','normal', ...
        'Color',S.text);

    set(a, ...
        'XTick',[1 round(numel(xx)/2) numel(xx)], ...
        'XTickLabel',{'1','n/2','n'});

    ylabel(a,'score','FontSize',F(S,5.8));
else
    set(a,'XTick',[],'YTick',[0 1]);
end

end

%% ========================================================================
% A — HIDDEN PERFORMANCE GAUGE
% ========================================================================
function draw_hidden_gauge(ax,p,S)

cx = p(1)+0.50*p(3);
cy = p(2)+0.38*p(4);
rx = 0.48*p(3);
ry = 0.36*p(4);

th = linspace(pi,0,120);
plot(ax,cx+rx*cos(th),cy+ry*sin(th),'-', ...
    'Color',S.axis, ...
    'LineWidth',2.0);

th1 = linspace(pi,2*pi/3,35);
th2 = linspace(2*pi/3,pi/3,35);
th3 = linspace(pi/3,0,35);

plot(ax,cx+0.90*rx*cos(th1),cy+0.90*ry*sin(th1),'-', ...
    'Color',[0.10 0.55 0.20], ...
    'LineWidth',3.0);

plot(ax,cx+0.90*rx*cos(th2),cy+0.90*ry*sin(th2),'-', ...
    'Color',[0.96 0.72 0.05], ...
    'LineWidth',3.0);

plot(ax,cx+0.90*rx*cos(th3),cy+0.90*ry*sin(th3),'-', ...
    'Color',S.red, ...
    'LineWidth',3.0);

needle = pi/6;
plot(ax,[cx cx+0.55*rx*cos(needle)], ...
        [cy cy+0.55*ry*sin(needle)],'-', ...
    'Color',S.text, ...
    'LineWidth',1.8);

scatter(ax,cx,cy,24, ...
    'MarkerFaceColor',S.text, ...
    'MarkerEdgeColor','none');

end

%% ========================================================================
% B — WORLD ROC CURVES
% ========================================================================
function draw_world_roc(fig,ax,W,isSuccess,p,S)

P = ax.Position;

if isSuccess
    y = double(W.success_outcome(:));
    aucShown = double(W.auc_success);
    edge = S.blue;
    face = S.bluePale;
else
    y = double(W.failure_outcome(:));
    aucShown = double(W.auc_failure);
    edge = S.red;
    face = S.redPale;
end

s = double(W.score(:));

round_box(ax,p,face,edge,0.9);

[FPR,TPR] = local_roc(y,s);

a = axes(fig,'Position',relpos(P,[ ...
    p(1)+0.11*p(3), ...
    p(2)+0.26*p(4), ...
    0.77*p(3), ...
    0.55*p(4)]));
turn_off_toolbar(a);
hold(a,'on');

plot(a,FPR,TPR,'-', ...
    'Color',edge, ...
    'LineWidth',1.5);

markStep = max(1,round(numel(FPR)/20));
markIdx = 1:markStep:numel(FPR);

scatter(a,FPR(markIdx),TPR(markIdx),8, ...
    'MarkerFaceColor',edge, ...
    'MarkerEdgeColor','none');

plot(a,[0 1],[0 1],'--', ...
    'Color',[0.80 0.80 0.80], ...
    'LineWidth',0.6);

axis(a,[0 1 0 1]);

set(a, ...
    'FontName',S.font, ...
    'FontSize',F(S,4.7), ...
    'Box','off', ...
    'TickDir','out', ...
    'XTick',[0 1], ...
    'YTick',[0 1], ...
    'XColor',S.axis, ...
    'YColor',S.axis);

text(ax,p(1)+0.50*p(3),p(2)+0.075*p(4),sprintf('AUC = %.2f',aucShown), ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.4), ...
    'FontWeight','normal', ...
    'Color',edge);

end

function [fpr,tpr] = local_roc(y,s)

y = double(y(:));
s = double(s(:));

valid = isfinite(y) & isfinite(s);
y = y(valid);
s = s(valid);

[ss,ord] = sort(s,'descend');
yy = y(ord);

P = sum(yy==1);
N = sum(yy==0);

assert(P>0 && N>0,'ROC requires both outcome classes.');

tp = cumsum(yy==1);
fp = cumsum(yy==0);
change = [find(diff(ss)~=0); numel(ss)];

tpr = [0; tp(change)/P; 1];
fpr = [0; fp(change)/N; 1];

end

%% ========================================================================
% B/C/D — ROLE STRIP
% ========================================================================
function draw_role_strip(ax,p,face,edge,line1,line2,S)

round_box(ax,p,face,edge,0.9);

text(ax,p(1)+p(3)/2,p(2)+0.61*p(4),line1, ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,8.8), ...
    'FontWeight','bold', ...
    'Color',edge);

text(ax,p(1)+p(3)/2,p(2)+0.24*p(4),line2, ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,5.7), ...
    'Color',edge);

end

%% ========================================================================
% C — CURRENT AUDIT
% ========================================================================
function draw_current_audit(ax,p,S)

text(ax,p(1)+0.50*p(3),p(2)+0.92*p(4),'current audit', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.0), ...
    'FontWeight','bold', ...
    'Color',S.text);

x0 = p(1)+0.12*p(3);
y  = p(2)+0.56*p(4);

for k = 1:5
    scatter(ax,x0+(k-1)*0.16*p(3),y,40, ...
        'MarkerFaceColor','w', ...
        'MarkerEdgeColor',S.text, ...
        'LineWidth',0.8);
end

text(ax,p(1)+0.50*p(3),p(2)+0.20*p(4),'audit size m \uparrow   V \downarrow', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.4), ...
    'Color',S.green);

end

%% ========================================================================
% C — HISTORICAL EVIDENCE
% ========================================================================
function draw_history_evidence(ax,p,S)

text(ax,p(1)+0.50*p(3),p(2)+0.92*p(4),'historical evidence', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.0), ...
    'FontWeight','bold', ...
    'Color',S.text);

x0 = p(1)+0.15*p(3);
y  = p(2)+0.50*p(4);

for k = 1:4
    rectangle(ax, ...
        'Position',[ ...
            x0+(k-1)*0.18*p(3), ...
            y, ...
            0.085*p(3), ...
            0.22*p(4)], ...
        'FaceColor',0.72*[1 1 1] + 0.28*S.purple, ...
        'EdgeColor',S.purple, ...
        'LineWidth',0.8);
end

text(ax,p(1)+0.50*p(3),p(2)+0.18*p(4),'candidate reuse', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.2), ...
    'Color',S.muted);

end

%% ========================================================================
% D — COMPOSITION CASES
% ========================================================================
function draw_composition_case(ax,p,S,label,isPreserved)

if isPreserved
    edge = S.green;
    face = S.greenPale;
else
    edge = S.red;
    face = S.redPale;
end

round_box(ax,p,face,edge,0.9);

text(ax,p(1)+0.50*p(3),p(2)+0.83*p(4),['benefit ' label], ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.3), ...
    'FontWeight','bold', ...
    'Color',edge);

% Fixed composition
fx = p(1)+0.12*p(3);
fy = p(2)+0.36*p(4);

for k = 1:4
    rectangle(ax, ...
        'Position',[ ...
            fx+(k-1)*0.075*p(3), ...
            fy, ...
            0.040*p(3), ...
            0.16*p(4)], ...
        'FaceColor',0.72*[1 1 1] + 0.28*S.blue, ...
        'EdgeColor',S.blue, ...
        'LineWidth',0.7);
end

text(ax,p(1)+0.235*p(3),p(2)+0.12*p(4),'fixed', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.3), ...
    'Color',S.muted);

% Arrow
arrow_norm(ax, ...
    [p(1)+0.405*p(3) p(2)+0.44*p(4)], ...
    [p(1)+0.580*p(3) p(2)+0.44*p(4)], ...
    S.axis,1.0);

% Adaptive composition
ax0 = p(1)+0.64*p(3);
ay0 = p(2)+0.44*p(4);

if isPreserved
    sizes = [65 55 45 35 26];
else
    sizes = [70 70 70 70 70];
end

for k = 1:numel(sizes)
    scatter(ax,ax0+(k-1)*0.065*p(3),ay0,sizes(k), ...
        'MarkerFaceColor',S.red, ...
        'MarkerEdgeColor',[0.45 0 0], ...
        'LineWidth',0.6);
end

text(ax,p(1)+0.770*p(3),p(2)+0.12*p(4),'adaptive', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.3), ...
    'Color',S.muted);

end

%% ========================================================================
% C — CMDO SYSTEM STRUCTURE
% Information-flow view:
%
% Deployment evidence -> IDENTIFY -> REUSE -> Fixed-use value -> PRESERVE
%                            ^           ^
%                            |           |
%                    Current outcomes   Historical evidence
%                            |
%                    Current direct estimate
%
% Fixed-use value --adaptive use--> PRESERVE
%                                      |
%                                      v
%                            Final performance
% ========================================================================
function draw_structure_panel(ax,S)

%% ------------------------------------------------------------------------
% GEOMETRY
% -------------------------------------------------------------------------

% Main horizontal chain
pDep      = [0.020 0.385 0.170 0.430];
pIdentify = [0.240 0.490 0.180 0.205];
pReuse    = [0.480 0.490 0.180 0.205];
pFixed    = [0.700 0.515 0.130 0.155];
pPreserve = [0.855 0.490 0.130 0.205];

% Information / output nodes
pCurrent  = [0.230 0.245 0.200 0.125];
pDirect   = [0.220 0.055 0.220 0.120];

pHistory  = [0.470 0.775 0.200 0.125];

pFinal    = [0.840 0.155 0.150 0.175];


%% ========================================================================
% 1. DEPLOYMENT EVIDENCE
% ========================================================================

round_box( ...
    ax, ...
    pDep, ...
    [0.985 0.990 1.000], ...
    S.blue, ...
    0.95);

text( ...
    ax, ...
    pDep(1)+pDep(3)/2, ...
    pDep(2)+0.82*pDep(4), ...
    'Deployment evidence', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.4), ...
    'FontWeight','bold', ...
    'Color',S.blue);

% Compact internal information elements
items = { ...
    'Inputs', ...
    'Scores', ...
    'Predictions', ...
    'Telemetry'};

yItems = [0.64 0.48 0.32 0.16];

for k = 1:4

    yy = ...
        pDep(2) + ...
        yItems(k)*pDep(4);

    % small pale information strip
    rectangle( ...
        ax, ...
        'Position',[ ...
            pDep(1)+0.018, ...
            yy-0.035, ...
            pDep(3)-0.036, ...
            0.070], ...
        'Curvature',[0.05 0.05], ...
        'FaceColor',[0.995 0.997 1.000], ...
        'EdgeColor',0.70*[1 1 1]+0.30*S.blue, ...
        'LineWidth',0.60);

    text( ...
        ax, ...
        pDep(1)+pDep(3)/2, ...
        yy, ...
        items{k}, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontName',S.font, ...
        'FontSize',F(S,6.1), ...
        'Color',S.text);

end


%% ========================================================================
% 2. IDENTIFY — OBSERVABILITY
% ========================================================================

rectangle( ...
    ax, ...
    'Position',pIdentify, ...
    'Curvature',[1 1], ...
    'FaceColor',[0.965 0.980 1.000], ...
    'EdgeColor',S.blue, ...
    'LineWidth',1.25);

text( ...
    ax, ...
    pIdentify(1)+pIdentify(3)/2, ...
    pIdentify(2)+0.62*pIdentify(4), ...
    'IDENTIFY', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,8.9), ...
    'FontWeight','bold', ...
    'Color',S.blue);

text( ...
    ax, ...
    pIdentify(1)+pIdentify(3)/2, ...
    pIdentify(2)+0.34*pIdentify(4), ...
    'Observability', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.1), ...
    'FontWeight','bold', ...
    'Color',S.text);


%% ========================================================================
% 3. REPRESENTATIVE CURRENT OUTCOMES
% ========================================================================

round_box( ...
    ax, ...
    pCurrent, ...
    S.greenPale, ...
    S.green, ...
    0.90);

text( ...
    ax, ...
    pCurrent(1)+pCurrent(3)/2, ...
    pCurrent(2)+pCurrent(4)/2, ...
    {'Representative','current outcomes'}, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.5), ...
    'FontWeight','bold', ...
    'Color',S.green);

% Outcomes -> IDENTIFY
arrow_norm( ...
    ax, ...
    [pCurrent(1)+pCurrent(3)/2 ...
     pCurrent(2)+pCurrent(4)+0.005], ...
    [pIdentify(1)+pIdentify(3)/2 ...
     pIdentify(2)-0.005], ...
    S.green, ...
    1.05);


%% ========================================================================
% 4. CURRENT DIRECT ESTIMATE
% ========================================================================

round_box( ...
    ax, ...
    pDirect, ...
    [0.985 0.992 1.000], ...
    S.blue, ...
    0.85);

text( ...
    ax, ...
    pDirect(1)+pDirect(3)/2, ...
    pDirect(2)+0.60*pDirect(4), ...
    'Current direct estimate', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.3), ...
    'FontWeight','bold', ...
    'Color',S.blue);

text( ...
    ax, ...
    pDirect(1)+pDirect(3)/2, ...
    pDirect(2)+0.28*pDirect(4), ...
    '\pm uncertainty', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.0), ...
    'Color',S.text);

% Current outcomes -> direct estimate
arrow_norm( ...
    ax, ...
    [pCurrent(1)+pCurrent(3)/2 ...
     pCurrent(2)-0.004], ...
    [pDirect(1)+pDirect(3)/2 ...
     pDirect(2)+pDirect(4)+0.004], ...
    S.blue, ...
    0.90);


%% ========================================================================
% 5. REUSE — ADMISSIBILITY
% ========================================================================

rectangle( ...
    ax, ...
    'Position',pReuse, ...
    'Curvature',[1 1], ...
    'FaceColor',S.greenPale, ...
    'EdgeColor',S.green, ...
    'LineWidth',1.25);

text( ...
    ax, ...
    pReuse(1)+pReuse(3)/2, ...
    pReuse(2)+0.62*pReuse(4), ...
    'REUSE', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,8.9), ...
    'FontWeight','bold', ...
    'Color',S.green);

text( ...
    ax, ...
    pReuse(1)+pReuse(3)/2, ...
    pReuse(2)+0.34*pReuse(4), ...
    'Admissibility', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.1), ...
    'FontWeight','bold', ...
    'Color',S.text);


%% ========================================================================
% 6. HISTORICAL EVIDENCE
% ========================================================================

round_box( ...
    ax, ...
    pHistory, ...
    [0.988 0.982 0.998], ...
    S.purple, ...
    0.90);

text( ...
    ax, ...
    pHistory(1)+pHistory(3)/2, ...
    pHistory(2)+pHistory(4)/2, ...
    'Historical evidence', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.7), ...
    'FontWeight','bold', ...
    'Color',S.purple);

% Historical evidence -> REUSE
arrow_norm( ...
    ax, ...
    [pHistory(1)+pHistory(3)/2 ...
     pHistory(2)-0.006], ...
    [pReuse(1)+pReuse(3)/2 ...
     pReuse(2)+pReuse(4)+0.006], ...
    S.purple, ...
    1.00);


%% ========================================================================
% 7. FIXED-USE VALUE
% ========================================================================

round_box( ...
    ax, ...
    pFixed, ...
    [0.975 0.995 0.985], ...
    S.green, ...
    0.95);

text( ...
    ax, ...
    pFixed(1)+pFixed(3)/2, ...
    pFixed(2)+0.62*pFixed(4), ...
    'Fixed-use', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.5), ...
    'FontWeight','bold', ...
    'Color',S.green);

text( ...
    ax, ...
    pFixed(1)+pFixed(3)/2, ...
    pFixed(2)+0.33*pFixed(4), ...
    'risk', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.5), ...
    'FontWeight','bold', ...
    'Color',S.green);


%% ========================================================================
% 8. PRESERVE — ADAPTIVE COMPOSABILITY
% ========================================================================

rectangle( ...
    ax, ...
    'Position',pPreserve, ...
    'Curvature',[1 1], ...
    'FaceColor',S.redPale, ...
    'EdgeColor',S.red, ...
    'LineWidth',1.25);

text( ...
    ax, ...
    pPreserve(1)+pPreserve(3)/2, ...
    pPreserve(2)+0.62*pPreserve(4), ...
    'PRESERVE', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,9.4), ...
    'FontWeight','bold', ...
    'Color',S.red);

text( ...
    ax, ...
    pPreserve(1)+pPreserve(3)/2, ...
    pPreserve(2)+0.34*pPreserve(4), ...
    'Composability', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,5.8), ...
    'FontWeight','bold', ...
    'Color',S.text);


%% ========================================================================
% 9. MAIN EVIDENTIAL CHAIN
% ========================================================================

%% ========================================================================
% ARROWS — STRONG VISUAL HIERARCHY
% ========================================================================

% -------------------------------------------------------------------------
% Deployment evidence -> IDENTIFY
% -------------------------------------------------------------------------
arrow_clear( ...
    ax, ...
    [pDep(1)+pDep(3)+0.004, ...
     pIdentify(2)+pIdentify(4)/2], ...
    [pIdentify(1)-0.008, ...
     pIdentify(2)+pIdentify(4)/2], ...
    S.blue, ...
    1.8, ...
    0.020, ...
    0.012);

% -------------------------------------------------------------------------
% Representative outcomes -> IDENTIFY
% -------------------------------------------------------------------------
arrow_clear( ...
    ax, ...
    [pCurrent(1)+pCurrent(3)/2, ...
     pCurrent(2)+pCurrent(4)+0.005], ...
    [pIdentify(1)+pIdentify(3)/2, ...
     pIdentify(2)-0.006], ...
    S.green, ...
    1.5, ...
    0.022, ...
    0.010);

% -------------------------------------------------------------------------
% Current outcomes -> direct estimate
% -------------------------------------------------------------------------
arrow_clear( ...
    ax, ...
    [pCurrent(1)+pCurrent(3)/2, ...
     pCurrent(2)-0.004], ...
    [pDirect(1)+pDirect(3)/2, ...
     pDirect(2)+pDirect(4)+0.005], ...
    S.blue, ...
    1.35, ...
    0.020, ...
    0.009);

% -------------------------------------------------------------------------
% Historical evidence -> REUSE
% -------------------------------------------------------------------------
arrow_clear( ...
    ax, ...
    [pHistory(1)+pHistory(3)/2, ...
     pHistory(2)-0.006], ...
    [pReuse(1)+pReuse(3)/2, ...
     pReuse(2)+pReuse(4)+0.006], ...
    S.purple, ...
    1.5, ...
    0.022, ...
    0.010);

% -------------------------------------------------------------------------
% MAIN CMDO CHAIN
% IDENTIFY -> REUSE -> FIXED-USE VALUE -> PRESERVE
% These should be the visually strongest arrows.
% -------------------------------------------------------------------------

arrow_clear( ...
    ax, ...
    [pIdentify(1)+pIdentify(3)+0.006, ...
     pIdentify(2)+pIdentify(4)/2], ...
    [pReuse(1)-0.010, ...
     pReuse(2)+pReuse(4)/2], ...
    S.axis, ...
    2.1, ...
    0.025, ...
    0.014);

arrow_clear( ...
    ax, ...
    [pReuse(1)+pReuse(3)+0.006, ...
     pReuse(2)+pReuse(4)/2], ...
    [pFixed(1)-0.010, ...
     pFixed(2)+pFixed(4)/2], ...
    S.green, ...
    1.9, ...
    0.023, ...
    0.013);

arrow_clear( ...
    ax, ...
    [pFixed(1)+pFixed(3)+0.005, ...
     pFixed(2)+pFixed(4)/2], ...
    [pPreserve(1)-0.010, ...
     pPreserve(2)+pPreserve(4)/2], ...
    S.red, ...
    1.9, ...
    0.023, ...
    0.013);

% Adaptive-use label belongs to this transition
text( ...
    ax, ...
    (pFixed(1)+pFixed(3)+pPreserve(1))/2, ...
    pFixed(2)+pFixed(4)/2+0.105, ...
    'adaptive rule', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,5.8), ...
    'FontWeight','bold', ...
    'Color',S.red);

% -------------------------------------------------------------------------
% DIRECT ESTIMATE -> REUSE
% Dashed path: baseline entering admissibility comparison
% -------------------------------------------------------------------------

xStart = pDirect(1)+pDirect(3);
yStart = pDirect(2)+0.50*pDirect(4);

xTurn = pReuse(1)+0.50*pReuse(3);
yTop  = pReuse(2)-0.035;

plot( ...
    ax, ...
    [xStart xTurn xTurn], ...
    [yStart yStart yTop], ...
    '--', ...
    'Color',S.green, ...
    'LineWidth',1.25);

% Strong arrowhead only on final vertical segment
arrow_clear( ...
    ax, ...
    [xTurn yTop], ...
    [xTurn pReuse(2)-0.005], ...
    S.green, ...
    1.25, ...
    0.020, ...
    0.010);

% -------------------------------------------------------------------------
% PRESERVE -> FINAL PERFORMANCE
% -------------------------------------------------------------------------
arrow_clear( ...
    ax, ...
    [pPreserve(1)+pPreserve(3)/2, ...
     pPreserve(2)-0.005], ...
    [pFinal(1)+pFinal(3)/2, ...
     pFinal(2)+pFinal(4)+0.008], ...
    S.red, ...
    1.8, ...
    0.024, ...
    0.012);


%% ========================================================================
% 10. DIRECT ESTIMATE ALSO ENTERS THE REUSE DECISION
% Dashed path = baseline/current evidence used in admissibility comparison
% ========================================================================

xStart = ...
    pDirect(1)+pDirect(3);

yStart = ...
    pDirect(2)+0.50*pDirect(4);

xTurn = ...
    pReuse(1)+0.50*pReuse(3);

yEnd = ...
    pReuse(2)-0.020;

plot( ...
    ax, ...
    [xStart xTurn xTurn], ...
    [yStart yStart yEnd], ...
    '--', ...
    'Color',S.green, ...
    'LineWidth',0.90);

arrow_norm( ...
    ax, ...
    [xTurn yEnd], ...
    [xTurn pReuse(2)-0.004], ...
    S.green, ...
    0.90);


%% ========================================================================
% 11. FINAL PERFORMANCE
% ========================================================================

round_box( ...
    ax, ...
    pFinal, ...
    [1.000 0.980 0.980], ...
    S.red, ...
    0.95);

text( ...
    ax, ...
    pFinal(1)+pFinal(3)/2, ...
    pFinal(2)+0.65*pFinal(4), ...
    'Performance estimate', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.4), ...
    'FontWeight','bold', ...
    'Color',S.red);

text( ...
    ax, ...
    pFinal(1)+pFinal(3)/2, ...
    pFinal(2)+0.32*pFinal(4), ...
    'Reuse-risk diagnostics', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,5.8), ...
    'FontWeight','bold', ...
    'Color',S.red);

% PRESERVE -> final performance
arrow_norm( ...
    ax, ...
    [pPreserve(1)+pPreserve(3)/2 ...
     pPreserve(2)-0.004], ...
    [pFinal(1)+pFinal(3)/2 ...
     pFinal(2)+pFinal(4)+0.006], ...
    S.red, ...
    1.05);

end


%% ========================================================================
% CLEAR ARROW FOR PANEL C
% Robust shaft + explicit triangular arrowhead
% ========================================================================
function arrow_clear(ax,p1,p2,c,lw,headL,headW)

x1 = p1(1);
y1 = p1(2);

x2 = p2(1);
y2 = p2(2);

dx = x2-x1;
dy = y2-y1;

L = hypot(dx,dy);

if L <= eps
    return;
end

% Unit direction
ux = dx/L;
uy = dy/L;

% Do not let arrowhead become too large for a short arrow
headL = min(headL,0.30*L);

% Base of triangular head
xb = x2-headL*ux;
yb = y2-headL*uy;

% Perpendicular vector
px = -uy;
py =  ux;

% Shaft
plot( ...
    ax, ...
    [x1 xb], ...
    [y1 yb], ...
    '-', ...
    'Color',c, ...
    'LineWidth',lw, ...
    'Clipping','off');

% Explicit filled triangular head
patch( ...
    ax, ...
    [ ...
        x2, ...
        xb+headW*px, ...
        xb-headW*px], ...
    [ ...
        y2, ...
        yb+headW*py, ...
        yb-headW*py], ...
    c, ...
    'EdgeColor',c, ...
    'LineWidth',0.45, ...
    'Clipping','off');

end
