function Figure5_PhaseBoundary(varargin)
% FIGURE5_PHASEBOUNDARY  CMDO controlled AUC stress-test operating region.
%
% Usage:
%   Figure5_PhaseBoundary
%   Figure5_PhaseBoundary('CSVPath',csvPath,'OutDir',outDir)
%
% INPUT
%   Default: tracked source_data/figure5_submission/
%            CMDO_SystemStress_AUC_StateSummary_v1_1.csv
%
% Heatmap quantity:
%   100 * (MAE_method - MAE_direct) / MAE_direct
%
% For each budget x Lambda cell, the displayed quantity is the WORST value
% over tested true-AUC and mismatch-direction states.

p = inputParser;
addParameter(p,'CSVPath','',@(x)ischar(x) || isstring(x));
addParameter(p,'OutDir','',@(x)ischar(x) || isstring(x));
parse(p,varargin{:});
opt = p.Results;

clc;
close all;

thisFile = mfilename('fullpath');
if isempty(thisFile)
    scriptDir = pwd;
else
    scriptDir = fileparts(thisFile);
end

if strlength(string(opt.CSVPath)) == 0
    repoRoot = fileparts(fileparts(scriptDir));
    csvPath = fullfile( ...
        repoRoot, ...
        'source_data', ...
        'figure5_submission', ...
        'CMDO_SystemStress_AUC_StateSummary_v1_1.csv');
else
    csvPath = char(opt.CSVPath);
end

if ~isfile(csvPath)
    error('CMDO:Figure5SourceMissing', ...
        ['Missing Figure-5 state-summary CSV:' newline '%s' newline ...
         'Use the tracked submission CSV, or pass CSVPath explicitly.'],csvPath);
end

fprintf('\nUsing dense-Lambda result:\n%s\n\n',csvPath);
T = readtable(csvPath);

requiredVars = { ...
    'true_auc', ...
    'budget', ...
    'lambda_nominal', ...
    'bias_sign', ...
    'method', ...
    'method_label', ...
    'mae', ...
    'direct_mae', ...
    'mean_excess_mae', ...
    'gain_percent'};

for i = 1:numel(requiredVars)
    if ~ismember(requiredVars{i},T.Properties.VariableNames)
        error('CMDO:Figure5ColumnMissing', ...
            'Required column missing: %s',requiredVars{i});
    end
end

%% ============================================================
% 2. METHOD DEFINITIONS
% ============================================================

M_CMDO   = 'PC_PAIRED_HOEFFDING';
M_USTAT  = 'PC_USTAT_MCDIARMID';
M_DELONG = 'PC_DELONG';
M_PLUGIN = 'PC_PLUGIN';

methods = { ...
    M_CMDO, ...
    M_USTAT, ...
    M_DELONG, ...
    M_PLUGIN};

methodNames = { ...
    'CMDO', ...
    'U-stat', ...
    'DeLong', ...
    'Plug-in'};

budgets = sort(unique(T.budget(:)))';
lambdas = sort(unique(T.lambda_nominal(:)))';

nB = numel(budgets);
nL = numel(lambdas);

%% ============================================================
% 3. BUILD NORMALIZED WORST-CASE PHASE MAPS
% ============================================================

Znorm = nan( ...
    nB, ...
    nL, ...
    numel(methods));

Zraw = nan( ...
    nB, ...
    nL, ...
    numel(methods));

for im = 1:numel(methods)

    for ib = 1:nB

        for il = 1:nL

            mask = ...
                strcmp(T.method,methods{im}) & ...
                T.budget == budgets(ib) & ...
                abs( ...
                T.lambda_nominal-lambdas(il)) < 1e-12;

            if ~any(mask)

                error( ...
                    ['Missing state:\n', ...
                     'method=%s  budget=%g  Lambda=%g'], ...
                    methods{im}, ...
                    budgets(ib), ...
                    lambdas(il));
            end

            excess = ...
                T.mean_excess_mae(mask);

            direct = ...
                T.direct_mae(mask);

            normalized = ...
                100 .* excess ./ direct;

            Znorm(ib,il,im) = ...
                max(normalized);

            Zraw(ib,il,im) = ...
                max(excess);
        end
    end
end

Z_CMDO   = Znorm(:,:,1);
Z_USTAT  = Znorm(:,:,2);
Z_DELONG = Znorm(:,:,3);
Z_PLUGIN = Znorm(:,:,4);

%% ============================================================
% 4. CRITICAL LAMBDA BY BUDGET
%
% Largest tested Lambda reached CONTIGUOUSLY from Lambda = 0
% while every tested AUC/sign state remains non-inferior.
% ============================================================

criticalLambda = ...
    zeros(nB,numel(methods));

for im = 1:numel(methods)

    Z = Zraw(:,:,im);

    for ib = 1:nB

        crit = 0;

        for il = 1:nL

            if Z(ib,il) <= 0

                crit = lambdas(il);

            else

                break;
            end
        end

        criticalLambda(ib,im) = crit;
    end
end

%% ============================================================
% 5. PAIRED CMDO vs U-STAT
%
% Exact matching on:
%
% true_auc x budget x Lambda x bias_sign
% ============================================================

keyVars = { ...
    'true_auc', ...
    'budget', ...
    'lambda_nominal', ...
    'bias_sign'};

TC = T( ...
    strcmp(T.method,M_CMDO), ...
    [keyVars {'gain_percent'}]);

TU = T( ...
    strcmp(T.method,M_USTAT), ...
    [keyVars {'gain_percent'}]);

TC.Properties.VariableNames{end} = ...
    'gain_CMDO';

TU.Properties.VariableNames{end} = ...
    'gain_USTAT';

P = innerjoin( ...
    TC, ...
    TU, ...
    'Keys',keyVars);

P.advantage_pp = ...
    P.gain_CMDO - P.gain_USTAT;

% Shared empirically robust region
sharedMask = ...
    P.lambda_nominal <= 1.0 + 1e-12;

Pshared = ...
    P(sharedMask,:);

%% ============================================================
% 6. STYLE
% ============================================================

C_CMDO = ...
    [0.07 0.34 0.68];

C_USTAT = ...
    [0.09 0.58 0.55];

C_DELONG = ...
    [0.91 0.52 0.08];

C_PLUGIN = ...
    [0.80 0.18 0.16];

C_TEXT = ...
    [0.15 0.15 0.15];

C_MUTED = ...
    [0.46 0.46 0.46];

C_GRID = ...
    [0.86 0.86 0.86];

fsAxis  = 10.5;
fsTitle = 12.2;
fsPanel = 18;
fsSmall = 12;

% Heatmap clipping only for visualization
displayLim = 10;

%% ============================================================
% 7. PANEL B SUMMARY STATISTICS
% ============================================================

rng(20260831);

meanAdv = ...
    nan(size(budgets));

q25 = ...
    nan(size(budgets));

q75 = ...
    nan(size(budgets));

for ib = 1:nB

    vals = ...
        Pshared.advantage_pp( ...
        Pshared.budget == budgets(ib));

    meanAdv(ib) = ...
        mean(vals);

    q25(ib) = ...
        empiricalQuantile(vals,0.25);

    q75(ib) = ...
        empiricalQuantile(vals,0.75);
end

allAdv = ...
    Pshared.advantage_pp;

yr = ...
    max(allAdv)-min(allAdv);

if yr <= 0
    yr = 1;
end

overallMeanAdv = ...
    mean(Pshared.advantage_pp);

fracPositive = ...
    mean(Pshared.advantage_pp > 0);

%% ============================================================
% 8. FIGURE CANVAS
% ============================================================

fig = figure( ...
    'Color','w', ...
    'Position',[40 30 1120 850], ...
    'Renderer','painters');

colormap( ...
    fig, ...
    blueWhiteRed(257));

% ------------------------------------------------------------
% Layout
%
% A + B = headline results
% C     = full-width explanatory phase maps
% ------------------------------------------------------------

posA = ...
    [0.080 0.570 0.390 0.340];

posB = ...
    [0.550 0.570 0.390 0.340];

posC = ...
    [0.080 0.095 0.860 0.330];

%% ============================================================
% PANEL A
% ROBUSTNESS BOUNDARY
% ============================================================

axA = axes( ...
    'Parent',fig, ...
    'Position',posA);

hideToolbarSafe(axA);

hold(axA,'on');
box(axA,'off');

% ------------------------------------------------------------
% Tested ceiling
% ------------------------------------------------------------

plot( ...
    axA, ...
    [min(budgets)*0.80 ...
     max(budgets)*1.25], ...
    [max(lambdas) ...
     max(lambdas)], ...
    ':', ...
    'Color',[0.60 0.60 0.60], ...
    'LineWidth',1.15);

% ------------------------------------------------------------
% Plug-in
% ------------------------------------------------------------

hPlugin = plot( ...
    axA, ...
    budgets, ...
    criticalLambda(:,4), ...
    '-o', ...
    'Color',C_PLUGIN, ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor',C_PLUGIN, ...
    'LineWidth',1.65, ...
    'MarkerSize',6.0);

% ------------------------------------------------------------
% DeLong
% ------------------------------------------------------------

hDeLong = plot( ...
    axA, ...
    budgets, ...
    criticalLambda(:,3), ...
    '-s', ...
    'Color',C_DELONG, ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor',C_DELONG, ...
    'LineWidth',1.65, ...
    'MarkerSize',6.0);

% ------------------------------------------------------------
% U-stat
% ------------------------------------------------------------

hUstat = plot( ...
    axA, ...
    budgets, ...
    criticalLambda(:,2), ...
    '-^', ...
    'Color',C_USTAT, ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor',C_USTAT, ...
    'LineWidth',2.20, ...
    'MarkerSize',7.2);

% ------------------------------------------------------------
% CMDO
% ------------------------------------------------------------

hCMDO = plot( ...
    axA, ...
    budgets, ...
    criticalLambda(:,1), ...
    '-o', ...
    'Color',C_CMDO, ...
    'MarkerFaceColor',C_CMDO, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',2.65, ...
    'MarkerSize',8.0);

set( ...
    axA, ...
    'XScale','log', ...
    'XTick',budgets, ...
    'XTickLabel',compose('%g',budgets), ...
    'YTick',[0 1 2 3 4], ...
    'FontSize',fsAxis, ...
    'TickDir','out', ...
    'LineWidth',1.0);

xlabel( ...
    axA, ...
    'Current-outcome budget, m');

ylabel( ...
    axA, ...
    {'Largest tested \Lambda with'; ...
     'complete non-inferiority'});

xlim( ...
    axA, ...
    [min(budgets)*0.82 ...
     max(budgets)*1.20]);

ylim( ...
    axA, ...
    [-0.05 ...
     max(lambdas)+0.22]);

grid(axA,'on');

axA.GridAlpha = 0.13;
axA.GridColor = C_GRID;

leftTitle( ...
    axA, ...
    'Guarded reuse expands the non-inferior region', ...
    fsTitle);

panelLabel( ...
    axA, ...
    'A', ...
    fsPanel);

legend( ...
    axA, ...
    [hPlugin hDeLong hUstat hCMDO], ...
    {'Plug-in','DeLong','U-stat','CMDO'}, ...
    'Location','southeast', ...
    'Box','off', ...
    'FontSize',fsSmall);

text( ...
    axA, ...
    0.98, ...
    0.96, ...
    '\Lambda = 4: tested grid limit', ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontSize',fsSmall, ...
    'Color',C_MUTED);

%% ============================================================
% PANEL B
% EFFICIENCY WITHIN SHARED ROBUST REGION
% ============================================================

axB = axes( ...
    'Parent',fig, ...
    'Position',posB);

hideToolbarSafe(axB);

hold(axB,'on');
box(axB,'off');

% ------------------------------------------------------------
% Zero reference
% ------------------------------------------------------------

plot( ...
    axB, ...
    [min(budgets)*0.75 ...
     max(budgets)*1.30], ...
    [0 0], ...
    '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.0);

% ------------------------------------------------------------
% Individual matched states
% ------------------------------------------------------------

for ib = 1:nB

    vals = ...
        Pshared.advantage_pp( ...
        Pshared.budget == budgets(ib));

    jitter = ...
        exp(0.055*randn(size(vals)));

    xj = ...
        budgets(ib).*jitter;

    scatter( ...
        axB, ...
        xj, ...
        vals, ...
        21, ...
        [0.82 0.88 0.96], ...
        'filled', ...
        'MarkerEdgeColor','none');
end

% ------------------------------------------------------------
% IQR
% ------------------------------------------------------------

for ib = 1:nB

    plot( ...
        axB, ...
        [budgets(ib) budgets(ib)], ...
        [q25(ib) q75(ib)], ...
        '-', ...
        'Color',C_CMDO, ...
        'LineWidth',3.0);
end

% ------------------------------------------------------------
% Mean
% ------------------------------------------------------------

plot( ...
    axB, ...
    budgets, ...
    meanAdv, ...
    '-o', ...
    'Color',C_CMDO, ...
    'MarkerFaceColor',C_CMDO, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',2.35, ...
    'MarkerSize',7.4);

set( ...
    axB, ...
    'XScale','log', ...
    'XTick',budgets, ...
    'XTickLabel',compose('%g',budgets), ...
    'FontSize',fsAxis, ...
    'TickDir','out', ...
    'LineWidth',1.0);

xlabel( ...
    axB, ...
    'Current-outcome audit budget, m');

ylabel( ...
    axB, ...
    'CMDO - U-stat MAE gain (pp)');

xlim( ...
    axB, ...
    [min(budgets)*0.82 ...
     max(budgets)*1.20]);

ylim( ...
    axB, ...
    [min(-0.15,min(allAdv)-0.10*yr), ...
     max(allAdv)+0.22*yr]);

grid(axB,'on');

axB.GridAlpha = 0.13;
axB.GridColor = C_GRID;

leftTitle( ...
    axB, ...
    'Efficiency differs within the shared robust region', ...
    fsTitle);

panelLabel( ...
    axB, ...
    'B', ...
    fsPanel);

% % ------------------------------------------------------------
% % Region definition
% % ------------------------------------------------------------
% 
% text( ...
%     axB, ...
%     0.025, ...
%     0.92, ...
%     '\Lambda \leq 1 shared robust region', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','left', ...
%     'VerticalAlignment','top', ...
%     'FontSize',fsSmall, ...
%     'Color',C_MUTED);

% ------------------------------------------------------------
% Main result box
% ------------------------------------------------------------

summaryText = { ...
    sprintf('mean difference +%.2f pp',overallMeanAdv)
    sprintf('CMDO higher in %.0f%% of states',100*fracPositive)};

text( ...
    axB, ...
    0.975, ...
    0.3, ...
    summaryText, ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontSize',fsSmall+0.9, ...
    'FontWeight','bold', ...
    'Color',C_CMDO, ...
    'BackgroundColor','w', ...
    'Margin',5, ...
    'EdgeColor',[0.84 0.89 0.96]);

%% ============================================================
% PANEL C
% FULL-WIDTH OPERATING REGION MAPS
% ============================================================

axCmaster = axes( ...
    'Parent',fig, ...
    'Position',posC);

hideToolbarSafe(axCmaster);

axis(axCmaster,'off');

leftTitle( ...
    axCmaster, ...
    'Operating regions explain the robustness-efficiency trade-off', ...
    fsTitle);

panelLabel( ...
    axCmaster, ...
    'C', ...
    fsPanel);

drawnow;

p = ...
    axCmaster.Position;

% ------------------------------------------------------------
% Geometry inside panel C
% ------------------------------------------------------------

leftMargin = ...
    0.035*p(3);

rightMargin = ...
    0.095*p(3);

gap = ...
    0.050*p(3);

bottomMargin = ...
    0.205*p(4);

topMargin = ...
    0.175*p(4);

wSmall = ...
    (p(3) ...
    - leftMargin ...
    - rightMargin ...
    - 2*gap) / 3;

hSmall = ...
    p(4) ...
    - bottomMargin ...
    - topMargin;

x1 = ...
    p(1)+leftMargin;

x2 = ...
    x1+wSmall+gap;

x3 = ...
    x2+wSmall+gap;

y0 = ...
    p(2)+bottomMargin;

posC1 = ...
    [x1 y0 wSmall hSmall];

posC2 = ...
    [x2 y0 wSmall hSmall];

posC3 = ...
    [x3 y0 wSmall hSmall];

% ------------------------------------------------------------
% CMDO
% ------------------------------------------------------------

axC1 = axes( ...
    'Parent',fig, ...
    'Position',posC1);

hideToolbarSafe(axC1);

plotPhaseMapWide( ...
    axC1, ...
    Z_CMDO, ...
    budgets, ...
    lambdas, ...
    displayLim, ...
    'CMDO', ...
    fsAxis);

ylabel( ...
    axC1, ...
    'Current-outcome budget, m');

% ------------------------------------------------------------
% U-stat
% ------------------------------------------------------------

axC2 = axes( ...
    'Parent',fig, ...
    'Position',posC2);

hideToolbarSafe(axC2);

plotPhaseMapWide( ...
    axC2, ...
    Z_USTAT, ...
    budgets, ...
    lambdas, ...
    displayLim, ...
    'U-stat', ...
    fsAxis);

ylabel(axC2,'');
set(axC2,'YTickLabel',[]);

% ------------------------------------------------------------
% Plug-in
% ------------------------------------------------------------

axC3 = axes( ...
    'Parent',fig, ...
    'Position',posC3);

hideToolbarSafe(axC3);

plotPhaseMapWide( ...
    axC3, ...
    Z_PLUGIN, ...
    budgets, ...
    lambdas, ...
    displayLim, ...
    'Plug-in', ...
    fsAxis);

ylabel(axC3,'');
set(axC3,'YTickLabel',[]);

% ------------------------------------------------------------
% Same colour limits
% ------------------------------------------------------------

caxis( ...
    axC1, ...
    [-displayLim displayLim]);

caxis( ...
    axC2, ...
    [-displayLim displayLim]);

caxis( ...
    axC3, ...
    [-displayLim displayLim]);

% ------------------------------------------------------------
% Shared colourbar
%
% Create it from axC3 but restore axC3 so all heatmaps remain
% equal width.
% ------------------------------------------------------------

cb = ...
    colorbar(axC3,'eastoutside');

axC3.Position = ...
    posC3;

cb.Position = [ ...
    p(1)+0.945*p(3), ...
    y0, ...
    0.016*p(3), ...
    hSmall];

cb.Label.String = ...
    {'Worst relative excess MAE (%)'; ...
     'clipped at \pm10%'};

cb.Label.FontSize = ...
    fsSmall+0.2;

cb.FontSize = ...
    8.2;

% ------------------------------------------------------------
% Shared Lambda label
% ------------------------------------------------------------

text( ...
    axCmaster, ...
    0.47, ...
    0.080, ...
    '\Lambda = B^2/V', ...
    'Units','normalized', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontSize',9.5, ...
    'Color',C_TEXT);



%% ============================================================
% 9. EXPORT
% ============================================================

drawnow;

if strlength(string(opt.OutDir)) == 0
    outdir = fullfile(scriptDir,'output');
else
    outdir = char(opt.OutDir);
end

if ~isfolder(outdir)
    mkdir(outdir);
end

pngPath = ...
    fullfile( ...
    outdir, ...
    'Figure5_PhaseBoundary_Final_3Panel.png');

pdfPath = ...
    fullfile( ...
    outdir, ...
    'Figure5_PhaseBoundary_Final_3Panel.pdf');

exportgraphics( ...
    fig, ...
    pngPath, ...
    'Resolution',300, ...
    'BackgroundColor','white');

exportgraphics( ...
    fig, ...
    pdfPath, ...
    'ContentType','vector', ...
    'BackgroundColor','white');

%% ============================================================
% 10. CONSOLE SUMMARY
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('FIGURE 5 FINAL 3-PANEL ANALYSIS\n');
fprintf('============================================================\n');

fprintf('Input:\n%s\n\n',csvPath);

fprintf('Critical tested Lambda by budget\n\n');

fprintf( ...
    '%8s %10s %10s %10s %10s\n', ...
    'm', ...
    'CMDO', ...
    'U-stat', ...
    'DeLong', ...
    'Plug-in');

for ib = 1:nB

    fprintf( ...
        '%8g %10.2f %10.2f %10.2f %10.2f\n', ...
        budgets(ib), ...
        criticalLambda(ib,1), ...
        criticalLambda(ib,2), ...
        criticalLambda(ib,3), ...
        criticalLambda(ib,4));
end

fprintf('\n');

fprintf( ...
    'Shared robust region Lambda <= 1:\n');

fprintf( ...
    'Mean CMDO-U-stat advantage = %.4f pp\n', ...
    overallMeanAdv);

fprintf( ...
    'Paired states CMDO > U-stat = %.2f %%\n', ...
    100*fracPositive);

fprintf('\n');

fprintf('PNG:\n%s\n',pngPath);
fprintf('PDF:\n%s\n',pdfPath);

fprintf('============================================================\n\n');

end

%% ============================================================
% LOCAL FUNCTION
% FULL-WIDTH PHASE MAP
% ============================================================
function plotPhaseMapWide( ...
    ax, ...
    Z, ...
    budgets, ...
    lambdas, ...
    displayLim, ...
    titleText, ...
    fsAxis)

hold(ax,'on');

Zdisplay = ...
    min(max(Z,-displayLim),displayLim);

imagesc( ...
    ax, ...
    1:numel(lambdas), ...
    1:numel(budgets), ...
    Zdisplay);

% Keep useful Lambda ticks now that panel C is full width
preferred = ...
    [0 0.5 1 2 4];

shownVals = ...
    preferred( ...
    ismember(preferred,lambdas));

[~,shownIdx] = ...
    ismember(shownVals,lambdas);

if isempty(shownIdx)

    shownIdx = ...
        1:numel(lambdas);

    shownVals = ...
        lambdas;
end

set( ...
    ax, ...
    'YDir','normal', ...
    'XTick',shownIdx, ...
    'XTickLabel',compose('%g',shownVals), ...
    'YTick',1:numel(budgets), ...
    'YTickLabel',compose('%g',budgets), ...
    'FontSize',fsAxis-0.5, ...
    'TickDir','out', ...
    'LineWidth',0.9);

caxis( ...
    ax, ...
    [-displayLim displayLim]);

box(ax,'off');

% ------------------------------------------------------------
% Zero-excess boundary
% ------------------------------------------------------------

[XI,YI] = meshgrid( ...
    1:numel(lambdas), ...
    1:numel(budgets));

try

    contour( ...
        ax, ...
        XI, ...
        YI, ...
        Z, ...
        [0 0], ...
        'k-', ...
        'LineWidth',1.75);

catch
end

% ------------------------------------------------------------
% Harmful cells
% ------------------------------------------------------------

for ib = 1:size(Z,1)

    for il = 1:size(Z,2)

        if Z(ib,il) > 0

            text( ...
                ax, ...
                il, ...
                ib, ...
                '\times', ...
                'HorizontalAlignment','center', ...
                'VerticalAlignment','middle', ...
                'FontSize',9.4, ...
                'FontWeight','bold', ...
                'Color',[0.22 0.04 0.04]);
        end
    end
end

title( ...
    ax, ...
    titleText, ...
    'FontSize',10.8, ...
    'FontWeight','bold');

end

%% ============================================================
% LOCAL FUNCTION
% BLUE-WHITE-RED DIVERGING COLORMAP
% ============================================================

function cmap = blueWhiteRed(n)

if nargin < 1
    n = 257;
end

n1 = ...
    floor(n/2);

n2 = ...
    n-n1;

blue = ...
    [0.12 0.39 0.72];

white = ...
    [1 1 1];

red = ...
    [0.79 0.18 0.16];

left = [ ...
    linspace(blue(1),white(1),n1)' ...
    linspace(blue(2),white(2),n1)' ...
    linspace(blue(3),white(3),n1)' ];

right = [ ...
    linspace(white(1),red(1),n2)' ...
    linspace(white(2),red(2),n2)' ...
    linspace(white(3),red(3),n2)' ];

cmap = ...
    [left;right];

end

%% ============================================================
% LOCAL FUNCTION
% EMPIRICAL QUANTILE
% ============================================================

function q = empiricalQuantile(x,p)

x = ...
    sort(x(:));

n = ...
    numel(x);

if n == 0

    q = NaN;

    return;
end

if n == 1

    q = x(1);

    return;
end

r = ...
    1+(n-1)*p;

lo = ...
    floor(r);

hi = ...
    ceil(r);

if lo == hi

    q = x(lo);

else

    w = ...
        r-lo;

    q = ...
        (1-w)*x(lo) ...
        + w*x(hi);
end

end

%% ============================================================
% LOCAL FUNCTION
% LEFT-ALIGNED TITLE
% ============================================================

function h = leftTitle( ...
    ax, ...
    str, ...
    fontSize)

h = title( ...
    ax, ...
    str, ...
    'FontSize',fontSize, ...
    'FontWeight','bold');

try

    h.Units = ...
        'normalized';

    p = ...
        h.Position;

    p(1) = ...
        0;

    h.Position = ...
        p;

    h.HorizontalAlignment = ...
        'left';

catch
end

end

%% ============================================================
% LOCAL FUNCTION
% HIDE AXES TOOLBAR
% ============================================================

function hideToolbarSafe(ax)

try

    ax.Toolbar.Visible = ...
        'off';

catch

    try
        axtoolbar(ax,{});
    catch
    end
end

end

%% ============================================================
% LOCAL FUNCTION
% PANEL LABEL
% ============================================================

function panelLabel( ...
    ax, ...
    labelText, ...
    fontSize)

text( ...
    ax, ...
    -0.075, ...
    1.030, ...
    labelText, ...
    'Units','normalized', ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'Clipping','off');

end
