function ED2_IntegrityControls_v2(outputDir, repoRoot)
% ED2_INTEGRITYCONTROLS_V2
%
% Extended Data Figure 2
% Role separation localizes a coupling pathway but incurs finite-audit cost.
%
% Scientific role after main-figure reorganization:
%
%   A  Role separation isolates decision and evaluation
%   B  Role separation suppresses coupling signatures
%   C  Role separation carries a finite-audit cost
%   D  Locked external mechanism challenge
%
% Main Fig. 5 establishes PRESERVE / adaptive composability.
% ED2 provides the detailed mechanistic evidence behind one candidate
% coupling pathway without treating that pathway as a universal mechanism.
%
% Notes:
%   - B/C use locked summary values from the current CMDO analysis.
%   - D loads the real locked external dependence decomposition when the
%     repository is available; otherwise it falls back to current values.
%
% Usage:
%   ED2_IntegrityControls_v2
%
% or:
%   ED2_IntegrityControls_v2([], ...
%       'C:\Users\zyx\CMDO-Reproducibility')
%
% -------------------------------------------------------------------------

close all;

%% ========================================================================
% 0) PATHS
% ========================================================================

thisFile = mfilename('fullpath');

if isempty(thisFile)
    scriptDir = pwd;
else
    scriptDir = fileparts(thisFile);
end

if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(scriptDir,'output');
end

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

if nargin < 2 || isempty(repoRoot)
    repoRoot = local_find_cmdo_repo(scriptDir);
end

%% ========================================================================
% 1) STYLE
% ========================================================================

FONT = 'Arial';

FS_LETTER = 22;
FS_TITLE  = 11.5;
FS_AXIS   = 9.2;
FS_TICK   = 8.5;
FS_SMALL  = 8.0;
FS_TINY   = 7.0;

navy   = [0.02 0.27 0.67];
blue   = [0.04 0.34 0.78];
green  = [0.02 0.50 0.20];
red    = [0.84 0.08 0.06];
orange = [0.94 0.39 0.05];
purple = [0.47 0.20 0.74];

grey   = [0.44 0.44 0.44];
dgrey  = [0.20 0.20 0.20];
ltgrey = [0.72 0.72 0.72];

panelBlue   = local_mix(blue,[1 1 1],0.82);
panelGreen  = local_mix(green,[1 1 1],0.84);
panelOrange = local_mix(orange,[1 1 1],0.87);
panelPurple = local_mix(purple,[1 1 1],0.87);

%% ========================================================================
% 2) LOCKED MECHANISM SUMMARY VALUES
% ========================================================================

% Shared-audit versus role-separated coupling summaries.
corr_shared = 0.940;
corr_sep    = 0.056;

disp_shared = 9.45;
disp_sep    = 2.19;

corr_drop = 100*(1-corr_sep/corr_shared);
disp_drop = 100*(1-disp_sep/disp_shared);

% Finite-audit consequences of the strict role-separated control.
cost_vals = [6.54, -85.55, 98.80];

% Locked external mechanism checks.
georgia_checks = 3;
cpsc_checks    = 2;
n_checks       = 4;

%% ========================================================================
% 3) LOCKED EXTERNAL DECOMPOSITION
% ========================================================================

state_labels = { ...
    'Georgia 128', ...
    'Georgia 256', ...
    'Georgia 512', ...
    'Georgia 1024', ...
    'CPSC 128', ...
    'CPSC 256', ...
    'CPSC 512', ...
    'CPSC 1024'};

% Fallback values only if local repository file cannot be found.
x_fixed = [46,33,17,17,33,19,5,12];
x_adapt = [29,15,-11,-10,11,-10,-27,-4];

% Retain the machine-readable frozen verdict for console auditing only.
% It is intentionally NOT displayed as manuscript text.
gateText = 'MECHANISM NOT CONFIRMED';

if ~isempty(repoRoot)

    u10Path = fullfile( ...
        repoRoot, ...
        'U10_Prospective_ECG', ...
        '02_Posthoc_Diagnostics', ...
        'U10_DEPENDENCE_DECOMPOSITION.csv');

    if isfile(u10Path)

        U10 = readtable( ...
            u10Path, ...
            'VariableNamingRule','preserve');

        need = { ...
            'dataset', ...
            'budget', ...
            'shared_adaptive_gain_pct', ...
            'shared_constant_mean_gain_pct'};

        for i = 1:numel(need)

            if ~ismember(need{i},U10.Properties.VariableNames)

                error( ...
                    'U10 table missing field: %s', ...
                    need{i});

            end

        end

        ds = string(U10.dataset);
        bg = double(U10.budget);

        order = [];

        dsOrder = ["georgia","cpsc_2018"];

        for d = 1:numel(dsOrder)

            idx = find(ds==dsOrder(d));

            [~,o] = sort(bg(idx),'ascend');

            order = [order; idx(o)]; %#ok<AGROW>

        end

        U10 = U10(order,:);

        x_adapt = ...
            double(U10.shared_adaptive_gain_pct(:))';

        x_fixed = ...
            double(U10.shared_constant_mean_gain_pct(:))';

        state_labels = ...
            cell(1,height(U10));

        for i = 1:height(U10)

            if string(U10.dataset(i))=="georgia"
                cohort = 'Georgia';
            else
                cohort = 'CPSC';
            end

            state_labels{i} = ...
                sprintf( ...
                    '%s %d', ...
                    cohort, ...
                    double(U10.budget(i)));

        end

    end

    gatePath = fullfile( ...
        repoRoot, ...
        'U10_Prospective_ECG', ...
        '01_Prospective_Result', ...
        'U10_PRIMARY_RESULT.json');

    if isfile(gatePath)

        J = jsondecode(fileread(gatePath));

        if isfield(J,'primary_verdict')

            gateText = ...
                strrep( ...
                    char(string(J.primary_verdict)), ...
                    '_',' ');

        end

    end

end

%% ========================================================================
% 4) AUDIT QUANTITIES
% ========================================================================

xi_vals = ...
    x_fixed-x_adapt;

n_fixed_beneficial = ...
    nnz(x_fixed>0);

n_adapt_harmful = ...
    nnz(x_adapt<0);

n_xi_positive = ...
    nnz(xi_vals>0);

fprintf('\n============================================================\n');
fprintf(' CMDO EXTENDED DATA FIGURE 2\n');
fprintf(' Role separation and coupling-pathway diagnostics\n');
fprintf('============================================================\n');

fprintf('Output directory: %s\n',outputDir);

if ~isempty(repoRoot)
    fprintf('Repository      : %s\n',repoRoot);
end

fprintf('\nCoupling diagnostics\n');
fprintf('Weight-error coupling : %.3f -> %.3f (drop %.1f%%)\n', ...
    corr_shared,corr_sep,corr_drop);

fprintf('Cross-term displacement: %.2f -> %.2f pp (drop %.1f%%)\n', ...
    disp_shared,disp_sep,disp_drop);

fprintf('\nLocked external challenge\n');
fprintf('Georgia checks   = %d/%d\n',georgia_checks,n_checks);
fprintf('CPSC 2018 checks = %d/%d\n',cpsc_checks,n_checks);
fprintf('Fixed beneficial = %d/%d\n', ...
    n_fixed_beneficial,numel(x_fixed));
fprintf('Adaptive harmful = %d/%d\n', ...
    n_adapt_harmful,numel(x_adapt));
fprintf('Xi positive      = %d/%d\n', ...
    n_xi_positive,numel(xi_vals));
fprintf('Frozen verdict   = %s\n',gateText);

%% ========================================================================
% 5) CANVAS
% ========================================================================

fig = figure( ...
    'Color','w', ...
    'Position',[60 45 1040 820], ...
    'Renderer','painters', ...
    'Name','CMDO Extended Data Figure 2', ...
    'NumberTitle','off');

PA = [0.025 0.515 0.465 0.455];
PB = [0.510 0.515 0.465 0.455];

PC = [0.025 0.040 0.465 0.435];
PD = [0.510 0.040 0.465 0.435];

%% ========================================================================
% PANEL A
% ROLE SEPARATION ISOLATES DECISION AND EVALUATION
% ========================================================================

axA0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PA);

axis(axA0,[0 1 0 1]);
axis(axA0,'off');
hold(axA0,'on');

local_panel_border( ...
    axA0, ...
    [0.005 0.005 0.99 0.99], ...
    panelBlue, ...
    1.0);

local_panel_header( ...
    axA0, ...
    'A', ...
    'Role separation isolates decision and evaluation', ...
    0.025,0.955, ...
    navy,FONT,FS_LETTER,FS_TITLE);

% -------------------------------------------------------------------------
% Shared audit
% -------------------------------------------------------------------------

text( ...
    axA0, ...
    0.075,0.825, ...
    'Shared audit', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.7, ...
    'FontWeight','bold', ...
    'Color',navy);

local_box( ...
    axA0, ...
    [0.075 0.635 0.165 0.115], ...
    {'Current','audit'}, ...
    navy,FONT,FS_SMALL);

local_box( ...
    axA0, ...
    [0.355 0.720 0.180 0.105], ...
    {'Borrowing','decision'}, ...
    green,FONT,FS_SMALL);

local_box( ...
    axA0, ...
    [0.355 0.545 0.180 0.105], ...
    {'Current','evaluation'}, ...
    red,FONT,FS_SMALL);

local_box( ...
    axA0, ...
    [0.730 0.630 0.180 0.120], ...
    {'Adaptive','evaluator'}, ...
    purple,FONT,FS_SMALL);

local_arrow_axes( ...
    axA0, ...
    [0.240 0.355], ...
    [0.690 0.765], ...
    navy);

local_arrow_axes( ...
    axA0, ...
    [0.240 0.355], ...
    [0.690 0.600], ...
    navy);

local_arrow_axes( ...
    axA0, ...
    [0.535 0.730], ...
    [0.765 0.690], ...
    green);

local_arrow_axes( ...
    axA0, ...
    [0.535 0.730], ...
    [0.600 0.690], ...
    red);

text( ...
    axA0, ...
    0.445,0.505, ...
    'same outcomes serve both roles', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY, ...
    'FontAngle','italic', ...
    'Color',grey);

plot( ...
    axA0, ...
    [0.06 0.93], ...
    [0.470 0.470], ...
    '--', ...
    'Color',[0.70 0.70 0.70], ...
    'LineWidth',0.8);

% -------------------------------------------------------------------------
% Role-separated audit
% -------------------------------------------------------------------------

text( ...
    axA0, ...
    0.075,0.405, ...
    'Role separated', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.7, ...
    'FontWeight','bold', ...
    'Color',green);

local_box( ...
    axA0, ...
    [0.075 0.245 0.165 0.100], ...
    {'Evaluation','audit half'}, ...
    navy,FONT,FS_SMALL-0.2);

local_box( ...
    axA0, ...
    [0.075 0.085 0.165 0.100], ...
    {'Decision','audit half'}, ...
    green,FONT,FS_SMALL-0.2);

local_box( ...
    axA0, ...
    [0.355 0.245 0.180 0.100], ...
    {'Current','evaluation'}, ...
    red,FONT,FS_SMALL);

local_box( ...
    axA0, ...
    [0.355 0.085 0.180 0.100], ...
    {'Borrowing','decision'}, ...
    green,FONT,FS_SMALL);

local_box( ...
    axA0, ...
    [0.730 0.160 0.180 0.120], ...
    {'Role-separated','evaluator'}, ...
    purple,FONT,FS_SMALL-0.2);

local_arrow_axes( ...
    axA0, ...
    [0.240 0.355], ...
    [0.295 0.295], ...
    navy);

local_arrow_axes( ...
    axA0, ...
    [0.240 0.355], ...
    [0.135 0.135], ...
    green);

local_arrow_axes( ...
    axA0, ...
    [0.535 0.730], ...
    [0.295 0.220], ...
    red);

local_arrow_axes( ...
    axA0, ...
    [0.535 0.730], ...
    [0.135 0.220], ...
    green);

text( ...
    axA0, ...
    0.445,0.035, ...
    'non-overlapping outcomes separate the two roles', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY, ...
    'FontAngle','italic', ...
    'Color',grey);

%% ========================================================================
% PANEL B
% ROLE SEPARATION SUPPRESSES COUPLING SIGNATURES
% ========================================================================

axB0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PB);

axis(axB0,[0 1 0 1]);
axis(axB0,'off');
hold(axB0,'on');

local_panel_border( ...
    axB0, ...
    [0.005 0.005 0.99 0.99], ...
    panelGreen, ...
    1.0);

local_panel_header( ...
    axB0, ...
    'B', ...
    'Role separation suppresses coupling signatures', ...
    0.025,0.955, ...
    green,FONT,FS_LETTER,FS_TITLE);

% -------------------------------------------------------------------------
% Weight-error coupling
% -------------------------------------------------------------------------

axB1 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',local_relpos(PB,[0.195 0.570 0.650 0.235]));

hold(axB1,'on');

plot( ...
    axB1, ...
    [corr_sep corr_shared], ...
    [1 2], ...
    '-', ...
    'Color',ltgrey, ...
    'LineWidth',1.5);

scatter( ...
    axB1, ...
    corr_sep,1, ...
    65,green, ...
    'filled', ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.6);

scatter( ...
    axB1, ...
    corr_shared,2, ...
    65,red, ...
    'filled', ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.6);

text( ...
    axB1, ...
    corr_sep+0.035,0.80, ...
    sprintf('%.3f',corr_sep), ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',green);

text( ...
    axB1, ...
    corr_shared-0.018,2.20, ...
    sprintf('%.3f',corr_shared), ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',red);

set( ...
    axB1, ...
    'XLim',[0 1.02], ...
    'YLim',[0.55 2.45], ...
    'YTick',[1 2], ...
    'YTickLabel',{'Role separated','Shared audit'}, ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

xlabel( ...
    axB1, ...
    'Coupling magnitude', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

title( ...
    axB1, ...
    'Weight-error coupling', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold');

text( ...
    axB0, ...
    0.885,0.670, ...
    sprintf('\\downarrow %.1f%%',corr_drop), ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.7, ...
    'FontWeight','bold', ...
    'Color',purple);

% -------------------------------------------------------------------------
% Cross-term displacement
% -------------------------------------------------------------------------

axB2 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',local_relpos(PB,[0.195 0.175 0.650 0.235]));

hold(axB2,'on');

plot( ...
    axB2, ...
    [disp_sep disp_shared], ...
    [1 2], ...
    '-', ...
    'Color',ltgrey, ...
    'LineWidth',1.5);

scatter( ...
    axB2, ...
    disp_sep,1, ...
    65,green, ...
    'filled', ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.6);

scatter( ...
    axB2, ...
    disp_shared,2, ...
    65,red, ...
    'filled', ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.6);

text( ...
    axB2, ...
    disp_sep+0.25,0.80, ...
    sprintf('%.2f',disp_sep), ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',green);

text( ...
    axB2, ...
    disp_shared-0.15,2.20, ...
    sprintf('%.2f',disp_shared), ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',red);

set( ...
    axB2, ...
    'XLim',[0 10.1], ...
    'YLim',[0.55 2.45], ...
    'YTick',[1 2], ...
    'YTickLabel',{'Role separated','Shared audit'}, ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

xlabel( ...
    axB2, ...
    'Cross-term displacement (pp)', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

text( ...
    axB0, ...
    0.885,0.280, ...
    sprintf('\\downarrow %.1f%%',disp_drop), ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.7, ...
    'FontWeight','bold', ...
    'Color',purple);

%% ========================================================================
% PANEL C
% ROLE SEPARATION CARRIES A FINITE-AUDIT COST
% ========================================================================

axC0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PC);

axis(axC0,[0 1 0 1]);
axis(axC0,'off');
hold(axC0,'on');

local_panel_border( ...
    axC0, ...
    [0.005 0.005 0.99 0.99], ...
    panelOrange, ...
    1.0);

local_panel_header( ...
    axC0, ...
    'C', ...
    'Role separation carries a finite-audit cost', ...
    0.025,0.955, ...
    orange,FONT,FS_LETTER,FS_TITLE);

axC = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',local_relpos(PC,[0.250 0.185 0.720 0.625]));

hold(axC,'on');

for i = 1:3

    plot( ...
        axC, ...
        [0 cost_vals(i)], ...
        [i i], ...
        '-', ...
        'Color',ltgrey, ...
        'LineWidth',1.5);

end

scatter( ...
    axC, ...
    cost_vals(1),1, ...
    72,green, ...
    'filled', ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.6);

scatter( ...
    axC, ...
    cost_vals(2),2, ...
    72,red, ...
    'filled', ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.6);

scatter( ...
    axC, ...
    cost_vals(3),3, ...
    72,orange, ...
    'filled', ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.6);

xline( ...
    axC, ...
    0, ...
    '--', ...
    'Color',[0.45 0.45 0.45], ...
    'LineWidth',0.9);


labelsC = { ...
    'vs same-half direct', ...
    'vs full-budget direct', ...
    'direct split tax'};

for i = 1:3

    if cost_vals(i)>=0
        dx = 2.2;
        ha = 'left';
    else
        dx = -2.2;
        ha = 'right';
    end

    if i==1
        cc = green;
    elseif i==2
        cc = red;
    else
        cc = orange;
    end

    text( ...
        axC, ...
        cost_vals(i)+dx,i, ...
        sprintf('%+.2f%%',cost_vals(i)), ...
        'HorizontalAlignment',ha, ...
        'VerticalAlignment','middle', ...
        'FontName',FONT, ...
        'FontSize',FS_SMALL, ...
        'FontWeight','bold', ...
        'Color',cc);

end

set( ...
    axC, ...
    'YDir','reverse', ...
    'YTick',1:3, ...
    'YTickLabel',labelsC, ...
    'XLim',[-150 150], ...
    'YLim',[0.5 3.5], ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

xlabel( ...
    axC, ...
    'Relative change (%)', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);



%% ========================================================================
% PANEL D
% LOCKED EXTERNAL MECHANISM CHALLENGE
% ========================================================================

axD0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PD);

axis(axD0,[0 1 0 1]);
axis(axD0,'off');
hold(axD0,'on');

local_panel_border( ...
    axD0, ...
    [0.005 0.005 0.99 0.99], ...
    panelPurple, ...
    1.0);

local_panel_header( ...
    axD0, ...
    'D', ...
    'Locked external mechanism challenge', ...
    0.025,0.955, ...
    purple,FONT,FS_LETTER,FS_TITLE);

% Natural-language cohort-level summary rather than a machine verdict.
local_summary_box( ...
    axD0, ...
    [0.700 0.805 0.255 0.135], ...
    purple, ...
    { ...
     sprintf('Georgia: %d/%d checks',georgia_checks,n_checks), ...
     sprintf('CPSC 2018: %d/%d checks',cpsc_checks,n_checks) ...
    }, ...
    FONT, ...
    FS_TINY+0.5);

axD = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',local_relpos(PD,[0.205 0.185 0.720 0.590]));

hold(axD,'on');

y = 8:-1:1;

for i = 1:numel(y)

    plot( ...
        axD, ...
        [x_adapt(i) x_fixed(i)], ...
        [y(i) y(i)], ...
        '-', ...
        'Color',[0.73 0.73 0.73], ...
        'LineWidth',1.3);

end

hFixed = scatter( ...
    axD, ...
    x_fixed,y, ...
    62,'s','filled', ...
    'MarkerFaceColor', ...
        local_mix(green,[1 1 1],0.30), ...
    'MarkerEdgeColor',green, ...
    'LineWidth',0.9);

hAdapt = scatter( ...
    axD, ...
    x_adapt,y, ...
    62,'o','filled', ...
    'MarkerFaceColor',red, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.5);

xline( ...
    axD, ...
    0, ...
    '--', ...
    'Color',[0.45 0.45 0.45], ...
    'LineWidth',0.9);

% Separate the two external cohorts.
plot( ...
    axD, ...
    [-80 60], ...
    [4.5 4.5], ...
    ':', ...
    'Color',[0.72 0.72 0.72], ...
    'LineWidth',0.8);

xAll = [x_fixed(:);x_adapt(:)];

xLo = ...
    min(-70,floor(min(xAll)/10)*10-5);

xHi = ...
    max(55,ceil(max(xAll)/10)*10+5);

set( ...
    axD, ...
    'XLim',[xLo xHi], ...
    'YLim',[0.5 8.5], ...
    'YTick',1:8, ...
    'YTickLabel',fliplr(state_labels), ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

xlabel( ...
    axD, ...
    'MSE gain (%)', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

legend( ...
    axD, ...
    [hFixed hAdapt], ...
    {'Matched fixed-use','Shared adaptive'}, ...
    'Location','southwest', ...
    'Box','off', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY+0.2);


%% ========================================================================
% 6) EXPORT
% ========================================================================

drawnow;

set(fig,'InvertHardcopy','off');

figPath = ...
    fullfile( ...
        outputDir, ...
        'ED2_IntegrityControls_v2.fig');

pngPath = ...
    fullfile( ...
        outputDir, ...
        'ED2_IntegrityControls_v2.png');

pdfPath = ...
    fullfile( ...
        outputDir, ...
        'ED2_IntegrityControls_v2.pdf');

savefig(fig,figPath);

try

    exportgraphics( ...
        fig, ...
        pngPath, ...
        'Resolution',600, ...
        'BackgroundColor','white');

    exportgraphics( ...
        fig, ...
        pdfPath, ...
        'ContentType','vector', ...
        'BackgroundColor','white');

catch ME

    warning( ...
        'exportgraphics failed: %s. Falling back to screen-matched print.', ...
        ME.message);

    oldUnits = ...
        get(fig,'Units');

    set(fig,'Units','inches');

    posIn = ...
        get(fig,'Position');

    set(fig,'Units',oldUnits);

    set(fig,'PaperUnits','inches');

    set( ...
        fig, ...
        'PaperSize',[posIn(3) posIn(4)]);

    set( ...
        fig, ...
        'PaperPosition',[0 0 posIn(3) posIn(4)]);

    set(fig,'PaperPositionMode','manual');

    print( ...
        fig, ...
        pngPath, ...
        '-dpng', ...
        '-r600');

    print( ...
        fig, ...
        pdfPath, ...
        '-dpdf', ...
        '-painters');

end

fprintf('\n============================================================\n');
fprintf(' ED2 MECHANISM AUDIT\n');
fprintf('============================================================\n');

fprintf('Weight-error coupling      : %.3f -> %.3f\n', ...
    corr_shared,corr_sep);

fprintf('Cross-term displacement    : %.2f -> %.2f pp\n', ...
    disp_shared,disp_sep);

fprintf('Georgia mechanism checks   : %d/%d\n', ...
    georgia_checks,n_checks);

fprintf('CPSC 2018 mechanism checks : %d/%d\n', ...
    cpsc_checks,n_checks);

fprintf('Frozen verdict             : %s\n', ...
    gateText);

fprintf('\nSaved:\n');
fprintf('%s\n',figPath);
fprintf('%s\n',pngPath);
fprintf('%s\n',pdfPath);

end


%% =========================================================================
% HELPERS
% =========================================================================

function local_panel_border(ax,pos,color,lineWidth)

rectangle( ...
    ax, ...
    'Position',pos, ...
    'FaceColor','none', ...
    'EdgeColor',color, ...
    'LineWidth',lineWidth);

end


function local_panel_header( ...
    ax,letter,titleText,x,y,color,fontName,fsLetter,fsTitle)

text( ...
    ax,x,y,letter, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsLetter, ...
    'FontWeight','bold', ...
    'Color',color);

text( ...
    ax,x+0.072,y,titleText, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsTitle, ...
    'FontWeight','bold', ...
    'Color',color);

end


function local_box( ...
    ax,pos,lines,color,fontName,fontSize)

rectangle( ...
    ax, ...
    'Position',pos, ...
    'FaceColor','w', ...
    'EdgeColor',color, ...
    'LineWidth',0.95);

text( ...
    ax, ...
    pos(1)+pos(3)/2, ...
    pos(2)+pos(4)/2, ...
    lines, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'Color',color);

end


function local_arrow_axes( ...
    ax,xv,yv,color)

annotation( ...
    ancestor(ax,'figure'), ...
    'arrow', ...
    ax.Position(1)+xv*ax.Position(3), ...
    ax.Position(2)+yv*ax.Position(4), ...
    'Color',color, ...
    'LineWidth',1.0, ...
    'HeadLength',6, ...
    'HeadWidth',6);

end


function local_summary_box( ...
    ax,pos,color,lines,fontName,fontSize)

rectangle( ...
    ax, ...
    'Position',pos, ...
    'FaceColor','w', ...
    'EdgeColor',color, ...
    'LineWidth',0.9);

text( ...
    ax, ...
    pos(1)+pos(3)/2, ...
    pos(2)+pos(4)/2, ...
    lines, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'Color',color);

end


function pos = local_relpos(panelPos,rel)

pos = [ ...
    panelPos(1)+rel(1)*panelPos(3), ...
    panelPos(2)+rel(2)*panelPos(4), ...
    rel(3)*panelPos(3), ...
    rel(4)*panelPos(4)];

end


function c = local_mix(c1,c2,alpha)

c = ...
    (1-alpha).*c1 + ...
    alpha.*c2;

end


function repoRoot = local_find_cmdo_repo(scriptDir)

repoRoot = '';

starts = {scriptDir,pwd};

for s = 1:numel(starts)

    p = starts{s};

    for k = 1:8

        if isempty(p)
            break;
        end

        if isfolder(fullfile(p,'U10_Prospective_ECG'))

            repoRoot = p;
            return;

        end

        parent = fileparts(p);

        if strcmp(parent,p)
            break;
        end

        p = parent;

    end

end

home = ...
    strtrim(getenv('USERPROFILE'));

if isempty(home)
    home = strtrim(getenv('HOME'));
end

if ~isempty(home)

    candidates = { ...
        fullfile(home,'CMDO-Reproducibility'), ...
        fullfile(home,'Documents','CMDO-Reproducibility'), ...
        fullfile(home,'Desktop','CMDO-Reproducibility')};

    for i = 1:numel(candidates)

        if isfolder( ...
                fullfile( ...
                    candidates{i}, ...
                    'U10_Prospective_ECG'))

            repoRoot = candidates{i};
            return;

        end

    end

end

end