function ED3
%ED3 Pair-complete candidate audit and frozen selection.
%
% Panel b contains all seven pair-complete candidate methods.
% Its textboxes can be dragged and their positions saved.

close all;
clc;
rng(20260728,'twister');

cfg = cmdo_config('ED3');
DATA_DIR  = cfg.canonicalRecordDir;
CACHE_DIR = fullfile(cfg.cacheRoot,'ED_CURRENT_FINAL');
OUT_DIR   = cfg.extendedOutputDir;

if ~exist(DATA_DIR,'dir')
    error( ...
        'ED3:MissingData', ...
        'Canonical record folder not found: %s', ...
        DATA_DIR);
end

if ~exist(CACHE_DIR,'dir')
    mkdir(CACHE_DIR);
end

if ~exist(OUT_DIR,'dir')
    mkdir(OUT_DIR);
end

U5E = ed_load_u5e(DATA_DIR,CACHE_DIR);
U5F = ed_load_u5f(DATA_DIR,CACHE_DIR);

ed_make_3(U5E,U5F,OUT_DIR);

fprintf( ...
    '\nED3 completed. Output folder:\n%s\n', ...
    OUT_DIR);

end


function ed_make_3(U5E,U5F,outDir)

summary = U5F.audit;
state   = U5E.state;

%% All seven pair-complete candidates
methodCodes = [ ...
    "PC_DELONG"; ...
    "PC_DELONG_VARGATE"; ...
    "PC_ORACLE"; ...
    "PC_PAIRED_HOEFFDING"; ...
    "PC_PLUGIN"; ...
    "PC_PLUGIN_VARGATE"; ...
    "PC_USTAT_MCDIARMID"];

methodLabels = { ...
    'DeLong'; ...
    'DeLong + gate'; ...
    'Oracle'; ...
    'Paired Hoeffding'; ...
    'Plug-in'; ...
    'Plug-in + gate'; ...
    'U-stat McDiarmid'};

%% Figure and fixed panel geometry
fig = figure( ...
    'Position',[35 25 900 1000], ...
    'Color','w', ...
    'Name','Extended Data Figure 3', ...
    'NumberTitle','off', ...
    'Renderer','painters');

% Fixed positions prevent legends and annotations from changing alignment.
axA = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.080+0.03 0.645 0.365 0.285]);

axB = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.570+0.03 0.645 0.365 0.285]);

axC = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.080+0.03 0.340 0.365 0.225]);

axD = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.570+0.03 0.340 0.365 0.225]);

axE = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.080+0.03 0.095 0.855 0.155]);

%% ========================================================================
% a — eligibility gates
% ========================================================================
ax = axA;
hold(ax,'on');

M = false(numel(methodCodes),5);

for i = 1:numel(methodCodes)

    r = summary( ...
        string(summary.method)==methodCodes(i),:);

    if isempty(r)
        continue;
    end

    M(i,1) = ...
        isfinite(r.minimum_simultaneous_coverage) && ...
        r.minimum_simultaneous_coverage >= 0.98;

    M(i,2) = ...
        isfinite(r.minimum_block_no_harm_rate) && ...
        r.minimum_block_no_harm_rate >= 1-1e-12;

    M(i,3) = ...
        isfinite(r.maximum_identity_residual) && ...
        abs(r.maximum_identity_residual) <= 1e-12;

    M(i,4) = ...
        isfinite(r.minimum_target_gain) && ...
        r.minimum_target_gain >= -1e-12;

    M(i,5) = ed_to_logical(r.eligible);
end

imagesc(ax,M);

colormap(ax,[ ...
    0.18 0.36 0.58; ...
    0.65 0.00 0.18]);

caxis(ax,[0 1]);

xticks(ax,1:5);
xticklabels(ax,{ ...
    'Coverage', ...
    'No harm', ...
    'Identity', ...
    'All targets', ...
    'Eligibility'});

xtickangle(ax,25);

yticks(ax,1:numel(methodLabels));
yticklabels(ax,methodLabels);

for i = 1:size(M,1)
    for j = 1:size(M,2)

        if M(i,j)
            symbol = char(10003);
            textColor = [1 1 1];
        else
            symbol = char(215);
            textColor = [0.10 0.10 0.10];
        end

        text( ...
            ax, ...
            j, ...
            i, ...
            symbol, ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontSize',13, ...
            'FontWeight','bold', ...
            'Color',textColor);
    end
end

title( ...
    ax, ...
    'Prespecified eligibility gates', ...
    'FontWeight','bold');

ed_style(ax,8.5);
ed_panel_letter(fig,ax,'a');

%% ========================================================================
% b — complete seven-candidate frontier with draggable textboxes
% ========================================================================
ax = axB;
hold(ax,'on');

panelBMethodCodes = methodCodes;
panelBLabels      = string(methodLabels);
panelBColors      = lines(numel(panelBMethodCodes));

xB = nan(numel(panelBMethodCodes),1);
yB = nan(numel(panelBMethodCodes),1);
sizeB = nan(numel(panelBMethodCodes),1);
strictB = false(numel(panelBMethodCodes),1);

pointHandlesB = gobjects(numel(panelBMethodCodes),1);

for i = 1:numel(panelBMethodCodes)

    r = summary( ...
        string(summary.method)==panelBMethodCodes(i),:);

    if isempty(r)
        error( ...
            'ED3:MissingMethod', ...
            'Panel-b method missing from canonical audit: %s', ...
            panelBMethodCodes(i));
    end

    xB(i) = 100 * double(r.worst_target_budget_regret);
    yB(i) = 100 * double(r.pooled_gain);

    sizeB(i) = ...
        65 + 650 * max(double(r.mean_weight),0);

    strictB(i) = ed_to_logical(r.strict_candidate);

    if panelBMethodCodes(i) == "PC_ORACLE"
        markerB = 'p';

    elseif strictB(i)
        markerB = 'd';

    elseif contains(panelBMethodCodes(i),"PLUGIN")
        markerB = 's';

    else
        markerB = 'o';
    end

    pointHandlesB(i) = scatter( ...
        ax, ...
        xB(i), ...
        yB(i), ...
        sizeB(i), ...
        panelBColors(i,:), ...
        markerB, ...
        'filled', ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.75);
end

% Prespecified regret gate.
xline( ...
    ax, ...
    0.5, ...
    '--', ...
    'Color',[0.12 0.47 0.71], ...
    'LineWidth',1.25, ...
    'HandleVisibility','off');

xlabel(ax,'Worst target-budget regret (%)');
ylabel(ax,'Pooled gain versus full direct (%)');

title( ...
    ax, ...
    'Efficiency-tail-safety frontier', ...
    'FontWeight','bold');

xUpper = max([0.60; 1.13*xB]);
yUpper = max([9.50; 1.08*yB]);

xlim(ax,[0 xUpper]);
ylim(ax,[0 yUpper]);

text( ...
    ax, ...
    0.5, ...
    0.985*yUpper, ...
    'regret gate', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',8, ...
    'Color',[0.15 0.15 0.15]);

grid(ax,'on');
ed_style(ax,8.5);
ed_panel_letter(fig,ax,'b');

%% Panel-b draggable label positions
panelBPositionFile = fullfile( ...
    outDir, ...
    'ExtendedData3_panelB_label_positions.mat');

defaultLabelPosB = [ ...
    0.410 4.62; ...   % DeLong
    0.490 0.95; ...   % DeLong + gate
    0.105 8.95; ...   % Oracle
    0.120 2.55; ...   % Paired Hoeffding
    0.455 8.10; ...   % Plug-in
    0.360 1.68; ...   % Plug-in + gate
    0.100 1.88];      % U-stat McDiarmid

% Keep defaults within the current axes.
defaultLabelPosB(:,1) = min( ...
    max(defaultLabelPosB(:,1),0.02*xUpper), ...
    0.96*xUpper);

defaultLabelPosB(:,2) = min( ...
    max(defaultLabelPosB(:,2),0.04*yUpper), ...
    0.96*yUpper);

labelPosB = defaultLabelPosB;

if exist(panelBPositionFile,'file')

    savedB = load(panelBPositionFile);

    validPositionMatrix = ...
        isfield(savedB,'labelPosB') && ...
        isequal(size(savedB.labelPosB), ...
        size(defaultLabelPosB));

    validMethodOrder = true;

    if isfield(savedB,'panelBMethodCodes')
        validMethodOrder = isequal( ...
            string(savedB.panelBMethodCodes(:)), ...
            panelBMethodCodes(:));
    end

    if validPositionMatrix && validMethodOrder
        labelPosB = savedB.labelPosB;
    end
end

labelHandlesB  = gobjects(numel(panelBMethodCodes),1);
leaderHandlesB = gobjects(numel(panelBMethodCodes),1);

for i = 1:numel(panelBMethodCodes)

    leaderHandlesB(i) = plot( ...
        ax, ...
        [xB(i),labelPosB(i,1)], ...
        [yB(i),labelPosB(i,2)], ...
        '-', ...
        'Color',[0.32 0.32 0.32], ...
        'LineWidth',0.65, ...
        'HandleVisibility','off', ...
        'HitTest','off', ...
        'PickableParts','none');

    labelHandlesB(i) = text( ...
        ax, ...
        labelPosB(i,1), ...
        labelPosB(i,2), ...
        panelBLabels(i), ...
        'FontName','Arial', ...
        'FontSize',7.8, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'BackgroundColor','w', ...
        'EdgeColor',[0.72 0.72 0.72], ...
        'LineWidth',0.45, ...
        'Margin',1.5, ...
        'Clipping','off', ...
        'PickableParts','all', ...
        'HitTest','on');

    setappdata( ...
        labelHandlesB(i), ...
        'AnchorPoint', ...
        [xB(i),yB(i)]);

    setappdata( ...
        labelHandlesB(i), ...
        'LeaderHandle', ...
        leaderHandlesB(i));

    labelHandlesB(i).ButtonDownFcn = ...
        @(src,~) ed_start_label_drag(src,fig);
end

%% ========================================================================
% c — state-level regret distributions
% ========================================================================
ax = axC;
hold(ax,'on');

distCodes = [ ...
    "PC_DELONG", ...
    "PC_PAIRED_HOEFFDING", ...
    "PC_USTAT_MCDIARMID"];

distLabels = { ...
    'DeLong', ...
    'Paired Hoeffding', ...
    'U-stat McDiarmid'};

budgetOrder  = sort(unique(state.budget));
budgetColors = lines(numel(budgetOrder));
budgetMarkers = {'o','s','^','d','p'};

budgetLegendHandles = gobjects(numel(budgetOrder),1);

for i = 1:3

    mMethod = ...
        string(state.method)==distCodes(i);

    v = double( ...
        state.mae_regret_vs_full_direct(mMethod));

    v = v(isfinite(v));

    ed_violin( ...
        ax, ...
        i, ...
        v, ...
        [0.72 0.82 0.95], ...
        0.34, ...
        0.30);

    for j = 1:numel(budgetOrder)

        m = ...
            mMethod & ...
            state.budget==budgetOrder(j);

        vv = double( ...
            state.mae_regret_vs_full_direct(m));

        vv = vv(isfinite(vv));

        scatter( ...
            ax, ...
            i + 0.05*randn(size(vv)), ...
            vv, ...
            18, ...
            budgetColors(j,:), ...
            budgetMarkers{j}, ...
            'filled', ...
            'MarkerEdgeColor','none');

        if i == 1
            budgetLegendHandles(j) = scatter( ...
                ax, ...
                NaN,NaN, ...
                24, ...
                budgetColors(j,:), ...
                budgetMarkers{j}, ...
                'filled', ...
                'MarkerEdgeColor','none');
        end
    end

    med = median(v,'omitnan');

    plot( ...
        ax, ...
        [i-0.20 i+0.20], ...
        [med med], ...
        'Color',[0.12 0.47 0.71], ...
        'LineWidth',1.8);
end

yline( ...
    ax, ...
    0, ...
    '--', ...
    'Color',[0.12 0.47 0.71], ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xticks(ax,1:3);
xticklabels(ax,distLabels);
xtickangle(ax,15);

ylabel(ax,'State-level MAE regret versus full direct');

title( ...
    ax, ...
    'State-level regret distributions', ...
    'FontWeight','bold');

legend( ...
    ax, ...
    budgetLegendHandles, ...
    cellstr(string(budgetOrder)), ...
    'Location','southwest', ...
    'NumColumns',2, ...
    'Box','off', ...
    'FontSize',6.7);

grid(ax,'on');
ed_style(ax,8.5);
ed_panel_letter(fig,ax,'c');

%% ========================================================================
% d — simultaneous coverage by budget
% ========================================================================
ax = axD;
hold(ax,'on');

% Clear, publication-friendly method colours.
covColors = [ ...
    0.0000 0.4470 0.7410; ...   % DeLong: blue
    0.8500 0.3250 0.0980; ...   % Paired Hoeffding: red-orange
    0.2000 0.6300 0.2500];      % U-stat McDiarmid: green

% Small horizontal offsets are visual only.
% They prevent identical coverage trajectories from covering one another.
methodOffset = [-1.25, 0, 1.25];
meanOffset   = -0.22;
minOffset    =  0.22;

coverageHandles = gobjects(6,1);
coverageLabels  = strings(6,1);

handleIndex = 0;

for i = 1:3

    means = nan(size(budgetOrder));
    mins  = nan(size(budgetOrder));

    for j = 1:numel(budgetOrder)

        m = ...
            string(state.method)==distCodes(i) & ...
            state.budget==budgetOrder(j);

        v = double(state.simultaneous_coverage(m));
        v = v(isfinite(v));

        means(j) = mean(v,'omitnan');
        mins(j)  = min(v,[],'omitnan');
    end

    % Separate mean and minimum slightly on the x axis.
    xMean = budgetOrder + methodOffset(i) + meanOffset;
    xMin  = budgetOrder + methodOffset(i) + minOffset;

    handleIndex = handleIndex + 1;

    coverageHandles(handleIndex) = plot( ...
        ax, ...
        xMean, ...
        means, ...
        '-', ...
        'Color',covColors(i,:), ...
        'LineWidth',1.65, ...
        'Marker','o', ...
        'MarkerSize',5.5, ...
        'MarkerFaceColor','w', ...
        'MarkerEdgeColor',covColors(i,:));

    coverageLabels(handleIndex) = ...
        string(distLabels{i}) + ": mean";

    handleIndex = handleIndex + 1;

    coverageHandles(handleIndex) = plot( ...
        ax, ...
        xMin, ...
        mins, ...
        '--', ...
        'Color',covColors(i,:), ...
        'LineWidth',1.45, ...
        'Marker','x', ...
        'MarkerSize',6.0, ...
        'MarkerEdgeColor',covColors(i,:));

    coverageLabels(handleIndex) = ...
        string(distLabels{i}) + ": minimum";
end

% Prespecified minimum-coverage gate.
yline( ...
    ax, ...
    0.98, ...
    ':', ...
    'Color',[0.25 0.25 0.25], ...
    'LineWidth',1.15, ...
    'HandleVisibility','off');

text( ...
    ax, ...
    max(budgetOrder), ...
    0.974, ...
    'minimum coverage gate', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'Color',[0.25 0.25 0.25], ...
    'FontSize',7.5);

xlabel(ax,'Outcome budget');
ylabel(ax,'Simultaneous coverage');

title( ...
    ax, ...
    'Simultaneous coverage by budget', ...
    'FontWeight','bold');

xticks(ax,budgetOrder);
xlim(ax,[0 140]);

% Add space above 1.000 so coincident lines are not hidden by the top border.
ylim(ax,[0.20 1.025]);

legend( ...
    ax, ...
    coverageHandles, ...
    cellstr(coverageLabels), ...
    'Location','southwest', ...
    'NumColumns',1, ...
    'Box','off', ...
    'FontSize',6.5);

grid(ax,'on');
ed_style(ax,8.5);
ed_panel_letter(fig,ax,'d');

%% ========================================================================
% e — borrowing and fallback behaviour
% ========================================================================
ax = axE;
hold(ax,'on');

W = nan(numel(methodCodes),2);

for i = 1:numel(methodCodes)

    r = summary( ...
        string(summary.method)==methodCodes(i),:);

    if isempty(r)
        continue;
    end

    W(i,:) = [ ...
        double(r.mean_weight), ...
        double(r.fallback_rate)];
end

barE = bar(ax,W,'grouped');

barE(1).FaceColor = [0.00 0.4470 0.7410];
barE(2).FaceColor = [0.8500 0.3250 0.0980];

xticks(ax,1:numel(methodLabels));
xticklabels(ax,methodLabels);
xtickangle(ax,20);

ylabel(ax,'Fraction');

title( ...
    ax, ...
    'Borrowing and fallback behaviour', ...
    'FontWeight','bold');

legend( ...
    ax, ...
    {'Mean transport weight','Fallback rate'}, ...
    'Location','north', ...
    'NumColumns',2, ...
    'Box','off');

ylim(ax,[0 1]);

grid(ax,'on');
ed_style(ax,8.5);
ed_panel_letter(fig,ax,'e');

%% ========================================================================
% Canonical audit printed to command window
% ========================================================================
fprintf('\nED3 canonical audit:\n');
fprintf('  U5F audit rows: %d\n',height(summary));
fprintf('  Panel-b pair-complete candidates: %d\n',numel(panelBMethodCodes));
fprintf('  Panel-b methods:\n');

for i = 1:numel(panelBMethodCodes)
    fprintf( ...
        '    %-24s regret=%8.4f%% gain=%8.4f%%\n', ...
        panelBMethodCodes(i), ...
        xB(i), ...
        yB(i));
end

fprintf( ...
    ['  Reference/full rows intentionally excluded from panel b: ' ...
     'DIRECT_FULL, ORACLE_FULL, PLUGIN_FULL\n']);

%% ========================================================================
% Manual label adjustment and final export
% ========================================================================
drawnow;

if usejava('desktop')

    instructionBox = annotation( ...
        fig, ...
        'textbox', ...
        [0.260 0.010 0.455 0.032], ...
        'String', ...
        ['Drag the seven panel-b textboxes, then click ' ...
         '"Save panel b labels & figure"'], ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontName','Arial', ...
        'FontSize',9, ...
        'FontWeight','bold', ...
        'BackgroundColor',[1.00 1.00 0.88], ...
        'EdgeColor',[0.65 0.65 0.45], ...
        'FitBoxToText','off');

    finishButton = uicontrol( ...
        fig, ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[0.735 0.010 0.205 0.034], ...
        'String','Save panel b labels & figure', ...
        'FontSize',9.2, ...
        'FontWeight','bold', ...
        'Callback',@(~,~) uiresume(fig));

    uiwait(fig);

    if ~isgraphics(fig)
        return;
    end

    labelPosB = nan(numel(labelHandlesB),2);

    for i = 1:numel(labelHandlesB)

        p = labelHandlesB(i).Position;
        labelPosB(i,:) = p(1:2);
    end

    save( ...
        panelBPositionFile, ...
        'labelPosB', ...
        'panelBMethodCodes', ...
        'panelBLabels');

    if isgraphics(finishButton)
        delete(finishButton);
    end

    if isgraphics(instructionBox)
        delete(instructionBox);
    end
end

drawnow;

ed_save( ...
    fig, ...
    outDir, ...
    'ExtendedData3_Pair_Complete_Candidate_Audit');

fprintf( ...
    '\nPanel-b label positions saved to:\n%s\n', ...
    panelBPositionFile);

end


%% ========================================================================
% Loaders
% ========================================================================
function U5E = ed_load_u5e(dataDir,cacheDir)

d = ed_extract( ...
    dataDir, ...
    cacheDir, ...
    'StageU5E_Canonical_Records_v1.0.zip');

U5E.summary = ed_read( ...
    d, ...
    'StageU5E_Method_Summary_v1.0.csv');

U5E.state = ed_read( ...
    d, ...
    'StageU5E_Pair_Complete_State_Results_v1.0.csv');

end


function U5F = ed_load_u5f(dataDir,cacheDir)

d = ed_extract( ...
    dataDir, ...
    cacheDir, ...
    'StageU5F_Canonical_Records_v1.0.zip');

U5F.audit = ed_read( ...
    d, ...
    'StageU5F_Candidate_Selection_Audit_v1.0.csv');

end


function stageDir = ed_extract(dataDir,cacheDir,zipName)

zipPath = fullfile(dataDir,zipName);

if ~exist(zipPath,'file')
    error( ...
        'ED:MissingZip', ...
        'Missing canonical archive: %s', ...
        zipPath);
end

stageDir = fullfile( ...
    cacheDir, ...
    erase(zipName,'.zip'));

readyFile = fullfile(stageDir,'.ready');

if ~exist(readyFile,'file')

    if exist(stageDir,'dir')
        rmdir(stageDir,'s');
    end

    mkdir(stageDir);
    unzip(zipPath,stageDir);

    fid = fopen(readyFile,'w');

    if fid > 0
        fprintf(fid,'ready\n');
        fclose(fid);
    end
end

end


function T = ed_read(stageDir,fileName)

hits = dir(fullfile(stageDir,'**',fileName));

if isempty(hits)
    error( ...
        'ED:MissingCSV', ...
        'CSV not found after extraction: %s', ...
        fileName);
end

T = readtable( ...
    fullfile(hits(1).folder,hits(1).name), ...
    'VariableNamingRule','preserve');

end


%% ========================================================================
% Export and plotting helpers
% ========================================================================
function ed_save(fig,outDir,stem)

drawnow;

exportgraphics( ...
    fig, ...
    fullfile(outDir,[stem '.png']), ...
    'Resolution',300, ...
    'BackgroundColor','white');

exportgraphics( ...
    fig, ...
    fullfile(outDir,[stem '.tiff']), ...
    'Resolution',300, ...
    'BackgroundColor','white');

exportgraphics( ...
    fig, ...
    fullfile(outDir,[stem '.pdf']), ...
    'ContentType','vector', ...
    'BackgroundColor','white');

savefig( ...
    fig, ...
    fullfile(outDir,[stem '.fig']));

fprintf('Saved: %s\n',stem);

end


function ed_style(ax,fontSize)

set( ...
    ax, ...
    'FontName','Arial', ...
    'FontSize',fontSize, ...
    'LineWidth',0.85, ...
    'TickDir','out', ...
    'Box','off', ...
    'Layer','top');

end


function ed_panel_letter(fig,ax,s)
% Place panel letter outside the axes.

drawnow;
pos = ax.Position;

x = max(0.008,pos(1)-0.032);
y = min(0.972,pos(2)+pos(4)+0.006);

annotation( ...
    fig, ...
    'textbox', ...
    [x y 0.025 0.025], ...
    'String',s, ...
    'LineStyle','none', ...
    'FitBoxToText','off', ...
    'FontName','Arial', ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle');

end


function ed_violin(ax,x0,v,faceColor,halfWidth,faceAlpha)

v = double(v(:));
v = v(isfinite(v));

if numel(v) < 2
    return;
end

vMin = min(v);
vMax = max(v);

if vMax <= vMin
    vMin = vMin-1e-6;
    vMax = vMax+1e-6;
end

yGrid = linspace(vMin,vMax,180)';

sigmaValue = std(v,0);

bandwidth = ...
    1.06 * sigmaValue * numel(v)^(-1/5);

if ~isfinite(bandwidth) || bandwidth <= 0
    bandwidth = max((vMax-vMin)/20,eps);
end

z = bsxfun(@minus,yGrid,v') / bandwidth;

density = ...
    mean(exp(-0.5*z.^2),2) / ...
    (bandwidth*sqrt(2*pi));

if max(density) <= 0 || ~all(isfinite(density))
    density = ones(size(density));
end

width = ...
    halfWidth * density / max(density);

patch( ...
    ax, ...
    [x0-width;flipud(x0+width)], ...
    [yGrid;flipud(yGrid)], ...
    faceColor, ...
    'FaceAlpha',faceAlpha, ...
    'EdgeColor',[0.45 0.45 0.45], ...
    'LineWidth',0.6, ...
    'HandleVisibility','off');

end


function tf = ed_to_logical(value)
% Convert table cell/string/numeric/logical values into one logical scalar.

if isempty(value)
    tf = false;
    return;
end

while iscell(value)

    if isempty(value)
        tf = false;
        return;
    end

    value = value{1};
end

if islogical(value)

    tf = any(value(:));

elseif isnumeric(value)

    numericValue = double(value(:));

    tf = any( ...
        isfinite(numericValue) & ...
        numericValue ~= 0);

else

    textValue = lower(strtrim(string(value)));

    trueValues = [ ...
        "true", ...
        "1", ...
        "yes", ...
        "y", ...
        "pass", ...
        "passed", ...
        "eligible"];

    tf = any(ismember(textValue,trueValues));
end

tf = logical(tf);

end


%% ========================================================================
% Draggable panel-b textbox helpers
% ========================================================================
function ed_start_label_drag(labelHandle,figHandle)

if ~isgraphics(labelHandle) || ~isgraphics(figHandle)
    return;
end

set( ...
    figHandle, ...
    'Pointer','fleur', ...
    'WindowButtonMotionFcn', ...
    @(~,~) ed_drag_label(labelHandle), ...
    'WindowButtonUpFcn', ...
    @(~,~) ed_stop_label_drag(figHandle));

end


function ed_drag_label(labelHandle)

if ~isgraphics(labelHandle)
    return;
end

ax = ancestor(labelHandle,'axes');

if isempty(ax) || ~isgraphics(ax)
    return;
end

currentPoint = ax.CurrentPoint;

xValue = currentPoint(1,1);
yValue = currentPoint(1,2);

xLimits = ax.XLim;
yLimits = ax.YLim;

xPadding = 0.025 * diff(xLimits);
yPadding = 0.040 * diff(yLimits);

xValue = min( ...
    max(xValue,xLimits(1)+xPadding), ...
    xLimits(2)-xPadding);

yValue = min( ...
    max(yValue,yLimits(1)+yPadding), ...
    yLimits(2)-yPadding);

labelHandle.Position = [xValue yValue 0];

anchorPoint = getappdata( ...
    labelHandle, ...
    'AnchorPoint');

leaderHandle = getappdata( ...
    labelHandle, ...
    'LeaderHandle');

if isgraphics(leaderHandle)

    leaderHandle.XData = [anchorPoint(1),xValue];
    leaderHandle.YData = [anchorPoint(2),yValue];
end

drawnow limitrate nocallbacks;

end


function ed_stop_label_drag(figHandle)

if ~isgraphics(figHandle)
    return;
end

set( ...
    figHandle, ...
    'Pointer','arrow', ...
    'WindowButtonMotionFcn','', ...
    'WindowButtonUpFcn','');

end
