function ED4
%ED4 Complete U6 independent-reserve detail.
%
% Canonical content:
%   a  State-level gain for all 16 targets and 5 outcome budgets
%   b  Frozen-observer transport weight for all 80 states
%   c  Median and 10–90% gain trajectory across targets
%   d  Minimum coverage, plug-in risk geometry and exact fallback integrity
%
% Reads the frozen StageU6 canonical records directly.

close all;
clc;
rng(20260728,'twister');

cfg = cmdo_config('ED4');
DATA_DIR  = cfg.canonicalRecordDir;
CACHE_DIR = fullfile(cfg.cacheRoot,'ED_CURRENT_FINAL');
OUT_DIR   = cfg.extendedOutputDir;

if ~exist(DATA_DIR,'dir')
    error( ...
        'ED4:MissingData', ...
        'Canonical record folder not found: %s', ...
        DATA_DIR);
end

if ~exist(CACHE_DIR,'dir')
    mkdir(CACHE_DIR);
end

if ~exist(OUT_DIR,'dir')
    mkdir(OUT_DIR);
end

U6 = ed_load_u6(DATA_DIR,CACHE_DIR);

ed_make_4(U6,OUT_DIR);

fprintf( ...
    '\nED4 completed. Output folder:\n%s\n', ...
    OUT_DIR);

end


function ed_make_4(U6,outDir)

S = U6.state;
T = U6.target;

%% ========================================================================
% Canonical structure and validation
% ========================================================================
familyOrder = [ ...
    "ACS_PUBLIC_COVERAGE_2024"; ...
    "MEDICAL_DERMOSCOPY"; ...
    "NATURAL_IMAGE"];

expectedBudgets = [8;16;32;64;128];

budgets = sort(unique(double(S.budget(:))));

if height(T) ~= 16
    error( ...
        'ED4:TargetCount', ...
        'Expected 16 U6 targets, found %d.', ...
        height(T));
end

if numel(unique(string(T.family))) ~= 3
    error( ...
        'ED4:FamilyCount', ...
        'Expected 3 U6 families.');
end

if ~isequal(budgets(:),expectedBudgets)
    error( ...
        'ED4:BudgetSet', ...
        'Expected budgets [8 16 32 64 128].');
end

if height(S) ~= height(T)*numel(budgets)
    error( ...
        'ED4:StateCount', ...
        ['Expected %d target-budget states, ' ...
         'found %d.'], ...
        height(T)*numel(budgets), ...
        height(S));
end

%% ========================================================================
% Target ordering
% Group by family, then order targets by target-level gain.
% ========================================================================
targetOrder = strings(0,1);

for f = 1:numel(familyOrder)

    Tf = T( ...
        string(T.family)==familyOrder(f),:);

    if isempty(Tf)
        error( ...
            'ED4:MissingFamily', ...
            'Missing U6 family: %s', ...
            familyOrder(f));
    end

    [~,orderWithinFamily] = sort( ...
        double(Tf.gain_vs_full_direct), ...
        'descend');

    targetOrder = [ ...
        targetOrder; ...
        string(Tf.target(orderWithinFamily))]; %#ok<AGROW>
end

if numel(targetOrder) ~= 16 || ...
        numel(unique(targetOrder)) ~= 16

    error( ...
        'ED4:TargetRoster', ...
        'The ordered target roster is incomplete or duplicated.');
end

%% ========================================================================
% Build the complete 16 × 5 state matrices
% ========================================================================
nTargets = numel(targetOrder);
nBudgets = numel(budgets);

gainMatrix   = nan(nTargets,nBudgets);
weightMatrix = nan(nTargets,nBudgets);

for i = 1:nTargets

    for j = 1:nBudgets

        m = ...
            string(S.target)==targetOrder(i) & ...
            double(S.budget)==budgets(j);

        if nnz(m) ~= 1
            error( ...
                'ED4:StateMultiplicity', ...
                ['Expected exactly one state for target %s ' ...
                 'at budget %d; found %d.'], ...
                targetOrder(i), ...
                budgets(j), ...
                nnz(m));
        end

        gainMatrix(i,j) = ...
            double(S.direct_mae(m)) ...
            - double(S.mae(m));

        weightMatrix(i,j) = ...
            double(S.mean_weight(m));
    end
end

shortNames = arrayfun( ...
    @ed_short_u6, ...
    targetOrder, ...
    'UniformOutput',false);

allStateGain = ...
    double(S.direct_mae) ...
    - double(S.mae);

%% ========================================================================
% Figure canvas with fixed geometry
% Fixed positions prevent colorbars and legends from changing alignment.
% ========================================================================
fig = figure( ...
    'Position',[40 40 900 800], ...
    'Color','w', ...
    'Name','Extended Data Figure 4', ...
    'NumberTitle','off', ...
    'Renderer','painters');

% 两张 heatmap 都保留完整 y-axis labels。
% 中间留出足够空间，避免 panel b 标签压到 panel a。
axA = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.115 0.575 0.235 0.335]);

axB = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.610 0.575 0.235 0.335]);

axC = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.115 0.105 0.300 0.335]);

axD = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.610 0.105 0.300 0.335]);

%% ========================================================================
% a — gain by target and budget
% ========================================================================
ax = axA;

imagesc(ax,gainMatrix);

colormap( ...
    ax, ...
    ed_white_to_color([0.84 0.15 0.16],256));

gainMaximum = max(gainMatrix(:),[],'omitnan');

if ~isfinite(gainMaximum) || gainMaximum <= 0
    gainMaximum = 1;
end

caxis(ax,[0 gainMaximum]);

set(ax,'YDir','reverse');

xticks(ax,1:nBudgets);
xticklabels(ax,string(budgets));

yticks(ax,1:nTargets);
yticklabels(ax,shortNames);

xlabel(ax,'Outcome budget');

title( ...
    ax, ...
    'Gain by target and budget', ...
    'FontWeight','bold', ...
    'FontSize',11.5);

% Family separators:
% ACS targets 1–5, Derma targets 6–11, CIFAR targets 12–16.
hold(ax,'on');

plot( ...
    ax, ...
    [0.5 nBudgets+0.5], ...
    [5.5 5.5], ...
    'w-', ...
    'LineWidth',1.6, ...
    'HandleVisibility','off');

plot( ...
    ax, ...
    [0.5 nBudgets+0.5], ...
    [11.5 11.5], ...
    'w-', ...
    'LineWidth',1.6, ...
    'HandleVisibility','off');

xlim(ax,[0.5 nBudgets+0.5]);
ylim(ax,[0.5 nTargets+0.5]);

ed_style(ax,8.5);

% Dedicated colour bar.
cbA = colorbar(ax);
cbA.Units = 'normalized';
cbA.Position = [0.360 0.575 0.012 0.335];
cbA.Label.String = 'Direct MAE - observer MAE';
cbA.Label.FontName = 'Arial';
cbA.Label.FontSize = 8.5;

% Restore axes after colour-bar creation.
ax.Position = [0.115 0.575 0.235 0.335];

ed_panel_letter(fig,ax,'a');
ax.YAxis.FontSize = 8.2;

%% ========================================================================
% b — transport weight by state
% ========================================================================
ax = axB;

imagesc(ax,weightMatrix);

colormap( ...
    ax, ...
    ed_white_to_color([0.12 0.47 0.71],256));

weightMaximum = max(weightMatrix(:),[],'omitnan');

if ~isfinite(weightMaximum) || weightMaximum <= 0
    weightMaximum = 1;
end

caxis(ax,[0 weightMaximum]);

set(ax,'YDir','reverse');

xticks(ax,1:nBudgets);
xticklabels(ax,string(budgets));

% Panel b uses exactly the same row order as panel a.
% Repeating all 16 labels would waste space and overlap panel a.
yticks(ax,1:nTargets);
yticklabels(ax,shortNames);
ax.YAxis.FontSize = 7.8;

% ylabel(ax,'Same target order as panel a', ...
%     'FontSize',8, ...
%     'Color',[0.35 0.35 0.35]);

xlabel(ax,'Outcome budget');

title( ...
    ax, ...
    'Transport weight by state', ...
    'FontWeight','bold', ...
    'FontSize',11.5);

hold(ax,'on');

plot( ...
    ax, ...
    [0.5 nBudgets+0.5], ...
    [5.5 5.5], ...
    'w-', ...
    'LineWidth',1.6, ...
    'HandleVisibility','off');

plot( ...
    ax, ...
    [0.5 nBudgets+0.5], ...
    [11.5 11.5], ...
    'w-', ...
    'LineWidth',1.6, ...
    'HandleVisibility','off');

xlim(ax,[0.5 nBudgets+0.5]);
ylim(ax,[0.5 nTargets+0.5]);

ed_style(ax,8.5);

cbB = colorbar(ax);
cbB.Units = 'normalized';
cbB.Position = [0.855 0.575 0.012 0.335];
cbB.Label.String = 'Mean transport weight';
cbB.Label.FontName = 'Arial';
cbB.Label.FontSize = 8.5;

ax.Position = [0.610 0.575 0.235 0.335];

ed_panel_letter(fig,ax,'b');

%% ========================================================================
% c — gain trajectory across budgets
% ========================================================================
ax = axC;
hold(ax,'on');

medianGain = nan(nBudgets,1);
gainQ10    = nan(nBudgets,1);
gainQ90    = nan(nBudgets,1);

for j = 1:nBudgets

    stateGainAtBudget = ...
        double(S.direct_mae(S.budget==budgets(j))) ...
        - double(S.mae(S.budget==budgets(j)));

    medianGain(j) = ...
        median(stateGainAtBudget,'omitnan');

    gainQ10(j) = ...
        ed_quantile(stateGainAtBudget,0.10);

    gainQ90(j) = ...
        ed_quantile(stateGainAtBudget,0.90);
end

hBand = fill( ...
    ax, ...
    [budgets;flipud(budgets)], ...
    [gainQ10;flipud(gainQ90)], ...
    [0.75 0.75 0.75], ...
    'FaceAlpha',0.45, ...
    'EdgeColor','none', ...
    'DisplayName','10–90% across targets');

hMedian = plot( ...
    ax, ...
    budgets, ...
    medianGain, ...
    '-o', ...
    'Color',[0.12 0.47 0.71], ...
    'LineWidth',1.8, ...
    'MarkerSize',5.5, ...
    'MarkerFaceColor',[0.12 0.47 0.71], ...
    'DisplayName','Median gain');

yline( ...
    ax, ...
    0, ...
    '--', ...
    'Color',[0.85 0.15 0.15], ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xticks(ax,budgets);
xlim(ax,[min(budgets)-4 max(budgets)+4]);

gainUpperLimit = 1.10*max(gainQ90,[],'omitnan');

if ~isfinite(gainUpperLimit) || gainUpperLimit <= 0
    gainUpperLimit = 1;
end

ylim(ax,[-0.00015 gainUpperLimit]);

xlabel(ax,'Outcome budget');
ylabel(ax,'Direct MAE - observer MAE');

title( ...
    ax, ...
    'Gain by outcome budget', ...
    'FontWeight','bold', ...
    'FontSize',11.5);

legend( ...
    ax, ...
    [hBand hMedian], ...
    {'10–90% across targets','Median gain'}, ...
    'Location','northeast', ...
    'Box','off', ...
    'FontSize',8);

text( ...
    ax, ...
    0.03, ...
    0.07, ...
    sprintf( ...
        '%d/%d states improved', ...
        nnz(allStateGain>0), ...
        numel(allStateGain)), ...
    'Units','normalized', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'FontName','Arial', ...
    'FontSize',8, ...
    'FontWeight','bold', ...
    'BackgroundColor','w', ...
    'Margin',2);

grid(ax,'on');
ax.GridAlpha = 0.12;

ed_style(ax,8.5);
ed_panel_letter(fig,ax,'c');

%% ========================================================================
% d — certification gates
% ========================================================================
ax = axD;
hold(ax,'on');

minimumCoverage = nan(nBudgets,1);
minimumNoHarm   = nan(nBudgets,1);

for j = 1:nBudgets

    m = double(S.budget)==budgets(j);

    minimumCoverage(j) = min( ...
        double(S.simultaneous_coverage(m)), ...
        [], ...
        'omitnan');

    minimumNoHarm(j) = min( ...
        double(S.block_no_harm_rate(m)), ...
        [], ...
        'omitnan');
end

% Both trajectories equal 1.000.
% The thick blue solid line and thinner orange dashed line allow both
% identical trajectories to remain visible without changing x or y data.
hCoverage = plot( ...
    ax, ...
    budgets, ...
    minimumCoverage, ...
    '-o', ...
    'Color',[0.00 0.4470 0.7410], ...
    'LineWidth',2.5, ...
    'MarkerSize',8, ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor',[0.00 0.4470 0.7410], ...
    'DisplayName','Minimum simultaneous coverage');

hNoHarm = plot( ...
    ax, ...
    budgets, ...
    minimumNoHarm, ...
    '--s', ...
    'Color',[0.8500 0.3250 0.0980], ...
    'LineWidth',1.45, ...
    'MarkerSize',5.5, ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor',[0.8500 0.3250 0.0980], ...
    'DisplayName','Min plug-in risk-geometry rate');

xticks(ax,budgets);
xlim(ax,[min(budgets)-5 max(budgets)+5]);

ylim(ax,[0.995 1.0012]);

xlabel(ax,'Outcome budget');
ylabel(ax,'Minimum rate across targets');

title( ...
    ax, ...
    'Certification gates', ...
    'FontWeight','bold', ...
    'FontSize',11.5);

legend( ...
    ax, ...
    [hCoverage hNoHarm], ...
    { ...
        'Minimum simultaneous coverage', ...
        'Minimum plug-in risk-geometry rate'}, ...
    'Location','southeast', ...
    'Box','off', ...
    'FontSize',8);

text( ...
    ax, ...
    max(budgets), ...
    1.00032, ...
    'Both rates = 1.000 at every budget', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'Color',[0.35 0.35 0.35], ...
    'FontSize',8);

maximumIdentityResidual = max( ...
    abs(double(S.maximum_identity_residual)), ...
    [], ...
    'omitnan');

text( ...
    ax, ...
    0.03, ...
    0.08, ...
    sprintf( ...
        'Max fallback identity residual = %.0e', ...
        maximumIdentityResidual), ...
    'Units','normalized', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'FontName','Arial', ...
    'FontSize',8, ...
    'FontWeight','bold', ...
    'BackgroundColor','w', ...
    'Margin',2);

grid(ax,'on');
ax.GridAlpha = 0.12;

ed_style(ax,8.5);
ed_panel_letter(fig,ax,'d');

%% ========================================================================
% Canonical-data audit
% ========================================================================
pooledObserverMAE = mean( ...
    double(S.mae), ...
    'omitnan');

pooledDirectMAE = mean( ...
    double(S.direct_mae), ...
    'omitnan');

pooledGainPercent = ...
    100 * ...
    (pooledDirectMAE-pooledObserverMAE) ...
    / pooledDirectMAE;

worstTargetBudgetRegret = max( ...
    double(S.mae_regret_vs_full_direct), ...
    [], ...
    'omitnan');

fprintf('\nED4 canonical-data audit:\n');

fprintf( ...
    '  Targets / families / budgets / states: %d / %d / %d / %d\n', ...
    height(T), ...
    numel(unique(string(T.family))), ...
    numel(budgets), ...
    height(S));

fprintf( ...
    '  Budgets: %s\n', ...
    sprintf('%d ',budgets));

fprintf( ...
    '  Improved target-budget states: %d/%d\n', ...
    nnz(allStateGain>0), ...
    numel(allStateGain));

fprintf( ...
    '  State-gain range: %.9f to %.9f\n', ...
    min(allStateGain,[],'omitnan'), ...
    max(allStateGain,[],'omitnan'));

fprintf( ...
    '  Pooled observer/direct MAE: %.9f / %.9f\n', ...
    pooledObserverMAE, ...
    pooledDirectMAE);

fprintf( ...
    '  Relative pooled gain: %.6f%%\n', ...
    pooledGainPercent);

fprintf( ...
    '  Worst target-budget regret: %.9f\n', ...
    worstTargetBudgetRegret);

fprintf( ...
    '  Minimum coverage / risk geometry: %.9f / %.9f\n', ...
    min(minimumCoverage,[],'omitnan'), ...
    min(minimumNoHarm,[],'omitnan'));

fprintf( ...
    '  Maximum identity residual: %.3e\n', ...
    maximumIdentityResidual);

%% Export
ed_save( ...
    fig, ...
    outDir, ...
    'ExtendedData4_U6_Independent_Reserve_Detail');

end


%% ========================================================================
% Canonical-record loader
% ========================================================================
function U6 = ed_load_u6(dataDir,cacheDir)

stageDir = ed_extract( ...
    dataDir, ...
    cacheDir, ...
    'StageU6_Canonical_Records_v1.0.zip');

U6.state = ed_read( ...
    stageDir, ...
    'StageU6_Audit_State_Results_v1.0.csv');

U6.target = ed_read( ...
    stageDir, ...
    'StageU6_Target_Summary_v1.0.csv');

end


function stageDir = ed_extract(dataDir,cacheDir,zipName)

zipPath = cmdo.find_unique_file(dataDir,zipName);

if ~exist(zipPath,'file')
    error( ...
        'ED:MissingZip', ...
        'Missing canonical archive: %s', ...
        zipPath);
end

stageDir = fullfile( ...
    cacheDir, ...
    erase(zipName,'.zip'));

readyFile = fullfile(stageDir,'.ready');

if ~exist(readyFile,'file')

    if exist(stageDir,'dir')
        rmdir(stageDir,'s');
    end

    mkdir(stageDir);
    unzip(zipPath,stageDir);

    fid = fopen(readyFile,'w');

    if fid > 0
        fprintf(fid,'ready\n');
        fclose(fid);
    end
end

end


function T = ed_read(stageDir,fileName)

hits = dir(fullfile(stageDir,'**',fileName));

if isempty(hits)
    error( ...
        'ED:MissingCSV', ...
        'CSV not found after extraction: %s', ...
        fileName);
end

T = readtable( ...
    fullfile(hits(1).folder,hits(1).name), ...
    'VariableNamingRule','preserve');

end


%% ========================================================================
% Export and visual helpers
% ========================================================================
function ed_save(fig,outDir,stem)

drawnow;

exportgraphics( ...
    fig, ...
    fullfile(outDir,[stem '.png']), ...
    'Resolution',300, ...
    'BackgroundColor','white');

exportgraphics( ...
    fig, ...
    fullfile(outDir,[stem '.tiff']), ...
    'Resolution',300, ...
    'BackgroundColor','white');

exportgraphics( ...
    fig, ...
    fullfile(outDir,[stem '.pdf']), ...
    'ContentType','vector', ...
    'BackgroundColor','white');

savefig( ...
    fig, ...
    fullfile(outDir,[stem '.fig']));

fprintf('Saved: %s\n',stem);

end


function ed_style(ax,fontSize)

set( ...
    ax, ...
    'FontName','Arial', ...
    'FontSize',fontSize, ...
    'LineWidth',0.85, ...
    'TickDir','out', ...
    'Box','off', ...
    'Layer','top');

ax.XAxis.TickLabelInterpreter = 'none';
ax.YAxis.TickLabelInterpreter = 'none';

end


function ed_panel_letter(fig,ax,labelText)
% Place panel letters outside the axes without changing axes geometry.

drawnow;

positionValue = ax.Position;

xValue = max( ...
    0.008, ...
    positionValue(1)-0.030);

yValue = min( ...
    0.970, ...
    positionValue(2)+positionValue(4)+0.006);

annotation( ...
    fig, ...
    'textbox', ...
    [xValue yValue 0.025 0.028], ...
    'String',labelText, ...
    'LineStyle','none', ...
    'FitBoxToText','off', ...
    'FontName','Arial', ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle');

end


function q = ed_quantile(values,probability)

values = sort(double(values(:)));
values = values(isfinite(values));

if isempty(values)
    q = NaN;
    return;
end

if numel(values)==1
    q = values;
    return;
end

rankValue = ...
    1 + ...
    (numel(values)-1)*probability;

lowerIndex = floor(rankValue);
upperIndex = ceil(rankValue);

if lowerIndex==upperIndex

    q = values(lowerIndex);

else

    q = ...
        values(lowerIndex) ...
        + ...
        (rankValue-lowerIndex) ...
        * ...
        (values(upperIndex)-values(lowerIndex));
end

end


function colorMapValue = ed_white_to_color(targetColor,nColors)

if nargin < 2
    nColors = 256;
end

targetColor = double(targetColor(:)');

colorMapValue = [ ...
    linspace(1,targetColor(1),nColors)', ...
    linspace(1,targetColor(2),nColors)', ...
    linspace(1,targetColor(3),nColors)'];

end


function shortName = ed_short_u6(targetName)

targetName = string(targetName);

switch targetName

    case "ACS_PUBLIC_COVERAGE_2024_FL"
        shortName = 'ACS-FL';

    case "ACS_PUBLIC_COVERAGE_2024_IL"
        shortName = 'ACS-IL';

    case "ACS_PUBLIC_COVERAGE_2024_OH"
        shortName = 'ACS-OH';

    case "ACS_PUBLIC_COVERAGE_2024_PA"
        shortName = 'ACS-PA';

    case "ACS_PUBLIC_COVERAGE_2024_TX"
        shortName = 'ACS-TX';

    case "DERMA_CLEAN"
        shortName = 'Derma-clean';

    case "DERMA_NOISE_0_08"
        shortName = 'Derma-noise';

    case "DERMA_BLUR_1_0"
        shortName = 'Derma-blur';

    case "DERMA_GAMMA_1_4"
        shortName = 'Derma-gamma';

    case "DERMA_JPEG_35"
        shortName = 'Derma-JPEG';

    case "DERMA_DOWNSAMPLE_14"
        shortName = 'Derma-downsample';

    case "CIFAR_CAT_DOG_CLEAN"
        shortName = 'CIFAR-clean';

    case "CIFAR_CAT_DOG_GRAYSCALE"
        shortName = 'CIFAR-greyscale';

    case "CIFAR_CAT_DOG_NOISE_0_10"
        shortName = 'CIFAR-noise';

    case "CIFAR_CAT_DOG_BLUR_1_2"
        shortName = 'CIFAR-blur';

    case "CIFAR_CAT_DOG_JPEG_30"
        shortName = 'CIFAR-JPEG';

    otherwise
        shortName = char(replace(targetName,"_","-"));
end

end
