function ED6
%ED6 Generate CURRENT CMDO Extended Data Figure 6.
% Standalone: reads the frozen canonical ZIP records directly.

close all;
clc;
rng(20260728,'twister');

cfg = cmdo_config('ED6');
DATA_DIR  = cfg.canonicalRecordDir;
CACHE_DIR = fullfile(cfg.cacheRoot,'ED_CURRENT_FINAL');
OUT_DIR   = cfg.extendedOutputDir;

if ~exist(DATA_DIR,'dir')
    error('ED6:MissingData','Canonical record folder not found: %s',DATA_DIR);
end
if ~exist(CACHE_DIR,'dir'), mkdir(CACHE_DIR); end
if ~exist(OUT_DIR,'dir'), mkdir(OUT_DIR); end

U7 = ed_load_u7(DATA_DIR,CACHE_DIR);
ed_make_6(U7,OUT_DIR);

fprintf('\nED6 completed. Output folder:\n%s\n',OUT_DIR);
end


function ed_make_6(U7,outDir)

target        = U7.target;
metricSummary = U7.metric;
rates         = U7.rates;
state         = U7.state;

%% ========================================================================
% Canonical metric definitions
% ========================================================================
metricCodes = [ ...
    "SENSITIVITY"; ...
    "SPECIFICITY"; ...
    "AUC"; ...
    "BALANCED_ACCURACY"; ...
    "BRIER_UTILITY"];

metricLabels = { ...
    'Sensitivity'; ...
    'Specificity'; ...
    'AUC'; ...
    'Balanced accuracy'; ...
    'Brier utility'};

% Fixed metric colours used consistently across panels a, b and d.
metricColors = [ ...
    0.1216 0.4667 0.7059; ...  % Sensitivity: blue
    1.0000 0.4980 0.0549; ...  % Specificity: orange
    0.1725 0.6275 0.1725; ...  % AUC: green
    0.8392 0.1529 0.1569; ...  % Balanced accuracy: red
    0.4941 0.1843 0.5569];     % Brier utility: purple

%% ========================================================================
% Canonical-record validation
% ========================================================================
if height(metricSummary) ~= 5
    error( ...
        'ED6:MetricSummaryCount', ...
        'Expected 5 metric-summary rows; found %d.', ...
        height(metricSummary));
end

if height(target) ~= 80
    error( ...
        'ED6:TargetCount', ...
        'Expected 80 target-metric rows; found %d.', ...
        height(target));
end

if height(state) ~= 400
    error( ...
        'ED6:StateCount', ...
        'Expected 400 state rows; found %d.', ...
        height(state));
end

if height(rates) ~= 28
    error( ...
        'ED6:RateCount', ...
        'Expected 28 root-budget-rate rows; found %d.', ...
        height(rates));
end

stateBudgets = sort(unique(double(state.budget)));
expectedStateBudgets = [16;32;64;128;256];

if ~isequal(stateBudgets(:),expectedStateBudgets)
    error( ...
        'ED6:StateBudgets', ...
        'Expected state budgets [16 32 64 128 256].');
end

if numel(unique(string(target.stratum))) ~= 16
    error( ...
        'ED6:StratumCount', ...
        'Expected 16 prespecified clinical strata.');
end

%% ========================================================================
% Fixed figure geometry
% Avoid tiledlayout shifting caused by legends.
% ========================================================================
fig = figure( ...
    'Position',[40 40 900 700], ...
    'Color','w', ...
    'Name','Extended Data Figure 6', ...
    'NumberTitle','off', ...
    'Renderer','painters');

axA = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.075 0.565 0.390 0.365]);

axB = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.575 0.565 0.350 0.365]);

axC = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.075 0.095 0.390 0.350]);

axD = axes( ...
    fig, ...
    'Units','normalized', ...
    'Position',[0.575 0.095 0.350 0.350]);

%% ========================================================================
% a — stratum-level relative gain distributions
% ========================================================================
ax = axA;
hold(ax,'on');

allRelativeGain = nan(height(target),1);

for i = 1:numel(metricCodes)

    m = string(target.metric)==metricCodes(i);

    values = ...
        double(target.gain(m)) ...
        ./ double(target.direct_mae(m));

    values = values(isfinite(values));

    if numel(values) ~= 16
        error( ...
            'ED6:MetricStrataCount', ...
            'Expected 16 strata for %s; found %d.', ...
            metricCodes(i), ...
            numel(values));
    end

    allRelativeGain(m) = values;

    ed_violin( ...
        ax, ...
        i, ...
        values, ...
        [0.82 0.82 0.82], ...
        0.34, ...
        0.36);

    scatter( ...
        ax, ...
        i + 0.045*randn(size(values)), ...
        values, ...
        24, ...
        metricColors(i,:), ...
        'filled', ...
        'MarkerEdgeColor','none', ...
        'MarkerFaceAlpha',0.88);

    medianValue = median(values,'omitnan');

    plot( ...
        ax, ...
        [i-0.19 i+0.19], ...
        [medianValue medianValue], ...
        'k-', ...
        'LineWidth',1.8);
end

yline( ...
    ax, ...
    0, ...
    '--', ...
    'Color',[0.85 0.15 0.15], ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xticks(ax,1:5);
xticklabels(ax,metricLabels);
xtickangle(ax,25);

ylabel(ax,'Relative gain by stratum');

title( ...
    ax, ...
    'Stratum-level gain distributions', ...
    'FontWeight','bold', ...
    'FontSize',11.5);

gainMinimum = min(allRelativeGain,[],'omitnan');
gainMaximum = max(allRelativeGain,[],'omitnan');
gainRange   = gainMaximum-gainMinimum;

if ~isfinite(gainRange) || gainRange <= 0
    gainRange = 0.01;
end

ylim( ...
    ax, ...
    [min(-0.005,gainMinimum-0.08*gainRange), ...
     gainMaximum+0.08*gainRange]);

grid(ax,'on');
ax.GridAlpha = 0.11;

ed_style(ax,8.5);
ed_panel_letter(fig,ax,'a');

%% ========================================================================
% b — metric-specific worst regret
% ========================================================================
ax = axB;
hold(ax,'on');

worstRegret = nan(5,1);
pooledGain  = nan(5,1);

for i = 1:5

    r = metricSummary( ...
        string(metricSummary.metric)==metricCodes(i),:);

    if height(r) ~= 1
        error( ...
            'ED6:MetricSummaryMultiplicity', ...
            'Expected one summary row for %s.', ...
            metricCodes(i));
    end

    worstRegret(i) = double(r.worst_regret);
    pooledGain(i)  = 100*double(r.relative_gain);
end

% Scale for readable tick labels.
worstScaled = 1e4*worstRegret;

barColors = repmat([0.20 0.63 0.25],5,1);
barColors(worstRegret>0,:) = ...
    repmat([0.92 0.40 0.20],nnz(worstRegret>0),1);

barB = barh( ...
    ax, ...
    worstScaled, ...
    0.65, ...
    'FaceColor','flat', ...
    'EdgeColor','none');

barB.CData = barColors;

set(ax,'YDir','reverse');

yticks(ax,1:5);
yticklabels(ax,metricLabels);

xline( ...
    ax, ...
    0, ...
    '-', ...
    'Color',[0.25 0.25 0.25], ...
    'LineWidth',0.9, ...
    'HandleVisibility','off');

scaledMinimum = min([0;worstScaled]);
scaledMaximum = max([0;worstScaled]);
scaledRange   = scaledMaximum-scaledMinimum;

if ~isfinite(scaledRange) || scaledRange <= 0
    scaledRange = 1;
end

xlim( ...
    ax, ...
    [scaledMinimum-0.14*scaledRange, ...
     scaledMaximum+0.22*scaledRange]);

for i = 1:5

    if worstScaled(i) >= 0

        textX = worstScaled(i)+0.025*scaledRange;
        horizontalAlignment = 'left';

    else

        textX = worstScaled(i)-0.025*scaledRange;
        horizontalAlignment = 'right';
    end

    text( ...
        ax, ...
        textX, ...
        i, ...
        sprintf('%+.3f',worstScaled(i)), ...
        'HorizontalAlignment',horizontalAlignment, ...
        'VerticalAlignment','middle', ...
        'FontName','Arial', ...
        'FontSize',7.8, ...
        'FontWeight','bold');
end

xlabel(ax,'Worst stratum-budget regret (x10^{-4})');

title( ...
    ax, ...
    'Worst-state regret is metric-specific', ...
    'FontWeight','bold', ...
    'FontSize',11.5);

% Legend proxies for regret sign.
hSafe = scatter( ...
    ax,NaN,NaN,50,'s','filled', ...
    'MarkerFaceColor',[0.20 0.63 0.25], ...
    'MarkerEdgeColor','none');

hPositive = scatter( ...
    ax,NaN,NaN,50,'s','filled', ...
    'MarkerFaceColor',[0.92 0.40 0.20], ...
    'MarkerEdgeColor','none');

legend( ...
    ax, ...
    [hSafe hPositive], ...
    {'Non-positive worst regret', ...
     'Positive worst regret'}, ...
    'Location','southeast', ...
    'Box','off', ...
    'FontSize',7.5);

grid(ax,'on');
ax.GridAlpha = 0.11;

ed_style(ax,8.5);
ed_panel_letter(fig,ax,'b');

%% ========================================================================
% c — root-budget contraction and measured slopes
% ========================================================================
ax = axC;
hold(ax,'on');

rateCodes = [ ...
    "AUC_USTATISTIC"; ...
    "BERNOULLI_ACCURACY"; ...
    "BOUNDED_BRIER_UTILITY"; ...
    "BOUNDED_SENSITIVITY"];

rateLabels = { ...
    'AUC U-statistic'; ...
    'Bernoulli accuracy'; ...
    'Bounded Brier utility'; ...
    'Bounded sensitivity'};

rateColors = [ ...
    0.1216 0.4667 0.7059; ...
    1.0000 0.4980 0.0549; ...
    0.1725 0.6275 0.1725; ...
    0.8392 0.1529 0.1569];

rateHandles = gobjects(4,1);
rateLegendLabels = strings(4,1);

for i = 1:4

    R = rates( ...
        string(rates.metric)==rateCodes(i),:);

    if height(R) ~= 7
        error( ...
            'ED6:RateBudgetCount', ...
            'Expected 7 rate rows for %s; found %d.', ...
            rateCodes(i), ...
            height(R));
    end

    [orderedBudget,orderIndex] = ...
        sort(double(R.budget));

    orderedMAE = ...
        double(R.mae(orderIndex));

    slopeValue = ...
        mean(double(R.slope),'omitnan');

    rateHandles(i) = plot( ...
        ax, ...
        orderedBudget, ...
        orderedMAE, ...
        '-o', ...
        'Color',rateColors(i,:), ...
        'LineWidth',1.55, ...
        'MarkerSize',5.2, ...
        'MarkerFaceColor',rateColors(i,:), ...
        'MarkerEdgeColor',rateColors(i,:));

    rateLegendLabels(i) = sprintf( ...
        '%s (slope %.3f)', ...
        rateLabels{i}, ...
        slopeValue);
end

set(ax, ...
    'XScale','log', ...
    'YScale','log');

rateBudgets = sort(unique(double(rates.budget)));

xticks(ax,rateBudgets);
xticklabels(ax,string(rateBudgets));

xlim(ax,[14 1200]);

xlabel(ax,'Outcome budget');
ylabel(ax,'MAE');

title( ...
    ax, ...
    'Root-budget contraction across functionals', ...
    'FontWeight','bold', ...
    'FontSize',11.5);

legend( ...
    ax, ...
    rateHandles, ...
    cellstr(rateLegendLabels), ...
    'Location','northeast', ...
    'NumColumns',1, ...
    'Box','off', ...
    'FontSize',7.2);

grid(ax,'on');
ax.GridAlpha = 0.11;
ax.MinorGridAlpha = 0.06;

ed_style(ax,8.5);
ed_panel_letter(fig,ax,'c');

%% ========================================================================
% d — borrowing by metric and outcome budget
% ========================================================================
ax = axD;
hold(ax,'on');

budgets = sort(unique(double(state.budget)));
weightHandles = gobjects(5,1);

for i = 1:5

    meanWeightByBudget = nan(numel(budgets),1);

    for j = 1:numel(budgets)

        m = ...
            string(state.metric)==metricCodes(i) & ...
            double(state.budget)==budgets(j);

        values = double(state.mean_weight(m));
        values = values(isfinite(values));

        if numel(values) ~= 16
            error( ...
                'ED6:StateMetricBudgetCount', ...
                ['Expected 16 strata for metric %s ' ...
                 'at budget %d; found %d.'], ...
                metricCodes(i), ...
                budgets(j), ...
                numel(values));
        end

        meanWeightByBudget(j) = ...
            mean(values,'omitnan');
    end

    weightHandles(i) = plot( ...
        ax, ...
        budgets, ...
        meanWeightByBudget, ...
        '-o', ...
        'Color',metricColors(i,:), ...
        'LineWidth',1.55, ...
        'MarkerSize',5.5, ...
        'MarkerFaceColor',metricColors(i,:), ...
        'MarkerEdgeColor',metricColors(i,:));
end

xticks(ax,budgets);
xlim(ax,[8 275]);

ylim(ax,[0 0.075]);

xlabel(ax,'Outcome budget');
ylabel(ax,'Mean transport weight');

title( ...
    ax, ...
    'Borrowing differs by metric and budget', ...
    'FontWeight','bold', ...
    'FontSize',11.5);

legend( ...
    ax, ...
    weightHandles, ...
    metricLabels, ...
    'Location','northeast', ...
    'NumColumns',2, ...
    'Box','off', ...
    'FontSize',7.2);

grid(ax,'on');
ax.GridAlpha = 0.11;

ed_style(ax,8.5);
ed_panel_letter(fig,ax,'d');

%% ========================================================================
% Canonical-data audit
% ========================================================================
fprintf('\nED6 canonical-data audit:\n');
fprintf('  Metrics / strata / target rows: %d / %d / %d\n', ...
    numel(metricCodes), ...
    numel(unique(string(target.stratum))), ...
    height(target));

fprintf('  State rows / state budgets: %d / %d\n', ...
    height(state), ...
    numel(stateBudgets));

fprintf('  Root-budget rate rows: %d\n',height(rates));

fprintf('\n  Metric-level results:\n');

for i = 1:5

    fprintf( ...
        '    %-20s gain=%7.4f%%  worst regret=%+.9f\n', ...
        metricLabels{i}, ...
        pooledGain(i), ...
        worstRegret(i));
end

fprintf('\n  Root-budget slopes:\n');

for i = 1:4

    R = rates(string(rates.metric)==rateCodes(i),:);

    fprintf( ...
        '    %-25s slope=%+.6f\n', ...
        rateLabels{i}, ...
        mean(double(R.slope),'omitnan'));
end

%% Export
ed_save( ...
    fig, ...
    outDir, ...
    'ExtendedData6_Multimetric_Support_And_Limits');

end

function U7 = ed_load_u7(dataDir,cacheDir)
d = ed_extract(dataDir,cacheDir,'StageU7_Canonical_Records_v1.0.zip');
U7.state  = ed_read(d,'StageU7_State_Results_v1.0.csv');
U7.target = ed_read(d,'StageU7_Target_Metric_Summary_v1.0.csv');
U7.metric = ed_read(d,'StageU7_Metric_Summary_v1.0.csv');
U7.rates  = ed_read(d,'StageU7_Label_Complexity_Rates_v1.0.csv');
end

function stageDir = ed_extract(dataDir,cacheDir,zipName)
zipPath = cmdo.find_unique_file(dataDir,zipName);
if ~exist(zipPath,'file')
    error('ED:MissingZip','Missing canonical archive: %s',zipPath);
end
stageDir = fullfile(cacheDir,erase(zipName,'.zip'));
ready = fullfile(stageDir,'.ready');
if ~exist(ready,'file')
    if exist(stageDir,'dir'), rmdir(stageDir,'s'); end
    mkdir(stageDir);
    unzip(zipPath,stageDir);
    fid = fopen(ready,'w');
    if fid>0, fprintf(fid,'ready\n'); fclose(fid); end
end
end

function T = ed_read(stageDir,fileName)
hits = dir(fullfile(stageDir,'**',fileName));
if isempty(hits)
    error('ED:MissingCSV','CSV not found after extraction: %s',fileName);
end
T = readtable(fullfile(hits(1).folder,hits(1).name), ...
    'VariableNamingRule','preserve');
end

function ed_save(fig,outDir,stem)
drawnow;
exportgraphics(fig,fullfile(outDir,[stem '.png']), ...
    'Resolution',300,'BackgroundColor','white');
exportgraphics(fig,fullfile(outDir,[stem '.tiff']), ...
    'Resolution',300,'BackgroundColor','white');
exportgraphics(fig,fullfile(outDir,[stem '.pdf']), ...
    'ContentType','vector','BackgroundColor','white');
savefig(fig,fullfile(outDir,[stem '.fig']));
fprintf('Saved: %s\n',stem);
end

function ed_style(ax,fontSize)
set(ax,'FontName','Arial','FontSize',fontSize, ...
    'LineWidth',.85,'TickDir','out','Box','off','Layer','top');
end

function ed_panel_letter(fig,ax,labelText)
% Place panel letters outside the axes with fixed figure geometry.

drawnow;

positionValue = ax.Position;

xValue = max( ...
    0.008, ...
    positionValue(1)-0.038);

yValue = min( ...
    0.972, ...
    positionValue(2)+positionValue(4)+0.006);

annotation( ...
    fig, ...
    'textbox', ...
    [xValue yValue 0.026 0.028], ...
    'String',labelText, ...
    'LineStyle','none', ...
    'FitBoxToText','off', ...
    'FontName','Arial', ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle');

end

function ed_violin(ax,x0,v,faceColor,halfWidth,faceAlpha)
v = double(v(:));
v = v(isfinite(v));
if numel(v)<2, return; end

vmin = min(v); vmax = max(v);
if vmax<=vmin
    vmin = vmin-1e-6; vmax = vmax+1e-6;
end
yg = linspace(vmin,vmax,180)';
sd = std(v,0);
bw = 1.06*sd*numel(v)^(-1/5);
if ~isfinite(bw) || bw<=0, bw=max((vmax-vmin)/20,eps); end
Z = bsxfun(@minus,yg,v')/bw;
f = mean(exp(-.5*Z.^2),2)/(bw*sqrt(2*pi));
if max(f)<=0 || ~all(isfinite(f)), f=ones(size(f)); end
w = halfWidth*f/max(f);
patch(ax,[x0-w;flipud(x0+w)],[yg;flipud(yg)],faceColor, ...
    'FaceAlpha',faceAlpha,'EdgeColor',[.45 .45 .45], ...
    'LineWidth',.6,'HandleVisibility','off');
end

function q = ed_quantile(v,p)
v = sort(double(v(:)));
v = v(isfinite(v));
if isempty(v), q=NaN; return; end
if numel(v)==1, q=v; return; end
r = 1 + (numel(v)-1)*p;
lo = floor(r); hi = ceil(r);
if lo==hi
    q = v(lo);
else
    q = v(lo)+(r-lo)*(v(hi)-v(lo));
end
end

function cmap = ed_diverging_map(n)
if nargin<1, n=256; end
n1 = floor(n/2); n2 = n-n1;
blue = [.12 .47 .71]; white = [1 1 1]; red = [.84 .15 .16];
c1 = [linspace(blue(1),white(1),n1)', ...
      linspace(blue(2),white(2),n1)', ...
      linspace(blue(3),white(3),n1)'];
c2 = [linspace(white(1),red(1),n2)', ...
      linspace(white(2),red(2),n2)', ...
      linspace(white(3),red(3),n2)'];
cmap = [c1;c2];
end


function cmap = ed_white_to_color(targetColor,n)
if nargin<2, n=256; end
targetColor = double(targetColor(:)');
cmap = [linspace(1,targetColor(1),n)', ...
        linspace(1,targetColor(2),n)', ...
        linspace(1,targetColor(3),n)'];
end

function s = ed_short_u4(x)
x = string(x);
switch x
    case "EMNIST_DIGITS", s='EMNIST DIGITS';
    case "QMNIST_TEST50K", s='QMNIST TEST50K';
    case "GENRE_facetoface", s='facetoface';
    case "GENRE_letters", s='letters';
    case "GENRE_nineeleven", s='nineeleven';
    case "GENRE_oup", s='oup';
    case "GENRE_verbatim", s='verbatim';
    otherwise, s=char(x);
end
end

function s = ed_short_u6(x)
x = string(x);
switch x
    case "ACS_PUBLIC_COVERAGE_2024_FL", s='ACS-FL';
    case "ACS_PUBLIC_COVERAGE_2024_IL", s='ACS-IL';
    case "ACS_PUBLIC_COVERAGE_2024_OH", s='ACS-OH';
    case "ACS_PUBLIC_COVERAGE_2024_PA", s='ACS-PA';
    case "ACS_PUBLIC_COVERAGE_2024_TX", s='ACS-TX';
    case "DERMA_CLEAN", s='Derma-clean';
    case "DERMA_NOISE_0_08", s='Derma-noise';
    case "DERMA_BLUR_1_0", s='Derma-blur';
    case "DERMA_GAMMA_1_4", s='Derma-gamma';
    case "DERMA_JPEG_35", s='Derma-JPEG';
    case "DERMA_DOWNSAMPLE_14", s='Derma-downsample';
    case "CIFAR_CAT_DOG_CLEAN", s='CIFAR-clean';
    case "CIFAR_CAT_DOG_GRAYSCALE", s='CIFAR-greyscale';
    case "CIFAR_CAT_DOG_NOISE_0_10", s='CIFAR-noise';
    case "CIFAR_CAT_DOG_BLUR_1_2", s='CIFAR-blur';
    case "CIFAR_CAT_DOG_JPEG_30", s='CIFAR-JPEG';
    otherwise, s=char(replace(x,"_","-"));
end
end

function s = ed_pretty_stratum(x)
x = string(x);
switch x
    case "ER_AGE_50_69", s='Age 50-69';
    case "ER_AGE_GE70", s='Age >=70';
    case "ER_AGE_LT50", s='Age <50';
    case "ER_ALL", s='All ER';
    case "ER_DIAGNOSES_GE7", s='Diagnoses >=7';
    case "ER_DIAGNOSES_LE6", s='Diagnoses <=6';
    case "ER_FEMALE", s='Female';
    case "ER_INSULIN_ACTIVE", s='Insulin active';
    case "ER_INSULIN_NONE", s='No insulin';
    case "ER_LONG_STAY_GE5", s='Stay >=5 d';
    case "ER_MALE", s='Male';
    case "ER_PRIOR_UTILIZATION_POSITIVE", s='Prior use >0';
    case "ER_PRIOR_UTILIZATION_ZERO", s='Prior use =0';
    case "ER_RACE_AFRICAN_AMERICAN", s='African American';
    case "ER_RACE_CAUCASIAN", s='Caucasian';
    case "ER_SHORT_STAY_LE4", s='Stay <=4 d';
    otherwise, s=char(replace(x,"_"," "));
end
end

function out = ternary(cond,a,b)
if cond, out=a; else, out=b; end
end
