function Figure3(outputDir)
%FIGURE3 Final merged six-panel Figure 3.
%
% Direct render from canonical CMDO data.
% No Legacy_Figure3 / Legacy_Figure4 source figures are generated.
%
% Final structure:
%
% a  Universal component law fails heterogeneously
%
% b  Transport bias controls reuse utility and borrowing
%    top    = MAE utility vs estimated transport bias
%    bottom = selected borrowing weight vs estimated transport bias
%
% c  Development navigates the efficiency-safety frontier
%    candidate landscape + highlighted development trajectory
%
% d  Pair completeness removes the split-estimator tax
%
% e  Exact direct fallback is algebraic
%
% f  Complete regret distributions expose tail safety


close all;


%% ========================================================================
% USER-ADJUSTABLE FONT CONTROL
%
% Change FONT_SCALE only to resize every explicit font size in Figure 3.
%
% 1.00 = original size
% 1.10 = all fonts 10% larger
% 1.20 = all fonts 20% larger
% 0.90 = all fonts 10% smaller
%
% All scientific data, calculations and panel geometry are unchanged.
% ========================================================================

FONT_SCALE = 1.0;

fs = @(x) x .* FONT_SCALE;


%% ========================================================================
% PATHS
% ========================================================================

scriptDir = fileparts(mfilename('fullpath'));

if ~isempty(scriptDir)
    addpath(genpath(scriptDir));
end


requiredHelpers = { ...
    'cmdo_config', ...
    'cmdo_load_all', ...
    'cmdo_lowess_bootstrap', ...
    'cmdo_summary_value', ...
    'cmdo_short_target'};

for i = 1:numel(requiredHelpers)

    if exist(requiredHelpers{i},'file') == 0

        error( ...
            'Figure3:MissingHelper', ...
            'Required helper is not on the MATLAB path: %s', ...
            requiredHelpers{i});

    end

end


%% ========================================================================
% LOAD CANONICAL DATA DIRECTLY
% ========================================================================

cfg3 = cmdo_config('Figure3');
D3 = cmdo_load_all(cfg3);

cfg4 = cmdo_config('Figure4');
D4 = cmdo_load_all(cfg4);


rng(20260728,'twister');


reviewerRoot = strtrim(getenv('CMDO_OUTPUT_ROOT'));

if nargin < 1 || isempty(outputDir)
    if ~isempty(reviewerRoot)
        outputDir = fullfile(reviewerRoot,'figures','main');
    else
        outputDir = cfg3.outputDir;
    end
end


if ~exist(outputDir,'dir')
    mkdir(outputDir);
end


%% ========================================================================
% FIGURE CANVAS
% ========================================================================

fig = figure( ...
    'Position',[30 20 800 900], ...
    'Color','w', ...
    'Renderer','painters', ...
    'Name','CMDO Figure 3', ...
    'NumberTitle','off');


annotation( ...
    fig, ...
    'textbox', ...
    [0.05 0.965 0.90 0.025], ...
    'String','Falsification and hardening of the guarded observer', ...
    'LineStyle','none', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName','Arial', ...
    'FontWeight','bold', ...
    'FontSize',fs(16), ...
    'Margin',0);


%% ========================================================================
% FINAL PANEL GEOMETRY
%
%        a                         b
%
%        c                         d
%
%        e                         f
% ========================================================================

slotA = [0.055 0.690 0.410 0.235];
slotB = [0.535 0.690 0.410 0.235];

slotC = [0.055 0.380 0.410 0.235];
slotD = [0.535 0.380 0.410 0.235];

slotE = [0.055 0.070 0.410 0.235];
slotF = [0.535 0.070 0.410 0.235];


%% ========================================================================
% PANEL HEADERS
% ========================================================================

panelLetters = 'abcdef';

panelTitles = { ...
    'A universal component law fails heterogeneously', ...
    'Transport bias controls reuse utility and borrowing', ...
    'Development navigates the efficiency-safety frontier', ...
    'Pair completeness removes the split-estimator tax', ...
    'Exact direct fallback is algebraic', ...
    'Complete regret distributions expose tail safety'};

slots = [ ...
    slotA; ...
    slotB; ...
    slotC; ...
    slotD; ...
    slotE; ...
    slotF];


for k = 1:6

    r = slots(k,:);

    annotation( ...
        fig, ...
        'textbox', ...
        [r(1)-0.028 r(2)+r(4)+0.012 0.025 0.022], ...
        'String',panelLetters(k), ...
        'LineStyle','none', ...
        'FontName','Arial', ...
        'FontWeight','bold', ...
        'FontSize',fs(15), ...
        'Margin',0);


    annotation( ...
        fig, ...
        'textbox', ...
        [r(1) r(2)+r(4)+0.010 r(3) 0.022], ...
        'String',panelTitles{k}, ...
        'LineStyle','none', ...
        'FontName','Arial', ...
        'FontWeight','bold', ...
        'FontSize',fs(10.2), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'Interpreter','none', ...
        'Margin',0);

end


%% ========================================================================
% a — UNIVERSAL COMPONENT LAW
% ========================================================================

axAHeat = axes( ...
    fig, ...
    'Position',[ ...
        slotA(1), ...
        slotA(2)+0.595*slotA(4), ...
        0.78*slotA(3), ...
        0.335*slotA(4)]);


d = D3.u4c_pred;


universalError = ...
    abs(d.component_pred - d.truth_direct_mae);


rootBudgetError = ...
    abs(d.rootn_pred - d.truth_direct_mae);


advantage = rootBudgetError - universalError;


targetOrder = string(D3.u4c_fits.target);

budgetOrder = sort(unique(d.budget),'descend');


H = NaN(numel(budgetOrder),numel(targetOrder));


for i = 1:numel(budgetOrder)

    for j = 1:numel(targetOrder)

        m = ...
            d.budget == budgetOrder(i) ...
            & string(d.target) == targetOrder(j);

        vals = advantage(m);
        vals = vals(isfinite(vals));

        if ~isempty(vals)
            H(i,j) = mean(vals);
        end

    end

end


imagesc(axAHeat,H);


colormap(axAHeat,parula(256));


limH = max(abs(H(:)),[],'omitnan');

if ~isfinite(limH) || limH <= 0
    limH = 1;
end


caxis(axAHeat,[-limH limH]);


pbaspect(axAHeat,[13 3.6 1]);


xticks(axAHeat,1:numel(targetOrder));


shortLabels = strings(size(targetOrder));

for j = 1:numel(targetOrder)
    shortLabels(j) = cmdo_short_target(targetOrder(j));
end


xticklabels(axAHeat,shortLabels);

xtickangle(axAHeat,48);


yticks(axAHeat,1:numel(budgetOrder));

yticklabels(axAHeat,string(budgetOrder));


xlabel(axAHeat,'');

ylabel(axAHeat,'Outcome budget');


f3_style_axes(axAHeat,fs(7.6));


axAHeat.XAxis.TickLabelInterpreter = 'none';
axAHeat.YAxis.TickLabelInterpreter = 'none';


try
    axAHeat.XLabel.Units = 'normalized';
    axAHeat.XLabel.Position(2) = -0.42;
catch
end


% ------------------------------------------------------------------------
% Colorbar
% ------------------------------------------------------------------------

cb = colorbar(axAHeat);


cb.Position = [ ...
    slotA(1)+0.80*slotA(3), ...
    slotA(2)+0.655*slotA(4), ...
    0.018*slotA(3), ...
    0.225*slotA(4)];


cb.FontName = 'Arial';
cb.FontSize = fs(6.5);
cb.TickDirection = 'out';


cb.Label.String = 'root - universal';
cb.Label.FontName = 'Arial';
cb.Label.FontSize = fs(6.6);


% ------------------------------------------------------------------------
% Late-budget summary
% ------------------------------------------------------------------------

axABar = axes( ...
    fig, ...
    'Position',[ ...
        slotA(1)+0.25*slotA(3), ...
        slotA(2)+0.000*slotA(4), ...
        0.68*slotA(3), ...
        0.125*slotA(4)]);


uv = D3.u4c_fits.component_late_mae;
rv = D3.u4c_fits.rootn_late_mae;


validU = isfinite(uv);
validR = isfinite(rv);


meanLate = [ ...
    mean(uv(validU)), ...
    mean(rv(validR))];


semLate = [ ...
    std(uv(validU),0) / sqrt(nnz(validU)), ...
    std(rv(validR),0) / sqrt(nnz(validR))];


bars = barh( ...
    axABar, ...
    1:2, ...
    meanLate, ...
    0.50, ...
    'FaceColor','flat');


bars.CData = [ ...
    0.12 0.47 0.71; ...
    1.00 0.50 0.05];


hold(axABar,'on');


capHalf = 0.10;


for ii = 1:2

    plot( ...
        axABar, ...
        [meanLate(ii)-semLate(ii), meanLate(ii)+semLate(ii)], ...
        [ii ii], ...
        'k-', ...
        'LineWidth',1);


    plot( ...
        axABar, ...
        [meanLate(ii)-semLate(ii), meanLate(ii)-semLate(ii)], ...
        [ii-capHalf ii+capHalf], ...
        'k-', ...
        'LineWidth',1);


    plot( ...
        axABar, ...
        [meanLate(ii)+semLate(ii), meanLate(ii)+semLate(ii)], ...
        [ii-capHalf ii+capHalf], ...
        'k-', ...
        'LineWidth',1);

end


yticks(axABar,1:2);


yticklabels( ...
    axABar, ...
    { ...
    'Universal component law', ...
    'Root-budget baseline'});


set(axABar,'YDir','reverse');


xlabel(axABar,'Late-budget trajectory MAE');


title( ...
    axABar, ...
    'Late-budget MAE', ...
    'FontWeight','bold', ...
    'FontSize',fs(7.5));


nUniversalBetter = ...
    nnz(isfinite(uv) & isfinite(rv) & uv < rv);


text( ...
    axABar, ...
    0.98, ...
    0.82, ...
    sprintf('%d/%d better', ...
    nUniversalBetter,numel(targetOrder)), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontName','Arial', ...
    'FontSize',fs(6.6), ...
    'FontWeight','bold', ...
    'BackgroundColor','w', ...
    'Margin',1);


xMaxBar = max(meanLate + semLate);


if ~isfinite(xMaxBar) || xMaxBar <= 0
    xMaxBar = 1;
end


xlim(axABar,[0 1.15*xMaxBar]);


grid(axABar,'on');
axABar.GridAlpha = 0.10;


f3_style_axes(axABar,fs(6.9));


%% ========================================================================
% b — TRANSPORT BIAS CONTROLS UTILITY AND BORROWING
% ========================================================================

families = [ ...
    "ACS_INCOME_2022", ...
    "MEDICAL_XRAY", ...
    "AMAZON_LANGUAGES"];


familyLabels = { ...
    'Population transfer', ...
    'Medical acquisition shifts', ...
    'Multilingual severe shift'};


familyMarkers = { ...
    'o', ...
    's', ...
    '^'};


familyColors = [ ...
    0.1216 0.4667 0.7059; ...
    1.0000 0.4980 0.0549; ...
    0.1725 0.6275 0.1725];


xBias = D3.u5b_state.mean_sentinel_bias_sq;


familyValue = string(D3.u5b_state.family);


cluster = ...
    familyValue ...
    + "::" ...
    + string(D3.u5b_state.target);


% ------------------------------------------------------------------------
% b-top — transport utility
% ------------------------------------------------------------------------

axB1 = axes( ...
    fig, ...
    'Position',[ ...
        slotB(1), ...
        slotB(2)+0.54*slotB(4), ...
        slotB(3), ...
        0.39*slotB(4)]);


hold(axB1,'on');


yUtility = D3.u5b_state.sentinel_gain_vs_direct;


finiteB1 = ...
    isfinite(xBias) ...
    & isfinite(yUtility) ...
    & ~ismissing(cluster);


[gridB1,fitB1,loB1,hiB1] = ...
    cmdo_lowess_bootstrap( ...
    xBias(finiteB1), ...
    yUtility(finiteB1), ...
    cluster(finiteB1), ...
    0.42, ...
    300, ...
    20260728);


gridB1 = gridB1(:);
fitB1 = fitB1(:);
loB1 = loB1(:);
hiB1 = hiB1(:);


hBandB1 = fill( ...
    axB1, ...
    [gridB1; flipud(gridB1)], ...
    [loB1; flipud(hiB1)], ...
    [0.92 0.55 0.55], ...
    'FaceAlpha',0.18, ...
    'EdgeColor','none', ...
    'DisplayName','95% bootstrap');


hLowessB1 = plot( ...
    axB1, ...
    gridB1, ...
    fitB1, ...
    'Color',[0.05 0.45 0.82], ...
    'LineWidth',1.8, ...
    'DisplayName','LOWESS');


hFam = gobjects(3,1);


for k = 1:3

    m = ...
        familyValue == families(k) ...
        & isfinite(xBias) ...
        & isfinite(yUtility);


    hFam(k) = scatter( ...
        axB1, ...
        xBias(m), ...
        yUtility(m), ...
        25, ...
        'filled', ...
        'Marker',familyMarkers{k}, ...
        'MarkerFaceColor',familyColors(k,:), ...
        'MarkerEdgeColor',familyColors(k,:), ...
        'DisplayName',familyLabels{k});

end


yline( ...
    axB1, ...
    0, ...
    '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');


ylabel( ...
    axB1, ...
    {'Same-budget MAE', ...
    'reduction vs direct'});


axB1.XTickLabel = {};


xMaxB = max(xBias(finiteB1),[],'omitnan');


if ~isfinite(xMaxB) || xMaxB <= 0
    xMaxB = 1;
end


xlim(axB1,[0 1.04*xMaxB]);


legend( ...
    axB1, ...
    [hFam; hLowessB1; hBandB1], ...
    [familyLabels, ...
    {'LOWESS','95% bootstrap'}], ...
    'Location','northeast', ...
    'NumColumns',2, ...
    'Box','off', ...
    'FontSize',fs(6.0));


f3_style_axes(axB1,fs(7.1));


% ------------------------------------------------------------------------
% b-bottom — selected borrowing weight
% ------------------------------------------------------------------------

axB2 = axes( ...
    fig, ...
    'Position',[ ...
        slotB(1), ...
        slotB(2)+0.04*slotB(4), ...
        slotB(3), ...
        0.36*slotB(4)]);


hold(axB2,'on');


yWeightRaw = D3.u5b_state.mean_sentinel_weight;
yWeight = max(yWeightRaw,0);


finiteB2 = ...
    isfinite(xBias) ...
    & isfinite(yWeightRaw) ...
    & ~ismissing(cluster);


[gridB2,fitB2,loB2,hiB2] = ...
    cmdo_lowess_bootstrap( ...
    xBias(finiteB2), ...
    yWeightRaw(finiteB2), ...
    cluster(finiteB2), ...
    0.42, ...
    300, ...
    20260729);


gridB2 = gridB2(:);

fitB2 = max(fitB2(:),0);
loB2 = max(loB2(:),0);
hiB2 = max(hiB2(:),0);


fill( ...
    axB2, ...
    [gridB2; flipud(gridB2)], ...
    [loB2; flipud(hiB2)], ...
    [0.92 0.55 0.55], ...
    'FaceAlpha',0.18, ...
    'EdgeColor','none', ...
    'HandleVisibility','off');


plot( ...
    axB2, ...
    gridB2, ...
    fitB2, ...
    'Color',[0.05 0.45 0.82], ...
    'LineWidth',1.8, ...
    'HandleVisibility','off');


for k = 1:3

    m = ...
        familyValue == families(k) ...
        & isfinite(xBias) ...
        & isfinite(yWeight);


    scatter( ...
        axB2, ...
        xBias(m), ...
        yWeight(m), ...
        24, ...
        'filled', ...
        'Marker',familyMarkers{k}, ...
        'MarkerFaceColor',familyColors(k,:), ...
        'MarkerEdgeColor',familyColors(k,:), ...
        'HandleVisibility','off');

end


xlabel( ...
    axB2, ...
    'Estimated target-specific transport bias, B^2');

ylabel( ...
    axB2, ...
    {'Selected transport', ...
    'weight, w'});


xlim(axB2,[0 1.04*xMaxB]);


yMaxB2 = max( ...
    [hiB2; yWeight(finiteB2)], ...
    [], ...
    'omitnan');


if ~isfinite(yMaxB2) || yMaxB2 <= 0
    yMaxB2 = 1;
end


ylim(axB2,[0 1.05*yMaxB2]);


f3_style_axes(axB2,fs(7.1));


%% ========================================================================
% c — DEVELOPMENT NAVIGATES THE EFFICIENCY-SAFETY FRONTIER
% ========================================================================

axC = axes( ...
    fig, ...
    'Position',slotC);


hold(axC,'on');


pointLabel = strings(0,1);
pointGain = zeros(0,1);
pointRegret = zeros(0,1);
pointStage = strings(0,1);


direct = mean(D3.u5b_state.direct_mae,'omitnan');


earlyColumns = { ...
    'label_free_mae', ...
    'sentinel_mae', ...
    'oracle_mae'};


earlyLabels = [ ...
    "Label-free", ...
    "Sentinel", ...
    "Oracle"];


for k = 1:3

    v = D3.u5b_state.(earlyColumns{k});


    pointLabel(end+1,1) = earlyLabels(k);


    pointGain(end+1,1) = ...
        100 * ...
        (direct - mean(v,'omitnan')) ...
        / direct;


    pointRegret(end+1,1) = ...
        max( ...
        v - D3.u5b_state.direct_mae, ...
        [], ...
        'omitnan');


    pointStage(end+1,1) = "Early candidates";

end


u5dMethods = [ ...
    "DELONG_NORMAL", ...
    "PAIRED_HOEFFDING", ...
    "USTAT_MCDIARMID"];


for k = 1:numel(u5dMethods)

    idx = find( ...
        string(D3.u5d_summary.method) == u5dMethods(k), ...
        1);


    if isempty(idx)
        continue;
    end


    pointLabel(end+1,1) = u5dMethods(k);


    pointGain(end+1,1) = ...
        100 * ...
        D3.u5d_summary.gain_vs_full_direct(idx);


    pointRegret(end+1,1) = ...
        D3.u5d_summary. ...
        worst_target_budget_regret_vs_full(idx);


    pointStage(end+1,1) = "Split hardening";

end


u5eMethods = [ ...
    "PC_DELONG", ...
    "PC_DELONG_VARGATE", ...
    "PC_PLUGIN", ...
    "PC_PLUGIN_VARGATE", ...
    "PC_USTAT_MCDIARMID"];


for k = 1:numel(u5eMethods)

    idx = find( ...
        string(D3.u5e_summary.method) == u5eMethods(k), ...
        1);


    if isempty(idx)
        continue;
    end


    pointLabel(end+1,1) = u5eMethods(k);


    pointGain(end+1,1) = ...
        100 * ...
        D3.u5e_summary.gain_vs_full_direct(idx);


    pointRegret(end+1,1) = ...
        D3.u5e_summary.worst_target_budget_regret(idx);


    pointStage(end+1,1) = "Pair-complete candidates";

end


idxFrozen = find( ...
    string(D3.u5f_audit.method) ...
    == "PC_PAIRED_HOEFFDING", ...
    1);


if ~isempty(idxFrozen)

    pointLabel(end+1,1) = "Frozen U5F";


    pointGain(end+1,1) = ...
        100 * ...
        D3.u5f_audit.pooled_gain(idxFrozen);


    pointRegret(end+1,1) = ...
        D3.u5f_audit. ...
        worst_target_budget_regret(idxFrozen);


    pointStage(end+1,1) = "Frozen / independent";

end


u6Direct = mean(D3.u6_state.direct_mae,'omitnan');


pointLabel(end+1,1) = "Independent U6";


pointGain(end+1,1) = ...
    100 * ...
    (u6Direct - mean(D3.u6_state.mae,'omitnan')) ...
    / u6Direct;


pointRegret(end+1,1) = ...
    max( ...
    D3.u6_state.mae_regret_vs_full_direct, ...
    [], ...
    'omitnan');


pointStage(end+1,1) = "Frozen / independent";


u7AUCrow = ...
    string(D4.u7_metric.metric) == "AUC";


if any(u7AUCrow)

    pointLabel(end+1,1) = "Sealed U7 AUC";


    pointGain(end+1,1) = ...
        100 * ...
        D4.u7_metric.relative_gain(u7AUCrow);


    pointRegret(end+1,1) = ...
        D4.u7_metric.worst_regret(u7AUCrow);


    pointStage(end+1,1) = "Confirmation";

end


stageNames = [ ...
    "Early candidates", ...
    "Split hardening", ...
    "Pair-complete candidates", ...
    "Frozen / independent", ...
    "Confirmation"];


stageLabels = { ...
    'Early candidates', ...
    'Split hardening', ...
    'Pair-complete candidates', ...
    'Frozen / independent', ...
    'Confirmation'};


stageMarkers = { ...
    'o', ...
    's', ...
    'D', ...
    'p', ...
    '^'};


stageSizes = [ ...
    38 ...
    40 ...
    40 ...
    60 ...
    55];


stageColors = [ ...
    0.1216 0.4667 0.7059; ...
    1.0000 0.4980 0.0549; ...
    0.1725 0.6275 0.1725; ...
    0.8392 0.1529 0.1569; ...
    0.4941 0.1843 0.5569];


stageHandles = gobjects(numel(stageNames),1);


for k = 1:numel(stageNames)

    m = pointStage == stageNames(k);


    stageHandles(k) = scatter( ...
        axC, ...
        pointGain(m), ...
        pointRegret(m), ...
        stageSizes(k), ...
        'filled', ...
        'Marker',stageMarkers{k}, ...
        'MarkerFaceColor',stageColors(k,:), ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.4, ...
        'DisplayName',stageLabels{k});

end


trajLabel = [ ...
    "Naive split"; ...
    "U5D DeLong"; ...
    "Pair-complete DeLong"; ...
    "U5D plugin"; ...
    "Frozen PC-Hoeffding"; ...
    "Independent U6"; ...
    "Sealed U7 AUC"];


trajGain = [ ...
    100 * cmdo_summary_value( ...
    D4.u5d_summary, ...
    'SPLIT_DIRECT', ...
    'gain_vs_full_direct'); ...
    100 * cmdo_summary_value( ...
    D4.u5d_summary, ...
    'DELONG_NORMAL', ...
    'gain_vs_full_direct'); ...
    100 * cmdo_summary_value( ...
    D4.u5e_summary, ...
    'PC_DELONG', ...
    'gain_vs_full_direct'); ...
    100 * cmdo_summary_value( ...
    D4.u5d_summary, ...
    'PLUGIN_FULL', ...
    'gain_vs_full_direct'); ...
    100 * cmdo_summary_value( ...
    D4.u5f_audit, ...
    'PC_PAIRED_HOEFFDING', ...
    'pooled_gain'); ...
    100 * ...
    (mean(D4.u6_state.direct_mae,'omitnan') - ...
    mean(D4.u6_state.mae,'omitnan')) ...
    / mean(D4.u6_state.direct_mae,'omitnan'); ...
    100 * ...
    D4.u7_metric.relative_gain( ...
    string(D4.u7_metric.metric)=="AUC")];


trajRegret = [ ...
    cmdo_summary_value( ...
    D4.u5d_summary, ...
    'SPLIT_DIRECT', ...
    'worst_target_budget_regret_vs_full'); ...
    cmdo_summary_value( ...
    D4.u5d_summary, ...
    'DELONG_NORMAL', ...
    'worst_target_budget_regret_vs_full'); ...
    cmdo_summary_value( ...
    D4.u5e_summary, ...
    'PC_DELONG', ...
    'worst_target_budget_regret'); ...
    cmdo_summary_value( ...
    D4.u5d_summary, ...
    'PLUGIN_FULL', ...
    'worst_target_budget_regret_vs_full'); ...
    cmdo_summary_value( ...
    D4.u5f_audit, ...
    'PC_PAIRED_HOEFFDING', ...
    'pooled_gain'); ...
    max( ...
    D4.u6_state.mae_regret_vs_full_direct, ...
    [], ...
    'omitnan'); ...
    D4.u7_metric.worst_regret( ...
    string(D4.u7_metric.metric)=="AUC")];


% IMPORTANT:
% preserve the source-code regret field for frozen U5F.
trajRegret(5) = ...
    cmdo_summary_value( ...
    D4.u5f_audit, ...
    'PC_PAIRED_HOEFFDING', ...
    'worst_target_budget_regret');


plot( ...
    axC, ...
    trajGain, ...
    trajRegret, ...
    '-', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.15, ...
    'HandleVisibility','off');


scatter( ...
    axC, ...
    trajGain, ...
    trajRegret, ...
    52, ...
    'o', ...
    'MarkerFaceColor','none', ...
    'MarkerEdgeColor',[0.10 0.10 0.10], ...
    'LineWidth',1.0, ...
    'HandleVisibility','off');


yline( ...
    axC, ...
    0, ...
    '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');


xline( ...
    axC, ...
    0, ...
    ':', ...
    'Color',[0.00 0.45 0.75], ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');


xlabel( ...
    axC, ...
    'Relative reduction in pooled MAE vs direct (%)');


ylabel( ...
    axC, ...
    'Worst target-budget regret');


allGain = [pointGain; trajGain];
allRegret = [pointRegret; trajRegret];


xSpan = max(allGain)-min(allGain);
ySpan = max(allRegret)-min(allRegret);


if ~isfinite(xSpan) || xSpan <= 0
    xSpan = 1;
end


if ~isfinite(ySpan) || ySpan <= 0
    ySpan = 1;
end


xlim( ...
    axC, ...
    [ ...
    min(-5.2,min(allGain)-0.06*xSpan), ...
    max(allGain)+0.08*xSpan]);


ylim( ...
    axC, ...
    [ ...
    min(-0.0025,min(allRegret)-0.10*ySpan), ...
    max(allRegret)+0.10*ySpan]);


drawnow;


xL = axC.XLim;
yL = axC.YLim;


dx = diff(xL);
dy = diff(yL);


calloutNames = [ ...
    "Naive split", ...
    "Pair-complete DeLong", ...
    "Frozen PC-Hoeffding", ...
    "Independent U6", ...
    "Sealed U7 AUC"];


calloutPos = [ ...
    0.055 0.91; ...
    0.55  0.60; ...
    0.27  0.19; ...
    0.375 0.055; ...
    0.645 0.025];


for q = 1:numel(calloutNames)

    k = find(trajLabel == calloutNames(q),1);


    if isempty(k)
        continue;
    end


    xText = ...
        xL(1) ...
        + calloutPos(q,1)*dx;


    yText = ...
        yL(1) ...
        + calloutPos(q,2)*dy;


    plot( ...
        axC, ...
        [trajGain(k) xText], ...
        [trajRegret(k) yText], ...
        '-', ...
        'Color',[0.52 0.52 0.52], ...
        'LineWidth',0.55, ...
        'HandleVisibility','off');


    scatter( ...
        axC, ...
        trajGain(k), ...
        trajRegret(k), ...
        18, ...
        'o', ...
        'MarkerFaceColor','w', ...
        'MarkerEdgeColor',[0.15 0.15 0.15], ...
        'LineWidth',0.7, ...
        'HandleVisibility','off');


    text( ...
        axC, ...
        xText, ...
        yText, ...
        calloutNames(q), ...
        'FontName','Arial', ...
        'FontSize',fs(6.4), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'BackgroundColor','w', ...
        'EdgeColor','none', ...
        'Margin',0.45, ...
        'Clipping','off');

end


legend( ...
    axC, ...
    stageHandles, ...
    stageLabels, ...
    'Location','northoutside', ...
    'NumColumns',3, ...
    'Box','off', ...
    'FontSize',fs(6.2));


grid(axC,'on');
axC.GridAlpha = 0.11;


f3_style_axes(axC,fs(7.3));


%% ========================================================================
% d — PAIR COMPLETENESS
% ========================================================================

axD = axes( ...
    fig, ...
    'Position',slotD);


hold(axD,'on');


axis(axD,[0 1 0 1]);
axis(axD,'off');


text( ...
    axD, ...
    0.25, ...
    0.88, ...
    'Naive split', ...
    'HorizontalAlignment','center', ...
    'FontWeight','bold', ...
    'FontSize',fs(9.5));


text( ...
    axD, ...
    0.75, ...
    0.88, ...
    'Pair-complete construction', ...
    'HorizontalAlignment','center', ...
    'FontWeight','bold', ...
    'FontSize',fs(9.5));


f3_draw_pair_matrix( ...
    axD, ...
    0.06, ...
    0.43, ...
    0.37, ...
    0.34, ...
    false, ...
    FONT_SCALE);


f3_draw_pair_matrix( ...
    axD, ...
    0.57, ...
    0.43, ...
    0.37, ...
    0.34, ...
    true, ...
    FONT_SCALE);


text( ...
    axD, ...
    0.25, ...
    0.27, ...
    { ...
    'Cross-fold pairs are discarded', ...
    '\Rightarrow positive certification tax'}, ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',fs(8.2));


text( ...
    axD, ...
    0.755, ...
    0.285, ...
    ['$D_{\mathrm{full}} = ' ...
    '\frac{\sum_{g,h\in\{A,B\}} n_{P_g}n_{N_h}D_{gh}}' ...
    '{\sum_{g,h\in\{A,B\}}n_{P_g}n_{N_h}}$'], ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',fs(8.8));


text( ...
    axD, ...
    0.755, ...
    0.15, ...
    { ...
    'Observation-disjoint sensing:', ...
    'AA \leftrightarrow BB,  AB \leftrightarrow BA', ...
    'All four pair blocks are retained.'}, ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',fs(7.4));


%% ========================================================================
% e — EXACT FALLBACK
% ========================================================================

axE = axes( ...
    fig, ...
    'Position',slotE);


hold(axE,'on');


u7AUC = ...
    D4.u7_rep( ...
    string(D4.u7_rep.metric)=="AUC",:);


scatter( ...
    axE, ...
    D4.u6_rep.direct_full_auc, ...
    D4.u6_rep.direct_full_auc, ...
    13, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor',[0.0000 0.4470 0.7410], ...
    'MarkerEdgeColor','none', ...
    'MarkerFaceAlpha',0.16, ...
    'HandleVisibility','off');


scatter( ...
    axE, ...
    u7AUC.direct, ...
    u7AUC.direct, ...
    15, ...
    '^', ...
    'filled', ...
    'MarkerFaceColor',[0.8500 0.3250 0.0980], ...
    'MarkerEdgeColor','none', ...
    'MarkerFaceAlpha',0.16, ...
    'HandleVisibility','off');


hIdentity = plot( ...
    axE, ...
    [0 1], ...
    [0 1], ...
    '--', ...
    'Color',[0.15 0.15 0.15], ...
    'LineWidth',1.15, ...
    'DisplayName','Identity, y = x');


hU6 = scatter( ...
    axE, ...
    NaN, ...
    NaN, ...
    36, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor',[0.0000 0.4470 0.7410], ...
    'DisplayName',sprintf('U6 (n=%d)',height(D4.u6_rep)));


hU7 = scatter( ...
    axE, ...
    NaN, ...
    NaN, ...
    40, ...
    '^', ...
    'filled', ...
    'MarkerFaceColor',[0.8500 0.3250 0.0980], ...
    'DisplayName',sprintf('U7 AUC (n=%d)',height(u7AUC)));


xlim(axE,[-0.01 1.01]);
ylim(axE,[-0.01 1.01]);


axis(axE,'square');


xlabel(axE,'Full direct AUC');


ylabel( ...
    axE, ...
    'Pair-complete estimate at w = 0');


legend( ...
    axE, ...
    [hU6 hU7 hIdentity], ...
    'Location','northwest', ...
    'Box','off', ...
    'FontSize',fs(6.5));


grid(axE,'on');

axE.GridAlpha = 0.13;


f3_style_axes(axE,fs(7.3));


maxResidual = max( ...
    [ ...
    abs(D4.u6_rep.identity_residual); ...
    abs(u7AUC.identity_residual)], ...
    [], ...
    'omitnan');


text( ...
    axE, ...
    0.97, ...
    0.055, ...
    sprintf('max|r| = %.2e',maxResidual), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontWeight','bold', ...
    'FontSize',fs(7), ...
    'BackgroundColor','w', ...
    'Margin',1);


%% ========================================================================
% f — COMPLETE REGRET DISTRIBUTIONS
% ========================================================================

axF = axes( ...
    fig, ...
    'Position',slotF);


hold(axF,'on');


vals = { ...
    D4.u5d_state.mae_regret_vs_full_direct( ...
    string(D4.u5d_state.method)=="SPLIT_DIRECT"), ...
    D4.u5d_state.mae_regret_vs_full_direct( ...
    string(D4.u5d_state.method)=="DELONG_NORMAL"), ...
    D4.u5e_state.mae_regret_vs_full_direct( ...
    string(D4.u5e_state.method)=="PC_DELONG"), ...
    D4.u5e_state.mae_regret_vs_full_direct( ...
    string(D4.u5e_state.method)=="PC_PAIRED_HOEFFDING"), ...
    D4.u6_state.mae_regret_vs_full_direct, ...
    D4.u7_state.regret( ...
    string(D4.u7_state.metric)=="AUC")};


labelsF = { ...
    sprintf('Naive\nsplit'), ...
    sprintf('U5D\nDeLong'), ...
    sprintf('Pair-complete\nDeLong'), ...
    sprintf('Frozen PC-\nHoeffding'), ...
    sprintf('Independent\nU6'), ...
    sprintf('Sealed\nU7 AUC')};


colorsF = [ ...
    0.1216 0.4667 0.7059; ...
    1.0000 0.4980 0.0549; ...
    0.1725 0.6275 0.1725; ...
    0.8392 0.1529 0.1569; ...
    0.4941 0.1843 0.5569; ...
    0.4667 0.6745 0.1882];


for k = 1:numel(vals)

    v = double(vals{k});
    v = v(isfinite(v));


    f3_violin( ...
        axF, ...
        k, ...
        v, ...
        colorsF(k,:), ...
        0.29);


    jitter = 0.042*randn(size(v));


    scatter( ...
        axF, ...
        k+jitter, ...
        v, ...
        10, ...
        colorsF(k,:), ...
        'filled', ...
        'MarkerEdgeColor','none', ...
        'MarkerFaceAlpha',0.34);


    medV = median(v,'omitnan');


    plot( ...
        axF, ...
        [k-0.21 k+0.21], ...
        [medV medV], ...
        'k-', ...
        'LineWidth',1.8);


    maxV = max(v,[],'omitnan');


    text( ...
        axF, ...
        k, ...
        min(maxV+0.00055,0.0154), ...
        sprintf('worst %.5f',maxV), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontName','Arial', ...
        'FontSize',fs(5.8), ...
        'BackgroundColor','w', ...
        'Margin',0.5);

end


yline( ...
    axF, ...
    0, ...
    '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',0.8);


xlim(axF,[0.45 numel(vals)+0.55]);

ylim(axF,[-0.016 0.016]);


xticks(axF,1:numel(vals));

xticklabels(axF,labelsF);


ylabel(axF,'Target-budget regret');


grid(axF,'on');

axF.XGrid = 'off';

axF.GridAlpha = 0.10;


axF.XAxis.TickLabelInterpreter = 'none';


f3_style_axes(axF,fs(7.0));


%% ========================================================================
% COMMAND-WINDOW AUDIT
% ========================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf(' Figure 3 direct-render audit\n');
fprintf('============================================================\n');

fprintf('No Legacy Figure3/Figure4 source figures were rendered.\n');


fprintf( ...
    'Panel a: %d prospective targets.\n', ...
    numel(targetOrder));


fprintf( ...
    'Panel b: %d U5B states; shared bias coordinate.\n', ...
    height(D3.u5b_state));


fprintf( ...
    'Panel c: %d candidate-landscape points + %d trajectory milestones.\n', ...
    numel(pointGain), ...
    numel(trajGain));


fprintf( ...
    'Panel e: U6=%d, U7-AUC=%d, max identity residual=%.3g.\n', ...
    height(D4.u6_rep), ...
    height(u7AUC), ...
    maxResidual);


fprintf('============================================================\n');


%% ========================================================================
% EXPORT
% ========================================================================

drawnow;


baseName = ...
    'Figure3_Falsification_Hardening_Final_6Panel';


exportgraphics( ...
    fig, ...
    fullfile(outputDir,[baseName '.png']), ...
    'Resolution',300, ...
    'BackgroundColor','white');


exportgraphics( ...
    fig, ...
    fullfile(outputDir,[baseName '.pdf']), ...
    'ContentType','vector', ...
    'BackgroundColor','white');


try

    exportgraphics( ...
        fig, ...
        fullfile(outputDir,[baseName '.svg']), ...
        'ContentType','vector', ...
        'BackgroundColor','white');

catch
end


savefig( ...
    fig, ...
    fullfile(outputDir,[baseName '.fig']));


fprintf('\nFinal Figure 3 written to:\n%s\n',outputDir);

end


%% =========================================================================
% LOCAL HELPERS
% =========================================================================

function f3_style_axes(ax,fontSize)

set( ...
    ax, ...
    'Box','off', ...
    'FontName','Arial', ...
    'FontSize',fontSize, ...
    'LineWidth',0.8, ...
    'TickDir','out', ...
    'Layer','top');

end


function f3_draw_pair_matrix( ...
    ax,x0,y0,width,height,pairComplete,fontScale)


if nargin < 7 || isempty(fontScale)
    fontScale = 1;
end


cellWidth = width/2;
cellHeight = height/2;


labels = { ...
    'P_A \times N_A', ...
    'P_A \times N_B', ...
    'P_B \times N_A', ...
    'P_B \times N_B'};


for q = 1:4

    col = mod(q-1,2);
    row = floor((q-1)/2);


    kept = ...
        pairComplete ...
        || q==1 ...
        || q==4;


    if kept

        faceColor = [0.88 0.96 0.90];
        statusText = 'kept';

    else

        faceColor = [1.00 0.90 0.90];
        statusText = 'discarded';

    end


    x = x0 + col*cellWidth;


    y = ...
        y0 ...
        + (1-row)*cellHeight;


    rectangle( ...
        ax, ...
        'Position',[ ...
        x y cellWidth cellHeight], ...
        'FaceColor',faceColor, ...
        'EdgeColor',[0.35 0.35 0.35], ...
        'LineWidth',0.7);


    text( ...
        ax, ...
        x+0.5*cellWidth, ...
        y+0.62*cellHeight, ...
        labels{q}, ...
        'Interpreter','tex', ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontSize',8.2*fontScale);


    text( ...
        ax, ...
        x+0.5*cellWidth, ...
        y+0.28*cellHeight, ...
        statusText, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontSize',7.2*fontScale, ...
        'FontWeight','bold');

end

end


function f3_violin( ...
    ax,xCenter,values,faceColor,maxHalfWidth)


values = double(values(:));
values = values(isfinite(values));


if numel(values) < 2
    return;
end


vMin = min(values);
vMax = max(values);


if vMax <= vMin

    vMin = vMin-1e-6;
    vMax = vMax+1e-6;

end


yGrid = linspace(vMin,vMax,180)';


sigmaV = std(values,0);


bandwidth = ...
    1.06 ...
    * sigmaV ...
    * numel(values)^(-1/5);


if ~isfinite(bandwidth) || bandwidth <= 0

    bandwidth = ...
        max( ...
        (vMax-vMin)/20, ...
        eps);

end


z = ...
    (yGrid-values') ...
    ./ bandwidth;


density = ...
    mean(exp(-0.5*z.^2),2) ...
    ./ (bandwidth*sqrt(2*pi));


maxDensity = max(density);


if ~isfinite(maxDensity) || maxDensity <= 0
    return;
end


halfWidth = ...
    maxHalfWidth ...
    * density ...
    / maxDensity;


patch( ...
    ax, ...
    [ ...
    xCenter-halfWidth; ...
    flipud(xCenter+halfWidth)], ...
    [ ...
    yGrid; ...
    flipud(yGrid)], ...
    faceColor, ...
    'FaceAlpha',0.26, ...
    'EdgeColor','none', ...
    'HandleVisibility','off');

end
