function Figure5_PreU8
%FIGURE5 Independent cross-domain confirmation of the frozen observer.
%
% Canonical content:
%   a  Relative improvement for all 16 independent U6 targets
%   b  Same-budget baseline versus frozen observer
%   c  Bias observability across the sealed reserve
%   d  Safety across the complete budget trajectory
%
% Selected labels in panel c can be dragged and saved.

close all;

%% User option
MANUAL_PANEL_C_LABELS = ~strcmp(getenv('CMDO_BATCH_MODE'), '1');

%% Project and canonical records
scriptDir = fileparts(mfilename('fullpath'));

if ~isempty(scriptDir)
    addpath(genpath(scriptDir));
end

cfg = cmdo_config('Figure5');
D = cmdo_load_all(cfg);

rng(20260728, 'twister');

outDir = cfg.outputDir;

if ~exist(outDir, 'dir')
    mkdir(outDir);
end

%% Figure canvas
fig = figure( ...
    'Position', [25 25 900 880], ...
    'Color', 'w', ...
    'Renderer', 'painters', ...
    'Name', 'CMDO Figure 5', ...
    'NumberTitle', 'off');

tl = tiledlayout( ...
    fig, ...
    2, 2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

title(tl, ...
    'Independent confirmation of the frozen observer', ...
    'FontWeight', 'bold', ...
    'FontSize', 17);

axA = nexttile(tl, 1);
axB = nexttile(tl, 2);
axC = nexttile(tl, 3);
axD = nexttile(tl, 4);

%% Canonical target ordering
% Group by family, then sort by relative improvement within each family.

Traw = D.u6_target;

familyOrder = [ ...
    "ACS_PUBLIC_COVERAGE_2024", ...
    "MEDICAL_DERMOSCOPY", ...
    "NATURAL_IMAGE"];

familyLabels = { ...
    'Population transfer', ...
    'Medical acquisition shifts', ...
    'Natural-image shifts'};

familyColors = [ ...
    0.1216 0.4667 0.7059; ...
    1.0000 0.4980 0.0549; ...
    0.8392 0.1529 0.1569];

T = Traw([],:);

for f = 1:numel(familyOrder)

    Tf = Traw( ...
        string(Traw.family) == familyOrder(f), :);

    relativeGainF = ...
        100 .* Tf.gain_vs_full_direct ./ Tf.direct_mae;

    [~, orderF] = sort(relativeGainF, 'descend');

    T = [T; Tf(orderF,:)]; %#ok<AGROW>
end

nTargets = height(T);

targetNames = strings(nTargets, 1);
targetColors = zeros(nTargets, 3);

for i = 1:nTargets

    targetNames(i) = ...
        f5_short_target(string(T.target(i)));

    familyIndex = find( ...
        familyOrder == string(T.family(i)), ...
        1, ...
        'first');

    targetColors(i,:) = familyColors(familyIndex,:);
end

relativeGain = ...
    100 .* T.gain_vs_full_direct ./ T.direct_mae;

%% ========================================================================
% a — all independent targets improved
% ========================================================================
hold(axA, 'on');
cmdo_safe_panel_letter(axA, 'a');

title(axA, ...
    'All 16 unseen targets improved', ...
    'FontWeight', 'bold', ...
    'FontSize', 11.5);

barA = barh( ...
    axA, ...
    1:nTargets, ...
    relativeGain, ...
    0.68, ...
    'FaceColor', 'flat', ...
    'EdgeColor', 'none');

barA.CData = targetColors;

set(axA, 'YDir', 'reverse');

yticks(axA, 1:nTargets);
yticklabels(axA, targetNames);

xlabel(axA, 'Relative AUC MAE reduction (%)');

xMaxA = max(relativeGain);

if ~isfinite(xMaxA) || xMaxA <= 0
    xMaxA = 1;
end

xlim(axA, [0, 1.14 * xMaxA]);

for i = 1:nTargets

    text( ...
        axA, ...
        relativeGain(i) + 0.025 * xMaxA, ...
        i, ...
        sprintf('%.2f%%', relativeGain(i)), ...
        'FontName', 'Arial', ...
        'FontSize', 7.7, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'middle');
end

% Family legend proxies.
hFamilyA = gobjects(3,1);

for f = 1:3

    hFamilyA(f) = scatter( ...
        axA, ...
        NaN, NaN, ...
        62, ...
        's', ...
        'filled', ...
        'MarkerFaceColor', familyColors(f,:), ...
        'MarkerEdgeColor', familyColors(f,:), ...
        'DisplayName', familyLabels{f});
end

legend( ...
    axA, ...
    hFamilyA, ...
    familyLabels, ...
    'Location', 'southoutside', ...
    'NumColumns', 3, ...
    'Box', 'off', ...
    'FontSize', 8);

set(axA, ...
    'XGrid', 'on', ...
    'YGrid', 'off');

axA.GridAlpha = 0.12;

cmdo_safe_apply_axes_style(axA);
axA.YAxis.TickLabelInterpreter = 'none';

%% ========================================================================
% b — same-budget efficiency
% ========================================================================
hold(axB, 'on');
cmdo_safe_panel_letter(axB, 'b');

title(axB, ...
    'Same-budget efficiency', ...
    'FontWeight', 'bold', ...
    'FontSize', 11.5);

barB = bar( ...
    axB, ...
    [T.direct_mae, T.mae], ...
    'grouped');

barB(1).FaceColor = [0.1216 0.4667 0.7059];
barB(1).EdgeColor = 'none';
barB(1).DisplayName = 'Same-budget full-direct estimator';

barB(2).FaceColor = [1.0000 0.4980 0.0549];
barB(2).EdgeColor = 'none';
barB(2).DisplayName = 'Frozen observer';

xticks(axB, 1:nTargets);
xticklabels(axB, targetNames);
xtickangle(axB, 55);

ylabel(axB, 'Same-budget AUC MAE');

yMaxB = max([T.direct_mae; T.mae]);

if ~isfinite(yMaxB) || yMaxB <= 0
    yMaxB = 1;
end

ylim(axB, [0, 1.13 * yMaxB]);

% Relative reduction above each pair.
for i = 1:nTargets

    pairTop = max(T.direct_mae(i), T.mae(i));

    text( ...
    axB, ...
    i, ...
    pairTop + 0.014 * yMaxB, ...
    sprintf('-%.1f%%', relativeGain(i)), ...
    'Rotation', 55, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'bottom', ...
    'FontName', 'Arial', ...
    'FontSize', 7.2, ...
    'FontWeight', 'bold', ...
    'Color', [0.05 0.58 0.26], ...
    'Clipping', 'off');
end

legend( ...
    axB, ...
    'Location', 'northwest', ...
    'NumColumns', 2, ...
    'Box', 'off', ...
    'FontSize', 8.5);

set(axB, ...
    'XGrid', 'off', ...
    'YGrid', 'on');

axB.GridAlpha = 0.10;

cmdo_safe_apply_axes_style(axB);
axB.XAxis.TickLabelInterpreter = 'none';

%% ========================================================================
% c — bias observability in the sealed reserve
% ========================================================================
hold(axC, 'on');
cmdo_safe_panel_letter(axC, 'c');

maxBudget = max(D.u6_state.budget);

M = D.u6_state( ...
    D.u6_state.budget == maxBudget, :);

xC = double(M.mean_sensor_abs_gap);
yC = double(M.transport_abs_error);

familyC = string(M.family);

rhoC = cmdo_spearman(xC, yC);
pC = f5_spearman_pvalue(rhoC, numel(xC));

title(axC, ...
    sprintf('Bias observability in reserve (\\rho = %.3f)', rhoC), ...
    'FontWeight', 'bold', ...
    'FontSize', 11.5);

% Linear regression and confidence interval.
validC = isfinite(xC) & isfinite(yC);

xFit = xC(validC);
yFit = yC(validC);

nFit = numel(xFit);

design = [ones(nFit,1), xFit];
beta = design \ yFit;

xGrid = linspace( ...
    min(xFit), ...
    max(xFit), ...
    250)';

yGrid = beta(1) + beta(2) .* xGrid;

residual = yFit - design * beta;
degreesFreedom = max(nFit - 2, 1);

residualVariance = ...
    sum(residual.^2) / degreesFreedom;

xMean = mean(xFit);
sxx = sum((xFit - xMean).^2);

if ~isfinite(sxx) || sxx <= 0
    sxx = eps;
end

standardError = sqrt( ...
    residualVariance .* ...
    (1/nFit + (xGrid - xMean).^2 ./ sxx));

tCritical = f5_tcritical95(degreesFreedom);

lowerCI = yGrid - tCritical .* standardError;
upperCI = yGrid + tCritical .* standardError;

fill( ...
    axC, ...
    [xGrid; flipud(xGrid)], ...
    [lowerCI; flipud(upperCI)], ...
    [0.70 0.70 0.70], ...
    'FaceAlpha', 0.22, ...
    'EdgeColor', 'none', ...
    'HandleVisibility', 'off');

plot( ...
    axC, ...
    xGrid, ...
    yGrid, ...
    'k-', ...
    'LineWidth', 1.7, ...
    'HandleVisibility', 'off');

% Family-coloured points.
hFamilyC = gobjects(3,1);

for f = 1:3

    m = familyC == familyOrder(f);

    hFamilyC(f) = scatter( ...
        axC, ...
        xC(m), ...
        yC(m), ...
        58, ...
        'o', ...
        'filled', ...
        'MarkerFaceColor', familyColors(f,:), ...
        'MarkerEdgeColor', 'w', ...
        'LineWidth', 0.65, ...
        'DisplayName', familyLabels{f});
end

xlabel(axC, 'Paired-sensor discrepancy');
ylabel(axC, 'True transport absolute error');

xSpanC = max(xC) - min(xC);
ySpanC = max(yC) - min(yC);

if ~isfinite(xSpanC) || xSpanC <= 0
    xSpanC = 1;
end

if ~isfinite(ySpanC) || ySpanC <= 0
    ySpanC = 1;
end

xlim(axC, [ ...
    min(xC) - 0.07 * xSpanC, ...
    max(xC) + 0.07 * xSpanC]);

ylim(axC, [ ...
    max(0, min(yC) - 0.10 * ySpanC), ...
    max(yC) + 0.12 * ySpanC]);

legend( ...
    axC, ...
    hFamilyC, ...
    familyLabels, ...
    'Location', 'northwest', ...
    'Box', 'off', ...
    'FontSize', 8.2);

text( ...
    axC, ...
    0.97, ...
    0.08, ...
    sprintf('\\rho = %.3f', rhoC), ...
    'Units', 'normalized', ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom', ...
    'FontName', 'Arial', ...
    'FontSize', 8.5, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', 'w', ...
    'EdgeColor', 'none', ...
    'Margin', 2);

set(axC, ...
    'XGrid', 'on', ...
    'YGrid', 'on');

axC.GridAlpha = 0.12;

cmdo_safe_apply_axes_style(axC);

% Selected draggable labels.
selectedTargetsC = [ ...
    "ACS_PUBLIC_COVERAGE_2024_IL"; ...
    "DERMA_CLEAN"; ...
    "DERMA_GAMMA_1_4"; ...
    "CIFAR_CAT_DOG_BLUR_1_2"; ...
    "DERMA_DOWNSAMPLE_14"];

selectedLabelsC = [ ...
    "ACS-IL"; ...
    "Derma clean"; ...
    "Derma gamma"; ...
    "CIFAR blur"; ...
    "Derma downsample"];

defaultLabelPosC = NaN(numel(selectedTargetsC), 2);

labelOffsetsC = [ ...
     0.045,  0.045; ...
     0.055, -0.035; ...
    -0.050,  0.050; ...
    -0.055,  0.045; ...
     0.035,  0.050];

anchorC = NaN(numel(selectedTargetsC), 2);

for k = 1:numel(selectedTargetsC)

    idx = find( ...
        string(M.target) == selectedTargetsC(k), ...
        1, ...
        'first');

    if isempty(idx)
        error( ...
            'Figure5:MissingTarget', ...
            'Panel-c target not found: %s', ...
            char(selectedTargetsC(k)));
    end

    anchorC(k,:) = [xC(idx), yC(idx)];

    defaultLabelPosC(k,:) = [ ...
        xC(idx) + labelOffsetsC(k,1) * xSpanC, ...
        yC(idx) + labelOffsetsC(k,2) * ySpanC];
end

labelPosFileC = fullfile( ...
    outDir, ...
    'Figure5_panelC_label_positions.mat');

labelPosC = defaultLabelPosC;

if exist(labelPosFileC, 'file')

    savedLabelDataC = load(labelPosFileC);

    if isfield(savedLabelDataC, 'labelPosC') && ...
            isequal(size(savedLabelDataC.labelPosC), ...
            size(defaultLabelPosC))

        labelPosC = savedLabelDataC.labelPosC;
    end
end

labelHandlesC = gobjects(numel(selectedTargetsC), 1);
leaderHandlesC = gobjects(numel(selectedTargetsC), 1);

for k = 1:numel(selectedTargetsC)

    leaderHandlesC(k) = plot( ...
        axC, ...
        [anchorC(k,1), labelPosC(k,1)], ...
        [anchorC(k,2), labelPosC(k,2)], ...
        '-', ...
        'Color', [0.30 0.30 0.30], ...
        'LineWidth', 0.65, ...
        'HandleVisibility', 'off');

    labelHandlesC(k) = text( ...
        axC, ...
        labelPosC(k,1), ...
        labelPosC(k,2), ...
        selectedLabelsC(k), ...
        'FontName', 'Arial', ...
        'FontSize', 7.8, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'BackgroundColor', 'w', ...
        'EdgeColor', 'none', ...
        'Margin', 1, ...
        'Clipping', 'off', ...
        'PickableParts', 'all', ...
        'HitTest', 'on');

    setappdata( ...
        labelHandlesC(k), ...
        'AnchorPoint', ...
        anchorC(k,:));

    setappdata( ...
        labelHandlesC(k), ...
        'LeaderHandle', ...
        leaderHandlesC(k));

    labelHandlesC(k).ButtonDownFcn = ...
        @(src, ~) f5_start_label_drag(src, fig);
end

%% ========================================================================
% d — safety across the full budget trajectory
% ========================================================================
hold(axD, 'on');
cmdo_safe_panel_letter(axD, 'd');

title(axD, ...
    'Safety across outcome budgets', ...
    'FontWeight', 'bold', ...
    'FontSize', 11.5);

budgetOrder = sort(unique(D.u6_state.budget));

violinColor = [1.0000 0.4980 0.0549];

for i = 1:numel(budgetOrder)

    budgetValue = budgetOrder(i);

    valuesD = double( ...
        D.u6_state.mae_regret_vs_full_direct( ...
        D.u6_state.budget == budgetValue));

    valuesD = valuesD(isfinite(valuesD));

    f5_violin( ...
        axD, ...
        i, ...
        valuesD, ...
        violinColor, ...
        0.34);

    jitterD = 0.045 .* randn(size(valuesD));

    scatter( ...
        axD, ...
        i + jitterD, ...
        valuesD, ...
        13, ...
        violinColor, ...
        'filled', ...
        'MarkerEdgeColor', 'none', ...
        'MarkerFaceAlpha', 0.72);

    medianD = median(valuesD, 'omitnan');

    plot( ...
        axD, ...
        [i - 0.22, i + 0.22], ...
        [medianD, medianD], ...
        'k-', ...
        'LineWidth', 2);
end

yline( ...
    axD, ...
    0, ...
    '--', ...
    'Color', [0.00 0.45 0.75], ...
    'LineWidth', 1.0);

xlim(axD, [0.45, numel(budgetOrder) + 0.55]);

xticks(axD, 1:numel(budgetOrder));
xticklabels(axD, string(budgetOrder));

xlabel(axD, 'Outcome budget');
ylabel(axD, 'Target-level regret');

yMinD = min(D.u6_state.mae_regret_vs_full_direct, [], 'omitnan');

ylim(axD, [ ...
    min(-0.010, 1.05 * yMinD), ...
    0.0004]);

set(axD, ...
    'XGrid', 'off', ...
    'YGrid', 'on');

axD.GridAlpha = 0.10;

cmdo_safe_apply_axes_style(axD);

%% Canonical U6 summary for panel d
pooledObserverMAE = mean(D.u6_state.mae, 'omitnan');
pooledDirectMAE = mean(D.u6_state.direct_mae, 'omitnan');

pooledGain = ...
    100 .* ...
    (pooledDirectMAE - pooledObserverMAE) ...
    ./ pooledDirectMAE;

worstState = max( ...
    D.u6_state.mae_regret_vs_full_direct, ...
    [], ...
    'omitnan');

familyNames = unique(string(Traw.family), 'stable');
familyRegret = NaN(numel(familyNames),1);

for f = 1:numel(familyNames)

    m = string(Traw.family) == familyNames(f);

    familyRegret(f) = ...
        mean(Traw.mae(m), 'omitnan') ...
        - mean(Traw.direct_mae(m), 'omitnan');
end

worstFamily = max(familyRegret, [], 'omitnan');

meanWeight = mean( ...
    D.u6_state.mean_weight, ...
    'omitnan');

maximumIdentityResidual = max( ...
    D.u6_state.maximum_identity_residual, ...
    [], ...
    'omitnan');

summaryString = sprintf( ...
    ['Worst state = %.6f\n' ...
     'Worst family = %.6f\n' ...
     'Mean weight = %.4f\n' ...
     'Exact fallback residual = %.0g'], ...
    worstState, ...
    worstFamily, ...
    meanWeight, ...
    maximumIdentityResidual);

text( ...
    axD, ...
    0.97, ...
    0.08, ...
    summaryString, ...
    'Units', 'normalized', ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom', ...
    'FontName', 'Arial', ...
    'FontSize', 8.2, ...
    'BackgroundColor', 'w', ...
    'EdgeColor', [0.65 0.65 0.65], ...
    'Margin', 5);

%% Canonical-data audit
fprintf('\nFigure 5 canonical-data audit:\n');

fprintf( ...
    '  Targets = %d; positive targets = %d; families = %d\n', ...
    nTargets, ...
    nnz(relativeGain > 0), ...
    numel(familyOrder));

fprintf( ...
    '  Relative target improvement range = %.3f%% to %.3f%%\n', ...
    min(relativeGain), ...
    max(relativeGain));

fprintf( ...
    '  Pooled MAE = %.9f; direct = %.9f; gain = %.6f%%\n', ...
    pooledObserverMAE, ...
    pooledDirectMAE, ...
    pooledGain);

fprintf( ...
    '  Bias observability rho = %.9f; p = %.6g\n', ...
    rhoC, ...
    pC);

fprintf( ...
    '  Budgets = %s; worst state regret = %.9f\n', ...
    sprintf('%d ', budgetOrder), ...
    worstState);

%% Optional manual adjustment of panel-c labels
drawnow;

if MANUAL_PANEL_C_LABELS && usejava('desktop')

    instructionBox = annotation( ...
        fig, ...
        'textbox', ...
        [0.285 0.006 0.420 0.032], ...
        'String', ...
        'Drag the selected labels in panel c, then click Save label positions', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Arial', ...
        'FontSize', 9, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [1.00 1.00 0.88], ...
        'EdgeColor', [0.65 0.65 0.45], ...
        'FitBoxToText', 'off');

    finishButton = uicontrol( ...
        fig, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.730 0.007 0.170 0.034], ...
        'String', 'Save label positions', ...
        'FontSize', 9, ...
        'FontWeight', 'bold', ...
        'Callback', @(~, ~) uiresume(fig));

    uiwait(fig);

    if ~isgraphics(fig)
        return;
    end

    labelPosC = NaN(numel(labelHandlesC), 2);

    for k = 1:numel(labelHandlesC)

        positionValue = labelHandlesC(k).Position;
        labelPosC(k,:) = positionValue(1:2);
    end

    save( ...
        labelPosFileC, ...
        'labelPosC', ...
        'selectedTargetsC', ...
        'selectedLabelsC');

    if isgraphics(finishButton)
        delete(finishButton);
    end

    if isgraphics(instructionBox)
        delete(instructionBox);
    end
end

%% Export
drawnow;

cmdo_safe_save_figure( ...
    fig, ...
    cfg, ...
    'Figure5_U6_Independent_Confirmation');

end


function label = f5_short_target(target)
% Convert canonical target identifiers into compact readable labels.

target = string(target);

switch target

    case "ACS_PUBLIC_COVERAGE_2024_FL"
        label = "ACS-FL";

    case "ACS_PUBLIC_COVERAGE_2024_IL"
        label = "ACS-IL";

    case "ACS_PUBLIC_COVERAGE_2024_OH"
        label = "ACS-OH";

    case "ACS_PUBLIC_COVERAGE_2024_PA"
        label = "ACS-PA";

    case "ACS_PUBLIC_COVERAGE_2024_TX"
        label = "ACS-TX";

    case "DERMA_CLEAN"
        label = "Derma clean";

    case "DERMA_NOISE_0_08"
        label = "Derma noise";

    case "DERMA_BLUR_1_0"
        label = "Derma blur";

    case "DERMA_GAMMA_1_4"
        label = "Derma gamma";

    case "DERMA_JPEG_35"
        label = "Derma JPEG";

    case "DERMA_DOWNSAMPLE_14"
        label = "Derma downsample";

    case "CIFAR_CAT_DOG_CLEAN"
        label = "CIFAR clean";

    case "CIFAR_CAT_DOG_GRAYSCALE"
        label = "CIFAR grayscale";

    case "CIFAR_CAT_DOG_NOISE_0_10"
        label = "CIFAR noise";

    case "CIFAR_CAT_DOG_BLUR_1_2"
        label = "CIFAR blur";

    case "CIFAR_CAT_DOG_JPEG_30"
        label = "CIFAR JPEG";

    otherwise
        label = replace(target, "_", " ");
end

end


function pValue = f5_spearman_pvalue(rhoValue, sampleCount)
% Two-sided Student-t approximation for Spearman correlation.
% For the canonical U6 data this reproduces p = 1.10059e-06.

if sampleCount <= 2 || ~isfinite(rhoValue)
    pValue = NaN;
    return;
end

rhoValue = max(min(rhoValue, 1 - eps), -1 + eps);

degreesFreedom = sampleCount - 2;

tStatistic = ...
    abs(rhoValue) .* ...
    sqrt(degreesFreedom ./ (1 - rhoValue.^2));

betaArgument = ...
    degreesFreedom ./ ...
    (degreesFreedom + tStatistic.^2);

pValue = betainc( ...
    betaArgument, ...
    degreesFreedom / 2, ...
    0.5);

end


function criticalValue = f5_tcritical95(degreesFreedom)
% Two-sided 95% Student-t critical value without Statistics Toolbox.

if degreesFreedom <= 0
    criticalValue = 1.96;
    return;
end

betaValue = betaincinv( ...
    0.05, ...
    degreesFreedom / 2, ...
    0.5);

criticalValue = sqrt( ...
    degreesFreedom .* ...
    (1 - betaValue) ./ betaValue);

end


function f5_violin(ax, xCenter, values, faceColor, maxHalfWidth)
% Toolbox-independent Gaussian KDE violin.

values = double(values(:));
values = values(isfinite(values));

if numel(values) < 2
    return;
end

valueMinimum = min(values);
valueMaximum = max(values);

if valueMaximum <= valueMinimum
    valueMinimum = valueMinimum - 1e-6;
    valueMaximum = valueMaximum + 1e-6;
end

yGrid = linspace( ...
    valueMinimum, ...
    valueMaximum, ...
    180)';

valueSigma = std(values, 0);

bandwidth = ...
    1.06 .* valueSigma .* numel(values).^(-1/5);

if ~isfinite(bandwidth) || bandwidth <= 0
    bandwidth = max( ...
        (valueMaximum - valueMinimum) / 20, ...
        eps);
end

zValue = ...
    (yGrid - values') ./ bandwidth;

density = ...
    mean(exp(-0.5 .* zValue.^2), 2) ...
    ./ (bandwidth .* sqrt(2*pi));

maximumDensity = max(density);

if ~isfinite(maximumDensity) || maximumDensity <= 0
    return;
end

halfWidth = ...
    maxHalfWidth .* density ./ maximumDensity;

patch( ...
    ax, ...
    [xCenter - halfWidth; ...
     flipud(xCenter + halfWidth)], ...
    [yGrid; flipud(yGrid)], ...
    faceColor, ...
    'FaceAlpha', 0.20, ...
    'EdgeColor', faceColor, ...
    'LineWidth', 0.45, ...
    'HandleVisibility', 'off');

end


function f5_start_label_drag(labelHandle, figHandle)
% Start dragging one panel-c label.

if ~isgraphics(labelHandle) || ~isgraphics(figHandle)
    return;
end

set(figHandle, ...
    'Pointer', 'fleur', ...
    'WindowButtonMotionFcn', ...
    @(~, ~) f5_drag_label(labelHandle), ...
    'WindowButtonUpFcn', ...
    @(~, ~) f5_stop_label_drag(figHandle));

end


function f5_drag_label(labelHandle)
% Move one label and update its leader line.

if ~isgraphics(labelHandle)
    return;
end

ax = ancestor(labelHandle, 'axes');

if isempty(ax) || ~isgraphics(ax)
    return;
end

currentPoint = ax.CurrentPoint;

xValue = currentPoint(1,1);
yValue = currentPoint(1,2);

xLimits = ax.XLim;
yLimits = ax.YLim;

xPadding = 0.025 .* diff(xLimits);
yPadding = 0.040 .* diff(yLimits);

xValue = min( ...
    max(xValue, xLimits(1) + xPadding), ...
    xLimits(2) - xPadding);

yValue = min( ...
    max(yValue, yLimits(1) + yPadding), ...
    yLimits(2) - yPadding);

labelHandle.Position = [xValue, yValue, 0];

anchorPoint = getappdata( ...
    labelHandle, ...
    'AnchorPoint');

leaderHandle = getappdata( ...
    labelHandle, ...
    'LeaderHandle');

if isgraphics(leaderHandle)

    leaderHandle.XData = [anchorPoint(1), xValue];
    leaderHandle.YData = [anchorPoint(2), yValue];
end

drawnow limitrate nocallbacks;

end


function f5_stop_label_drag(figHandle)
% Finish dragging.

if ~isgraphics(figHandle)
    return;
end

set(figHandle, ...
    'Pointer', 'arrow', ...
    'WindowButtonMotionFcn', '', ...
    'WindowButtonUpFcn', '');

end
