function Figure2_IDA_v4(outputDir)
% FIGURE2_IDA_V3
% CMDO Figure 2 — ordered system mechanism / theory figure.
%
% Final intended role:
%   A) The evidential order of deployment evaluation
%   B) IDENTIFY: structural ambiguity -> finite-sample uncertainty
%   C) REUSE: mismatch-versus-uncertainty geometry
%   D) PRESERVE: adaptive excess risk and cross-state adaptation frontier
%
% Visual style is intentionally matched to the final Figure 1:
%   - no poster-style overall title inside the artwork
%   - plain colored panel letters A/B/C/D (NO filled square backgrounds)
%   - blue = observability / IDENTIFY / Delta_E
%   - green = admissibility / REUSE / Lambda
%   - red = composability / PRESERVE / Xi
%   - thin, lightly tinted panel borders
%
% Panel B keeps the frozen seeded mechanism simulation:
%   seed = 20260728
%   audit budgets = [16 32 64 128 256 512 1024]
%   R = 400
%
% Panels C/D are theory/mechanism panels, not empirical validation.
%
% Usage:
%   Figure2_IDA_v4
%   Figure2_IDA_v4('C:\path\to\output')
%
% Output:
%   Figure2_IDA_v4.fig
%   Figure2_IDA_v4.png
%   Figure2_IDA_v4.pdf

close all;

%% ------------------------------------------------------------------------
% 0. STYLE
% -------------------------------------------------------------------------
FONT = 'Arial';

FS_LETTER = 22;
FS_TITLE  = 9;
FS_AXIS   = 9;
FS_TICK   = 9.8;
FS_SMALL  = 9;
FS_TINY   = 9;

navy   = [0.02 0.24 0.63];   % Figure-1 blue
blue   = [0.02 0.29 0.70];

green  = [0.02 0.48 0.20];
teal   = [0.02 0.45 0.38];

red    = [0.82 0.05 0.04];
orange = [0.93 0.27 0.08];

purple = [0.36 0.18 0.62];

grey   = [0.40 0.40 0.40];
dgrey  = [0.22 0.22 0.22];
lgrey  = [0.88 0.89 0.91];

panelBlue  = local_mix(blue,  [1 1 1],0.72);
panelGreen = local_mix(green, [1 1 1],0.72);
panelRed   = local_mix(red,   [1 1 1],0.72);

%% ------------------------------------------------------------------------
% 1. OUTPUT
% -------------------------------------------------------------------------
thisFile = mfilename('fullpath');
if isempty(thisFile)
    scriptDir = pwd;
else
    scriptDir = fileparts(thisFile);
end

if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(scriptDir,'output');
end
if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

%% ------------------------------------------------------------------------
% 2. FROZEN PANEL-B MECHANISM SIMULATION
% -------------------------------------------------------------------------
seed    = 20260728;
budgets = [16 32 64 128 256 512 1024];
R       = 400;

rng(seed,'twister');

% AUC truth for N(1,1) positives versus N(0,1) negatives:
% Phi(1/sqrt(2)) = 0.5*(1+erf(0.5))
auc_truth = 0.5*(1 + erf(0.5));

auc_abs_err = nan(R,numel(budgets));

for i = 1:numel(budgets)
    m = budgets(i);
    nPos = floor(m/2);
    nNeg = m - nPos;

    for r = 1:R
        posScores = randn(nPos,1) + 1;
        negScores = randn(nNeg,1);

        auc_r = local_auc(posScores,negScores);
        auc_abs_err(r,i) = abs(auc_r - auc_truth);
    end
end

auc_mean = mean(auc_abs_err,1,'omitnan');

auc_lo = zeros(size(auc_mean));
auc_hi = zeros(size(auc_mean));
for i = 1:numel(budgets)
    auc_lo(i) = local_quantile(auc_abs_err(:,i),0.10);
    auc_hi(i) = local_quantile(auc_abs_err(:,i),0.90);
end

pfit = polyfit(log10(budgets),log10(auc_mean),1);
auc_slope = pfit(1);

fprintf('\nFigure2_IDA\n');
fprintf('Panel-B seeded slope = %.4f\n',auc_slope);

%% ------------------------------------------------------------------------
% 3. FIGURE CANVAS
% -------------------------------------------------------------------------
fig = figure( ...
    'Color','w', ...
    'Position',[60 45 1300 800], ...
    'Renderer','painters', ...
    'Name','CMDO Figure 2 — evidential order', ...
    'NumberTitle','off');

% Top wide panel
pA = uipanel(fig,'Units','normalized', ...
    'Position',[0.025 0.650 0.950 0.325], ...
    'BackgroundColor','w','BorderType','none');

% Bottom row
pB = uipanel(fig,'Units','normalized', ...
    'Position',[0.025 0.045 0.306 0.575], ...
    'BackgroundColor','w','BorderType','none');

pC = uipanel(fig,'Units','normalized', ...
    'Position',[0.347 0.045 0.306 0.575], ...
    'BackgroundColor','w','BorderType','none');

pD = uipanel(fig,'Units','normalized', ...
    'Position',[0.669 0.045 0.306 0.575], ...
    'BackgroundColor','w','BorderType','none');

%% ========================================================================
% PANEL A — ORDERED EVALUATION SYSTEM
% ========================================================================
axA = axes('Parent',pA,'Units','normalized','Position',[0 0 1 1]);
axis(axA,[0 100 0 32]);
axis(axA,'off');
hold(axA,'on');

local_panel_border(axA,[0.5 0.5 99 31],panelBlue,1.05);

% IMPORTANT: plain panel letter, matching Figure 1.
local_panel_header(axA,'A','The evidential order', ...
    2.0,30.1,navy,FONT,21,14.0);

% -------------------------------------------------------------------------
% Deployment evidence
% -------------------------------------------------------------------------
local_box(axA,[2.2 7.0 13.5 19.8], ...
    [0.995 0.997 1.000],local_mix(blue,[1 1 1],0.35),1.0,0.06);

text(axA,8.95,25.0,'Deployment evidence', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold','Color',navy);

obsLabels = {'Inputs','Scores','Predictions','Telemetry'};
obsY = [20.8 17.1 13.4 9.7];

for k = 1:numel(obsLabels)
    local_box(axA,[3.5 obsY(k)-1.25 10.9 2.5], ...
        [1 1 1],local_mix(blue,[1 1 1],0.50),0.75,0.04);

    % small symbol
    switch k
        case 1
            local_database_icon(axA,4.55,obsY(k),0.52,navy);
        case 2
            local_star_icon(axA,4.55,obsY(k),0.45,navy);
        case 3
            local_trend_icon(axA,4.55,obsY(k),0.72,navy);
        case 4
            local_signal_icon(axA,4.55,obsY(k),0.75,navy);
    end

    text(axA,6.0,obsY(k),obsLabels{k}, ...
        'VerticalAlignment','middle', ...
        'FontName',FONT,'FontSize',FS_SMALL, ...
        'Color',dgrey);
end

% -------------------------------------------------------------------------
% Stage 1 — observability
% -------------------------------------------------------------------------
local_capsule(axA,[20.0 15.0 14.5 7.5], ...
    local_mix(blue,[1 1 1],0.10),navy,1.2);

text(axA,27.25,18.75,'Observability', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT,'FontSize',FS_TITLE-1, ...
    'FontWeight','bold','Color','w');

text(axA,26.6,24.2,'$\Delta_{\mathcal{E}}$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontSize',FS_SMALL+1.3, ...
    'Color',navy);

text(axA,26.9,24.2,'/ IDENTIFY', ...
    'Interpreter','none', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName','Arial', ...
    'FontSize',FS_SMALL+1.1, ...
    'FontWeight','bold', ...
    'Color',navy);

% current outcomes / direct estimate
local_box(axA,[21.0 7.4 12.5 5.0], ...
    [0.970 0.995 0.970],local_mix(green,[1 1 1],0.25),0.95,0.05);

text(axA,27.25,9.9,{'Representative','current outcomes'}, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT,'FontSize',FS_SMALL, ...
    'FontWeight','bold','Color',[0.08 0.32 0.12]);

local_box(axA,[20.0 1.9 14.5 4.3], ...
    [0.985 0.990 1.000],local_mix(blue,[1 1 1],0.30),0.95,0.05);

text(axA,27.25,4.05,{'Current direct estimate','\pm uncertainty'}, ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT,'FontSize',FS_SMALL, ...
    'FontWeight','bold','Color',navy);

% -------------------------------------------------------------------------
% Stage 2 — admissibility
% -------------------------------------------------------------------------
local_capsule(axA,[45.0 15.0 14.5 7.5], ...
    local_mix(teal,[1 1 1],0.08),[0.00 0.33 0.28],1.2);

text(axA,52.25,18.75,'Admissibility', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT,'FontSize',FS_TITLE-1, ...
    'FontWeight','bold','Color','w');

text(axA,48.25,24.2,'\Lambda / REUSE', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',FS_SMALL+1.3, ...
    'FontWeight','bold','Color',green);

% history input
local_box(axA,[45.9 25.4 12.7 4.1], ...
    [0.992 0.987 1.000],local_mix(purple,[1 1 1],0.25),0.95,0.05);

text(axA,52.25,27.45,'Historical evidence', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT,'FontSize',FS_SMALL+0.3, ...
    'FontWeight','bold','Color',purple);

% Guarded reuse / direct fallback
local_box(axA,[63.5 14.5 11.0 6.2], ...
    [0.985 1.000 0.995],local_mix(teal,[1 1 1],0.25),0.95,0.05);

text(axA,69.0,17.6,{'Fixed-use','value'}, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT,'FontSize',FS_SMALL, ...
    'FontWeight','bold','Color',[0.00 0.34 0.28]);

% -------------------------------------------------------------------------
% Stage 3 — adaptive composability
% -------------------------------------------------------------------------
local_capsule(axA,[76.8 15.0 13.2 7.5], ...
    local_mix(red,[1 1 1],0.03),[0.68 0.02 0.02],1.2);

text(axA,83.4,18.75,{'Adaptive','composability'}, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT,'FontSize',FS_TITLE-1.5, ...
    'FontWeight','bold','Color','w');

text(axA,83.4,24.2,'\Xi / PRESERVE', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',FS_SMALL+1.3, ...
    'FontWeight','bold','Color',red);

% Final output
local_box(axA,[91.2 13.8 7.8 9.8], ...
    [1.000 0.990 0.987],local_mix(red,[1 1 1],0.20),1.0,0.05);

text(axA,95.1,18.7,{'Final', 'performance','\pm justified','uncertainty'}, ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT,'FontSize',FS_SMALL, ...
    'FontWeight','bold','Color',red);

% -------------------------------------------------------------------------
% Panel-A arrows
% -------------------------------------------------------------------------
local_arrow(axA,15.9,18.75,19.2,18.75,navy,1.25);   % evidence -> observability
local_arrow(axA,34.8,18.75,44.2,18.75,navy,1.25);   % obs -> admissibility
local_arrow(axA,59.8,18.75,62.8,18.75,green,1.25);  % admissibility -> guarded
local_arrow(axA,74.8,18.75,76.2,18.75,navy,1.25);   % guarded -> adaptive
local_arrow(axA,90.3,18.75,90.9,18.75,red,1.25);    % adaptive -> final

% outcomes branch: representative outcomes augment the evidence channel
local_arrow(axA,27.25,12.8,27.25,14.6,green,1.05);
local_arrow(axA,27.25,7.0,27.25,6.5,navy,1.05);

% history -> admissibility
local_arrow(axA,52.25,25.1,52.25,22.8,purple,1.05);

% current direct estimate supplies same-budget uncertainty to admissibility
plot(axA,[34.6 52.25 52.25],[4.05 4.05 14.4],'--', ...
    'Color',local_mix(teal,[1 1 1],0.10), ...
    'LineWidth',1.0);
local_arrow(axA,52.25,14.4,52.25,14.85,teal,1.0);

%% ========================================================================
% PANEL B — OBSERVABILITY
% ========================================================================
axB0 = axes('Parent',pB,'Units','normalized','Position',[0 0 1 1]);
axis(axB0,[0 1 0 1]);
axis(axB0,'off');
hold(axB0,'on');

local_panel_border(axB0,[0.005 0.005 0.99 0.99],panelBlue,1.05);
local_panel_header(axB0,'B','IDENTIFY | From ambiguity to uncertainty', ...
    0.025,0.955,navy,FONT,20,12.2);

% Top schematic headings
text(axB0,0.14,0.875,'1  Same evidence', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',8.1,'FontWeight','bold','Color',dgrey);

text(axB0,0.545,0.875,'2  Compatible worlds', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',8.1,'FontWeight','bold','Color',dgrey);

text(axB0,0.865,0.875,'3  Add outcomes', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',8.1,'FontWeight','bold','Color',dgrey);

% Shared-score histogram
scoreDemo = [0.08 0.13 0.18 0.22 0.28 0.34 0.40 0.47 ...
             0.53 0.60 0.66 0.72 0.78 0.83 0.88 0.93];

axScore = axes('Parent',pB,'Units','normalized', ...
    'Position',[0.065 0.675 0.180 0.135]);
hold(axScore,'on');

edges = linspace(0,1,7);
histogram(axScore,scoreDemo,edges, ...
    'FaceColor',local_mix(blue,[1 1 1],0.70), ...
    'EdgeColor',navy,'LineWidth',0.8);

xlim(axScore,[0 1]);
ylim(axScore,[0 5]);

set(axScore,'XTick',[0 0.5 1],'YTick',[], ...
    'Box','off','FontName',FONT,'FontSize',FS_TINY, ...
    'TickDir','out','LineWidth',0.65);

xlabel(axScore,'Score','FontName',FONT,'FontSize',FS_TINY);

text(axB0,0.147,0.830,'Shared scores', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',FS_TINY,'Color',dgrey);

% Arrow to worlds
local_arrow(axB0,0.255,0.745,0.365,0.745,grey,0.9);

% Two compatible worlds with same scores
scoresW  = linspace(0.08,0.92,12);
ySuccess = [zeros(1,6) ones(1,6)];
yFailure = 1 - ySuccess;

axWorld1 = axes('Parent',pB,'Units','normalized', ...
    'Position',[0.435 0.725 0.175 0.083]);
hold(axWorld1,'on');

scatter(axWorld1,scoresW(ySuccess==0),zeros(1,sum(ySuccess==0)), ...
    14,green,'filled');
scatter(axWorld1,scoresW(ySuccess==1),ones(1,sum(ySuccess==1)), ...
    14,green,'filled');

xlim(axWorld1,[0 1]);
ylim(axWorld1,[-0.18 1.18]);

set(axWorld1,'XTick',[],'YTick',[0 1], ...
    'YTickLabel',{'0','1'}, ...
    'Box','off','FontName',FONT,'FontSize',FS_TINY, ...
    'TickDir','out','LineWidth',0.6);

axWorld2 = axes('Parent',pB,'Units','normalized', ...
    'Position',[0.435 0.615 0.175 0.083]);
hold(axWorld2,'on');

scatter(axWorld2,scoresW(yFailure==0),zeros(1,sum(yFailure==0)), ...
    14,red,'filled');
scatter(axWorld2,scoresW(yFailure==1),ones(1,sum(yFailure==1)), ...
    14,red,'filled');

xlim(axWorld2,[0 1]);
ylim(axWorld2,[-0.18 1.18]);

set(axWorld2,'XTick',[0 0.5 1],'YTick',[0 1], ...
    'YTickLabel',{'0','1'}, ...
    'Box','off','FontName',FONT,'FontSize',FS_TINY, ...
    'TickDir','out','LineWidth',0.6);

text(axB0,0.400,0.777,'WORLD+', ...
    'HorizontalAlignment','right', ...
    'FontName',FONT,'FontSize',FS_TINY, ...
    'FontWeight','bold','Color',green);

text(axB0,0.400,0.678,'WORLD-', ...
    'HorizontalAlignment','right', ...
    'FontName',FONT,'FontSize',FS_TINY, ...
    'FontWeight','bold','Color',red);

text(axB0,0.615,0.770,'AUC 1.00', ...
    'HorizontalAlignment','left', ...
    'FontName',FONT,'FontSize',FS_TINY, ...
    'FontWeight','bold','Color',green);

text(axB0,0.615,0.670,'AUC 0.00', ...
    'HorizontalAlignment','left', ...
    'FontName',FONT,'FontSize',FS_TINY, ...
    'FontWeight','bold','Color',red);

local_arrow(axB0,0.675,0.745,0.740,0.745,grey,0.9);

% Representative outcome intervals
auditY = [0.795 0.745 0.695 0.645];
auditHalfWidth = [0.060 0.045 0.033 0.022];

for k = 1:numel(auditY)
    yy = auditY(k);
    hw = auditHalfWidth(k);

    plot(axB0,[0.86-hw 0.86+hw],[yy yy],'-', ...
        'Color',green,'LineWidth',1.1);

    plot(axB0,[0.86-hw 0.86-hw],[yy-0.008 yy+0.008],'-', ...
        'Color',green,'LineWidth',0.8);

    plot(axB0,[0.86+hw 0.86+hw],[yy-0.008 yy+0.008],'-', ...
        'Color',green,'LineWidth',0.8);

    scatter(axB0,0.86,yy,13,green,'filled');
end

text(axB0,0.86,0.608,'$\Delta_{\mathcal{E}}\ \mathrm{closes}$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',FS_TINY, ...
    'Color',dgrey);

% Divider
plot(axB0,[0.045 0.955],[0.575 0.575],'-', ...
    'Color',[0.84 0.84 0.84],'LineWidth',0.8);

% Quantitative root-budget plot
axB = axes('Parent',pB,'Units','normalized', ...
    'Position',[0.150 0.090 0.790 0.425]);

hold(axB,'on');

fill(axB, ...
    [budgets fliplr(budgets)], ...
    [auc_lo fliplr(auc_hi)], ...
    local_mix(blue,[1 1 1],0.72), ...
    'EdgeColor','none','FaceAlpha',0.42);

plot(axB,budgets,auc_mean,'-o', ...
    'Color',blue, ...
    'MarkerFaceColor',blue, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',2.0,'MarkerSize',6.2);

ref = auc_mean(1).*(budgets/budgets(1)).^(-0.5);

plot(axB,budgets,ref,'--', ...
    'Color',[0.32 0.32 0.32], ...
    'LineWidth',1.0);

set(axB, ...
    'XScale','log', ...
    'YScale','log', ...
    'FontName',FONT, ...
    'FontSize',9.2, ...
    'LineWidth',0.8, ...
    'TickDir','out');
axB.XTickLabelRotation = 0;

xlim(axB,[14 1200]);
xticks(axB,budgets);
xticklabels(axB,{'16','32','64','128','256','512','1024'});

grid(axB,'on');
axB.GridAlpha = 0.10;

xlabel(axB,'Audited outcomes, m', ...
    'FontName',FONT,'FontSize',10.5);

ylabel(axB,'AUC error', ...
    'FontName',FONT,'FontSize',10.5);

text(axB,0.06,0.12,sprintf('slope = %.2f',auc_slope), ...
    'Units','normalized', ...
    'FontName',FONT,'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold','Color',navy);

%% ========================================================================
% PANEL C — ADMISSIBILITY
% ========================================================================
axC0 = axes('Parent',pC,'Units','normalized','Position',[0 0 1 1]);
axis(axC0,[0 1 0 1]);
axis(axC0,'off');
hold(axC0,'on');

local_panel_border(axC0,[0.005 0.005 0.99 0.99],panelGreen,1.05);
local_panel_header(axC0,'C','REUSE | Mismatch versus uncertainty', ...
    0.025,0.955,green,FONT,20,12.0);

axC = axes('Parent',pC,'Units','normalized', ...
    'Position',[0.170 0.205 0.765 0.555]);

hold(axC,'on');

lambda_line = logspace(-4,4,600);
w_boundary  = min(2./(1+lambda_line),1);

% Visual transition band around the analytic zero-gain contour.
% It is only a schematic band, NOT an empirical threshold.
band = 0.065;

w_low  = max(w_boundary-band,0);
w_high = min(w_boundary+band,1);

% beneficial region
patch(axC, ...
    [lambda_line fliplr(lambda_line)], ...
    [zeros(size(w_low)) fliplr(w_low)], ...
    local_mix(green,[1 1 1],0.80), ...
    'EdgeColor','none','FaceAlpha',0.95);

% transition band
patch(axC, ...
    [lambda_line fliplr(lambda_line)], ...
    [w_low fliplr(w_high)], ...
    [1.00 0.94 0.72], ...
    'EdgeColor','none','FaceAlpha',0.92);

% harmful region
patch(axC, ...
    [lambda_line fliplr(lambda_line)], ...
    [w_high fliplr(ones(size(w_high)))], ...
    local_mix(red,[1 1 1],0.83), ...
    'EdgeColor','none','FaceAlpha',0.95);

plot(axC,lambda_line,w_boundary,'--', ...
    'Color',[0.14 0.14 0.14], ...
    'LineWidth',1.55);

set(axC, ...
    'XScale','log', ...
    'FontName',FONT, ...
    'FontSize',9.5, ...
    'LineWidth',0.8, ...
    'TickDir','out');
axC.XTickLabelRotation = 0;

xlim(axC,[1e-4 1e4]);
ylim(axC,[0 1]);

xticks(axC,[1e-4 1e-2 1 1e2 1e4]);
yticks(axC,[0 0.25 0.50 0.75 1]);

xlabel(axC,'Evidence-admissibility ratio, \Lambda', ...
    'Interpreter','tex', ...
    'FontName',FONT,'FontSize',10.3);

ylabel(axC,'Borrowing weight, w', ...
    'FontName',FONT,'FontSize',10.3);

text(axC,2e-3,0.52,'helps', ...
    'FontName',FONT,'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold','Color',[0.02 0.35 0.10]);

text(axC,3,0.44,'transition', ...
    'FontName',FONT,'FontSize',FS_SMALL, ...
    'FontWeight','bold','Color',[0.58 0.39 0.00]);

text(axC,1.5e2,0.62,'hurts', ...
    'FontName',FONT,'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold','Color',[0.60 0.02 0.02]);

% zero-gain label
text(axC,1.6e-4,0.065,'--  zero-gain contour', ...
    'FontName',FONT,'FontSize',FS_TINY, ...
    'Color',dgrey, ...
    'BackgroundColor','w','Margin',2);

% Equation box above plot
text(axC0,0.73,0.835, ...
    '$\frac{R(w)}{V}=(1-w)^2+\Lambda w^2$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT,'FontSize',11.5, ...
    'Color',dgrey, ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.45 0.45 0.45], ...
    'Margin',5);

%% ========================================================================
% PANEL D — PRESERVE / COMPOSABILITY
% ========================================================================
axD0 = axes('Parent',pD,'Units','normalized','Position',[0 0 1 1]);
axis(axD0,[0 1 0 1]);
axis(axD0,'off');
hold(axD0,'on');

local_panel_border(axD0,[0.005 0.005 0.99 0.99],panelRed,1.05);
local_panel_header(axD0,'D','PRESERVE | Composability and adaptation frontier', ...
    0.025,0.955,red,FONT,20,10.8);

% -------------------------------------------------------------------------
% Adaptive-composition excess risk
% -------------------------------------------------------------------------
text(axD0,0.56,0.855, ...
    '$\frac{R_{\mathrm{adaptive}}}{V}=\frac{R_{\mathrm{fixed}}(\bar w)}{V}+\Xi$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT,'FontSize',11.2, ...
    'Color',dgrey, ...
    'BackgroundColor','w', ...
    'EdgeColor',local_mix(red,[1 1 1],0.10), ...
    'Margin',5);

% Upper schematic: a useful fixed rule can lose value after adaptation.
axD = axes('Parent',pD,'Units','normalized', ...
    'Position',[0.155 0.535 0.685 0.245]);
hold(axD,'on');

directRisk   = 1.00;
fixedRisk    = 0.72;
xiRisk       = 0.38;
adaptiveRisk = fixedRisk + xiRisk;

plot(axD,[0.55 3.45],[1 1],'--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',0.9);

rectangle(axD,'Position',[0.75 0 0.50 directRisk], ...
    'FaceColor',[0.90 0.90 0.91], ...
    'EdgeColor',[0.38 0.38 0.38], ...
    'LineWidth',0.8);

rectangle(axD,'Position',[1.75 0 0.50 fixedRisk], ...
    'FaceColor',local_mix(teal,[1 1 1],0.35), ...
    'EdgeColor',[0.00 0.35 0.30], ...
    'LineWidth',0.8);

rectangle(axD,'Position',[2.75 0 0.50 fixedRisk], ...
    'FaceColor',local_mix(teal,[1 1 1],0.35), ...
    'EdgeColor',[0.00 0.35 0.30], ...
    'LineWidth',0.8);

rectangle(axD,'Position',[2.75 fixedRisk 0.50 xiRisk], ...
    'FaceColor',local_mix(red,[1 1 1],0.12), ...
    'EdgeColor',red, ...
    'LineWidth',0.8);

text(axD,3.00,fixedRisk+xiRisk/2,'\Xi', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT,'FontSize',FS_SMALL+1, ...
    'FontWeight','bold','Color','w');

text(axD,1.00,1.155,'1.00', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',FS_TINY,'Color',dgrey);

text(axD,2.00,fixedRisk+0.155,'<1.00', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',FS_TINY,'Color',dgrey);

text(axD,3.00,adaptiveRisk+0.155,'>1.00', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',FS_TINY,'Color',dgrey);

set(axD, ...
    'XLim',[0.55 3.45], ...
    'YLim',[0 1.45], ...
    'XTick',[1 2 3], ...
    'XTickLabel',{'Direct','Fixed','Adaptive'}, ...
    'YTick',[0 0.5 1 1.5], ...
    'FontName',FONT, ...
    'FontSize',9.0, ...
    'LineWidth',0.8, ...
    'TickDir','out', ...
    'Box','off');
axD.XTickLabelRotation = 0;

ylabel(axD,'Normalized risk, R/V', ...
    'FontName',FONT,'FontSize',10.0);

% -------------------------------------------------------------------------
% Cross-state consequence: adaptation frontier
% H = exploitable heterogeneity opportunity
% A = allocation error
% C = mean composition excess risk
% The frontier is H = A + C.
% -------------------------------------------------------------------------
axF = axes('Parent',pD,'Units','normalized', ...
    'Position',[0.175 0.125 0.700 0.285]);
hold(axF,'on');

xFront = linspace(0,1,300);

% Regions
patch(axF,[0 1 1],[0 0 1], ...
    local_mix(red,[1 1 1],0.88), ...
    'EdgeColor','none','FaceAlpha',0.92);

patch(axF,[0 0 1],[0 1 1], ...
    local_mix(green,[1 1 1],0.86), ...
    'EdgeColor','none','FaceAlpha',0.92);

% Boundary H = A + C
plot(axF,xFront,xFront,'--', ...
    'Color',[0.18 0.18 0.18], ...
    'LineWidth',1.35);

text(axF,0.17,0.79,'adaptation worthwhile', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',8.5, ...
    'FontWeight','bold','Color',[0.02 0.35 0.10]);

text(axF,0.73,0.22,'fixed rule preferable', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',8.5, ...
    'FontWeight','bold','Color',[0.60 0.02 0.02]);

text(axF,0.18,0.62,'H > A + C', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',8.5, ...
    'FontWeight','bold','Color',[0.02 0.35 0.10]);

text(axF,0.78,0.38,'H \leq A + C', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT,'FontSize',8.5, ...
    'FontWeight','bold','Color',[0.60 0.02 0.02]);

set(axF, ...
    'XLim',[0 1], ...
    'YLim',[0 1], ...
    'XTick',[0 0.5 1], ...
    'YTick',[0 0.5 1], ...
    'FontName',FONT, ...
    'FontSize',8.8, ...
    'LineWidth',0.8, ...
    'TickDir','out', ...
    'Box','off');

xlabel(axF,'Allocation + composition,  A + C', ...
    'FontName',FONT,'FontSize',9.3);

ylabel(axF,'Heterogeneity opportunity,  H', ...
    'FontName',FONT,'FontSize',9.3);


%% ------------------------------------------------------------------------
% 4. EXPORT
% -------------------------------------------------------------------------
drawnow;

figPath = fullfile(outputDir,'Figure2_IDA_EvidentialOrder.fig');
pngPath = fullfile(outputDir,'Figure2_IDA_EvidentialOrder.png');
pdfPath = fullfile(outputDir,'Figure2_IDA_EvidentialOrder.pdf');

savefig(fig,figPath);

% Robust page geometry for MATLAB versions that fall back to PRINT.
set(fig,'PaperPositionMode','auto');
set(fig,'PaperUnits','inches');
figPos = get(fig,'Position');
pageH = 8.0;
pageW = pageH * figPos(3) / figPos(4);
set(fig,'PaperSize',[pageW pageH]);
set(fig,'PaperPosition',[0 0 pageW pageH]);

try
    exportgraphics(fig,pngPath,'Resolution',600);
    exportgraphics(fig,pdfPath,'ContentType','vector');
catch ME
    warning('exportgraphics failed (%s). Falling back to print.',ME.message);
    print(fig,pngPath,'-dpng','-r600');
    print(fig,pdfPath,'-dpdf','-painters','-bestfit');
end

fprintf('\nSaved:\n%s\n%s\n%s\n',figPath,pngPath,pdfPath);

end

%% =========================================================================
% HELPERS
% =========================================================================

function c = local_mix(c1,c2,alpha)
% alpha=0 -> c1; alpha=1 -> c2
c = (1-alpha).*c1 + alpha.*c2;
end

function local_panel_border(ax,pos,color,lineWidth)
rectangle(ax,'Position',pos,'Curvature',0.018, ...
    'FaceColor','none','EdgeColor',color,'LineWidth',lineWidth);
end

function local_panel_header(ax,letter,titleText,x,y,color,fontName,fsLetter,fsTitle)
% Figure-1 style: plain colored letter, NO background box.
text(ax,x,y,letter, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsLetter, ...
    'FontWeight','bold', ...
    'Color',color);

text(ax,x+0.055*(diff(xlim(ax))),y,titleText, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsTitle, ...
    'FontWeight','bold', ...
    'Color',color);
end

function local_box(ax,pos,faceColor,edgeColor,lineWidth,curvature)
rectangle(ax,'Position',pos, ...
    'Curvature',curvature, ...
    'FaceColor',faceColor, ...
    'EdgeColor',edgeColor, ...
    'LineWidth',lineWidth);
end

function local_capsule(ax,pos,faceColor,edgeColor,lineWidth)
rectangle(ax,'Position',pos, ...
    'Curvature',[1 1], ...
    'FaceColor',faceColor, ...
    'EdgeColor',edgeColor, ...
    'LineWidth',lineWidth);
end

function local_arrow(ax,x1,y1,x2,y2,color,lineWidth)
dx = x2-x1;
dy = y2-y1;

quiver(ax,x1,y1,dx,dy,0, ...
    'Color',color, ...
    'LineWidth',lineWidth, ...
    'MaxHeadSize',0.55);
end

function auc = local_auc(posScores,negScores)
scores = [posScores(:); negScores(:)];

ranks = local_tied_rank(double(scores));

nPos = numel(posScores);
nNeg = numel(negScores);

auc = (sum(ranks(1:nPos)) - nPos*(nPos+1)/2) / (nPos*nNeg);
end

function ranks = local_tied_rank(values)
[sortedValues,order] = sort(values);

ranks = zeros(size(values));

i = 1;
while i <= numel(sortedValues)
    j = i;

    while j < numel(sortedValues) && sortedValues(j+1) == sortedValues(i)
        j = j + 1;
    end

    avgRank = (i+j)/2;
    ranks(order(i:j)) = avgRank;

    i = j + 1;
end
end

function q = local_quantile(values,p)
values = sort(values(isfinite(values)));

if isempty(values)
    q = NaN;
    return;
end

idx = 1 + (numel(values)-1)*min(max(p,0),1);
lo  = floor(idx);
hi  = ceil(idx);
a   = idx-lo;

q = (1-a)*values(lo) + a*values(hi);
end

%% -------------------------------------------------------------------------
% Small deployment-evidence icons
% -------------------------------------------------------------------------
function local_database_icon(ax,x,y,s,color)
% simple cylinder
rectangle(ax,'Position',[x-s*0.55 y-s*0.42 s*1.10 s*0.84], ...
    'Curvature',[0.3 0.3], ...
    'FaceColor','none','EdgeColor',color,'LineWidth',0.8);
plot(ax,[x-s*0.55 x+s*0.55],[y y],'-','Color',color,'LineWidth',0.55);
end

function local_star_icon(ax,x,y,r,color)
th = (0:9)'*pi/5 + pi/2;
rr = repmat([r; 0.42*r],5,1);
xx = x + rr.*cos(th);
yy = y + rr.*sin(th);
patch(ax,xx,yy,'w','EdgeColor',color,'LineWidth',0.8);
end

function local_trend_icon(ax,x,y,s,color)
plot(ax,[x-s*0.55 x-s*0.20 x+s*0.05 x+s*0.50], ...
        [y-s*0.35 y-s*0.05 y-s*0.16 y+s*0.34], ...
        '-','Color',color,'LineWidth',0.9);
scatter(ax,x+s*0.50,y+s*0.34,8,color,'filled');
end

function local_signal_icon(ax,x,y,s,color)
theta = linspace(-pi/3,pi/3,30);
for k = 1:3
    r = s*(0.28 + 0.17*k);
    plot(ax,x+r*cos(theta),y+r*sin(theta), ...
        '-','Color',color,'LineWidth',0.65);
end
scatter(ax,x,y,8,color,'filled');
end
