function Figure4
%FIGURE4 Full-information pair-complete observer figure.
%
% Restores the canonical Figure 4 content:
%   a  Pair-coverage construction diagram
%   b  Exact fallback identity + residual-audit inset
%   c  Six complete regret distributions with violin envelopes
%   d  Seven-stage efficiency-safety trajectory
%
% Panel-d labels can be dragged manually. Their positions are saved and
% reused automatically on the next run.

close all;

%% User option
MANUAL_PANEL_D_LABELS = ~strcmp(getenv('CMDO_BATCH_MODE'), '1');

%% Project and canonical records
scriptDir = fileparts(mfilename('fullpath'));
if ~isempty(scriptDir)
    addpath(genpath(scriptDir));
end

cfg = cmdo_config('Figure4');
D = cmdo_load_all(cfg);
rng(20260728, 'twister');

outDir = cfg.outputDir;
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

%% Figure canvas
fig = figure( ...
    'Position', [25 25 1100 900], ...
    'Color', 'w', ...
    'Renderer', 'painters', ...
    'Name', 'CMDO Figure 4', ...
    'NumberTitle', 'off');

tl = tiledlayout( ...
    fig, ...
    2, 2, ...
    'TileSpacing', 'loose', ...
    'Padding', 'loose');

tl.OuterPosition = [0.04 0.04 0.92 0.91];

title(tl, ...
    'Pair-complete observer validation', ...
    'FontWeight', 'bold', ...
    'FontSize', 17);

% Create all four main axes before the inset so tiledlayout positions settle.
axA = nexttile(tl, 1);
axB = nexttile(tl, 2);
axC = nexttile(tl, 3);
axD = nexttile(tl, 4);

%% ========================================================================
% a — pair coverage diagram
% ========================================================================
hold(axA, 'on');
axis(axA, [0 1 0 1]);
axis(axA, 'off');
cmdo_safe_panel_letter(axA, 'a');

title(axA, ...
    'Pair coverage', ...
    'FontWeight', 'bold', ...
    'FontSize', 12);

text(axA, ...
    0.25, 0.88, ...
    'Naive split', ...
    'HorizontalAlignment', 'center', ...
    'FontWeight', 'bold', ...
    'FontSize', 10.5);

text(axA, ...
    0.75, 0.88, ...
    'Pair-complete construction', ...
    'HorizontalAlignment', 'center', ...
    'FontWeight', 'bold', ...
    'FontSize', 10.5);

% Two 2-by-2 pair matrices.
f4_draw_pair_matrix(axA, 0.06, 0.43, 0.37, 0.34, false);
f4_draw_pair_matrix(axA, 0.57, 0.43, 0.37, 0.34, true);

% Naive split consequence.
text(axA, ...
    0.25, 0.27, ...
    {'Cross-fold pairs are discarded', ...
     '\Rightarrow positive certification tax'}, ...
    'Interpreter', 'tex', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'top', ...
    'FontSize', 9.5);

% Pair-complete estimator identity.
text(axA, ...
    0.755, 0.285, ...
    ['$D_{\mathrm{full}} = ' ...
     '\frac{\sum_{g,h\in\{A,B\}} n_{P_g}n_{N_h}D_{gh}}' ...
     '{\sum_{g,h\in\{A,B\}}n_{P_g}n_{N_h}}$'], ...
    'Interpreter', 'latex', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'top', ...
    'FontSize', 10);

text(axA, ...
    0.755, 0.17, ...
    {'Observation-disjoint sensing:', ...
     'AA \leftrightarrow BB,  AB \leftrightarrow BA', ...
     'All four pair blocks are retained.'}, ...
    'Interpreter', 'tex', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'top', ...
    'FontSize', 8.5);

%% ========================================================================
% b — exact fallback identity with residual-audit inset
% ========================================================================
hold(axB, 'on');
cmdo_safe_panel_letter(axB, 'b');

title(axB, ...
    'Exact fallback identity', ...
    'FontWeight', 'bold', ...
    'FontSize', 11.5);

u7AUC = D.u7_rep(string(D.u7_rep.metric) == "AUC", :);

% Main plot data: slightly larger and less transparent
scatter(axB, ...
    D.u6_rep.direct_full_auc, ...
    D.u6_rep.direct_full_auc, ...
    18, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor', [0.0000 0.4470 0.7410], ...
    'MarkerEdgeColor', 'none', ...
    'MarkerFaceAlpha', 0.18, ...
    'MarkerEdgeAlpha', 0.18, ...
    'HandleVisibility', 'off');

scatter(axB, ...
    u7AUC.direct, ...
    u7AUC.direct, ...
    20, ...
    '^', ...
    'filled', ...
    'MarkerFaceColor', [0.8500 0.3250 0.0980], ...
    'MarkerEdgeColor', 'none', ...
    'MarkerFaceAlpha', 0.18, ...
    'MarkerEdgeAlpha', 0.18, ...
    'HandleVisibility', 'off');

hIdentity = plot(axB, [0 1], [0 1], '--', ...
    'Color', [0.15 0.15 0.15], ...
    'LineWidth', 1.2, ...
    'DisplayName', 'Identity, y = x');

% Opaque legend proxy markers (for clean legend only)
hU6Legend = scatter(axB, NaN, NaN, ...
    42, 'o', 'filled', ...
    'MarkerFaceColor', [0.0000 0.4470 0.7410], ...
    'MarkerEdgeColor', [0.0000 0.4470 0.7410], ...
    'DisplayName', sprintf('U6 (n=%d)', height(D.u6_rep)));

hU7Legend = scatter(axB, NaN, NaN, ...
    46, '^', 'filled', ...
    'MarkerFaceColor', [0.8500 0.3250 0.0980], ...
    'MarkerEdgeColor', [0.8500 0.3250 0.0980], ...
    'DisplayName', sprintf('U7 AUC (n=%d)', height(u7AUC)));

xlim(axB, [-0.01 1.01]);
ylim(axB, [-0.01 1.01]);
axis(axB, 'square');

xlabel(axB, 'Full direct AUC');
ylabel(axB, 'Pair-complete estimate at w = 0');

legend(axB, ...
    [hU6Legend hU7Legend hIdentity], ...
    {sprintf('U6 (n=%d)', height(D.u6_rep)), ...
     sprintf('U7 AUC (n=%d)', height(u7AUC)), ...
     'Identity, y = x'}, ...
    'Location', 'southwest', ...
    'Box', 'off', ...
    'FontSize', 8.0);

set(axB, 'XGrid', 'on', 'YGrid', 'on');
axB.GridAlpha = 0.16;
cmdo_safe_apply_axes_style(axB);

maxResidual = max([ ...
    abs(D.u6_rep.identity_residual); ...
    abs(u7AUC.identity_residual)], [], 'omitnan');

text(axB, ...
    0.60, 0.045, ...
    sprintf('max|r| = %.2e', maxResidual), ...
    'Units', 'normalized', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'bottom', ...
    'FontWeight', 'bold', ...
    'FontSize', 8.2, ...
    'BackgroundColor', 'w', ...
    'Margin', 1);

% ----- inset: independent residual audit, no legend -----
drawnow;
posB = axB.Position;

axBInset = axes(fig, ...
    'Position', [ ...
        posB(1) + 0.12 * posB(3), ...
        posB(2) + 0.59 * posB(4), ...
        0.34 * posB(3), ...
        0.21 * posB(4)], ...
    'Color', 'w', ...
    'Box', 'on');

hold(axBInset, 'on');

plot(axBInset, [0 0], [-0.35 1.35], '--', ...
    'Color', [0.45 0.45 0.45], ...
    'LineWidth', 0.8);

scatter(axBInset, ...
    0, 1, ...
    32, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor', [0.0000 0.4470 0.7410], ...
    'MarkerEdgeColor', 'none');

scatter(axBInset, ...
    0, 0, ...
    34, ...
    '^', ...
    'filled', ...
    'MarkerFaceColor', [0.8500 0.3250 0.0980], ...
    'MarkerEdgeColor', 'none');

xlim(axBInset, [-0.40 0.40]);
ylim(axBInset, [-0.35 1.35]);

xticks(axBInset, 0);
yticks(axBInset, [0 1]);
yticklabels(axBInset, {'U7', 'U6'});

xlabel(axBInset, 'Residual', 'FontSize', 6.5);

title(axBInset, ...
    sprintf('Residual audit: %d/%d zero', ...
        nnz(D.u6_rep.identity_residual == 0) + nnz(u7AUC.identity_residual == 0), ...
        height(D.u6_rep) + height(u7AUC)), ...
    'FontWeight', 'bold', ...
    'FontSize', 6.5);

set(axBInset, ...
    'FontName', 'Arial', ...
    'FontSize', 6.3, ...
    'LineWidth', 0.65, ...
    'TickDir', 'out');

uistack(axBInset, 'top');

%% ========================================================================
% c — complete certification-tax distributions with draggable worst labels
% ========================================================================
hold(axC, 'on');
cmdo_safe_panel_letter(axC, 'c');

title(axC, ...
    'Removal of the certification tax', ...
    'FontWeight', 'bold', ...
    'FontSize', 11.5);

vals = { ...
    D.u5d_state.mae_regret_vs_full_direct( ...
        string(D.u5d_state.method) == "SPLIT_DIRECT"), ...
    D.u5d_state.mae_regret_vs_full_direct( ...
        string(D.u5d_state.method) == "DELONG_NORMAL"), ...
    D.u5e_state.mae_regret_vs_full_direct( ...
        string(D.u5e_state.method) == "PC_DELONG"), ...
    D.u5e_state.mae_regret_vs_full_direct( ...
        string(D.u5e_state.method) == "PC_PAIRED_HOEFFDING"), ...
    D.u6_state.mae_regret_vs_full_direct, ...
    D.u7_state.regret( ...
        string(D.u7_state.metric) == "AUC")};

labelsC = { ...
    sprintf('Naive\nsplit'), ...
    sprintf('U5D\nDeLong'), ...
    sprintf('Pair-complete\nDeLong'), ...
    sprintf('Frozen PC-\nHoeffding'), ...
    sprintf('Independent\nU6'), ...
    sprintf('Sealed\nU7 AUC')};

colorsC = [ ...
    0.1216 0.4667 0.7059; ...
    1.0000 0.4980 0.0549; ...
    0.1725 0.6275 0.1725; ...
    0.8392 0.1529 0.1569; ...
    0.4941 0.1843 0.5569; ...
    0.4667 0.6745 0.1882];

worstXYC = nan(numel(vals),2);

for k = 1:numel(vals)
    v = double(vals{k});
    v = v(isfinite(v));

    % Violin envelope
    f4_violin(axC, k, v, colorsC(k, :), 0.31);

    % Deterministic jittered state points
    jitter = 0.045 * randn(size(v));

    scatter(axC, ...
        k + jitter, ...
        v, ...
        12, ...
        colorsC(k, :), ...
        'filled', ...
        'MarkerEdgeColor', 'none', ...
        'MarkerFaceAlpha', 0.38);

    % Median bar
    medV = median(v, 'omitnan');
    plot(axC, [k - 0.22, k + 0.22], [medV medV], ...
        'k-', 'LineWidth', 2.1);

    % Worst-state anchor point
    maxV = max(v, [], 'omitnan');
    worstXYC(k,:) = [k, maxV];
end

yline(axC, 0, '--', ...
    'Color', [0.35 0.35 0.35], ...
    'LineWidth', 0.9);

xlim(axC, [0.45, numel(vals) + 0.55]);
ylim(axC, [-0.016, 0.016]);

xticks(axC, 1:numel(vals));
xticklabels(axC, labelsC);
ylabel(axC, 'Target-budget regret');

set(axC, 'XGrid', 'off', 'YGrid', 'on');
axC.GridAlpha = 0.10;
cmdo_safe_apply_axes_style(axC);
axC.XAxis.TickLabelInterpreter = 'none';

% ----- draggable "worst ..." labels for panel c -----
defaultLabelPosC = [ ...
    0.90,  0.01500; ...
    2.10,  0.01390; ...
    2.95,  0.00570; ...
    3.70,  0.00320; ...
    4.95,  0.00455; ...
    6.02,  0.00185];

labelPosFileC = fullfile(outDir, 'Figure4_panelC_label_positions.mat');
labelPosC = defaultLabelPosC;

if exist(labelPosFileC, 'file')
    savedC = load(labelPosFileC);
    if isfield(savedC, 'labelPosC') && isequal(size(savedC.labelPosC), [numel(vals), 2])
        labelPosC = savedC.labelPosC;
    end
end

labelHandlesC = gobjects(numel(vals), 1);
leaderHandlesC = gobjects(numel(vals), 1);

for k = 1:numel(vals)
    anchor = worstXYC(k,:);
    txt = sprintf('worst %.4g', anchor(2));

    leaderHandlesC(k) = plot(axC, ...
        [anchor(1), labelPosC(k,1)], ...
        [anchor(2), labelPosC(k,2)], ...
        '-', ...
        'Color', [0.35 0.35 0.35], ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');

    labelHandlesC(k) = text(axC, ...
        labelPosC(k,1), ...
        labelPosC(k,2), ...
        txt, ...
        'FontName', 'Arial', ...
        'FontSize', 7.5, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'BackgroundColor', 'w', ...
        'EdgeColor', 'none', ...
        'Margin', 1.0, ...
        'Clipping', 'off', ...
        'PickableParts', 'all', ...
        'HitTest', 'on');

    setappdata(labelHandlesC(k), 'AnchorPoint', anchor);
    setappdata(labelHandlesC(k), 'LeaderHandle', leaderHandlesC(k));
    labelHandlesC(k).ButtonDownFcn = @(src, ~) f4_start_label_drag(src, fig);
end
%% ========================================================================
% d — seven-point efficiency-safety trajectory with draggable labels
% ========================================================================
hold(axD, 'on');
cmdo_safe_panel_letter(axD, 'd');

title(axD, ...
    'Efficiency-safety trajectory', ...
    'FontWeight', 'bold', ...
    'FontSize', 12);

labelD = [ ...
    "Naive split"; ...
    "U5D DeLong"; ...
    "Pair-complete DeLong"; ...
    "U5D plugin candidate"; ...
    "Frozen PC-Hoeffding"; ...
    "Independent U6"; ...
    "Sealed U7 AUC"];

gainD = [ ...
    100 * cmdo_summary_value( ...
        D.u5d_summary, ...
        'SPLIT_DIRECT', ...
        'gain_vs_full_direct'); ...
    100 * cmdo_summary_value( ...
        D.u5d_summary, ...
        'DELONG_NORMAL', ...
        'gain_vs_full_direct'); ...
    100 * cmdo_summary_value( ...
        D.u5e_summary, ...
        'PC_DELONG', ...
        'gain_vs_full_direct'); ...
    100 * cmdo_summary_value( ...
        D.u5d_summary, ...
        'PLUGIN_FULL', ...
        'gain_vs_full_direct'); ...
    100 * cmdo_summary_value( ...
        D.u5f_audit, ...
        'PC_PAIRED_HOEFFDING', ...
        'pooled_gain'); ...
    100 * ...
        (mean(D.u6_state.direct_mae, 'omitnan') - ...
         mean(D.u6_state.mae, 'omitnan')) / ...
         mean(D.u6_state.direct_mae, 'omitnan'); ...
    100 * D.u7_metric.relative_gain( ...
        string(D.u7_metric.metric) == "AUC")];

regretD = [ ...
    cmdo_summary_value( ...
        D.u5d_summary, ...
        'SPLIT_DIRECT', ...
        'worst_target_budget_regret_vs_full'); ...
    cmdo_summary_value( ...
        D.u5d_summary, ...
        'DELONG_NORMAL', ...
        'worst_target_budget_regret_vs_full'); ...
    cmdo_summary_value( ...
        D.u5e_summary, ...
        'PC_DELONG', ...
        'worst_target_budget_regret'); ...
    cmdo_summary_value( ...
        D.u5d_summary, ...
        'PLUGIN_FULL', ...
        'worst_target_budget_regret_vs_full'); ...
    cmdo_summary_value( ...
        D.u5f_audit, ...
        'PC_PAIRED_HOEFFDING', ...
        'worst_target_budget_regret'); ...
    max( ...
        D.u6_state.mae_regret_vs_full_direct, ...
        [], ...
        'omitnan'); ...
    D.u7_metric.worst_regret( ...
        string(D.u7_metric.metric) == "AUC")];

phaseD = [ ...
    "Development"; ...
    "Development"; ...
    "Development"; ...
    "Development"; ...
    "Frozen"; ...
    "Confirmation"; ...
    "Confirmation"];

developmentColor = [0.0000 0.4470 0.7410];
frozenColor = [0.8500 0.3250 0.0980];
confirmationColor = [0.4660 0.6740 0.1880];

mDev = phaseD == "Development";
mFrozen = phaseD == "Frozen";
mConfirm = phaseD == "Confirmation";

hDev = scatter( ...
    axD, ...
    gainD(mDev), ...
    regretD(mDev), ...
    78, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor', developmentColor, ...
    'MarkerEdgeColor', 'w', ...
    'LineWidth', 0.6, ...
    'DisplayName', 'Development');

hFrozen = scatter( ...
    axD, ...
    gainD(mFrozen), ...
    regretD(mFrozen), ...
    145, ...
    '*', ...
    'MarkerEdgeColor', frozenColor, ...
    'LineWidth', 1.4, ...
    'DisplayName', 'Frozen');

hConfirm = scatter( ...
    axD, ...
    gainD(mConfirm), ...
    regretD(mConfirm), ...
    82, ...
    'D', ...
    'filled', ...
    'MarkerFaceColor', confirmationColor, ...
    'MarkerEdgeColor', 'w', ...
    'LineWidth', 0.6, ...
    'DisplayName', 'Confirmation');

yline( ...
    axD, ...
    0, ...
    '--', ...
    'Color', [0.00 0.45 0.75], ...
    'LineWidth', 0.9, ...
    'HandleVisibility', 'off');

xline( ...
    axD, ...
    0, ...
    ':', ...
    'Color', [0.00 0.45 0.75], ...
    'LineWidth', 0.9, ...
    'HandleVisibility', 'off');

xlim(axD, [-5.2, 10.6]);
ylim(axD, [-0.0025, 0.0165]);

xlabel(axD, 'Pooled gain versus direct (%)');
ylabel(axD, 'Worst target-budget regret');

legend( ...
    axD, ...
    [hDev hFrozen hConfirm], ...
    'Location', 'northeast', ...
    'Box', 'off', ...
    'FontSize', 8.5);

set(axD, ...
    'XGrid', 'on', ...
    'YGrid', 'on');

axD.GridAlpha = 0.14;
cmdo_safe_apply_axes_style(axD);

% Default label positions.
defaultLabelPosD = [ ...
    -3.85,  0.01355; ...
     2.25,  0.01460; ...
     4.10,  0.00505; ...
     8.35,  0.00370; ...
    -0.95,  0.00215; ...
     2.60,  0.00115; ...
     3.25, -0.00175];

labelPosFileD = fullfile( ...
    outDir, ...
    'Figure4_panelD_label_positions.mat');

labelPosD = defaultLabelPosD;

if exist(labelPosFileD, 'file')
    savedLabelData = load(labelPosFileD);

    if isfield(savedLabelData, 'labelPosD') && ...
            isequal(size(savedLabelData.labelPosD), [7 2])

        labelPosD = savedLabelData.labelPosD;
    end
end

labelHandlesD = gobjects(7, 1);
leaderHandlesD = gobjects(7, 1);

for k = 1:7
    anchor = [gainD(k), regretD(k)];

    leaderHandlesD(k) = plot( ...
        axD, ...
        [anchor(1), labelPosD(k, 1)], ...
        [anchor(2), labelPosD(k, 2)], ...
        '-', ...
        'Color', [0.30 0.30 0.30], ...
        'LineWidth', 0.70, ...
        'HandleVisibility', 'off');

    labelHandlesD(k) = text( ...
        axD, ...
        labelPosD(k, 1), ...
        labelPosD(k, 2), ...
        labelD(k), ...
        'FontName', 'Arial', ...
        'FontSize', 7.0, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'BackgroundColor', 'w', ...
        'EdgeColor', 'none', ...
        'Margin', 0.5, ...
        'Clipping', 'off', ...
        'PickableParts', 'all', ...
        'HitTest', 'on');

    setappdata( ...
        labelHandlesD(k), ...
        'AnchorPoint', ...
        anchor);

    setappdata( ...
        labelHandlesD(k), ...
        'LeaderHandle', ...
        leaderHandlesD(k));

    labelHandlesD(k).ButtonDownFcn = ...
        @(src, ~) f4_start_label_drag(src, fig);
end

%% Canonical-data audit
fprintf('\nFigure 4 canonical-data audit:\n');

fprintf( ...
    '  Panel b: U6 = %d, U7 AUC = %d, max identity residual = %.3g\n', ...
    height(D.u6_rep), ...
    height(u7AUC), ...
    maxResidual);

fprintf( ...
    '  Panel c group sizes: %s\n', ...
    sprintf('%d ', cellfun(@numel, vals)));

fprintf( ...
    '  Panel d trajectory points = %d\n', ...
    numel(labelD));

%% Optional manual adjustment of panel-d labels
drawnow;

if MANUAL_PANEL_D_LABELS && usejava('desktop')
    instructionBox = annotation( ...
        fig, ...
        'textbox', ...
        [0.215 0.006 0.500 0.032], ...
        'String', ...
        'Drag panel c worst labels and panel d point labels, then click Save label positions', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Arial', ...
        'FontSize', 9, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [1.00 1.00 0.88], ...
        'EdgeColor', [0.65 0.65 0.45], ...
        'FitBoxToText', 'off');

    finishButton = uicontrol( ...
        fig, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.735 0.007 0.170 0.034], ...
        'String', 'Save label positions', ...
        'FontSize', 9, ...
        'FontWeight', 'bold', ...
        'Callback', @(~, ~) uiresume(fig));

    uiwait(fig);

    if ~isgraphics(fig)
        return;
    end

    % Save panel C label positions
    labelPosC = nan(numel(labelHandlesC), 2);
    for k = 1:numel(labelHandlesC)
        p = labelHandlesC(k).Position;
        labelPosC(k,:) = p(1:2);
    end
    save(labelPosFileC, 'labelPosC');

    % Save panel D label positions
    labelPosD = nan(7, 2);
    for k = 1:7
        p = labelHandlesD(k).Position;
        labelPosD(k,:) = p(1:2);
    end
    save(labelPosFileD, 'labelPosD', 'labelD');

    if isgraphics(finishButton)
        delete(finishButton);
    end

    if isgraphics(instructionBox)
        delete(instructionBox);
    end
end

%% Export
drawnow;

cmdo_safe_save_figure( ...
    fig, ...
    cfg, ...
    'Figure4_Pair_Complete_Observer');

end


function f4_draw_pair_matrix(ax, x0, y0, width, height, pairComplete)
% Draw a coloured 2-by-2 pair-coverage matrix.

cellWidth = width / 2;
cellHeight = height / 2;

labels = { ...
    'P_A \times N_A', ...
    'P_A \times N_B', ...
    'P_B \times N_A', ...
    'P_B \times N_B'};

for q = 1:4
    col = mod(q - 1, 2);
    row = floor((q - 1) / 2);

    kept = pairComplete || q == 1 || q == 4;

    if kept
        faceColor = [0.88 0.96 0.90];
        statusText = 'kept';
    else
        faceColor = [1.00 0.90 0.90];
        statusText = 'discarded';
    end

    x = x0 + col * cellWidth;
    y = y0 + (1 - row) * cellHeight;

    rectangle( ...
        ax, ...
        'Position', [x y cellWidth cellHeight], ...
        'FaceColor', faceColor, ...
        'EdgeColor', [0.35 0.35 0.35], ...
        'LineWidth', 0.8);

    text( ...
        ax, ...
        x + 0.5 * cellWidth, ...
        y + 0.62 * cellHeight, ...
        labels{q}, ...
        'Interpreter', 'tex', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontSize', 9.5);

    text( ...
        ax, ...
        x + 0.5 * cellWidth, ...
        y + 0.30 * cellHeight, ...
        statusText, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontSize', 8.5, ...
        'FontWeight', 'bold');
end

end


function f4_violin(ax, xCenter, values, faceColor, maxHalfWidth)
% Draw a toolbox-independent Gaussian KDE violin.

values = double(values(:));
values = values(isfinite(values));

if numel(values) < 2
    return;
end

vMin = min(values);
vMax = max(values);

if vMax <= vMin
    vMin = vMin - 1e-6;
    vMax = vMax + 1e-6;
end

yGrid = linspace(vMin, vMax, 180)';

sigmaV = std(values, 0);

bandwidth = ...
    1.06 * sigmaV * numel(values)^(-1/5);

if ~isfinite(bandwidth) || bandwidth <= 0
    bandwidth = max((vMax - vMin) / 20, eps);
end

z = ...
    (yGrid - values') ...
    ./ bandwidth;

density = ...
    mean(exp(-0.5 * z.^2), 2) ...
    ./ (bandwidth * sqrt(2*pi));

maxDensity = max(density);

if ~isfinite(maxDensity) || maxDensity <= 0
    return;
end

halfWidth = ...
    maxHalfWidth ...
    * density ...
    / maxDensity;

patch( ...
    ax, ...
    [xCenter - halfWidth; ...
     flipud(xCenter + halfWidth)], ...
    [yGrid; flipud(yGrid)], ...
    faceColor, ...
    'FaceAlpha', 0.26, ...
    'EdgeColor', 'none', ...
    'HandleVisibility', 'off');

end


function f4_start_label_drag(labelHandle, figHandle)
% Start dragging one panel-d label.

if ~isgraphics(labelHandle) || ~isgraphics(figHandle)
    return;
end

set(figHandle, ...
    'Pointer', 'fleur', ...
    'WindowButtonMotionFcn', ...
    @(~, ~) f4_drag_label(labelHandle), ...
    'WindowButtonUpFcn', ...
    @(~, ~) f4_stop_label_drag(figHandle));

end


function f4_drag_label(labelHandle)
% Move one label and update its leader line.

if ~isgraphics(labelHandle)
    return;
end

ax = ancestor(labelHandle, 'axes');

if isempty(ax) || ~isgraphics(ax)
    return;
end

point = ax.CurrentPoint;

x = point(1, 1);
y = point(1, 2);

xLimits = ax.XLim;
yLimits = ax.YLim;

xPad = 0.025 * diff(xLimits);
yPad = 0.040 * diff(yLimits);

x = min( ...
    max(x, xLimits(1) + xPad), ...
    xLimits(2) - xPad);

y = min( ...
    max(y, yLimits(1) + yPad), ...
    yLimits(2) - yPad);

labelHandle.Position = [x y 0];

anchor = getappdata(labelHandle, 'AnchorPoint');
leader = getappdata(labelHandle, 'LeaderHandle');

if isgraphics(leader)
    leader.XData = [anchor(1), x];
    leader.YData = [anchor(2), y];
end

drawnow limitrate nocallbacks;

end


function f4_stop_label_drag(figHandle)
% Finish dragging.

if ~isgraphics(figHandle)
    return;
end

set(figHandle, ...
    'Pointer', 'arrow', ...
    'WindowButtonMotionFcn', '', ...
    'WindowButtonUpFcn', '');

end
