function Figure1_IDA_RealData_Final(outputDir)
% FIGURE1_IDA_REALDATA_FINAL
% CMDO Figure 1 — old visual language retained, but with one unified Panel B.
%
% A  Monitoring does not establish performance
% B  The evidential order of post-deployment evaluation
%
% Panel B keeps the previous three-column visual grammar:
%   IDENTIFY -> REUSE -> PRESERVE
% while treating them as three sequential steps inside ONE panel.
%
% Scientific mapping:
%   IDENTIFY = Performance observability   (Delta_E)
%   REUSE  = Evidence admissibility      (Lambda)
%   PRESERVE = Adaptive composability      (Xi)

clc;
close all;

%% ========================================================================
%  USER-ADJUSTABLE DISPLAY CONTROLS
%  ========================================================================
FONT_SCALE = 1.34;
CANVAS = [30 30 940 800];

%% ------------------------------------------------------------------------
%  Load frozen real assets
%  ------------------------------------------------------------------------
[A, assetPath] = load_frozen_assets();

assert(isfield(A,'images') && numel(A.images) >= 4, ...
    'Need >=4 frozen image assets.');
assert(isfield(A,'tables') && numel(A.tables) >= 1, ...
    'Need >=1 frozen table asset.');
assert(isfield(A,'witnesses') && numel(A.witnesses) >= 2, ...
    'Need >=2 frozen U11 witnesses.');

W  = A.witnesses(1);
W2 = A.witnesses(2);

requiredWitnessFields = { ...
    'score','success_outcome','failure_outcome', ...
    'auc_success','auc_failure','name'};
for k = 1:numel(requiredWitnessFields)
    assert(isfield(W,requiredWitnessFields{k}), ...
        'Witness field missing: %s', requiredWitnessFields{k});
end

fprintf('\n============================================================\n');
fprintf(' CMDO FIGURE 1 — EVIDENTIAL ORDER\n');
fprintf('============================================================\n');
fprintf('Frozen asset package:\n  %s\n', assetPath);
fprintf('Primary U11 witness : %s | AUC %.2f <-> %.2f\n', ...
    char(string(W.name)), double(W.auc_success), double(W.auc_failure));
fprintf('Replication witness : %s | AUC %.2f <-> %.2f\n', ...
    char(string(W2.name)), double(W2.auc_success), double(W2.auc_failure));

%% ------------------------------------------------------------------------
%  Style / canvas
%  ------------------------------------------------------------------------
S = style_spec(FONT_SCALE);
fig = figure( ...
    'Color','w', ...
    'Units','pixels', ...
    'Position',CANVAS, ...
    'Renderer','painters', ...
    'InvertHardcopy','off');

%% ------------------------------------------------------------------------
%  Global geometry
%  ------------------------------------------------------------------------
x0 = 0.018;
right = 0.985;

Apos = [x0 0.655 right-x0 0.315];
Bpos = [x0 0.055 right-x0 0.565];

axA = panel_axes( ...
    fig, Apos, S, 'A', ...
    'Monitoring does not establish performance', S.blue);

axB = panel_axes( ...
    fig, Bpos, S, 'B', ...
    'The evidential order of post-deployment evaluation', S.purple);

%% ========================================================================
%  A — THE PROBLEM
%  Keep previous composition essentially unchanged.
%  ========================================================================
inputX = 0.020;
inputW = 0.300;

draw_real_image_triplet( ...
    fig, axA, A.images, [2 3 4], ...
    [inputX 0.505 inputW 0.300], S);

draw_real_table_snippet( ...
    axA, A.tables(1), ...
    [inputX 0.275 inputW 0.180], S);

arrow_norm(axA,[0.335 0.565],[0.382 0.565],S.axis,1.6);
draw_model_box(axA,[0.392 0.355 0.090 0.380],S);
arrow_norm(axA,[0.488 0.565],[0.545 0.565],S.axis,1.6);

draw_score_stream( ...
    fig, axA, W, ...
    [0.560 0.410 0.185 0.310], S, false);

arrow_norm(axA,[0.750 0.565],[0.792 0.565],S.axis,1.6);

text(axA,0.815,0.575,'?', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,31), ...
    'FontWeight','bold', ...
    'Color',S.red);

arrow_norm(axA,[0.837 0.565],[0.875 0.565],S.axis,1.6);

draw_hidden_gauge(axA,[0.885 0.410 0.085 0.300],S);

text(axA,0.985,0.360,{'current';'performance'}, ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.2), ...
    'Color',S.text);

text(axA,0.50,0.115,'Monitoring \neq performance knowledge', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,12.0), ...
    'FontWeight','bold', ...
    'Color',S.red);

%% ========================================================================
%  B — ONE PANEL, OLD THREE-COLUMN VISUAL LANGUAGE
%  KNOW -> REUSE -> TRUST
%  ========================================================================

% Three internal cards preserve the previous B/C/D visual rhythm.
cardY = 0.075;
cardH = 0.790;

pKnow  = [0.020 cardY 0.292 cardH];
pReuse = [0.354 cardY 0.292 cardH];
pTrust = [0.688 cardY 0.292 cardH];

round_box(axB,pKnow, [0.992 0.996 1.000], 0.72*[1 1 1]+0.28*S.blue, 0.8);
round_box(axB,pReuse,[0.992 1.000 0.994], 0.72*[1 1 1]+0.28*S.green,0.8);
round_box(axB,pTrust,[1.000 0.994 0.992], 0.72*[1 1 1]+0.28*S.red,  0.8);

% Sequential connectors: one chain, not three separate contributions.
arrow_norm(axB,[0.317 0.785],[0.349 0.785],S.axis,1.45);
arrow_norm(axB,[0.651 0.785],[0.683 0.785],S.axis,1.45);

%% ------------------------------------------------------------------------
%  IDENTIFY
%  ------------------------------------------------------------------------
text(axB,0.166,0.820,'IDENTIFY', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,11.5), ...
    'FontWeight','bold', ...
    'Color',S.blue);

text(axB,0.166,0.772,'Observability   $\Delta_{\mathcal{E}}$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.6), ...
    'Color',S.blue);

draw_score_stream( ...
    fig, axB, W, ...
    [0.050 0.545 0.230 0.135], S, true);

draw_world_roc( ...
    fig, axB, W, true, ...
    [0.043 0.205 0.118 0.255], S);

draw_world_roc( ...
    fig, axB, W, false, ...
    [0.171 0.205 0.118 0.255], S);

% Constructed observationally equivalent worlds.
text(axB,0.102,0.470,'World +', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.4), ...
    'FontWeight','bold', ...
    'Color',S.blue);

text(axB,0.230,0.470,'World -', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.4), ...
    'FontWeight','bold', ...
    'Color',S.red);

draw_role_strip( ...
    axB,[0.035 0.105 0.262 0.075], ...
    S.bluePale,S.blue, ...
    '$\Delta_{\mathcal{E}}$ / IDENTIFY', ...
    'Performance observability',S);

%% ------------------------------------------------------------------------
%  REUSE
%  ------------------------------------------------------------------------
text(axB,0.500,0.820,'REUSE', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,11.5), ...
    'FontWeight','bold', ...
    'Color',S.green);

text(axB,0.500,0.772,'Admissibility   $\Lambda$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.6), ...
    'Color',S.green);

draw_current_audit(axB,[0.372 0.555 0.118 0.120],S);
draw_history_evidence(axB,[0.510 0.555 0.118 0.120],S);

text(axB,0.425,0.500,'uncertainty  V', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,5.7), ...
    'Color',S.muted);

text(axB,0.575,0.500,'mismatch  B', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,5.7), ...
    'Color',S.muted);

arrow_norm(axB,[0.425 0.485],[0.475 0.425],S.muted,1.0);
arrow_norm(axB,[0.575 0.485],[0.525 0.425],S.muted,1.0);

round_box(axB,[0.425 0.345 0.150 0.090],S.greenPale,S.green,1.05);
text(axB,0.500,0.390,'\Lambda = B^2 / V', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,8.8), ...
    'FontWeight','bold', ...
    'Color',S.green);

% Restore the previous simple borrow / fallback geometry.
arrow_norm(axB,[0.500 0.340],[0.430 0.280],S.axis,1.0);
arrow_norm(axB,[0.500 0.340],[0.570 0.280],S.axis,1.0);

round_box(axB,[0.382 0.215 0.105 0.072],[0.985 0.995 0.988],S.green,0.9);
text(axB,0.435,0.251,'borrow', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.3), ...
    'FontWeight','bold', ...
    'Color',S.green);

round_box(axB,[0.513 0.215 0.105 0.072],[0.985 0.985 0.988],S.muted,0.9);
text(axB,0.565,0.251,'fallback', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.3), ...
    'FontWeight','bold', ...
    'Color',S.muted);

draw_role_strip( ...
    axB,[0.369 0.105 0.262 0.075], ...
    S.greenPale,S.green, ...
    '$\Lambda$ / REUSE', ...
    'Evidence admissibility',S);

%% ------------------------------------------------------------------------
%  PRESERVE
%  ------------------------------------------------------------------------
text(axB,0.834,0.820,'PRESERVE', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,11.5), ...
    'FontWeight','bold', ...
    'Color',S.red);

text(axB,0.834,0.772,'Composability   $\Xi$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.6), ...
    'Color',S.red);

draw_composition_case( ...
    axB,[0.720 0.470 0.235 0.170],S,'preserved',true);

draw_composition_case( ...
    axB,[0.720 0.260 0.235 0.170],S,'consumed',false);

round_box(axB,[0.785 0.185 0.105 0.055],S.redPale,S.red,0.9);
text(axB,0.837,0.212,'\Xi', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,8.0), ...
    'FontWeight','bold', ...
    'Color',S.red);

draw_role_strip( ...
    axB,[0.703 0.105 0.262 0.075], ...
    S.redPale,S.red, ...
    '$\Xi$ / PRESERVE', ...
    'Adaptive composability',S);

%% ------------------------------------------------------------------------
%  Export
%  ------------------------------------------------------------------------
if nargin < 1 || isempty(outputDir)
    thisFile = mfilename('fullpath');
    if isempty(thisFile)
        scriptDir = pwd;
    else
        scriptDir = fileparts(thisFile);
    end
    outputDir = fullfile(scriptDir,'output');
end

if ~isfolder(outputDir)
    mkdir(outputDir);
end

pngPath = fullfile(outputDir,'Figure1_Evidential_Order_Final_Worlds.png');
pdfPath = fullfile(outputDir,'Figure1_Evidential_Order_Final_Worlds.pdf');

exportgraphics(fig,pngPath,'Resolution',600);
exportgraphics(fig,pdfPath,'ContentType','vector');

fprintf('\n============================================================\n');
fprintf(' DONE\n');
fprintf('============================================================\n');
fprintf('PNG:\n  %s\n',pngPath);
fprintf('PDF:\n  %s\n',pdfPath);
fprintf('\nScientific note: Figure 1 uses one Panel B: IDENTIFY -> REUSE -> PRESERVE.\n');

end


%% ========================================================================
%  LOAD FROZEN ASSETS
%  ========================================================================

function [A, matPath] = load_frozen_assets()
% Load the unique repository-frozen submission asset.
%
% Canonical location:
%   source_data/figure1_assets/Figure1_assets_selected_v1.mat
%
% No recursive filesystem search is used in the submission renderer.

thisFile = mfilename('fullpath');

if isempty(thisFile)
    error( ...
        'CMDO:Figure1PathResolution', ...
        'Could not resolve Figure1_IDA_RealData_Final.m path.');
end

mainDir    = fileparts(thisFile);
figuresDir = fileparts(mainDir);
matlabDir  = fileparts(figuresDir);
repoRoot   = fileparts(matlabDir);

matPath = fullfile( ...
    repoRoot, ...
    'source_data', ...
    'figure1_assets', ...
    'Figure1_assets_selected_v1.mat');

if ~isfile(matPath)
    error( ...
        'CMDO:Figure1AssetMissing', ...
        'Frozen Figure 1 asset is missing: %s', ...
        matPath);
end

q = whos( ...
    '-file', ...
    matPath);

vars = string({q.name});

if ~any(vars == "Assets")
    error( ...
        'CMDO:Figure1AssetInvalid', ...
        'Frozen Figure 1 asset does not contain variable Assets: %s', ...
        matPath);
end

Q = load( ...
    matPath, ...
    'Assets');

A = Q.Assets;

fprintf( ...
    'Figure 1 frozen asset:\n%s\n', ...
    matPath);

end
%% ========================================================================
%  STYLE
%  ========================================================================

function S = style_spec(fontScale)


S.font = 'Arial';

S.scale = fontScale;


% -------------------------------------------------------------------------
% Text / axes
% -------------------------------------------------------------------------
S.text = ...
    [0.08 0.10 0.14];


S.axis = ...
    [0.22 0.24 0.28];


S.muted = ...
    [0.42 0.44 0.49];


S.line = ...
    [0.76 0.78 0.82];


% -------------------------------------------------------------------------
% Scientific colours
% -------------------------------------------------------------------------
S.blue = ...
    [0.04 0.25 0.66];


S.green = ...
    [0.02 0.42 0.18];


S.red = ...
    [0.80 0.08 0.07];


S.purple = ...
    [0.34 0.22 0.58];


% -------------------------------------------------------------------------
% Pale fills
% -------------------------------------------------------------------------
S.bluePale = ...
    [0.965 0.980 1.000];


S.greenPale = ...
    [0.965 0.995 0.972];


S.redPale = ...
    [1.000 0.972 0.965];


end


function v = F(S,x)

v = S.scale*x;

end


%% ========================================================================
%  PANEL FRAME / GEOMETRY
%  ========================================================================

function ax = panel_axes( ...
    fig, ...
    pos, ...
    S, ...
    letter, ...
    ttl, ...
    accent)


ax = axes( ...
    fig, ...
    'Position',pos);


axis(ax,[0 1 0 1]);
axis(ax,'off');

hold(ax,'on');

turn_off_toolbar(ax);


rectangle( ...
    ax, ...
    'Position',[0.003 0.003 0.994 0.994], ...
    'Curvature',[0.018 0.018], ...
    'FaceColor','w', ...
    'EdgeColor',0.70*[1 1 1]+0.30*accent, ...
    'LineWidth',1.0);


% -------------------------------------------------------------------------
% Panel letter
% -------------------------------------------------------------------------
text( ...
    ax, ...
    0.025, ...
    0.947, ...
    letter, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,13.5), ...
    'FontWeight','bold', ...
    'Color',accent);


% -------------------------------------------------------------------------
% Panel title
% -------------------------------------------------------------------------
text( ...
    ax, ...
    0.115, ...
    0.947, ...
    ttl, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',S.font, ...
    'FontSize',F(S,10.2), ...
    'FontWeight','bold', ...
    'Color',accent);


end


function round_box( ...
    ax, ...
    p, ...
    face, ...
    edge, ...
    lw)


rectangle( ...
    ax, ...
    'Position',p, ...
    'Curvature',[0.04 0.04], ...
    'FaceColor',face, ...
    'EdgeColor',edge, ...
    'LineWidth',lw);


end


function arrow_norm( ...
    ax, ...
    p1, ...
    p2, ...
    c, ...
    lw)


quiver( ...
    ax, ...
    p1(1), ...
    p1(2), ...
    p2(1)-p1(1), ...
    p2(2)-p1(2), ...
    0, ...
    'Color',c, ...
    'LineWidth',lw, ...
    'MaxHeadSize',0.85);


end


function p = relpos( ...
    parentPos, ...
    r)


p = [ ...
    parentPos(1)+r(1)*parentPos(3), ...
    parentPos(2)+r(2)*parentPos(4), ...
    r(3)*parentPos(3), ...
    r(4)*parentPos(4)];


end


function turn_off_toolbar(ax)


try

    ax.Toolbar.Visible = 'off';

catch

end


try

    disableDefaultInteractivity(ax);

catch

end


end


%% ========================================================================
%  A — REAL IMAGES
%  ========================================================================

function draw_real_image_triplet( ...
    fig, ...
    ax, ...
    images, ...
    idx, ...
    r, ...
    S)


P = ax.Position;


labels = { ...
    'Dermoscopy', ...
    'Breast ultrasound', ...
    'Retinal fundus'};


gap = 0.010;


tw = ...
    (r(3)-2*gap)/3;


for k = 1:3


    rr = [ ...
        r(1)+(k-1)*(tw+gap), ...
        r(2), ...
        tw, ...
        r(4)];


    a = axes( ...
        fig, ...
        'Position', ...
        relpos( ...
        P, ...
        [ ...
        rr(1), ...
        rr(2)+0.11*rr(4), ...
        rr(3), ...
        0.72*rr(4)]));


    turn_off_toolbar(a);


    I = ...
        images(idx(k)).image;


    image(a,I);

    axis(a,'image');

    axis(a,'off');


    set( ...
        a, ...
        'YDir','reverse');


    rectangle( ...
        a, ...
        'Position', ...
        [ ...
        0.5 ...
        0.5 ...
        size(I,2)-1 ...
        size(I,1)-1], ...
        'EdgeColor',[0.72 0.72 0.72], ...
        'LineWidth',0.7);


    text( ...
        ax, ...
        rr(1)+rr(3)/2, ...
        rr(2)+0.98*rr(4), ...
        labels{k}, ...
        'HorizontalAlignment','center', ...
        'FontName',S.font, ...
        'FontSize',F(S,6.6), ...
        'Color',S.text);


end


end


%% ========================================================================
%  A — REAL TABLE PREVIEW
%  ========================================================================

function draw_real_table_snippet( ...
    ax, ...
    T, ...
    p, ...
    S)


round_box( ...
    ax, ...
    p, ...
    [0.997 0.998 1.000], ...
    [0.55 0.58 0.63], ...
    0.8);


M = ...
    double(T.preview);


names = ...
    string(T.varNames);


nr = ...
    min(3,size(M,1));


nc = ...
    min(4,size(M,2));


M = ...
    M(1:nr,1:nc);


names = ...
    names(1:nc);


x0 = ...
    p(1)+0.014;


y0 = ...
    p(2)+0.025;


W = ...
    p(3)-0.028;


H = ...
    p(4)-0.050;


rowH = ...
    H/(nr+1);


colW = ...
    W/nc;


% -------------------------------------------------------------------------
% Header background
% -------------------------------------------------------------------------
rectangle( ...
    ax, ...
    'Position', ...
    [ ...
    x0 ...
    y0+nr*rowH ...
    W ...
    rowH], ...
    'FaceColor',[0.92 0.95 0.98], ...
    'EdgeColor','none');


% -------------------------------------------------------------------------
% Horizontal grid
% -------------------------------------------------------------------------
for rr = 0:(nr+1)


    yy = ...
        y0 + rr*rowH;


    plot( ...
        ax, ...
        [x0 x0+W], ...
        [yy yy], ...
        '-', ...
        'Color',[0.68 0.70 0.74], ...
        'LineWidth',0.55);


end


% -------------------------------------------------------------------------
% Vertical grid
% -------------------------------------------------------------------------
for cc = 0:nc


    xx = ...
        x0 + cc*colW;


    plot( ...
        ax, ...
        [xx xx], ...
        [y0 y0+H], ...
        '-', ...
        'Color',[0.68 0.70 0.74], ...
        'LineWidth',0.55);


end


% -------------------------------------------------------------------------
% Column names
% -------------------------------------------------------------------------
for c = 1:nc


    nm = ...
        short_name( ...
        names(c), ...
        5);


    text( ...
        ax, ...
        x0+(c-0.5)*colW, ...
        y0+(nr+0.5)*rowH, ...
        char(nm), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontName',S.font, ...
        'FontSize',F(S,5.2), ...
        'FontWeight','bold', ...
        'Color',S.text);


end


% -------------------------------------------------------------------------
% Table values
% -------------------------------------------------------------------------
for r0 = 1:nr


    for c = 1:nc


        text( ...
            ax, ...
            x0+(c-0.5)*colW, ...
            y0+(nr-r0+0.5)*rowH, ...
            sprintf( ...
            '%.2f', ...
            M(r0,c)), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontName',S.font, ...
            'FontSize',F(S,5.0), ...
            'Color',S.text);


    end


end


% -------------------------------------------------------------------------
% Table title — outside / above box
% -------------------------------------------------------------------------
text( ...
    ax, ...
    p(1)+p(3)/2, ...
    p(2)+p(4)+0.025, ...
    'Tabular input', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.2), ...
    'FontWeight','bold', ...
    'Color',S.text);


end


function s = short_name( ...
    x, ...
    maxLen)


s = ...
    char(string(x));


s = ...
    strrep( ...
    s, ...
    '_', ...
    '');


if numel(s) > maxLen

    s = ...
        s(1:maxLen);

end


s = ...
    string(s);


end


%% ========================================================================
%  A — MODEL ICON
%  ========================================================================

function draw_model_box( ...
    ax, ...
    p, ...
    S)


round_box( ...
    ax, ...
    p, ...
    [0.975 0.985 1.000], ...
    S.blue, ...
    0.9);


pts = [ ...
    0.18 0.25; ...
    0.18 0.50; ...
    0.18 0.75; ...
    0.50 0.18; ...
    0.50 0.40; ...
    0.50 0.62; ...
    0.50 0.82; ...
    0.82 0.30; ...
    0.82 0.55; ...
    0.82 0.75];


pts(:,1) = ...
    p(1)+p(3)*pts(:,1);


pts(:,2) = ...
    p(2)+p(4)*(0.23+0.55*pts(:,2));


for i = 1:3


    for j = 4:7


        plot( ...
            ax, ...
            [pts(i,1) pts(j,1)], ...
            [pts(i,2) pts(j,2)], ...
            '-', ...
            'Color',[0.55 0.62 0.72], ...
            'LineWidth',0.45);


    end


end


for i = 4:7


    for j = 8:10


        plot( ...
            ax, ...
            [pts(i,1) pts(j,1)], ...
            [pts(i,2) pts(j,2)], ...
            '-', ...
            'Color',[0.55 0.62 0.72], ...
            'LineWidth',0.45);


    end


end


scatter( ...
    ax, ...
    pts(:,1), ...
    pts(:,2), ...
    28, ...
    'MarkerFaceColor',[0.65 0.78 0.95], ...
    'MarkerEdgeColor',S.blue, ...
    'LineWidth',0.7);


text( ...
    ax, ...
    p(1)+p(3)/2, ...
    p(2)+0.075*p(4), ...
    'AI model', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.0), ...
    'FontWeight','bold', ...
    'Color',S.text);


end


%% ========================================================================
%  A/B — FROZEN SCORE STREAM
%  ========================================================================

function draw_score_stream( ...
    fig, ...
    ax, ...
    W, ...
    r, ...
    S, ...
    withTitle)


P = ...
    ax.Position;


a = axes( ...
    fig, ...
    'Position', ...
    relpos(P,r));


turn_off_toolbar(a);

hold(a,'on');


s = ...
    double(W.score(:));


n = ...
    numel(s);


take = ...
    unique( ...
    round( ...
    linspace( ...
    1, ...
    n, ...
    min(260,n))));


xx = ...
    1:numel(take);


ss = ...
    s(take);


plot( ...
    a, ...
    xx, ...
    ss, ...
    '-', ...
    'Color',[0.48 0.48 0.48], ...
    'LineWidth',0.55);


scatter( ...
    a, ...
    xx, ...
    ss, ...
    7, ...
    'MarkerFaceColor',[0.36 0.36 0.36], ...
    'MarkerEdgeColor','none');


ylim(a,[0 1]);

xlim( ...
    a, ...
    [1 max(2,numel(xx))]);


set( ...
    a, ...
    'FontName',S.font, ...
    'FontSize',F(S,5.4), ...
    'Box','off', ...
    'TickDir','out', ...
    'XColor',S.axis, ...
    'YColor',S.axis, ...
    'YTick',[0 0.5 1]);


if withTitle


    title( ...
        a, ...
        'Frozen score stream', ...
        'FontName',S.font, ...
        'FontSize',F(S,7.2), ...
        'FontWeight','normal', ...
        'Color',S.text);


    set( ...
        a, ...
        'XTick', ...
        [ ...
        1 ...
        round(numel(xx)/2) ...
        numel(xx)], ...
        'XTickLabel', ...
        {'1','n/2','n'});


    ylabel( ...
        a, ...
        'score', ...
        'FontSize',F(S,5.8));


else


    set( ...
        a, ...
        'XTick',[], ...
        'YTick',[0 1]);


end


end


%% ========================================================================
%  A — HIDDEN PERFORMANCE GAUGE
%  ========================================================================

function draw_hidden_gauge( ...
    ax, ...
    p, ...
    S)


cx = ...
    p(1)+0.50*p(3);


cy = ...
    p(2)+0.38*p(4);


rx = ...
    0.48*p(3);


ry = ...
    0.36*p(4);


th = ...
    linspace( ...
    pi, ...
    0, ...
    120);


plot( ...
    ax, ...
    cx+rx*cos(th), ...
    cy+ry*sin(th), ...
    '-', ...
    'Color',S.axis, ...
    'LineWidth',2.0);


th1 = ...
    linspace( ...
    pi, ...
    2*pi/3, ...
    35);


th2 = ...
    linspace( ...
    2*pi/3, ...
    pi/3, ...
    35);


th3 = ...
    linspace( ...
    pi/3, ...
    0, ...
    35);


plot( ...
    ax, ...
    cx+0.90*rx*cos(th1), ...
    cy+0.90*ry*sin(th1), ...
    '-', ...
    'Color',[0.10 0.55 0.20], ...
    'LineWidth',3.0);


plot( ...
    ax, ...
    cx+0.90*rx*cos(th2), ...
    cy+0.90*ry*sin(th2), ...
    '-', ...
    'Color',[0.96 0.72 0.05], ...
    'LineWidth',3.0);


plot( ...
    ax, ...
    cx+0.90*rx*cos(th3), ...
    cy+0.90*ry*sin(th3), ...
    '-', ...
    'Color',S.red, ...
    'LineWidth',3.0);


needle = ...
    pi/6;


plot( ...
    ax, ...
    [ ...
    cx ...
    cx+0.55*rx*cos(needle)], ...
    [ ...
    cy ...
    cy+0.55*ry*sin(needle)], ...
    '-', ...
    'Color',S.text, ...
    'LineWidth',1.8);


scatter( ...
    ax, ...
    cx, ...
    cy, ...
    24, ...
    'MarkerFaceColor',S.text, ...
    'MarkerEdgeColor','none');


end


%% ========================================================================
%  B — WORLD ROC CURVES
%  ========================================================================

function draw_world_roc( ...
    fig, ...
    ax, ...
    W, ...
    isSuccess, ...
    p, ...
    S)


P = ...
    ax.Position;


if isSuccess


    y = ...
        double(W.success_outcome(:));


    aucShown = ...
        double(W.auc_success);


    edge = ...
        S.blue;


    face = ...
        S.bluePale;


else


    y = ...
        double(W.failure_outcome(:));


    aucShown = ...
        double(W.auc_failure);


    edge = ...
        S.red;


    face = ...
        S.redPale;


end


s = ...
    double(W.score(:));


round_box( ...
    ax, ...
    p, ...
    face, ...
    edge, ...
    0.9);


[FPR,TPR] = ...
    local_roc( ...
    y, ...
    s);


a = axes( ...
    fig, ...
    'Position', ...
    relpos( ...
    P, ...
    [ ...
    p(1)+0.11*p(3), ...
    p(2)+0.26*p(4), ...
    0.77*p(3), ...
    0.55*p(4)]));


turn_off_toolbar(a);

hold(a,'on');


plot( ...
    a, ...
    FPR, ...
    TPR, ...
    '-', ...
    'Color',edge, ...
    'LineWidth',1.5);


markStep = ...
    max( ...
    1, ...
    round( ...
    numel(FPR)/20));


markIdx = ...
    1:markStep:numel(FPR);


scatter( ...
    a, ...
    FPR(markIdx), ...
    TPR(markIdx), ...
    8, ...
    'MarkerFaceColor',edge, ...
    'MarkerEdgeColor','none');


plot( ...
    a, ...
    [0 1], ...
    [0 1], ...
    '--', ...
    'Color',[0.80 0.80 0.80], ...
    'LineWidth',0.6);


axis(a,[0 1 0 1]);


set( ...
    a, ...
    'FontName',S.font, ...
    'FontSize',F(S,4.7), ...
    'Box','off', ...
    'TickDir','out', ...
    'XTick',[0 1], ...
    'YTick',[0 1], ...
    'XColor',S.axis, ...
    'YColor',S.axis);


text( ...
    ax, ...
    p(1)+0.50*p(3), ...
    p(2)+0.075*p(4), ...
    sprintf( ...
    'AUC = %.2f', ...
    aucShown), ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.4), ...
    'FontWeight','normal', ...
    'Color',edge);


end


function [fpr,tpr] = local_roc( ...
    y, ...
    s)


y = ...
    double(y(:));


s = ...
    double(s(:));


valid = ...
    isfinite(y) & ...
    isfinite(s);


y = ...
    y(valid);


s = ...
    s(valid);


[ss,ord] = ...
    sort( ...
    s, ...
    'descend');


yy = ...
    y(ord);


P = ...
    sum(yy==1);


N = ...
    sum(yy==0);


assert( ...
    P>0 && N>0, ...
    'ROC requires both outcome classes.');


tp = ...
    cumsum(yy==1);


fp = ...
    cumsum(yy==0);


change = [ ...
    find(diff(ss)~=0); ...
    numel(ss)];


tpr = [ ...
    0; ...
    tp(change)/P; ...
    1];


fpr = [ ...
    0; ...
    fp(change)/N; ...
    1];


end


%% ========================================================================
%  B/C/D — ROLE STRIP
%  ========================================================================

function draw_role_strip( ...
    ax, ...
    p, ...
    face, ...
    edge, ...
    line1, ...
    line2, ...
    S)


round_box( ...
    ax, ...
    p, ...
    face, ...
    edge, ...
    0.9);


text( ...
    ax, ...
    p(1)+p(3)/2, ...
    p(2)+0.61*p(4), ...
    line1, ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,8.8), ...
    'FontWeight','bold', ...
    'Color',edge);


text( ...
    ax, ...
    p(1)+p(3)/2, ...
    p(2)+0.24*p(4), ...
    line2, ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,5.7), ...
    'Color',edge);


end


%% ========================================================================
%  C — CURRENT AUDIT
%  ========================================================================

function draw_current_audit( ...
    ax, ...
    p, ...
    S)


text( ...
    ax, ...
    p(1)+0.50*p(3), ...
    p(2)+0.92*p(4), ...
    'current audit', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.0), ...
    'FontWeight','bold', ...
    'Color',S.text);


x0 = ...
    p(1)+0.12*p(3);


y = ...
    p(2)+0.56*p(4);


for k = 1:5


    scatter( ...
        ax, ...
        x0+(k-1)*0.16*p(3), ...
        y, ...
        40, ...
        'MarkerFaceColor','w', ...
        'MarkerEdgeColor',S.text, ...
        'LineWidth',0.8);


end


text( ...
    ax, ...
    p(1)+0.50*p(3), ...
    p(2)+0.20*p(4), ...
    'm \uparrow   V \downarrow', ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.4), ...
    'Color',S.green);


end


%% ========================================================================
%  C — HISTORICAL EVIDENCE
%  ========================================================================

function draw_history_evidence( ...
    ax, ...
    p, ...
    S)


text( ...
    ax, ...
    p(1)+0.50*p(3), ...
    p(2)+0.92*p(4), ...
    'historical evidence', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.0), ...
    'FontWeight','bold', ...
    'Color',S.text);


x0 = ...
    p(1)+0.15*p(3);


y = ...
    p(2)+0.50*p(4);


for k = 1:4


    rectangle( ...
        ax, ...
        'Position', ...
        [ ...
        x0+(k-1)*0.18*p(3), ...
        y, ...
        0.085*p(3), ...
        0.22*p(4)], ...
        'FaceColor', ...
        0.72*[1 1 1]+0.28*S.purple, ...
        'EdgeColor',S.purple, ...
        'LineWidth',0.8);


end


text( ...
    ax, ...
    p(1)+0.50*p(3), ...
    p(2)+0.18*p(4), ...
    'candidate reuse', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.2), ...
    'Color',S.muted);


end


%% ========================================================================
%  D — COMPOSITION CASES
%  ========================================================================

function draw_composition_case( ...
    ax, ...
    p, ...
    S, ...
    label, ...
    isPreserved)


if isPreserved


    edge = ...
        S.green;


    face = ...
        S.greenPale;


else


    edge = ...
        S.red;


    face = ...
        S.redPale;


end


round_box( ...
    ax, ...
    p, ...
    face, ...
    edge, ...
    0.9);


text( ...
    ax, ...
    p(1)+0.50*p(3), ...
    p(2)+0.83*p(4), ...
    ['benefit ' label], ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,7.3), ...
    'FontWeight','bold', ...
    'Color',edge);


% -------------------------------------------------------------------------
% Fixed composition
% -------------------------------------------------------------------------
fx = ...
    p(1)+0.12*p(3);


fy = ...
    p(2)+0.36*p(4);


for k = 1:4


    rectangle( ...
        ax, ...
        'Position', ...
        [ ...
        fx+(k-1)*0.075*p(3), ...
        fy, ...
        0.040*p(3), ...
        0.16*p(4)], ...
        'FaceColor', ...
        0.72*[1 1 1]+0.28*S.blue, ...
        'EdgeColor',S.blue, ...
        'LineWidth',0.7);


end


text( ...
    ax, ...
    p(1)+0.235*p(3), ...
    p(2)+0.12*p(4), ...
    'fixed', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.3), ...
    'Color',S.muted);


% -------------------------------------------------------------------------
% Arrow
% -------------------------------------------------------------------------
arrow_norm( ...
    ax, ...
    [ ...
    p(1)+0.405*p(3) ...
    p(2)+0.44*p(4)], ...
    [ ...
    p(1)+0.580*p(3) ...
    p(2)+0.44*p(4)], ...
    S.axis, ...
    1.0);


% -------------------------------------------------------------------------
% Adaptive composition
% -------------------------------------------------------------------------
ax0 = ...
    p(1)+0.64*p(3);


ay0 = ...
    p(2)+0.44*p(4);


if isPreserved


    sizes = ...
        [65 55 45 35 26];


else


    sizes = ...
        [70 70 70 70 70];


end


for k = 1:numel(sizes)


    scatter( ...
        ax, ...
        ax0+(k-1)*0.065*p(3), ...
        ay0, ...
        sizes(k), ...
        'MarkerFaceColor',S.red, ...
        'MarkerEdgeColor',[0.45 0 0], ...
        'LineWidth',0.6);


end


text( ...
    ax, ...
    p(1)+0.770*p(3), ...
    p(2)+0.12*p(4), ...
    'adaptive', ...
    'HorizontalAlignment','center', ...
    'FontName',S.font, ...
    'FontSize',F(S,6.3), ...
    'Color',S.muted);


end