function Figure3
%FIGURE3 Full-information CMDO Figure 3.
% Restores the complete canonical data content of the original figure:
%   a: U4C heatmap + late-budget bar comparison
%   b: all U5B states + LOWESS + cluster-bootstrap interval + risk model
%   c: all 13 development/frozen/independent candidates
%   d: all U5B states + LOWESS + cluster-bootstrap interval
%
% Panel-c labels can be dragged manually. Their positions are saved and
% automatically reused on the next run.

close all;

%% User option
MANUAL_PANEL_C_LABELS = ~strcmp(getenv('CMDO_BATCH_MODE'), '1');

%% Project and canonical records
scriptDir = fileparts(mfilename('fullpath'));
if ~isempty(scriptDir)
    addpath(genpath(scriptDir));
end

cfg = cmdo_config('Figure3');
D = cmdo_load_all(cfg);
rng(20260728, 'twister');

outDir = cfg.outputDir;
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

%% Figure canvas and manually controlled layout
fig = figure( ...
    'Position', [25 25 1000 900], ...
    'Color', 'w', ...
    'Renderer', 'painters', ...
    'Name', 'CMDO Figure 3', ...
    'NumberTitle', 'off');

% -------------------------------------------------------------------------
% Manually controlled axes layout
% -------------------------------------------------------------------------

% -------------------------------------------------------------------------
% Panel a layout: heatmap on top, horizontal bar chart below
% -------------------------------------------------------------------------
axA = axes( ...
    fig, ...
    'Position', [0.055 0.775 0.250 0.180]);

axABar = axes( ...
    fig, ...
    'Position', [0.055 0.625 0.250 0.095]);

% Panel b:
% One full-size empirical axes. The theoretical model will later be
% inserted inside this axes as an inset.
axB = axes( ...
    fig, ...
    'Position', [0.545 0.585 0.410 0.305]);

% Panels c and d
axC = axes( ...
    fig, ...
    'Position', [0.055 0.105 0.425 0.335]);

axD = axes( ...
    fig, ...
    'Position', [0.545 0.105 0.420 0.335]);

% Group titles and panel letters
f3_panel_header(fig, [0.035 0.930 0.030 0.030], 'a', 16);
f3_panel_header(fig, [0.075 0.930 0.390 0.030], ...
    'A universal component law fails heterogeneously', 13);

f3_panel_header(fig, [0.525 0.930 0.030 0.030], 'b', 16);
f3_panel_header(fig, [0.565 0.930 0.400 0.030], ...
    'Target-specific bias predicts transport utility', 13);

f3_panel_header(fig, [0.035 0.465 0.030 0.030], 'c', 16);
f3_panel_header(fig, [0.075 0.465 0.390 0.030], ...
    'Average efficiency and tail safety are distinct objectives', 13);

f3_panel_header(fig, [0.525 0.465 0.030 0.030], 'd', 16);
f3_panel_header(fig, [0.565 0.465 0.400 0.030], ...
    'Selected borrowing declines with estimated transport bias', 13);

%% ------------------------------------------------------------------------
% a — simple layout: heatmap + colour bar + horizontal bar chart
% -------------------------------------------------------------------------

% If axA / axABar were created earlier, remove them and rebuild cleanly.
if exist('axA', 'var') && isgraphics(axA)
    delete(axA);
end
if exist('axABar', 'var') && isgraphics(axABar)
    delete(axABar);
end

% -----------------------------
% Panel-a geometry (simple)
% -----------------------------
pa_left   = 0.055;
pa_bottom = 0.595;
pa_width  = 0.275;

heat_h    = 0.200;   % flatter heatmap
bar_h     = 0.045;   % separate bar chart
gap_h     = 0.100;   % clear gap between them

cb_w      = 0.011;
cb_gap    = 0.012;

main_w    = pa_width - cb_w - cb_gap;

% Heatmap axes
axA = axes(fig, ...
    'Position', [pa_left, pa_bottom + bar_h + gap_h, main_w, heat_h]);

% Bar-chart axes
axABar = axes(fig, ...
    'Position', [pa_left+0.1, pa_bottom, main_w, bar_h]);

% -----------------------------
% Heatmap data
% -----------------------------
d = D.u4c_pred;

universalError  = abs(d.component_pred - d.truth_direct_mae);
rootBudgetError = abs(d.rootn_pred    - d.truth_direct_mae);

% Positive means universal component law is better
advantage = rootBudgetError - universalError;

targetOrder = string(D.u4c_fits.target);
budgetOrder = sort(unique(d.budget), 'descend');

H = NaN(numel(budgetOrder), numel(targetOrder));

for i = 1:numel(budgetOrder)
    for j = 1:numel(targetOrder)
        m = d.budget == budgetOrder(i) & string(d.target) == targetOrder(j);
        vals = advantage(m);
        vals = vals(isfinite(vals));
        if ~isempty(vals)
            H(i, j) = mean(vals);
        end
    end
end

% -----------------------------
% Heatmap
% -----------------------------
imagesc(axA, H);
colormap(axA, parula(256));

limH = max(abs(H(:)), [], 'omitnan');
if ~isfinite(limH) || limH <= 0
    limH = 1;
end
caxis(axA, [-limH, limH]);

% Flatten the heatmap visually
pbaspect(axA, [13 5 1]);

xticks(axA, 1:numel(targetOrder));

shortLabels = strings(size(targetOrder));
for j = 1:numel(targetOrder)
    shortLabels(j) = cmdo_short_target(targetOrder(j));
end

xticklabels(axA, shortLabels);
xtickangle(axA, 50);

yticks(axA, 1:numel(budgetOrder));
yticklabels(axA, string(budgetOrder));

xlabel(axA, 'Prospective target');
ylabel(axA, 'Outcome budget');

f3_style_axes(axA, 8.5);
axA.XAxis.TickLabelInterpreter = 'none';
axA.YAxis.TickLabelInterpreter = 'none';

% -----------------------------
% Colour bar (just for heatmap)
% -----------------------------
cb = colorbar(axA);
cb.Position = [ ...
    pa_left + main_w + cb_gap, ...
    pa_bottom + bar_h + gap_h+0.05, ...
    cb_w, ...
    heat_h-0.1];

cb.FontName = 'Arial';
cb.FontSize = 8;
cb.TickDirection = 'out';
cb.Label.String = 'root - universal';
cb.Label.FontName = 'Arial';
cb.Label.FontSize = 7.5;
cb.Label.FontWeight = 'normal';
cb.Label.Rotation = 90;

% -----------------------------
% Late-budget summary bar chart
% -----------------------------
uv = D.u4c_fits.component_late_mae;
rv = D.u4c_fits.rootn_late_mae;

validU = isfinite(uv);
validR = isfinite(rv);

meanLate = [mean(uv(validU)), mean(rv(validR))];
semLate  = [ ...
    std(uv(validU), 0) / sqrt(nnz(validU)), ...
    std(rv(validR), 0) / sqrt(nnz(validR))];

bars = barh(axABar, 1:2, meanLate, 0.55, 'FaceColor', 'flat');
bars.CData = [ ...
    0.12 0.47 0.71; ...
    1.00 0.50 0.05];

hold(axABar, 'on');

% Manual horizontal error bars
capHalf = 0.10;
for ii = 1:2
    plot(axABar, ...
        [meanLate(ii)-semLate(ii), meanLate(ii)+semLate(ii)], ...
        [ii ii], ...
        'k-', 'LineWidth', 1.1);

    plot(axABar, ...
        [meanLate(ii)-semLate(ii), meanLate(ii)-semLate(ii)], ...
        [ii-capHalf ii+capHalf], ...
        'k-', 'LineWidth', 1.1);

    plot(axABar, ...
        [meanLate(ii)+semLate(ii), meanLate(ii)+semLate(ii)], ...
        [ii-capHalf ii+capHalf], ...
        'k-', 'LineWidth', 1.1);
end

yticks(axABar, 1:2);
yticklabels(axABar, { ...
    'Universal component law', ...
    'Root-budget baseline'});

set(axABar, 'YDir', 'reverse');

xlabel(axABar, 'Late-budget trajectory MAE');

% Keep title short and clean
title(axABar, 'Late-budget MAE', ...
    'FontWeight', 'bold', ...
    'FontSize', 8.2);

nUniversalBetter = nnz(isfinite(uv) & isfinite(rv) & uv < rv);

text(axABar, ...
    0.98, 0.88, ...
    sprintf('%d/%d better', nUniversalBetter, numel(targetOrder)), ...
    'Units', 'normalized', ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'top', ...
    'FontName', 'Arial', ...
    'FontSize', 7.5, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', 'w', ...
    'EdgeColor', 'none', ...
    'Margin', 1.0);

xMaxBar = max(meanLate + semLate);
if ~isfinite(xMaxBar) || xMaxBar <= 0
    xMaxBar = 1;
end
xlim(axABar, [0, 1.15 * xMaxBar]);

f3_style_axes(axABar, 8);
axABar.XAxis.TickLabelInterpreter = 'none';
axABar.YAxis.TickLabelInterpreter = 'none';
axABar.XAxis.Exponent = 0;
grid(axABar, 'on');
axABar.GridAlpha = 0.10;

%% ------------------------------------------------------------------------
% b — all U5B states, LOWESS, cluster bootstrap and risk-optimal weight
% -------------------------------------------------------------------------
hold(axB, 'on');

families = [ ...
    "ACS_INCOME_2022", ...
    "MEDICAL_XRAY", ...
    "AMAZON_LANGUAGES"];

familyLabels = { ...
    'Population transfer', ...
    'Medical acquisition shifts', ...
    'Multilingual severe shift'};

familyMarkers = {'o', 's', '^'};

familyColors = [ ...
    0.1216 0.4667 0.7059; ...
    1.0000 0.4980 0.0549; ...
    0.1725 0.6275 0.1725];

xBias = D.u5b_state.mean_sentinel_bias_sq;
yUtility = D.u5b_state.sentinel_gain_vs_direct;

familyValue = string(D.u5b_state.family);
cluster = familyValue + "::" + string(D.u5b_state.target);

finiteB = ...
    isfinite(xBias) ...
    & isfinite(yUtility) ...
    & ~ismissing(cluster);

[gridB, fitB, loB, hiB] = cmdo_lowess_bootstrap( ...
    xBias(finiteB), ...
    yUtility(finiteB), ...
    cluster(finiteB), ...
    0.42, ...
    300, ...
    20260728);

gridB = gridB(:);
fitB = fitB(:);
loB = loB(:);
hiB = hiB(:);

hBandB = fill( ...
    axB, ...
    [gridB; flipud(gridB)], ...
    [loB; flipud(hiB)], ...
    [0.92 0.55 0.55], ...
    'FaceAlpha', 0.18, ...
    'EdgeColor', 'none', ...
    'DisplayName', '95% cluster bootstrap');

hLowessB = plot( ...
    axB, ...
    gridB, ...
    fitB, ...
    'Color', [0.05 0.45 0.82], ...
    'LineWidth', 2.0, ...
    'DisplayName', 'LOWESS');

scatterHandlesB = gobjects(3, 1);

for k = 1:3
    m = ...
        familyValue == families(k) ...
        & isfinite(xBias) ...
        & isfinite(yUtility);

    scatterHandlesB(k) = scatter( ...
        axB, ...
        xBias(m), ...
        yUtility(m), ...
        34, ...
        'filled', ...
        'Marker', familyMarkers{k}, ...
        'MarkerFaceColor', familyColors(k, :), ...
        'MarkerEdgeColor', familyColors(k, :), ...
        'DisplayName', familyLabels{k});
end

yline( ...
    axB, ...
    0, ...
    '--', ...
    'Color', [0.35 0.35 0.35], ...
    'LineWidth', 0.9, ...
    'HandleVisibility', 'off');

xlabel(axB, ...
    'Estimated target-specific transport bias, B^2');

ylabel(axB, ...
    'Same-budget MAE reduction vs direct');

xMaxB = max(xBias(finiteB), [], 'omitnan');

if ~isfinite(xMaxB) || xMaxB <= 0
    xMaxB = 1;
end

xlim(axB, [0, 1.04 * xMaxB]);

f3_style_axes(axB, 8.5);

legend( ...
    axB, ...
    [scatterHandlesB; hLowessB; hBandB], ...
    [familyLabels, {'LOWESS', '95% bootstrap interval'}], ...
    'Location', 'northwest', ...
    'NumColumns', 2, ...
    'Box', 'off', ...
    'FontSize', 7.0);

% -------------------------------------------------------------------------
% Inset inside panel b: theoretical risk-optimal borrowing weight
% -------------------------------------------------------------------------
drawnow;

posB = axB.Position;

axBModel = axes( ...
    fig, ...
    'Position', [ ...
        posB(1) + 0.625 * posB(3), ...
        posB(2) + 0.485 * posB(4), ...
        0.345 * posB(3), ...
        0.420 * posB(4)], ...
    'Color', 'w');

hold(axBModel, 'on');

w = linspace(0, 1, 240);

riskVariance = 0.020;

biasLevels = [ ...
    0.002, ...
    0.020, ...
    0.120];

biasLabels = { ...
    'Low bias', ...
    'Intermediate bias', ...
    'High bias'};

riskColors = [ ...
    0.0000 0.4470 0.7410; ...
    0.8500 0.3250 0.0980; ...
    0.4660 0.6740 0.1880];

riskHandles = gobjects(3, 1);

for k = 1:3

    risk = ...
        (1 - w).^2 * riskVariance ...
        + w.^2 * biasLevels(k);

    wStar = ...
        riskVariance ...
        / (riskVariance + biasLevels(k));

    riskStar = ...
        (1 - wStar).^2 * riskVariance ...
        + wStar.^2 * biasLevels(k);

    riskHandles(k) = plot( ...
        axBModel, ...
        w, ...
        risk, ...
        'Color', riskColors(k, :), ...
        'LineWidth', 1.25, ...
        'DisplayName', biasLabels{k});

    scatter( ...
        axBModel, ...
        wStar, ...
        riskStar, ...
        18, ...
        riskColors(k, :), ...
        'filled', ...
        'MarkerEdgeColor', 'w', ...
        'LineWidth', 0.4, ...
        'HandleVisibility', 'off');
end

xlim(axBModel, [0 1]);

% Match the informative vertical range used by the original figure.
% The high-bias curve is intentionally clipped once risk becomes excessive.
ylim(axBModel, [0 0.026]);

xlabel( ...
    axBModel, ...
    'Borrowing weight, w', ...
    'FontSize', 6.8);

ylabel( ...
    axBModel, ...
    'Estimated risk', ...
    'FontSize', 6.8);

title( ...
    axBModel, ...
    'Bias shifts the risk-optimal weight', ...
    'FontWeight', 'bold', ...
    'FontSize', 7.5);

legend( ...
    axBModel, ...
    riskHandles, ...
    biasLabels, ...
    'Location', 'northoutside', ...
    'NumColumns', 1, ...
    'Box', 'off', ...
    'FontSize', 5.8);

set( ...
    axBModel, ...
    'Box', 'on', ...
    'FontName', 'Arial', ...
    'FontSize', 6.5, ...
    'LineWidth', 0.65, ...
    'TickDir', 'out', ...
    'Layer', 'top', ...
    'XGrid', 'off', ...
    'YGrid', 'off');

axBModel.XLabel.FontName = 'Arial';
axBModel.YLabel.FontName = 'Arial';
axBModel.Title.FontName = 'Arial';

% Ensure the inset remains visually above the empirical panel.
uistack(axBModel, 'top');

%% ------------------------------------------------------------------------
% c — complete 13-point development/freeze/independent trajectory
% -------------------------------------------------------------------------
hold(axC, 'on');

pointLabel = strings(0, 1);
pointGain = zeros(0, 1);
pointRegret = zeros(0, 1);
pointStage = strings(0, 1);

direct = mean(D.u5b_state.direct_mae, 'omitnan');

% Three early U5B candidates
earlyColumns = { ...
    'label_free_mae', ...
    'sentinel_mae', ...
    'oracle_mae'};

earlyLabels = [ ...
    "Label-free", ...
    "Sentinel", ...
    "Oracle"];

for k = 1:3
    v = D.u5b_state.(earlyColumns{k});

    pointLabel(end + 1, 1) = earlyLabels(k);

    pointGain(end + 1, 1) = ...
        100 * ...
        (direct - mean(v, 'omitnan')) ...
        / direct;

    pointRegret(end + 1, 1) = ...
        max( ...
            v - D.u5b_state.direct_mae, ...
            [], ...
            'omitnan');

    pointStage(end + 1, 1) = ...
        "Early candidates";
end

% Three U5D split-hardening candidates
u5dMethods = [ ...
    "DELONG_NORMAL", ...
    "PAIRED_HOEFFDING", ...
    "USTAT_MCDIARMID"];

for k = 1:numel(u5dMethods)
    m = ...
        string(D.u5d_summary.method) ...
        == u5dMethods(k);

    idx = find(m, 1, 'first');

    if isempty(idx)
        error( ...
            'Figure3:MissingU5DMethod', ...
            'Missing U5D method: %s', ...
            char(u5dMethods(k)));
    end

    pointLabel(end + 1, 1) = ...
        u5dMethods(k);

    pointGain(end + 1, 1) = ...
        100 * ...
        D.u5d_summary.gain_vs_full_direct(idx);

    pointRegret(end + 1, 1) = ...
        D.u5d_summary. ...
        worst_target_budget_regret_vs_full(idx);

    pointStage(end + 1, 1) = ...
        "Split hardening";
end

% Five U5E pair-complete candidates
u5eMethods = [ ...
    "PC_DELONG", ...
    "PC_DELONG_VARGATE", ...
    "PC_PLUGIN", ...
    "PC_PLUGIN_VARGATE", ...
    "PC_USTAT_MCDIARMID"];

for k = 1:numel(u5eMethods)
    m = ...
        string(D.u5e_summary.method) ...
        == u5eMethods(k);

    idx = find(m, 1, 'first');

    if isempty(idx)
        error( ...
            'Figure3:MissingU5EMethod', ...
            'Missing U5E method: %s', ...
            char(u5eMethods(k)));
    end

    pointLabel(end + 1, 1) = ...
        u5eMethods(k);

    pointGain(end + 1, 1) = ...
        100 * ...
        D.u5e_summary.gain_vs_full_direct(idx);

    pointRegret(end + 1, 1) = ...
        D.u5e_summary. ...
        worst_target_budget_regret(idx);

    pointStage(end + 1, 1) = ...
        "Pair-complete candidates";
end

% Frozen U5F method
m = ...
    string(D.u5f_audit.method) ...
    == "PC_PAIRED_HOEFFDING";

idx = find(m, 1, 'first');

if isempty(idx)
    error( ...
        'Figure3:MissingU5FMethod', ...
        'Missing frozen U5F PC_PAIRED_HOEFFDING method.');
end

pointLabel(end + 1, 1) = ...
    "Frozen U5F";

pointGain(end + 1, 1) = ...
    100 * D.u5f_audit.pooled_gain(idx);

pointRegret(end + 1, 1) = ...
    D.u5f_audit.worst_target_budget_regret(idx);

pointStage(end + 1, 1) = ...
    "Frozen / independent";

% Independent U6 confirmation
u6Direct = mean( ...
    D.u6_state.direct_mae, ...
    'omitnan');

pointLabel(end + 1, 1) = ...
    "Independent U6";

pointGain(end + 1, 1) = ...
    100 * ...
    (u6Direct - mean(D.u6_state.mae, 'omitnan')) ...
    / u6Direct;

pointRegret(end + 1, 1) = ...
    max( ...
        D.u6_state.mae_regret_vs_full_direct, ...
        [], ...
        'omitnan');

pointStage(end + 1, 1) = ...
    "Frozen / independent";

stageNames = [ ...
    "Early candidates", ...
    "Split hardening", ...
    "Pair-complete candidates", ...
    "Frozen / independent"];

stageLabels = { ...
    'Early candidates', ...
    'Split hardening', ...
    'Pair-complete candidates', ...
    'Frozen / independent'};

stageMarkers = { ...
    'o', ...
    's', ...
    'D', ...
    'p'};

stageSizes = [ ...
    55 ...
    58 ...
    58 ...
    105];

stageColors = [ ...
    0.1216 0.4667 0.7059; ...
    1.0000 0.4980 0.0549; ...
    0.1725 0.6275 0.1725; ...
    0.8392 0.1529 0.1569];

stageHandles = gobjects(4, 1);

for k = 1:4
    m = pointStage == stageNames(k);

    stageHandles(k) = scatter( ...
        axC, ...
        pointGain(m), ...
        pointRegret(m), ...
        stageSizes(k), ...
        'filled', ...
        'Marker', stageMarkers{k}, ...
        'MarkerFaceColor', stageColors(k, :), ...
        'MarkerEdgeColor', stageColors(k, :), ...
        'DisplayName', stageLabels{k});
end

yline( ...
    axC, ...
    0, ...
    '--', ...
    'Color', [0.35 0.35 0.35], ...
    'LineWidth', 0.9, ...
    'HandleVisibility', 'off');

xline( ...
    axC, ...
    0, ...
    ':', ...
    'Color', [0.00 0.45 0.75], ...
    'LineWidth', 0.9, ...
    'HandleVisibility', 'off');

xlabel( ...
    axC, ...
    'Relative reduction in pooled MAE vs direct (%)');

ylabel( ...
    axC, ...
    'Worst target-budget regret');

xSpanC = max(pointGain) - min(pointGain);
ySpanC = max(pointRegret) - min(pointRegret);

if ~isfinite(xSpanC) || xSpanC <= 0
    xSpanC = 1;
end

if ~isfinite(ySpanC) || ySpanC <= 0
    ySpanC = 1;
end

xlim(axC, [ ...
    min(-2.5, min(pointGain) - 0.08 * xSpanC), ...
    max(pointGain) + 0.08 * xSpanC]);

ylim(axC, [ ...
    min(pointRegret) - 0.12 * ySpanC, ...
    max(pointRegret) + 0.12 * ySpanC]);

legend( ...
    axC, ...
    stageHandles, ...
    stageLabels, ...
    'Location', 'northoutside', ...
    'NumColumns', 4, ...
    'Box', 'off', ...
    'FontSize', 7.5);

f3_style_axes(axC, 8.5);

% Five key labels; all 13 points remain visible
keyLabels = [ ...
    "Label-free", ...
    "Sentinel", ...
    "Oracle", ...
    "Frozen U5F", ...
    "Independent U6"];

defaultLabelPos = NaN(5, 2);

for k = 1:5
    idx = find( ...
        pointLabel == keyLabels(k), ...
        1, ...
        'first');

    switch keyLabels(k)
        case "Label-free"
            defaultLabelPos(k, :) = [ ...
                pointGain(idx) - 0.08 * xSpanC, ...
                pointRegret(idx)];

        case "Sentinel"
            defaultLabelPos(k, :) = [ ...
                pointGain(idx) + 0.055 * xSpanC, ...
                pointRegret(idx) + 0.030 * ySpanC];

        case "Oracle"
            defaultLabelPos(k, :) = [ ...
                pointGain(idx) + 0.055 * xSpanC, ...
                pointRegret(idx) - 0.020 * ySpanC];

        case "Frozen U5F"
            defaultLabelPos(k, :) = [ ...
                pointGain(idx) + 0.055 * xSpanC, ...
                pointRegret(idx) + 0.060 * ySpanC];

        case "Independent U6"
            defaultLabelPos(k, :) = [ ...
                pointGain(idx) + 0.060 * xSpanC, ...
                pointRegret(idx) + 0.025 * ySpanC];
    end
end

labelPosFile = fullfile( ...
    outDir, ...
    'Figure3_panelC_label_positions.mat');

labelPos = defaultLabelPos;

if exist(labelPosFile, 'file')
    savedLabelData = load(labelPosFile);

    if ...
            isfield(savedLabelData, 'labelPos') ...
            && isequal(size(savedLabelData.labelPos), [5 2])

        labelPos = savedLabelData.labelPos;
    end
end

labelHandles = gobjects(5, 1);
leaderHandles = gobjects(5, 1);

for k = 1:5
    idx = find( ...
        pointLabel == keyLabels(k), ...
        1, ...
        'first');

    anchor = [ ...
        pointGain(idx), ...
        pointRegret(idx)];

    leaderHandles(k) = plot( ...
        axC, ...
        [anchor(1), labelPos(k, 1)], ...
        [anchor(2), labelPos(k, 2)], ...
        '-', ...
        'Color', [0.30 0.30 0.30], ...
        'LineWidth', 0.65, ...
        'HandleVisibility', 'off');

    labelHandles(k) = text( ...
        axC, ...
        labelPos(k, 1), ...
        labelPos(k, 2), ...
        keyLabels(k), ...
        'FontName', 'Arial', ...
        'FontSize', 7.8, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'BackgroundColor', 'w', ...
        'EdgeColor', 'none', ...
        'Margin', 1.0, ...
        'Clipping', 'off', ...
        'PickableParts', 'all', ...
        'HitTest', 'on');

    setappdata( ...
        labelHandles(k), ...
        'AnchorPoint', ...
        anchor);

    setappdata( ...
        labelHandles(k), ...
        'LeaderHandle', ...
        leaderHandles(k));

    labelHandles(k).ButtonDownFcn = ...
        @(src, ~) f3_start_label_drag(src, fig);
end

%% ------------------------------------------------------------------------
% d — all U5B states, selected weight, LOWESS and cluster bootstrap
% -------------------------------------------------------------------------
hold(axD, 'on');

xBiasD = ...
    D.u5b_state.mean_sentinel_bias_sq;

yWeightRaw = ...
    D.u5b_state.mean_sentinel_weight;

yWeight = max(yWeightRaw, 0);

finiteD = ...
    isfinite(xBiasD) ...
    & isfinite(yWeightRaw) ...
    & ~ismissing(cluster);

[gridD, fitD, loD, hiD] = cmdo_lowess_bootstrap( ...
    xBiasD(finiteD), ...
    yWeightRaw(finiteD), ...
    cluster(finiteD), ...
    0.42, ...
    300, ...
    20260729);

gridD = gridD(:);
fitD = max(fitD(:), 0);
loD = max(loD(:), 0);
hiD = max(hiD(:), 0);

hBandD = fill( ...
    axD, ...
    [gridD; flipud(gridD)], ...
    [loD; flipud(hiD)], ...
    [0.92 0.55 0.55], ...
    'FaceAlpha', 0.18, ...
    'EdgeColor', 'none', ...
    'DisplayName', '95% cluster bootstrap');

hLowessD = plot( ...
    axD, ...
    gridD, ...
    fitD, ...
    'Color', [0.05 0.45 0.82], ...
    'LineWidth', 2.0, ...
    'DisplayName', 'LOWESS');

scatterHandlesD = gobjects(3, 1);

for k = 1:3
    m = ...
        familyValue == families(k) ...
        & isfinite(xBiasD) ...
        & isfinite(yWeight);

    scatterHandlesD(k) = scatter( ...
        axD, ...
        xBiasD(m), ...
        yWeight(m), ...
        34, ...
        'filled', ...
        'Marker', familyMarkers{k}, ...
        'MarkerFaceColor', familyColors(k, :), ...
        'MarkerEdgeColor', familyColors(k, :), ...
        'DisplayName', familyLabels{k});
end

xlabel( ...
    axD, ...
    'Estimated target-specific transport bias, B^2');

ylabel( ...
    axD, ...
    'Selected transport weight, w');

xMaxD = max( ...
    xBiasD(finiteD), ...
    [], ...
    'omitnan');

if ~isfinite(xMaxD) || xMaxD <= 0
    xMaxD = 1;
end

xlim(axD, [0, 1.04 * xMaxD]);

yMaxD = max( ...
    [hiD; yWeight(finiteD)], ...
    [], ...
    'omitnan');

if ~isfinite(yMaxD) || yMaxD <= 0
    yMaxD = 1;
end

ylim(axD, [0, 1.05 * yMaxD]);

legend( ...
    axD, ...
    [scatterHandlesD; hLowessD; hBandD], ...
    [familyLabels, {'LOWESS', '95% bootstrap interval'}], ...
    'Location', 'northoutside', ...
    'NumColumns', 2, ...
    'Box', 'off', ...
    'FontSize', 7.2);

f3_style_axes(axD, 8.5);

%% Canonical data audit printed to the Command Window
fprintf('\nFigure 3 canonical-data audit:\n');

fprintf( ...
    '  Panel a: %d targets x %d budgets; late-budget targets = %d\n', ...
    numel(targetOrder), ...
    numel(budgetOrder), ...
    numel(uv));

fprintf( ...
    '  Panels b/d: %d finite U5B audit-state rows across %d families\n', ...
    nnz(finiteB), ...
    numel(families));

fprintf( ...
    ['  Panel c: %d total points = ' ...
     '3 U5B + 3 U5D + 5 U5E + 1 U5F + 1 U6\n'], ...
    numel(pointLabel));

%% Optional manual adjustment of the five panel-c labels
drawnow;

if MANUAL_PANEL_C_LABELS && usejava('desktop')
    instructionBox = annotation( ...
        fig, ...
        'textbox', ...
        [0.285 0.010 0.445 0.030], ...
        'String', ...
        ['Drag the five labels in panel c, ' ...
         'then click Save label positions'], ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Arial', ...
        'FontSize', 9, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [1.00 1.00 0.88], ...
        'EdgeColor', [0.65 0.65 0.45], ...
        'FitBoxToText', 'off');

    finishButton = uicontrol( ...
        fig, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.745 0.010 0.170 0.032], ...
        'String', 'Save label positions', ...
        'FontSize', 9, ...
        'FontWeight', 'bold', ...
        'Callback', @(~, ~) uiresume(fig));

    uiwait(fig);

    if ~isgraphics(fig)
        return;
    end

    labelPos = NaN(5, 2);

    for k = 1:5
        p = labelHandles(k).Position;
        labelPos(k, :) = p(1:2);
    end

    save( ...
        labelPosFile, ...
        'labelPos', ...
        'keyLabels');

    if isgraphics(finishButton)
        delete(finishButton);
    end

    if isgraphics(instructionBox)
        delete(instructionBox);
    end
end

%% Export
drawnow;

stem = fullfile( ...
    outDir, ...
    'Figure3_Failure_Bias_And_Safety');

exportgraphics( ...
    fig, ...
    [stem '.png'], ...
    'Resolution', 300, ...
    'BackgroundColor', 'white');

exportgraphics( ...
    fig, ...
    [stem '.tiff'], ...
    'Resolution', 300, ...
    'BackgroundColor', 'white');

exportgraphics( ...
    fig, ...
    [stem '.pdf'], ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');

savefig(fig, [stem '.fig']);

fprintf( ...
    '\nFigure 3 saved to:\n%s\n', ...
    outDir);

end


function f3_style_axes(ax, fontSize)
% Conservative publication axes styling

set(ax, ...
    'Box', 'off', ...
    'FontName', 'Arial', ...
    'FontSize', fontSize, ...
    'LineWidth', 0.85, ...
    'TickDir', 'out', ...
    'Layer', 'top');

end


function f3_panel_header(fig, position, value, fontSize)
% Figure-normalized panel letter/title

annotation( ...
    fig, ...
    'textbox', ...
    position, ...
    'String', value, ...
    'FontName', 'Arial', ...
    'FontSize', fontSize, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'middle', ...
    'EdgeColor', 'none', ...
    'FitBoxToText', 'off');

end


function f3_start_label_drag(labelHandle, figHandle)
% Start dragging one panel-c label

if ~isgraphics(labelHandle) || ~isgraphics(figHandle)
    return;
end

set(figHandle, ...
    'Pointer', 'fleur', ...
    'WindowButtonMotionFcn', ...
    @(~, ~) f3_drag_label(labelHandle), ...
    'WindowButtonUpFcn', ...
    @(~, ~) f3_stop_label_drag(figHandle));

end


function f3_drag_label(labelHandle)
% Move a label and update its leader line

if ~isgraphics(labelHandle)
    return;
end

ax = ancestor(labelHandle, 'axes');

if isempty(ax) || ~isgraphics(ax)
    return;
end

cp = ax.CurrentPoint;

x = cp(1, 1);
y = cp(1, 2);

xl = ax.XLim;
yl = ax.YLim;

xPad = 0.02 * (xl(2) - xl(1));
yPad = 0.035 * (yl(2) - yl(1));

x = min( ...
    max(x, xl(1) + xPad), ...
    xl(2) - xPad);

y = min( ...
    max(y, yl(1) + yPad), ...
    yl(2) - yPad);

labelHandle.Position = [x y 0];

anchor = getappdata( ...
    labelHandle, ...
    'AnchorPoint');

leader = getappdata( ...
    labelHandle, ...
    'LeaderHandle');

if isgraphics(leader)
    leader.XData = [anchor(1), x];
    leader.YData = [anchor(2), y];
end

drawnow limitrate nocallbacks;

end


function f3_stop_label_drag(figHandle)
% Finish dragging

if ~isgraphics(figHandle)
    return;
end

set(figHandle, ...
    'Pointer', 'arrow', ...
    'WindowButtonMotionFcn', '', ...
    'WindowButtonUpFcn', '');

end
