function Figure3_FrozenReuse_v8(outputDir, repoRoot)
% FIGURE3_FROZENREUSE_V8
% CMDO Figure 3 — IDENTIFY:
% identical monitored evidence can conceal opposite performance.
%
% Scientific role
%   A) Observed model scores in two external ECG cohorts
%   B) Georgia: same observed outputs, opposite compatible performance
%   C) CPSC 2018: same observed outputs, opposite compatible performance
%
% IMPORTANT
%   - Uses frozen U11 score channels and constructed outcome worlds.
%   - Does NOT access true U10 target outcomes.
%   - Does NOT imply either constructed world is the real clinical world.
%
% Usage
%   Figure3_FrozenReuse_v8
%   Figure3_FrozenReuse_v8('C:\path\to\output')
%   Figure3_FrozenReuse_v8([], ...
%       'C:\Users\zyx\CMDO-Reproducibility')

close all;

%% ------------------------------------------------------------------------
% 0. STYLE
% -------------------------------------------------------------------------

FONT = 'Arial';

FS_LETTER = 22;
FS_TITLE  = 11.5;
FS_AXIS   = 9.5;
FS_TICK   = 9.0;
FS_SMALL  = 9.2;
FS_TINY   = 8.2;

navy  = [0.02 0.24 0.63];
blue  = [0.02 0.29 0.70];

red   = [0.82 0.05 0.04];
green = [0.02 0.48 0.20];

grey  = [0.42 0.42 0.42];
dgrey = [0.22 0.22 0.22];
lgrey = [0.82 0.82 0.82];

panelBlue = local_mix(blue,[1 1 1],0.72);

%% ------------------------------------------------------------------------
% 1. OUTPUT
% -------------------------------------------------------------------------

thisFile = mfilename('fullpath');

if isempty(thisFile)
    scriptDir = pwd;
else
    scriptDir = fileparts(thisFile);
end

if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(scriptDir,'output');
end

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

%% ------------------------------------------------------------------------
% 2. LOCATE CMDO REPOSITORY
% -------------------------------------------------------------------------

if nargin < 2
    repoRoot = '';
end

if isempty(repoRoot)
    repoRoot = local_find_cmdo_repo(scriptDir);
end

if isempty(repoRoot)
    error(['Could not locate CMDO-Reproducibility.' newline ...
        'Run, for example:' newline ...
        'Figure3_FrozenReuse_v8([],''' ...
        'C:\Users\zyx\CMDO-Reproducibility'')']);
end

fprintf('\n============================================================\n');
fprintf(' CMDO FIGURE 3 — IDENTIFY\n');
fprintf(' Same monitoring, opposite compatible performance\n');
fprintf('============================================================\n');
fprintf('Repository : %s\n',repoRoot);
fprintf('Output     : %s\n',outputDir);

%% ------------------------------------------------------------------------
% 3. LOAD FROZEN U11 INFORMATION-CLOSURE WORLDS
% -------------------------------------------------------------------------

U11 = local_load_u11(repoRoot);

% Explicit frozen checks.
assert(U11.georgia.scoreResidual == 0, ...
    'Georgia WORLD+ and WORLD- scores differ.');

assert(U11.cpsc.scoreResidual == 0, ...
    'CPSC WORLD+ and WORLD- scores differ.');

assert(U11.georgia.predictionIdentity, ...
    'Georgia prediction channels differ.');

assert(U11.cpsc.predictionIdentity, ...
    'CPSC prediction channels differ.');

assert(abs(U11.georgia.prevalencePlus - ...
           U11.georgia.prevalenceMinus) < 1e-12, ...
    'Georgia prevalence is not matched.');

assert(abs(U11.cpsc.prevalencePlus - ...
           U11.cpsc.prevalenceMinus) < 1e-12, ...
    'CPSC prevalence is not matched.');

%% ------------------------------------------------------------------------
% 4. CANVAS
% -------------------------------------------------------------------------

fig = figure( ...
    'Color','w', ...
    'Position',[55 50 1000 760], ...
    'Renderer','painters', ...
    'Name','CMDO Figure 3 — IDENTIFY', ...
    'NumberTitle','off');

% One wide monitoring panel, two lower cohort panels.
PA = [0.025 0.625 0.950 0.335];

PB = [0.025 0.055 0.460 0.525];

PC = [0.515 0.055 0.460 0.525];

%% ========================================================================
% PANEL A — SAME MONITORED EVIDENCE
% ========================================================================

axA0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PA);

axis(axA0,[0 1 0 1]);
axis(axA0,'off');
hold(axA0,'on');

local_panel_border( ...
    axA0, ...
    [0.005 0.005 0.99 0.99], ...
    panelBlue, ...
    1.05);

local_panel_header( ...
    axA0, ...
    'A', ...
    'Observed model scores', ...
    0.020, ...
    0.955, ...
    navy, ...
    FONT, ...
    FS_LETTER, ...
    FS_TITLE);

% -------------------------------------------------------------------------
% Georgia score stream
% -------------------------------------------------------------------------

axA1 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PA,[0.080 0.235 0.385 0.515]));

local_score_stream( ...
    axA1, ...
    U11.georgia.scoreRaw, ...
    grey, ...
    FONT, ...
    FS_AXIS);

title( ...
    axA1, ...
    sprintf('Georgia   n = %s', ...
    local_comma_integer(U11.georgia.n)), ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',dgrey);

ylabel( ...
    axA1, ...
    'Model score', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

% -------------------------------------------------------------------------
% CPSC 2018 score stream
% -------------------------------------------------------------------------

axA2 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PA,[0.535 0.235 0.385 0.515]));

local_score_stream( ...
    axA2, ...
    U11.cpsc.scoreRaw, ...
    grey, ...
    FONT, ...
    FS_AXIS);

title( ...
    axA2, ...
    sprintf('CPSC 2018   n = %s', ...
    local_comma_integer(U11.cpsc.n)), ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',dgrey);

ylabel( ...
    axA2, ...
    'Model score', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);



%% ========================================================================
% PANEL B — GEORGIA
% ========================================================================

axB0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PB);

axis(axB0,[0 1 0 1]);
axis(axB0,'off');
hold(axB0,'on');

local_panel_border( ...
    axB0, ...
    [0.005 0.005 0.99 0.99], ...
    panelBlue, ...
    1.05);

local_panel_header( ...
    axB0, ...
    'B', ...
    'Georgia: same outputs, opposite performance', ...
    0.025, ...
    0.955, ...
    navy, ...
    FONT, ...
    FS_LETTER, ...
    FS_TITLE);

text( ...
    axB0, ...
    0.50, ...
    0.855, ...
    sprintf('matched prevalence = %.6f', ...
    U11.georgia.prevalencePlus), ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY, ...
    'Color',grey);

% WORLD+
axB1 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PB,[0.160 0.565 0.610 0.190]));

local_world_strip( ...
    axB1, ...
    U11.georgia.yPlus, ...
    green, ...
    FONT, ...
    FS_AXIS, ...
    false);

text( ...
    axB0, ...
    0.120, ...
    0.650, ...
    'WORLD+', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',green);

text( ...
    axB0, ...
    0.805, ...
    0.650, ...
    sprintf('AUC = %.2f',U11.georgia.aucPlus), ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',green);

% WORLD-
axB2 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PB,[0.160 0.285 0.610 0.190]));

local_world_strip( ...
    axB2, ...
    U11.georgia.yMinus, ...
    red, ...
    FONT, ...
    FS_AXIS, ...
    true);

text( ...
    axB0, ...
    0.120, ...
    0.370, ...
    'WORLD-', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',red);

text( ...
    axB0, ...
    0.805, ...
    0.370, ...
    sprintf('AUC = %.2f',U11.georgia.aucMinus), ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',red);

% Delta_E
text( ...
    axB0, ...
    0.50, ...
    0.105, ...
    sprintf('$\\Delta_{\\mathcal{E}} = %.2f$', ...
    U11.georgia.aucGap), ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'Color',blue);

%% ========================================================================
% PANEL C — CPSC 2018
% ========================================================================

axC0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PC);

axis(axC0,[0 1 0 1]);
axis(axC0,'off');
hold(axC0,'on');

local_panel_border( ...
    axC0, ...
    [0.005 0.005 0.99 0.99], ...
    panelBlue, ...
    1.05);

local_panel_header( ...
    axC0, ...
    'C', ...
    'CPSC 2018: same outputs, opposite performance', ...
    0.025, ...
    0.955, ...
    navy, ...
    FONT, ...
    FS_LETTER, ...
    FS_TITLE);

text( ...
    axC0, ...
    0.50, ...
    0.855, ...
    sprintf('matched prevalence = %.6f', ...
    U11.cpsc.prevalencePlus), ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY, ...
    'Color',grey);

% WORLD+
axC1 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PC,[0.160 0.565 0.610 0.190]));

local_world_strip( ...
    axC1, ...
    U11.cpsc.yPlus, ...
    green, ...
    FONT, ...
    FS_AXIS, ...
    false);

text( ...
    axC0, ...
    0.120, ...
    0.650, ...
    'WORLD+', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',green);

text( ...
    axC0, ...
    0.805, ...
    0.650, ...
    sprintf('AUC = %.2f',U11.cpsc.aucPlus), ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',green);

% WORLD-
axC2 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PC,[0.160 0.285 0.610 0.190]));

local_world_strip( ...
    axC2, ...
    U11.cpsc.yMinus, ...
    red, ...
    FONT, ...
    FS_AXIS, ...
    true);

text( ...
    axC0, ...
    0.120, ...
    0.370, ...
    'WORLD-', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',red);

text( ...
    axC0, ...
    0.805, ...
    0.370, ...
    sprintf('AUC = %.2f',U11.cpsc.aucMinus), ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',red);

% Delta_E
text( ...
    axC0, ...
    0.50, ...
    0.105, ...
    sprintf('$\\Delta_{\\mathcal{E}} = %.2f$', ...
    U11.cpsc.aucGap), ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',14, ...
    'FontWeight','bold', ...
    'Color',blue);

%% ------------------------------------------------------------------------
% 5. AUDIT PRINTOUT
% -------------------------------------------------------------------------

fprintf('\n--- U11 IDENTIFY AUDIT ---\n');

fprintf(['Georgia : n=%d | prevalence=%.12f | ' ...
    'AUC+=%.12f | AUC-=%.12f | Delta_E=%.12f\n'], ...
    U11.georgia.n, ...
    U11.georgia.prevalencePlus, ...
    U11.georgia.aucPlus, ...
    U11.georgia.aucMinus, ...
    U11.georgia.aucGap);

fprintf(['CPSC    : n=%d | prevalence=%.12f | ' ...
    'AUC+=%.12f | AUC-=%.12f | Delta_E=%.12f\n'], ...
    U11.cpsc.n, ...
    U11.cpsc.prevalencePlus, ...
    U11.cpsc.aucPlus, ...
    U11.cpsc.aucMinus, ...
    U11.cpsc.aucGap);

fprintf('Georgia score identity residual : %.3e\n', ...
    U11.georgia.scoreResidual);

fprintf('CPSC score identity residual    : %.3e\n', ...
    U11.cpsc.scoreResidual);

fprintf('Georgia prediction identity     : %d\n', ...
    U11.georgia.predictionIdentity);

fprintf('CPSC prediction identity        : %d\n', ...
    U11.cpsc.predictionIdentity);

%% ------------------------------------------------------------------------
% 6. EXPORT
% -------------------------------------------------------------------------

drawnow;

% Keep current basename for compatibility with the existing runner.
baseName = 'Figure3_FrozenReuse_v8';

figPath = fullfile(outputDir,[baseName '.fig']);
pngPath = fullfile(outputDir,[baseName '.png']);
pdfPath = fullfile(outputDir,[baseName '.pdf']);

savefig(fig,figPath);

set(fig,'PaperPositionMode','auto');
set(fig,'PaperUnits','inches');

figPos = get(fig,'Position');

pageH = 7.6;
pageW = pageH * figPos(3) / figPos(4);

set(fig,'PaperSize',[pageW pageH]);
set(fig,'PaperPosition',[0 0 pageW pageH]);

try

    exportgraphics( ...
        fig, ...
        pngPath, ...
        'Resolution',600, ...
        'BackgroundColor','white');

    exportgraphics( ...
        fig, ...
        pdfPath, ...
        'ContentType','vector', ...
        'BackgroundColor','white');

catch ME

    warning( ...
        'Figure3 exportgraphics failed (%s). Falling back to print.', ...
        ME.message);

    print(fig,pngPath,'-dpng','-r600');
    print(fig,pdfPath,'-dpdf','-painters','-bestfit');

end

fprintf('\nSaved:\n%s\n%s\n%s\n', ...
    figPath,pngPath,pdfPath);

end

%% =========================================================================
% HELPERS
% =========================================================================

function U11 = local_load_u11(repoRoot)

paths.gp = fullfile( ...
    repoRoot, ...
    'U11_Information_Closure', ...
    '01_Result', ...
    'U11_WORLD_PLUS_georgia_v0.1.csv');

paths.gm = fullfile( ...
    repoRoot, ...
    'U11_Information_Closure', ...
    '01_Result', ...
    'U11_WORLD_MINUS_georgia_v0.1.csv');

paths.cp = fullfile( ...
    repoRoot, ...
    'U11_Information_Closure', ...
    '01_Result', ...
    'U11_WORLD_PLUS_cpsc_2018_v0.1.csv');

paths.cm = fullfile( ...
    repoRoot, ...
    'U11_Information_Closure', ...
    '01_Result', ...
    'U11_WORLD_MINUS_cpsc_2018_v0.1.csv');

f = fieldnames(paths);

for i = 1:numel(f)

    if ~isfile(paths.(f{i}))
        error( ...
            'Missing U11 world file:\n%s', ...
            paths.(f{i}));
    end

end

Tgp = readtable(paths.gp);
Tgm = readtable(paths.gm);

Tcp = readtable(paths.cp);
Tcm = readtable(paths.cm);

U11.georgia = local_parse_u11_pair( ...
    Tgp,Tgm,'Georgia');

U11.cpsc = local_parse_u11_pair( ...
    Tcp,Tcm,'CPSC 2018');

end

function S = local_parse_u11_pair(Tp,Tm,nameStr)

local_require_vars( ...
    Tp, ...
    {'score_af','predicted_af','synthetic_outcome'}, ...
    [nameStr ' WORLD+']);

local_require_vars( ...
    Tm, ...
    {'score_af','predicted_af','synthetic_outcome'}, ...
    [nameStr ' WORLD-']);

sp = double(Tp.score_af(:));
sm = double(Tm.score_af(:));

pp = double(Tp.predicted_af(:));
pm = double(Tm.predicted_af(:));

ypRaw = double(Tp.synthetic_outcome(:));
ymRaw = double(Tm.synthetic_outcome(:));

assert( ...
    numel(sp)==numel(sm), ...
    'U11 paired worlds have different lengths.');

% If record IDs are available, verify that those channels also match.
if ismember('record_id',Tp.Properties.VariableNames) && ...
        ismember('record_id',Tm.Properties.VariableNames)

    ridP = string(Tp.record_id);
    ridM = string(Tm.record_id);

    assert( ...
        isequal(ridP,ridM), ...
        'U11 record_id channels differ.');

end

scoreResidual = max(abs(sp-sm),[],'omitnan');

predictionIdentity = isequal(pp,pm);

% Preserve original frozen ordering for the monitoring-stream panel.
S.scoreRaw = sp;

% Sort only for the compatible-world visualization.
[scoreSorted,ord] = sort(sp,'ascend');

yp = ypRaw(ord);
ym = ymRaw(ord);

S.name = nameStr;

S.n = numel(sp);

S.score = scoreSorted;

S.yPlus = yp;
S.yMinus = ym;

S.prevalencePlus = mean(ypRaw,'omitnan');
S.prevalenceMinus = mean(ymRaw,'omitnan');

S.aucPlus = local_auc_rank(sp,ypRaw);
S.aucMinus = local_auc_rank(sm,ymRaw);

S.aucGap = abs( ...
    S.aucPlus - S.aucMinus);

S.scoreResidual = scoreResidual;

S.predictionIdentity = predictionIdentity;

end

function local_score_stream(ax,score,color,FONT,FS_AXIS)

score = double(score(:));

score = score(isfinite(score));

Nshow = min(240,numel(score));

idx = unique( ...
    round( ...
    linspace(1,numel(score),Nshow)));

s = score(idx);

x = 1:numel(s);

hold(ax,'on');

% Light vertical score stems.
h = stem( ...
    ax, ...
    x, ...
    s, ...
    'Marker','none', ...
    'Color',color, ...
    'LineWidth',0.55);

try
    h.BaseLine.Visible = 'off';
catch
end

scatter( ...
    ax, ...
    x, ...
    s, ...
    10, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor',color, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.25);

xlim(ax,[1 numel(x)]);

scoreMin = min(s,[],'omitnan');
scoreMax = max(s,[],'omitnan');

lo = min(0,scoreMin);
hi = max(1,scoreMax);

span = hi-lo;

if span<=0 || ~isfinite(span)
    span = 1;
end

ylim(ax,[lo-0.03*span hi+0.04*span]);

set( ...
    ax, ...
    'XTick',[1 round(numel(x)/2) numel(x)], ...
    'XTickLabel',{'1','n/2','n'}, ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS, ...
    'TickDir','out', ...
    'LineWidth',0.75, ...
    'Box','off');

xlabel( ...
    ax, ...
    'Record order', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

end

function local_world_strip(ax,y,color,FONT,FS_AXIS,showXLabel)

y = double(y(:));

Nshow = min(320,numel(y));

idx = unique( ...
    round( ...
    linspace(1,numel(y),Nshow)));

yy = y(idx);

x = 1:numel(yy);

hold(ax,'on');

% Light guides first.
plot( ...
    ax, ...
    [1 numel(yy)], ...
    [0 0], ...
    '-', ...
    'Color',[0.86 0.86 0.86], ...
    'LineWidth',0.65);

plot( ...
    ax, ...
    [1 numel(yy)], ...
    [1 1], ...
    '-', ...
    'Color',[0.86 0.86 0.86], ...
    'LineWidth',0.65);

% Actual constructed outcome world.
stairs( ...
    ax, ...
    x, ...
    yy, ...
    '-', ...
    'Color',color, ...
    'LineWidth',1.80);

step = max(1,round(numel(yy)/34));

markerIdx = 1:step:numel(yy);

scatter( ...
    ax, ...
    x(markerIdx), ...
    yy(markerIdx), ...
    20, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor',color, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.30);

xlim(ax,[1 numel(yy)]);
ylim(ax,[-0.10 1.10]);

set( ...
    ax, ...
    'YTick',[0 1], ...
    'YTickLabel',{'0','1'}, ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS-1, ...
    'TickDir','out', ...
    'LineWidth',0.70, ...
    'Box','off');

if showXLabel

    set( ...
        ax, ...
        'XTick',[1 numel(yy)], ...
        'XTickLabel',{'low','high'});

    xlabel( ...
        ax, ...
        'Model-score rank', ...
        'FontName',FONT, ...
        'FontSize',FS_AXIS);

else

    set(ax,'XTick',[]);

end

end

function auc = local_auc_rank(score,y)

score = double(score(:));
y = double(y(:));

m = isfinite(score) & isfinite(y);

score = score(m);
y = y(m);

n1 = nnz(y==1);
n0 = nnz(y==0);

if n1==0 || n0==0

    auc = NaN;
    return;

end

r = local_tied_rank(score);

sumR1 = sum(r(y==1));

auc = ...
    (sumR1 - n1*(n1+1)/2) / ...
    (n1*n0);

end

function r = local_tied_rank(v)

v = double(v(:));

n = numel(v);

[sv,ord] = sort(v,'ascend');

r = zeros(n,1);

i = 1;

while i<=n

    j = i;

    while j<n && sv(j+1)==sv(i)
        j = j+1;
    end

    r(ord(i:j)) = 0.5*(i+j);

    i = j+1;

end

end

function local_require_vars(T,vars,sourceName)

missing = strings(0,1);

for i = 1:numel(vars)

    if ~ismember(vars{i},T.Properties.VariableNames)

        missing(end+1,1) = string(vars{i}); %#ok<AGROW>

    end

end

if ~isempty(missing)

    error( ...
        '%s missing variables: %s', ...
        sourceName, ...
        strjoin(cellstr(missing),', '));

end

end

function local_panel_border(ax,pos,color,lineWidth)

rectangle( ...
    ax, ...
    'Position',pos, ...
    'Curvature',0.018, ...
    'FaceColor','none', ...
    'EdgeColor',color, ...
    'LineWidth',lineWidth);

end

function local_panel_header( ...
    ax,letter,titleText,x,y,color,fontName,fsLetter,fsTitle)

text( ...
    ax, ...
    x,y, ...
    letter, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsLetter, ...
    'FontWeight','bold', ...
    'Color',color);

text( ...
    ax, ...
    x+0.050, ...
    y, ...
    titleText, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsTitle, ...
    'FontWeight','bold', ...
    'Color',color);

end

function pos = local_relpos(panelPos,rel)

pos = [ ...
    panelPos(1) + rel(1)*panelPos(3), ...
    panelPos(2) + rel(2)*panelPos(4), ...
    rel(3)*panelPos(3), ...
    rel(4)*panelPos(4)];

end

function c = local_mix(c1,c2,alpha)

c = ...
    (1-alpha).*c1 + ...
    alpha.*c2;

end

function repoRoot = local_find_cmdo_repo(scriptDir)

repoRoot = '';

starts = {scriptDir,pwd};

for s = 1:numel(starts)

    p = starts{s};

    for k = 1:8

        if isempty(p)
            break;
        end

        if isfolder(fullfile(p,'U11_Information_Closure')) && ...
                isfolder(fullfile(p,'matlab'))

            repoRoot = p;
            return;

        end

        parent = fileparts(p);

        if strcmp(parent,p)
            break;
        end

        p = parent;

    end

end

userHome = strtrim(getenv('USERPROFILE'));

if isempty(userHome)
    userHome = strtrim(getenv('HOME'));
end

if ~isempty(userHome)

    candidates = { ...
        fullfile(userHome,'CMDO-Reproducibility'), ...
        fullfile(userHome,'Documents','CMDO-Reproducibility'), ...
        fullfile(userHome,'Desktop','CMDO-Reproducibility')};

    for i = 1:numel(candidates)

        p = candidates{i};

        if isfolder(fullfile(p,'U11_Information_Closure')) && ...
                isfolder(fullfile(p,'matlab'))

            repoRoot = p;
            return;

        end

    end

end

end

function s = local_comma_integer(n)

s = sprintf('%d',round(n));

k = length(s)-3;

while k>0

    s = [s(1:k) ',' s(k+1:end)]; %#ok<AGROW>

    k = k-3;

end

end