function Figure5(outputDir)
%FIGURE5 Operational confirmation and the external-system limit
%
% FINAL SEALED RENDERING SCRIPT
%
% No external scientific data files are read.
% All frozen Figure-5 derived values are embedded below.
%
% Default output:
%   same output folder as Figure4.m
%
% Usage:
%   Figure5
%
% Optional:
%   Figure5(outputDir)

close all;

%% ========================================================================
% USER-ADJUSTABLE FONT CONTROL
%
% Change ONLY these values to control all text in Figure 5.
% Every title, panel label, axis label, tick label, legend, annotation,
% inset label and value label uses the same font size.
% ========================================================================

FONT_SIZE = 8;
FONT_NAME = 'Arial';

%% ========================================================================
% OUTPUT PATH — SAME DEFAULT LOCATION AS FIGURE 4
% ========================================================================

if nargin < 1 || isempty(outputDir)
    reviewerRoot = strtrim(getenv('CMDO_OUTPUT_ROOT'));
    if ~isempty(reviewerRoot)
        outputDir = fullfile(reviewerRoot,'figures','main');
    elseif exist('cmdo_config','file') == 2
        cfg = cmdo_config('Figure5');
        outputDir = cfg.outputDir;
    else
        scriptDir = fileparts(mfilename('fullpath'));
        outputDir = fullfile(scriptDir,'output');
    end
end

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

fprintf('\n============================================================\n');
fprintf(' FIGURE 5 SEALED RENDERING\n');
fprintf('============================================================\n');
fprintf('No external scientific input files are used.\n');
fprintf('Output directory:\n%s\n',outputDir);

%% ========================================================================
% FROZEN U8 DATA
% ========================================================================

budgetsU8 = [ ...
    128 ...
    256 ...
    512 ...
    1024];

cycleLabels = { ...
    '2015-16', ...
    '2017-18', ...
    '2021-23'};

cycleShort = { ...
    '15-16', ...
    '17-18', ...
    '21-23'};

cycleColors = [ ...
    0.12 0.47 0.71; ...
    0.90 0.41 0.10; ...
    0.20 0.63 0.17];

cycleMarkers = { ...
    'o', ...
    's', ...
    '^'};

u8_direct = [ ...
    0.0297104973803115 ...
    0.0223724741936647 ...
    0.0159576039313353 ...
    0.0113473849304821; ...

    0.0345783772170187 ...
    0.0225076443553209 ...
    0.0140217365920187 ...
    0.0100745227337834; ...

    0.0325739999674874 ...
    0.0230023124566499 ...
    0.0141594687445812 ...
    0.0113272969454439];

u8_observer = [ ...
    0.0270113292327641 ...
    0.0197020398559131 ...
    0.0137977705213480 ...
    0.00958041385680301; ...

    0.0313692361377688 ...
    0.0198369083289561 ...
    0.0125113108771935 ...
    0.00887063271878266; ...

    0.0298161090743875 ...
    0.0210417315695891 ...
    0.0133647447753838 ...
    0.0103918883196933];

u8_mean_weight = [ ...
    0.0869954998546682 ...
    0.113700874848123 ...
    0.133153401606785 ...
    0.148227670936207; ...

    0.0879896659268942 ...
    0.112236420747721 ...
    0.133480071287840 ...
    0.136960438293556; ...

    0.0871764153873167 ...
    0.111320295839713 ...
    0.122225706903852 ...
    0.123470147680736];

u8_cycle_bias = [ ...
    0.000842575069734064; ...
    0.0150515266701597; ...
    0.0270837438943259];

u8_cycle_weight = [ ...
    0.120519361811446; ...
    0.117666649064003; ...
    0.111048141452905];

u8_pooled_gain_pct = ...
    10.072784761268316;

u8_mean_coverage = ...
    0.9683333333333334;

u8_min_coverage = ...
    0.94;

u8_worst_state_regret = ...
    -0.000794723969197435;

u8_slope = ...
    -0.531444237112;

u8_gain_pct = ...
    100 .* ...
    (u8_direct-u8_observer) ...
    ./ u8_direct;

u8_cycle_gain_pct = ...
    mean( ...
        u8_gain_pct, ...
        2, ...
        'omitnan');

%% ========================================================================
% FROZEN U9A DATA
% ========================================================================

u9a_labels = { ...
    'Hungary', ...
    'Switzerland', ...
    'VA Long Beach'};

u9a_gain_pct = [ ...
     0.9501723410978678; ...
    -3.6405194576282790; ...
     1.8417430381757400];

u9a_pooled_gain_pct = ...
    -0.11107948822981814;

u9a_mean_weight = ...
    0.012462595983469384;

u9a_worst_state_regret = ...
    0.0023637286286992596;

%% ========================================================================
% FROZEN U9B DATA
% ========================================================================

budgetsU9 = [ ...
    128 ...
    256 ...
    512 ...
    1024];

u9b_direct = [ ...
    0.0316853125 ...
    0.0212528125 ...
    0.01532296875 ...
    0.011246171875];

u9b_observer = [ ...
    0.03197451613562453 ...
    0.02230029082575096 ...
    0.01620864849191869 ...
    0.01193845421620120];

u9b_weight = [ ...
    0.0651411915015402 ...
    0.0604053330338837 ...
    0.0461494542946822 ...
    0.0327076870812761];

u9b_gain_pct_by_budget = [ ...
    -0.912737204736529 ...
    -4.928657445930818 ...
    -5.780079280777059 ...
    -6.155715463855992];

u9b_source_prevalence = ...
    0.08802124311565697;

u9b_target_prevalence = ...
    0.0571;

u9b_historical_auc = ...
    0.7569019259437727;

u9b_target_auc = ...
    0.5742562768401469;

u9b_historical_accuracy = ...
    0.6162733529990168;

u9b_target_accuracy = ...
    0.7485;

u9b_pooled_gain_pct = ...
    -3.665883893231158;

u9b_worst_budget_mean_regret = ...
    0.0010474783257509634;

u9b_mean_coverage = ...
    0.970;

u9b_min_coverage = ...
    0.945;

u9b_slope = ...
    -0.49550986646467715;

%% ========================================================================
% FROZEN-DATA SANITY CHECKS
% ========================================================================

assert(isequal(size(u8_direct),[3 4]));
assert(isequal(size(u8_observer),[3 4]));
assert(isequal(size(u8_mean_weight),[3 4]));

assert(numel(u8_cycle_bias)==3);
assert(numel(u8_cycle_weight)==3);

assert(numel(u9a_gain_pct)==3);

assert(numel(u9b_direct)==4);
assert(numel(u9b_observer)==4);
assert(numel(u9b_weight)==4);
assert(numel(u9b_gain_pct_by_budget)==4);

u9b_gain_reconstructed = ...
    100 .* ...
    (u9b_direct-u9b_observer) ...
    ./ u9b_direct;

u9b_gain_delta = ...
    max(abs( ...
        u9b_gain_reconstructed ...
        - u9b_gain_pct_by_budget));

assert( ...
    u9b_gain_delta < 1e-10, ...
    'Frozen U9B gain reconstruction failed.');

fprintf( ...
    'Frozen U9B gain reconstruction max delta = %.3e pp\n', ...
    u9b_gain_delta);

%% ========================================================================
% FIGURE SETUP
% ========================================================================

fig = figure( ...
    'Position',[40 10 1080 980], ...
    'Color','w', ...
    'Renderer','painters', ...
    'Name','CMDO Figure 5 - External-system limit', ...
    'NumberTitle','off');

tl = tiledlayout( ...
    fig, ...
    2,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

title( ...
    tl, ...
    'Operational confirmation and the external-system limit', ...
    'FontWeight','bold', ...
    'FontSize',FONT_SIZE);

axAcontainer = ...
    nexttile(tl,1);

axBcontainer = ...
    nexttile(tl,2);

axCcontainer = ...
    nexttile(tl,3,[1 2]);

axis(axAcontainer,'off');
axis(axBcontainer,'off');
axis(axCcontainer,'off');

drawnow;

%% ========================================================================
% PANEL a — U8 TEMPORAL RESERVE
% ========================================================================

title( ...
    axAcontainer, ...
    'Temporal confirmation', ...
    'FontWeight','bold', ...
    'FontSize',FONT_SIZE);

pA = ...
    axAcontainer.Position;

axA1 = axes( ...
    fig, ...
    'Position',[ ...
    pA(1)+0.05*pA(3), ...
    pA(2)+0.13*pA(4), ...
    0.58*pA(3), ...
    0.76*pA(4)], ...
    'Color','w');

axA2 = axes( ...
    fig, ...
    'Position',[ ...
    pA(1)+0.69*pA(3), ...
    pA(2)+0.36*pA(4), ...
    0.25*pA(3), ...
    0.25*pA(4)], ...
    'Color','w');

%% ------------------------------------------------------------------------
% a1 — main U8 temporal profile
% ------------------------------------------------------------------------

hold(axA1,'on');

for i = 1:3

    plot( ...
        axA1, ...
        budgetsU8, ...
        u8_direct(i,:), ...
        '--', ...
        'Color',cycleColors(i,:), ...
        'LineWidth',1.05, ...
        'Marker',cycleMarkers{i}, ...
        'MarkerFaceColor','w', ...
        'MarkerSize',5.4, ...
        'DisplayName',[cycleLabels{i} ' direct']);

    plot( ...
        axA1, ...
        budgetsU8, ...
        u8_observer(i,:), ...
        '-', ...
        'Color',cycleColors(i,:), ...
        'LineWidth',1.80, ...
        'Marker',cycleMarkers{i}, ...
        'MarkerFaceColor',cycleColors(i,:), ...
        'MarkerEdgeColor','w', ...
        'MarkerSize',5.8, ...
        'DisplayName',[cycleLabels{i} ' observer']);

end

set( ...
    axA1, ...
    'XScale','log');

xticks( ...
    axA1, ...
    budgetsU8);

xticklabels( ...
    axA1, ...
    {'128','256','512','1024'});

xlabel( ...
    axA1, ...
    'Screened-case budget');

ylabel( ...
    axA1, ...
    'Accuracy MAE');

title( ...
    axA1, ...
    sprintf( ...
        'Temporal profile (pooled %+.2f%%)', ...
        u8_pooled_gain_pct), ...
    'FontWeight','bold', ...
    'FontSize',FONT_SIZE);

set( ...
    axA1, ...
    'XGrid','on', ...
    'YGrid','on');

axA1.GridAlpha = ...
    0.10;

box( ...
    axA1, ...
    'off');

set( ...
    axA1, ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_SIZE);

lgdA = legend( ...
    axA1, ...
    'Location','southwest', ...
    'Box','off', ...
    'NumColumns',2, ...
    'FontSize',FONT_SIZE);

lgdA.ItemTokenSize = ...
    [9 8];

%% ------------------------------------------------------------------------
% a2 — cycle mean gain
% ------------------------------------------------------------------------

hold(axA2,'on');

bar( ...
    axA2, ...
    1:3, ...
    u8_cycle_gain_pct, ...
    0.62, ...
    'FaceColor',[0.78 0.84 0.93], ...
    'EdgeColor',[0.42 0.53 0.66]);

for i = 1:3

    text( ...
        axA2, ...
        i, ...
        u8_cycle_gain_pct(i)+0.22, ...
        sprintf( ...
            '%.2f%%', ...
            u8_cycle_gain_pct(i)), ...
        'HorizontalAlignment','center', ...
        'FontSize',FONT_SIZE, ...
        'FontWeight','bold');

end

xticks( ...
    axA2, ...
    1:3);

xticklabels( ...
    axA2, ...
    cycleShort);

ylabel( ...
    axA2, ...
    'Mean gain');

title( ...
    axA2, ...
    'Cycle-mean gain', ...
    'FontWeight','bold', ...
    'FontSize',FONT_SIZE);

set( ...
    axA2, ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_SIZE, ...
    'Box','on', ...
    'XGrid','off', ...
    'YGrid','on');

axA2.GridAlpha = ...
    0.10;

%% ------------------------------------------------------------------------
% U8 summary
% ------------------------------------------------------------------------

annotation( ...
    fig, ...
    'textbox', ...
    [ ...
    pA(1)+0.68*pA(3), ...
    pA(2)+0.73*pA(4), ...
    0.25*pA(3), ...
    0.12*pA(4)], ...
    'String',sprintf( ...
        [ ...
        'Coverage %.3f / %.3f\n' ...
        'Worst regret %.6f\n' ...
        'Slope %.3f'], ...
        u8_mean_coverage, ...
        u8_min_coverage, ...
        u8_worst_state_regret, ...
        u8_slope), ...
    'FitBoxToText','off', ...
    'BackgroundColor','none', ...
    'EdgeColor','none', ...
    'LineStyle','none', ...
    'Margin',0, ...
    'FontSize',FONT_SIZE, ...
    'FontWeight','bold', ...
    'Interpreter','none');

%% ========================================================================
% PANEL b — ADAPTATION AND BOUNDARY EVIDENCE
% ========================================================================

title( ...
    axBcontainer, ...
    'Adaptation across deployment shifts', ...
    'FontWeight','bold', ...
    'FontSize',FONT_SIZE);

pB = ...
    axBcontainer.Position;

axB1 = axes( ...
    fig, ...
    'Position',[ ...
    pB(1)+0.08*pB(3), ...
    pB(2)+0.69*pB(4), ...
    0.82*pB(3), ...
    0.15*pB(4)], ...
    'Color','w');

axB2 = axes( ...
    fig, ...
    'Position',[ ...
    pB(1)+0.08*pB(3), ...
    pB(2)+0.40*pB(4), ...
    0.82*pB(3), ...
    0.15*pB(4)], ...
    'Color','w');

axB3 = axes( ...
    fig, ...
    'Position',[ ...
    pB(1)+0.08*pB(3), ...
    pB(2)+0.11*pB(4), ...
    0.82*pB(3), ...
    0.15*pB(4)], ...
    'Color','w');

%% ------------------------------------------------------------------------
% b1 — U8 mismatch versus transport weight
% ------------------------------------------------------------------------

hold(axB1,'on');

xb1 = ...
    1:3;

yyaxis(axB1,'left');

bar( ...
    axB1, ...
    xb1, ...
    100*abs(u8_cycle_bias), ...
    0.55, ...
    'FaceColor',[0.84 0.88 0.94], ...
    'EdgeColor',[0.50 0.58 0.70]);

ylabel( ...
    axB1, ...
    'Mismatch (pp)');

yyaxis(axB1,'right');

plot( ...
    axB1, ...
    xb1, ...
    u8_cycle_weight, ...
    '-o', ...
    'Color',[0.55 0.30 0.75], ...
    'LineWidth',1.35, ...
    'MarkerFaceColor',[0.55 0.30 0.75], ...
    'MarkerEdgeColor','w', ...
    'MarkerSize',4.8);

ylabel( ...
    axB1, ...
    'Weight');

xticks( ...
    axB1, ...
    xb1);

xticklabels( ...
    axB1, ...
    cycleShort);

xlim( ...
    axB1, ...
    [0.5 3.5]);

title( ...
    axB1, ...
    'Mismatch contracts borrowing (12/12 improved)', ...
    'FontWeight','bold', ...
    'FontSize',FONT_SIZE);

set( ...
    axB1, ...
    'XGrid','off', ...
    'YGrid','on');

axB1.GridAlpha = ...
    0.10;

box(axB1,'off');

set( ...
    axB1, ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_SIZE);

%% ------------------------------------------------------------------------
% b2 — U9A centre gains
% ------------------------------------------------------------------------

hold(axB2,'on');

xb2 = ...
    1:3;

bar( ...
    axB2, ...
    xb2, ...
    u9a_gain_pct, ...
    0.56, ...
    'FaceColor',[0.74 0.82 0.92], ...
    'EdgeColor',[0.43 0.54 0.67]);

yline( ...
    axB2, ...
    0, ...
    'k-', ...
    'LineWidth',0.9);

for i = 1:3

    if u9a_gain_pct(i) >= 0

        text( ...
            axB2, ...
            xb2(i), ...
            u9a_gain_pct(i)+0.16, ...
            sprintf( ...
                '%+.2f%%', ...
                u9a_gain_pct(i)), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','bottom', ...
            'FontSize',FONT_SIZE, ...
            'FontWeight','bold');

    else

        text( ...
            axB2, ...
            xb2(i), ...
            u9a_gain_pct(i)-0.18, ...
            sprintf( ...
                '%+.2f%%', ...
                u9a_gain_pct(i)), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','top', ...
            'FontSize',FONT_SIZE, ...
            'FontWeight','bold');

    end

end

xticks( ...
    axB2, ...
    xb2);

xticklabels( ...
    axB2, ...
    u9a_labels);

ylabel( ...
    axB2, ...
    'Relative MAE change (%)');

ylim( ...
    axB2, ...
    [-5.2 3.2]);

yticks( ...
    axB2, ...
    [-4 -2 0 2]);

title( ...
    axB2, ...
    sprintf( ...
        'U9A centres: %+.2f%% pooled; w = %.4f', ...
        u9a_pooled_gain_pct, ...
        u9a_mean_weight), ...
    'FontWeight','bold', ...
    'FontSize',FONT_SIZE);

set( ...
    axB2, ...
    'XGrid','off', ...
    'YGrid','on');

axB2.GridAlpha = ...
    0.10;

box(axB2,'off');

set( ...
    axB2, ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_SIZE);

%% ------------------------------------------------------------------------
% b3 — U9B source-target shift
% ------------------------------------------------------------------------

hold(axB3,'on');

sourceVals = [ ...
    u9b_source_prevalence ...
    u9b_historical_auc ...
    u9b_historical_accuracy];

targetVals = [ ...
    u9b_target_prevalence ...
    u9b_target_auc ...
    u9b_target_accuracy];

Y = [ ...
    sourceVals(:), ...
    targetVals(:)];

hb = bar( ...
    axB3, ...
    Y, ...
    0.76, ...
    'grouped');

if numel(hb) >= 2

    hb(1).FaceColor = ...
        [0.12 0.47 0.71];

    hb(2).FaceColor = ...
        [0.90 0.41 0.10];

end

xticks( ...
    axB3, ...
    1:3);

xticklabels( ...
    axB3, ...
    {'Prev.','AUC','Acc.'});

ylim( ...
    axB3, ...
    [0 0.90]);

ylabel( ...
    axB3, ...
    'Value');

title( ...
    axB3, ...
    'Source-target shift', ...
    'FontWeight','bold', ...
    'FontSize',FONT_SIZE);

set( ...
    axB3, ...
    'XGrid','off', ...
    'YGrid','on');

axB3.GridAlpha = ...
    0.10;

box(axB3,'off');

set( ...
    axB3, ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_SIZE);

legend( ...
    axB3, ...
    {'Historical','Target'}, ...
    'Location','northwest', ...
    'Box','off', ...
    'FontSize',FONT_SIZE);

for j = 1:3

    text( ...
        axB3, ...
        j-0.15, ...
        sourceVals(j)+0.035, ...
        sprintf( ...
            '%.3f', ...
            sourceVals(j)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',FONT_SIZE, ...
        'FontWeight','bold');

    text( ...
        axB3, ...
        j+0.15, ...
        targetVals(j)+0.035, ...
        sprintf( ...
            '%.3f', ...
            targetVals(j)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',FONT_SIZE, ...
        'FontWeight','bold');

end

%% ========================================================================
% PANEL c — U9B EXTERNAL RESERVE
% ========================================================================

title( ...
    axCcontainer, ...
    'External-system limit', ...
    'FontWeight','bold', ...
    'FontSize',FONT_SIZE);

pC = ...
    axCcontainer.Position;

axC1 = axes( ...
    fig, ...
    'Position',[ ...
    pC(1)+0.05*pC(3), ...
    pC(2)+0.16*pC(4), ...
    0.40*pC(3), ...
    0.58*pC(4)], ...
    'Color','w');

axC2 = axes( ...
    fig, ...
    'Position',[ ...
    pC(1)+0.73*pC(3), ...
    pC(2)+0.30*pC(4), ...
    0.18*pC(3), ...
    0.30*pC(4)], ...
    'Color','w');

%% ------------------------------------------------------------------------
% c1 — U9B main profile
% ------------------------------------------------------------------------

hold(axC1,'on');

yyaxis(axC1,'left');

plot( ...
    axC1, ...
    budgetsU9, ...
    u9b_direct, ...
    '--o', ...
    'LineWidth',1.10, ...
    'MarkerSize',5.4, ...
    'MarkerFaceColor','w', ...
    'Color',[0.25 0.25 0.25], ...
    'DisplayName','Same-budget direct');

plot( ...
    axC1, ...
    budgetsU9, ...
    u9b_observer, ...
    '-s', ...
    'LineWidth',1.80, ...
    'MarkerSize',5.8, ...
    'MarkerFaceColor',[0.20 0.50 0.80], ...
    'MarkerEdgeColor','w', ...
    'Color',[0.20 0.50 0.80], ...
    'DisplayName','Guarded observer');

ylabel( ...
    axC1, ...
    'Accuracy MAE');

for i = 1:numel(budgetsU9)

    text( ...
        axC1, ...
        budgetsU9(i), ...
        u9b_observer(i)+0.00055, ...
        sprintf( ...
            '%+.2f%%', ...
            u9b_gain_pct_by_budget(i)), ...
        'HorizontalAlignment','center', ...
        'FontSize',FONT_SIZE, ...
        'FontWeight','bold');

end

yyaxis(axC1,'right');

plot( ...
    axC1, ...
    budgetsU9, ...
    u9b_weight, ...
    '-^', ...
    'LineWidth',1.10, ...
    'MarkerSize',5.0, ...
    'MarkerFaceColor',[0.55 0.30 0.75], ...
    'MarkerEdgeColor','w', ...
    'Color',[0.55 0.30 0.75], ...
    'DisplayName','Mean transport weight');

ylabel( ...
    axC1, ...
    'Mean transport weight');

set( ...
    axC1, ...
    'XScale','log');

xticks( ...
    axC1, ...
    budgetsU9);

xticklabels( ...
    axC1, ...
    {'128','256','512','1024'});

xlabel( ...
    axC1, ...
    'Verified-outcome budget');

set( ...
    axC1, ...
    'XGrid','on', ...
    'YGrid','on');

axC1.GridAlpha = ...
    0.10;

box(axC1,'off');

set( ...
    axC1, ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_SIZE);

legend( ...
    axC1, ...
    'Location','southwest', ...
    'Box','off', ...
    'FontSize',FONT_SIZE);

%% ------------------------------------------------------------------------
% U9B summary
% ------------------------------------------------------------------------

annotation( ...
    fig, ...
    'textbox', ...
    [ ...
    pC(1)+0.52*pC(3), ...
    pC(2)+0.56*pC(4), ...
    0.15*pC(3), ...
    0.16*pC(4)], ...
    'String',sprintf( ...
        [ ...
        'Pooled change %+.2f%%\n' ...
        'Worst regret %.6f\n' ...
        'Coverage %.3f / %.3f\n' ...
        'Slope %.3f'], ...
        u9b_pooled_gain_pct, ...
        u9b_worst_budget_mean_regret, ...
        u9b_mean_coverage, ...
        u9b_min_coverage, ...
        u9b_slope), ...
    'FitBoxToText','off', ...
    'BackgroundColor','none', ...
    'EdgeColor','none', ...
    'LineStyle','none', ...
    'Margin',0, ...
    'FontSize',FONT_SIZE, ...
    'FontWeight','bold', ...
    'Interpreter','none');

%% ------------------------------------------------------------------------
% c2 — pooled U8/U9 summary
% ------------------------------------------------------------------------

hold(axC2,'on');

vals = [ ...
    u8_pooled_gain_pct; ...
    u9a_pooled_gain_pct; ...
    u9b_pooled_gain_pct];

labels2 = { ...
    'U8 temporal', ...
    'U9A bridge', ...
    'U9B external'};

barh( ...
    axC2, ...
    1:3, ...
    vals, ...
    0.60, ...
    'FaceColor',[0.75 0.82 0.92], ...
    'EdgeColor',[0.43 0.54 0.67]);

xline( ...
    axC2, ...
    0, ...
    'k-', ...
    'LineWidth',0.9);

for i = 1:3

    if vals(i) >= 0

        text( ...
            axC2, ...
            vals(i)+0.20, ...
            i, ...
            sprintf( ...
                '%+.2f%%', ...
                vals(i)), ...
            'HorizontalAlignment','left', ...
            'VerticalAlignment','middle', ...
            'FontSize',FONT_SIZE, ...
            'FontWeight','bold');

    else

        text( ...
            axC2, ...
            vals(i)-0.20, ...
            i, ...
            sprintf( ...
                '%+.2f%%', ...
                vals(i)), ...
            'HorizontalAlignment','right', ...
            'VerticalAlignment','middle', ...
            'FontSize',FONT_SIZE, ...
            'FontWeight','bold');

    end

end

set( ...
    axC2, ...
    'YDir','reverse');

yticks( ...
    axC2, ...
    1:3);

yticklabels( ...
    axC2, ...
    labels2);

xlabel( ...
    axC2, ...
    'Relative MAE change');

xlim( ...
    axC2, ...
    [-10 12]);

xticks( ...
    axC2, ...
    [-10 -5 0 5 10]);

title( ...
    axC2, ...
    'Pooled comparison', ...
    'FontWeight','bold', ...
    'FontSize',FONT_SIZE);

set( ...
    axC2, ...
    'FontName',FONT_NAME, ...
    'FontSize',FONT_SIZE, ...
    'Box','on', ...
    'XGrid','on', ...
    'YGrid','off');

axC2.GridAlpha = ...
    0.10;

%% ------------------------------------------------------------------------
% Boundary note
% ------------------------------------------------------------------------

annotation( ...
    fig, ...
    'textbox', ...
    [ ...
    pC(1)+0.71*pC(3), ...
    pC(2)+0.10*pC(4), ...
    0.22*pC(3), ...
    0.08*pC(4)], ...
    'String', ...
    [ ...
    'U8 remains beneficial, U9A is mixed, and ' ...
    'U9B crosses the external-system limit.'], ...
    'FitBoxToText','off', ...
    'BackgroundColor','none', ...
    'EdgeColor','none', ...
    'LineStyle','none', ...
    'Margin',0, ...
    'FontSize',FONT_SIZE, ...
    'Interpreter','none');

%% ========================================================================
% AUDIT PRINTOUT
% ========================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf(' Figure 5 U8/U9 operational boundary audit\n');
fprintf('============================================================\n');

fprintf( ...
    'U8 pooled gain = %.6f%%\n', ...
    u8_pooled_gain_pct);

fprintf( ...
    'U8 cycle gains = %s\n', ...
    sprintf( ...
        '%.6f%% ', ...
        u8_cycle_gain_pct));

fprintf( ...
    'U9A pooled gain = %.6f%%\n', ...
    u9a_pooled_gain_pct);

fprintf( ...
    'U9A centre gains = %s\n', ...
    sprintf( ...
        '%+.6f%% ', ...
        u9a_gain_pct));

fprintf( ...
    'U9B pooled gain = %.6f%%\n', ...
    u9b_pooled_gain_pct);

fprintf( ...
    'U9B budget gains = %s\n', ...
    sprintf( ...
        '%+.6f%% ', ...
        u9b_gain_pct_by_budget));

fprintf('============================================================\n');

%% ========================================================================
% PANEL LABELS
% ========================================================================

drawnow;

f5_panel_label( ...
    fig, ...
    axAcontainer, ...
    'a', ...
    -0.030, ...
    0.004, ...
    FONT_NAME, ...
    FONT_SIZE);

f5_panel_label( ...
    fig, ...
    axBcontainer, ...
    'b', ...
    -0.030, ...
    0.004, ...
    FONT_NAME, ...
    FONT_SIZE);

f5_panel_label( ...
    fig, ...
    axCcontainer, ...
    'c', ...
    -0.030, ...
    0.006, ...
    FONT_NAME, ...
    FONT_SIZE);

% Final safety pass: force every font-bearing object to use exactly
% the same font name and font size, including axes labels, titles,
% tick labels, legends, colorbars and annotations.
f5_apply_uniform_font( ...
    fig, ...
    FONT_NAME, ...
    FONT_SIZE);

%% ========================================================================
% EXPORT
% ========================================================================

drawnow;

baseName = ...
    'Figure5_Operational_External_Admissibility_Boundary';

pngPath = ...
    fullfile( ...
        outputDir, ...
        [baseName '.png']);

pdfPath = ...
    fullfile( ...
        outputDir, ...
        [baseName '.pdf']);

svgPath = ...
    fullfile( ...
        outputDir, ...
        [baseName '.svg']);

figPath = ...
    fullfile( ...
        outputDir, ...
        [baseName '.fig']);

f5_safe_export( ...
    fig, ...
    pngPath, ...
    pdfPath, ...
    svgPath);

savefig( ...
    fig, ...
    figPath);

fprintf('\nFinal Figure 5 written to:\n%s\n',outputDir);
fprintf('PNG: %s\n',pngPath);
fprintf('PDF: %s\n',pdfPath);
fprintf('SVG: %s\n',svgPath);
fprintf('FIG: %s\n',figPath);

end

%% ========================================================================
% LOCAL HELPERS
% ========================================================================

function f5_panel_label(fig,ax,letter,dx,dy,fontName,fontSize)

if nargin < 4 || isempty(dx)
    dx = -0.030;
end

if nargin < 5 || isempty(dy)
    dy = 0.006;
end

if nargin < 6 || isempty(fontName)
    fontName = 'Arial';
end

if nargin < 7 || isempty(fontSize)
    fontSize = 9;
end

pos = ...
    ax.Position;

annotation( ...
    fig, ...
    'textbox', ...
    [ ...
    pos(1)+dx, ...
    pos(2)+pos(4)+dy, ...
    0.028, ...
    0.028], ...
    'String',letter, ...
    'LineStyle','none', ...
    'FitBoxToText','off', ...
    'Margin',0, ...
    'FontName',fontName, ...
    'FontWeight','bold', ...
    'FontSize',fontSize, ...
    'Interpreter','none', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top');

end

function f5_apply_uniform_font(fig,fontName,fontSize)

objects = findall(fig);

for k = 1:numel(objects)

    obj = objects(k);

    if isprop(obj,'FontName')
        try
            obj.FontName = fontName;
        catch
        end
    end

    if isprop(obj,'FontSize')
        try
            obj.FontSize = fontSize;
        catch
        end
    end

end

drawnow;

end

function f5_safe_export(fig,pngPath,pdfPath,svgPath)

try

    exportgraphics( ...
        fig, ...
        pngPath, ...
        'Resolution',300, ...
        'BackgroundColor','white');

catch

    print( ...
        fig, ...
        pngPath, ...
        '-dpng', ...
        '-r300');

end

try

    exportgraphics( ...
        fig, ...
        pdfPath, ...
        'ContentType','vector', ...
        'BackgroundColor','white');

catch

    print( ...
        fig, ...
        pdfPath, ...
        '-dpdf', ...
        '-painters');

end

try

    exportgraphics( ...
        fig, ...
        svgPath, ...
        'ContentType','vector', ...
        'BackgroundColor','white');

catch

    try

        saveas( ...
            fig, ...
            svgPath);

    catch

        warning( ...
            'Figure5:SVGExportFailed', ...
            'SVG export failed on this MATLAB version.');

    end

end

end
