function Figure5_InformationClosure_Composability_v8(outputDir, repoRoot)
% FIGURE5_INFORMATIONCLOSURE_COMPOSABILITY_V8
%
% CMDO Figure 5 — PRESERVE
% Adaptive composability and the boundary of adaptive evidence reuse
%
% Final main-text architecture:
%
%   Figure 3 : IDENTIFY
%   Figure 4 : REUSE
%   Figure 5 : PRESERVE
%
% Figure 5 — PRESERVE
%
% Central proposition:
%   Evidence value must survive adaptation.
%
% Panels:
%   A  Adaptation can consume fixed-use value
%   B  Locked testing limits mechanism generality
%   C  Breaking pairing reduces composition cost
%   D  Adaptation is worthwhile only when H > A + C
%
% This script intentionally DOES NOT redraw:
%   - U11 information-closure witness        -> Figure 3
%   - 185-state admissibility synthesis      -> Figure 4
%
% It uses only the U9B adaptive-composition decomposition and the
% separately locked / post-completion U10 analyses needed for PRESERVE.
%
% Usage:
%
%   Figure5_InformationClosure_Composability_v8
%
% or
%
%   Figure5_InformationClosure_Composability_v8([], ...
%       'C:\Users\zyx\CMDO-Reproducibility')
%
% -------------------------------------------------------------------------

close all;

%% ========================================================================
% 0) STYLE
% ========================================================================

FONT = 'Arial';

FS_LETTER = 21;
FS_TITLE  = 11.5;
FS_AXIS   = 10.5;
FS_TICK   = 9.5;
FS_SMALL  = 9.0;
FS_TINY   = 8.0;

blue   = [0.02 0.29 0.70];
navy   = [0.02 0.24 0.63];
green  = [0.02 0.48 0.20];
red    = [0.82 0.05 0.04];
purple = [0.43 0.17 0.70];

grey   = [0.43 0.43 0.43];
lgrey  = [0.82 0.82 0.82];
dgrey  = [0.22 0.22 0.22];

panelRed    = local_mix(red,    [1 1 1],0.79);
panelPurple = local_mix(purple, [1 1 1],0.81);

lightGreen  = local_mix(green,[1 1 1],0.88);
lightRed    = local_mix(red,  [1 1 1],0.90);
lightPurple = local_mix(purple,[1 1 1],0.88);

%% ========================================================================
% 1) PATHS
% ========================================================================

thisFile = mfilename('fullpath');

if isempty(thisFile)
    scriptDir = pwd;
else
    scriptDir = fileparts(thisFile);
end

if nargin < 2 || isempty(repoRoot)
    repoRoot = local_find_cmdo_repo(scriptDir);
end

if isempty(repoRoot)
    error(['Could not locate CMDO-Reproducibility.' newline ...
           'Run with an explicit repository path.']);
end

if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(scriptDir,'output');
end

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

fprintf('\n============================================================\n');
fprintf(' CMDO FIGURE 5 — PRESERVE\n');
fprintf(' Adaptive composability and adaptation frontier\n');
fprintf('============================================================\n');
fprintf('Repository : %s\n',repoRoot);
fprintf('Output     : %s\n',outputDir);

%% ========================================================================
% 2) U9B — ADAPTIVE-COMPOSITION EXCESS RISK
% ========================================================================

u9bPath = fullfile( ...
    repoRoot, ...
    'source_data', ...
    'figure6_admissibility', ...
    'U9B_external_composability_decomposition.csv');

if ~isfile(u9bPath)
    error('Missing U9B decomposition:\n%s',u9bPath);
end

U9B = readtable(u9bPath);

local_require_vars( ...
    U9B, ...
    {'budget', ...
     'scalar_gain_pct', ...
     'observed_gain_pct', ...
     'xi_downward_pp'}, ...
    'U9B composability decomposition');

u9bBudget = double(U9B.budget);
u9bFixed  = double(U9B.scalar_gain_pct);
u9bAdapt  = double(U9B.observed_gain_pct);
u9bXi     = double(U9B.xi_downward_pp);

% Preserve the original percentage-point decomposition for frozen auditing.
xiResidual = local_nanmax(abs((u9bFixed-u9bAdapt)-u9bXi));

% Convert fixed/adaptive gains into the normalized-risk coordinates used
% by the main-text PRESERVE definition:
%
%   R/V = 1 - gain/100
%   Xi  = [R_adaptive - R_fixed(mean w)]/V
%
% Therefore the original downward displacement in percentage points is
% exactly 100*Xi.
u9bFixedRisk = ...
    1 - u9bFixed./100;

u9bAdaptRisk = ...
    1 - u9bAdapt./100;

u9bXiRisk = ...
    u9bXi./100;

xiRiskResidual = ...
    local_nanmax( ...
    abs( ...
    (u9bAdaptRisk-u9bFixedRisk) - ...
    u9bXiRisk));

assert( ...
    xiResidual < 1e-9, ...
    'U9B Xi decomposition mismatch.');

assert( ...
    xiRiskResidual < 1e-12, ...
    'U9B normalized Xi decomposition mismatch.');

nXiPositive = nnz(u9bXi > 0);

benefitToHarm = ...
    (u9bFixed > 0) & ...
    (u9bAdapt < 0);

benefitToHarmN = nnz(benefitToHarm);

%% ========================================================================
% 3) U10 — POST-COMPLETION DEPENDENCE DECOMPOSITION
% ========================================================================

u10Path = fullfile( ...
    repoRoot, ...
    'U10_Prospective_ECG', ...
    '02_Posthoc_Diagnostics', ...
    'U10_DEPENDENCE_DECOMPOSITION.csv');

if ~isfile(u10Path)
    error('Missing U10 dependence decomposition:\n%s',u10Path);
end

U10 = readtable(u10Path);

local_require_vars( ...
    U10, ...
    {'dataset', ...
     'budget', ...
     'shared_adaptive_gain_pct', ...
     'shared_constant_mean_gain_pct', ...
     'B', ...
     'direct_mse', ...
     'shared_constant_mean_weight', ...
     'shared_adaptive_mse', ...
     'shared_constant_mean_mse', ...
     'shared_permuted_weight_mse', ...
     'shared_permuted_weight_mse_sd', ...
     'shared_tax_weight_heterogeneity'}, ...
    'U10 dependence decomposition');

u10Dataset = string(U10.dataset);
u10Budget  = double(U10.budget);

datasetOrder = ["georgia","cpsc_2018"];

rowOrder = [];

for d = 1:numel(datasetOrder)

    idx = find(u10Dataset == datasetOrder(d));

    [~,o] = sort(u10Budget(idx),'ascend');

    rowOrder = [rowOrder; idx(o)]; %#ok<AGROW>

end

U10 = U10(rowOrder,:);

u10Dataset = string(U10.dataset);
u10Budget  = double(U10.budget);

u10Adaptive = double(U10.shared_adaptive_gain_pct);
u10Fixed    = double(U10.shared_constant_mean_gain_pct);

assert(height(U10)==8, ...
    'Expected eight U10 cohort-budget cells.');

%% ========================================================================
% 4) U10 — HETEROGENEITY / ALLOCATION / COMPOSITION FRONTIER
% ========================================================================

u10B     = double(U10.B);
u10V     = double(U10.direct_mse);
u10MeanW = double(U10.shared_constant_mean_weight);

u10Lambda = (u10B.^2)./u10V;

u10Wstar = 1./(1+u10Lambda);

% matched-mean adaptive composition excess risk
u10XiExact = ...
    (double(U10.shared_adaptive_mse) - ...
     double(U10.shared_constant_mean_mse)) ./ u10V;

% permutation diagnostic
u10XiPerm = ...
    (double(U10.shared_permuted_weight_mse) - ...
     double(U10.shared_constant_mean_mse)) ./ u10V;

u10XiPermSD = ...
    double(U10.shared_permuted_weight_mse_sd) ./ u10V;

% role-separated heterogeneity-only prediction
u10XiHet = ...
    double(U10.shared_tax_weight_heterogeneity) ./ u10V;

% best single fixed reuse weight across states
wGlobal = 1/(1 + local_nanmean(u10Lambda));

% heterogeneity opportunity
u10Hi = ...
    (1+u10Lambda) .* ...
    (u10Wstar-wGlobal).^2;

% allocation error
u10Ai = ...
    (1+u10Lambda) .* ...
    (u10MeanW-u10Wstar).^2;

Hhac = local_nanmean(u10Hi);
Ahac = local_nanmean(u10Ai);

% mean composition excess risk
Chac  = local_nanmean(u10XiExact);
Cperm = local_nanmean(u10XiPerm);
Chet  = local_nanmean(u10XiHet);

% frontier coordinates
xShared = Ahac + Chac;
xPerm   = Ahac + Cperm;
xRole   = Ahac + Chet;

marginShared = Hhac - xShared;
marginPerm   = Hhac - xPerm;
marginRole   = Hhac - xRole;

cReductionPct = ...
    100*(Chac-Cperm)/Chac;

%% ------------------------------------------------------------------------
% Frozen numerical fingerprints
% -------------------------------------------------------------------------

assert(abs(Hhac -0.08614018) < 5e-7, ...
    'U10 H fingerprint mismatch.');

assert(abs(Ahac -0.01403814) < 5e-7, ...
    'U10 A fingerprint mismatch.');

assert(abs(Chac -0.21760208) < 5e-7, ...
    'U10 C fingerprint mismatch.');

assert(abs(Cperm-0.03214915) < 5e-7, ...
    'U10 permutation-C fingerprint mismatch.');

assert(abs(Chet -0.03136104) < 5e-7, ...
    'U10 role-separated-C fingerprint mismatch.');

%% ========================================================================
% 5) FROZEN PROSPECTIVE U10 CHALLENGE
% ========================================================================
%
% These are the locked prospective cohort-level summaries:
%
%                      role separation   cross-fitting
% Georgia                   3/4              3/4
% CPSC 2018                 2/4              2/4
%
% Georgia met the prespecified cohort-level criterion.
% CPSC 2018 did not.
%
% These are NOT reconstructed from the post-completion CSV above.

lockedChecks = [ ...
    3 3; ...
    2 2];

lockedDenom = 4;

cohortPassed = [true; false];

nCohortPassed = nnz(cohortPassed);

% Verify frozen primary gate if archived JSON is available.
u10PrimaryJson = fullfile( ...
    repoRoot, ...
    'U10_Prospective_ECG', ...
    '01_Prospective_Result', ...
    'U10_PRIMARY_RESULT.json');

if isfile(u10PrimaryJson)

    J = jsondecode(fileread(u10PrimaryJson));

    if isfield(J,'primary_verdict')

        rawVerdict = string(J.primary_verdict);

        assert( ...
            strcmpi(rawVerdict,"MECHANISM_NOT_CONFIRMED"), ...
            'Unexpected U10 frozen primary verdict.');

    end

end

%% ========================================================================
% 6) CANVAS
% ========================================================================

fig = figure( ...
    'Color','w', ...
    'Position',[55 35 860 820], ...
    'Renderer','painters', ...
    'Name','CMDO Figure 5 — PRESERVE', ...
    'NumberTitle','off');

% -------------------------------------------------------------------------
% Figure-level scientific statement
% -------------------------------------------------------------------------
annotation( ...
    fig, ...
    'textbox', ...
    [0.20 0.952 0.60 0.035], ...
    'String','Evidence value must survive adaptation', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'LineStyle','none', ...
    'FontName',FONT, ...
    'FontSize',14.5, ...
    'FontWeight','bold', ...
    'Color',dgrey);

% Leave a small band above the panels for the single figure-level message.
PA = [0.025 0.505 0.465 0.435];
PB = [0.510 0.505 0.465 0.435];

% Bottom: mechanism localization + larger adaptation frontier
PC = [0.025 0.045 0.465 0.430];
PD = [0.510 0.045 0.465 0.430];

%% ========================================================================
% PANEL A
% FIXED VALUE CAN BE LOST UNDER ADAPTATION
% ========================================================================

axA0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PA);

axis(axA0,[0 1 0 1]);
axis(axA0,'off');
hold(axA0,'on');

local_panel_border( ...
    axA0, ...
    [0.005 0.005 0.99 0.99], ...
    panelRed, ...
    1.10);

local_panel_header( ...
    axA0, ...
    'A', ...
    'Adaptation can consume fixed-use value', ...
    0.025,0.955, ...
    red, ...
    FONT, ...
    FS_LETTER, ...
    FS_TITLE);

% Xi is the central PRESERVE coordinate:
% adaptive risk relative to the matched fixed-use comparator.
text( ...
    axA0, ...
    0.770,0.880, ...
    '$\Xi=[R_{\rm adaptive}-R_{\rm fixed}(\bar w)]/V$', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',8.5, ...
    'Color',purple);

local_summary_box( ...
    axA0, ...
    [0.575 0.740 0.390 0.115], ...
    purple, ...
    { ...
     sprintf('\\Xi > 0: %d/4',nXiPositive), ...
     sprintf('benefit \\rightarrow harm: %d/4',benefitToHarmN) ...
    }, ...
    FONT, ...
    7.7);

axA = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PA,[0.135 0.165 0.800 0.565]));

hold(axA,'on');

yline( ...
    axA,1,'--','Direct = 1', ...
    'Color',[0.38 0.38 0.38], ...
    'LineWidth',0.9, ...
    'LabelHorizontalAlignment','right', ...
    'LabelVerticalAlignment','bottom');

xA = 1:numel(u9bBudget);

% matched fixed -> adaptive connector
for i = 1:numel(xA)

    plot( ...
        axA, ...
        [xA(i) xA(i)], ...
        [u9bFixedRisk(i) u9bAdaptRisk(i)], ...
        '-', ...
        'Color',[0.68 0.68 0.68], ...
        'LineWidth',1.7, ...
        'HandleVisibility','off');

end

% fixed comparator
hFixed = scatter( ...
    axA, ...
    xA, ...
    u9bFixedRisk, ...
    74, ...
    's', ...
    'filled', ...
    'MarkerFaceColor',green, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.7);

% adaptive observer
hAdaptive = scatter( ...
    axA, ...
    xA, ...
    u9bAdaptRisk, ...
    78, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor',red, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.7);

% Label the adaptive-composition gap in the native Xi units.
for i = 1:numel(xA)

    text( ...
        axA, ...
        xA(i)+0.10, ...
        0.5*(u9bFixedRisk(i)+u9bAdaptRisk(i)), ...
        sprintf('\\Xi=%.3f',u9bXiRisk(i)), ...
        'Interpreter','tex', ...
        'FontName',FONT, ...
        'FontSize',8.0, ...
        'FontWeight','bold', ...
        'Color',purple);

end

yMinA = ...
    local_nanmin( ...
    [u9bFixedRisk(:);u9bAdaptRisk(:);1]);

yMaxA = ...
    local_nanmax( ...
    [u9bFixedRisk(:);u9bAdaptRisk(:);1]);

padA = ...
    max(0.02,0.12*(yMaxA-yMinA));

set( ...
    axA, ...
    'XLim',[0.55 4.45], ...
    'YLim',[yMinA-padA yMaxA+padA], ...
    'XTick',1:4, ...
    'XTickLabel',string(u9bBudget), ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.8, ...
    'Box','off');

xlabel( ...
    axA, ...
    'Audited outcomes, m', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axA, ...
    'Normalized risk, R/V', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

% text( ...
%     axA, ...
%     0.02,0.96, ...
%     'lower is better', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','left', ...
%     'VerticalAlignment','top', ...
%     'FontName',FONT, ...
%     'FontSize',FS_TINY, ...
%     'FontAngle','italic', ...
%     'Color',grey);

legend( ...
    axA, ...
    [hFixed hAdaptive], ...
    {'Matched fixed','Adaptive'}, ...
    'Location','southeast', ...
    'Box','off', ...
    'FontName',FONT, ...
    'FontSize',7.8);

%% ========================================================================
% PANEL B
% LOCKED CHALLENGE LIMITS MECHANISM GENERALITY
% ========================================================================

axB0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PB);

axis(axB0,[0 1 0 1]);
axis(axB0,'off');
hold(axB0,'on');

local_panel_border( ...
    axB0, ...
    [0.005 0.005 0.99 0.99], ...
    panelPurple, ...
    1.10);

local_panel_header( ...
    axB0, ...
    'B', ...
    'Locked testing limits mechanism generality', ...
    0.025,0.955, ...
    purple, ...
    FONT, ...
    FS_LETTER, ...
    FS_TITLE);

% Matrix layout
xCenters = [0.52 0.785];
yCenters = [0.585 0.350];

boxW = 0.205;
boxH = 0.145;

% Column labels
text( ...
    axB0, ...
    xCenters(1),0.760, ...
    'Role separation', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',dgrey);

text( ...
    axB0, ...
    xCenters(2),0.760, ...
    'Cross-fitting', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL, ...
    'FontWeight','bold', ...
    'Color',dgrey);

% Row labels
text( ...
    axB0, ...
    0.105,yCenters(1), ...
    'Georgia', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',green);

text( ...
    axB0, ...
    0.105,yCenters(2), ...
    'CPSC 2018', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',FS_SMALL+0.5, ...
    'FontWeight','bold', ...
    'Color',red);

for r = 1:2

    for c = 1:2

        val = lockedChecks(r,c);

        if r == 1
            face = lightGreen;
            edge = green;
            txtc = green;
        else
            face = lightRed;
            edge = red;
            txtc = red;
        end

        rectangle( ...
            axB0, ...
            'Position',[ ...
                xCenters(c)-boxW/2, ...
                yCenters(r)-boxH/2, ...
                boxW, ...
                boxH], ...
            'FaceColor',face, ...
            'EdgeColor',edge, ...
            'LineWidth',1.05);

        text( ...
            axB0, ...
            xCenters(c), ...
            yCenters(r), ...
            sprintf('%d/%d',val,lockedDenom), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontName',FONT, ...
            'FontSize',14, ...
            'FontWeight','bold', ...
            'Color',txtc);

    end

end

% Bottom scientific conclusion
text( ...
    axB0, ...
    0.50,0.135, ...
    'Mechanism generality not confirmed', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',FONT, ...
    'FontSize',11.3, ...
    'FontWeight','bold', ...
    'Color',red);



%% ========================================================================
% PANEL C
% COMPOSITION COST CAN BE LOCALIZED
% ========================================================================

axC0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PC);

axis(axC0,[0 1 0 1]);
axis(axC0,'off');
hold(axC0,'on');

local_panel_border( ...
    axC0, ...
    [0.005 0.005 0.99 0.99], ...
    panelPurple, ...
    1.10);

local_panel_header( ...
    axC0, ...
    'C', ...
    'Breaking pairing reduces composition cost', ...
    0.025,0.955, ...
    purple, ...
    FONT, ...
    FS_LETTER, ...
    FS_TITLE);

axC = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PC,[0.175 0.225 0.760 0.595]));

hold(axC,'on');

cVals = [Chac Cperm Chet];

bC = bar( ...
    axC, ...
    1:3, ...
    cVals, ...
    0.56, ...
    'FaceColor','flat', ...
    'EdgeColor','none');

bC.CData = [ ...
    red; ...
    purple; ...
    [0.60 0.44 0.76]];

yTopC = max(cVals)*1.27;

set( ...
    axC, ...
    'XLim',[0.45 3.55], ...
    'YLim',[0 yTopC], ...
    'XTick',1:3, ...
    'XTickLabel',{'Shared','Permuted','Role-separated'}, ...
    'FontName',FONT, ...
    'FontSize',FS_TICK-0.7, ...
    'TickDir','out', ...
    'LineWidth',0.8, ...
    'Box','off');

ylabel( ...
    axC, ...
    'Composition excess risk, C', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS-0.2);

for i = 1:3

    text( ...
        axC, ...
        i, ...
        cVals(i)+0.012, ...
        sprintf('%.3f',cVals(i)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontName',FONT, ...
        'FontSize',8.5, ...
        'FontWeight','bold', ...
        'Color',dgrey);

end

% 85.2% reduction annotation
yArrow = max(cVals)*1.17;

plot( ...
    axC, ...
    [1.15 1.85], ...
    [yArrow yArrow], ...
    '-', ...
    'Color',purple, ...
    'LineWidth',1.4);

plot( ...
    axC, ...
    1.85,yArrow, ...
    '>', ...
    'Color',purple, ...
    'MarkerFaceColor',purple, ...
    'MarkerSize',5.5);

text( ...
    axC, ...
    1.50, ...
    yArrow+0.008, ...
    sprintf('-%.1f%%',cReductionPct), ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontName',FONT, ...
    'FontSize',8.6, ...
    'FontWeight','bold', ...
    'Color',purple);

text( ...
    axC0, ...
    0.50,0.070, ...
    'post-completion diagnostic', ...
    'HorizontalAlignment','center', ...
    'FontName',FONT, ...
    'FontSize',FS_TINY, ...
    'FontAngle','italic', ...
    'Color',grey);

%% ========================================================================
% PANEL D
% ADAPTATION FRONTIER
% ========================================================================

axD0 = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',PD);

axis(axD0,[0 1 0 1]);
axis(axD0,'off');
hold(axD0,'on');

local_panel_border( ...
    axD0, ...
    [0.005 0.005 0.99 0.99], ...
    panelRed, ...
    1.10);

local_panel_header( ...
    axD0, ...
    'D', ...
    'Adaptation is worthwhile only when H > A + C', ...
    0.025,0.955, ...
    red, ...
    FONT, ...
    FS_LETTER, ...
    FS_TITLE);

axD = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position', ...
    local_relpos(PD,[0.115 0.175 0.760 0.675]));

hold(axD,'on');

limD = 1.18 * max([ ...
    Hhac, ...
    xShared, ...
    xPerm, ...
    xRole]);

% give a stable visual range
limD = max(limD,0.27);

% ---------------- background regions ----------------

% Above H = A + C:
% opportunity exceeds cost -> adaptation worthwhile
patch( ...
    axD, ...
    [0 0 limD], ...
    [0 limD limD], ...
    lightGreen, ...
    'EdgeColor','none', ...
    'HandleVisibility','off');

% Below H = A + C:
% cost exceeds opportunity -> fixed rule preferable
patch( ...
    axD, ...
    [0 limD limD], ...
    [0 0 limD], ...
    lightRed, ...
    'EdgeColor','none', ...
    'HandleVisibility','off');

% frontier
plot( ...
    axD, ...
    [0 limD], ...
    [0 limD], ...
    '--', ...
    'Color',[0.25 0.25 0.25], ...
    'LineWidth',1.15, ...
    'HandleVisibility','off');

% ---------------- shared -> permutation arrow ----------------

quiver( ...
    axD, ...
    xShared,Hhac, ...
    xPerm-xShared,0, ...
    0, ...
    'Color',purple, ...
    'LineWidth',1.45, ...
    'MaxHeadSize',0.34, ...
    'HandleVisibility','off');

% ---------------- points ----------------

scatter( ...
    axD, ...
    xShared,Hhac, ...
    92, ...
    'o', ...
    'filled', ...
    'MarkerFaceColor',red, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');

scatter( ...
    axD, ...
    xPerm,Hhac, ...
    86, ...
    's', ...
    'filled', ...
    'MarkerFaceColor',purple, ...
    'MarkerEdgeColor','w', ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');

scatter( ...
    axD, ...
    xRole,Hhac, ...
    94, ...
    '^', ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor',purple, ...
    'LineWidth',1.3, ...
    'HandleVisibility','off');

% ---------------- point labels ----------------
% Data coordinates are NOT moved. Only text labels are separated.

text( ...
    axD, ...
    xShared+0.008, ...
    Hhac-0.012, ...
    'shared', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',FONT, ...
    'FontSize',8.3, ...
    'FontWeight','bold', ...
    'Color',red);

% Permuted and role-separated points are numerically very close.
% Separate labels vertically while preserving the actual point locations.
text( ...
    axD, ...
    xPerm+0.004, ...
    Hhac+0.018, ...
    'permuted', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'FontName',FONT, ...
    'FontSize',8.3, ...
    'FontWeight','bold', ...
    'Color',purple);

text( ...
    axD, ...
    xRole+0.026, ...
    Hhac-0.013, ...
    'role-separated', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',FONT, ...
    'FontSize',7.7, ...
    'Color',purple);

% ---------------- theoretical regions ----------------

text( ...
    axD, ...
    0.055*limD, ...
    0.82*limD, ...
    {'adaptation worthwhile','H > A + C'}, ...
    'Interpreter','tex', ...
    'FontName',FONT, ...
    'FontSize',8.5, ...
    'FontWeight','bold', ...
    'Color',green);

text( ...
    axD, ...
    0.55*limD, ...
    0.16*limD, ...
    {'fixed rule preferable','H \leq A + C'}, ...
    'Interpreter','tex', ...
    'FontName',FONT, ...
    'FontSize',8.5, ...
    'FontWeight','bold', ...
    'Color',red);

% Label the theoretical frontier itself.
text( ...
    axD, ...
    0.60*limD, ...
    0.625*limD, ...
    'H = A + C', ...
    'Rotation',45, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontName',FONT, ...
    'FontSize',7.8, ...
    'FontWeight','bold', ...
    'Color',dgrey);
% compact theory values
text( ...
    axD, ...
    0.095*limD, ...
    0.055*limD, ...
    sprintf('H = %.3f     A = %.3f',Hhac,Ahac), ...
    'FontName',FONT, ...
    'FontSize',8.2, ...
    'Color',dgrey);

set( ...
    axD, ...
    'XLim',[0 limD], ...
    'YLim',[0 limD], ...
    'FontName',FONT, ...
    'FontSize',FS_TICK, ...
    'TickDir','out', ...
    'LineWidth',0.8, ...
    'Box','off');

axis(axD,'square');

xlabel( ...
    axD, ...
    'Allocation + composition,  A + C', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

ylabel( ...
    axD, ...
    'Heterogeneity opportunity,  H', ...
    'FontName',FONT, ...
    'FontSize',FS_AXIS);

%% ========================================================================
% 7) AUDIT PRINTOUT
% ========================================================================

fprintf('\n============================================================\n');
fprintf(' FIGURE 5 PRESERVE AUDIT\n');
fprintf('============================================================\n');

fprintf('\nU9B adaptive composability\n');
fprintf('Xi positive          = %d/4\n',nXiPositive);
fprintf('Benefit -> harm      = %d/4\n',benefitToHarmN);
fprintf('Xi closure residual  = %.3e pp\n',xiResidual);
fprintf('Normalized Xi residual = %.3e\n',xiRiskResidual);

fprintf('\nU10 locked prospective challenge\n');
fprintf('Georgia role-separation = 3/4\n');
fprintf('Georgia cross-fitting   = 3/4\n');
fprintf('CPSC role-separation    = 2/4\n');
fprintf('CPSC cross-fitting      = 2/4\n');
fprintf('Cohorts meeting criterion = %d/2\n',nCohortPassed);
fprintf('Generality = NOT CONFIRMED\n');

fprintf('\nU10 post-completion composition analysis\n');
fprintf('H = %.8f\n',Hhac);
fprintf('A = %.8f\n',Ahac);
fprintf('C shared      = %.8f\n',Chac);
fprintf('C permuted    = %.8f\n',Cperm);
fprintf('C role-sep    = %.8f\n',Chet);
fprintf('C reduction   = %.3f%%\n',cReductionPct);

fprintf('\nFrontier\n');
fprintf('Shared       H-(A+C) = %.8f\n',marginShared);
fprintf('Permuted     H-(A+C) = %.8f\n',marginPerm);
fprintf('Role-sep     H-(A+C) = %.8f\n',marginRole);

%% ========================================================================
% 8) EXPORT
% ========================================================================

drawnow;

figPath = fullfile( ...
    outputDir, ...
    'Figure5_InformationClosure_Composability_v8.fig');

pngPath = fullfile( ...
    outputDir, ...
    'Figure5_InformationClosure_Composability_v8.png');

pdfPath = fullfile( ...
    outputDir, ...
    'Figure5_InformationClosure_Composability_v8.pdf');

savefig(fig,figPath);

set(fig,'PaperPositionMode','auto');
set(fig,'PaperUnits','inches');

figPos = get(fig,'Position');

pageH = 8.0;
pageW = pageH*figPos(3)/figPos(4);

set(fig,'PaperSize',[pageW pageH]);
set(fig,'PaperPosition',[0 0 pageW pageH]);

print(fig,pngPath,'-dpng','-r600');
print(fig,pdfPath,'-dpdf','-painters','-bestfit');

fprintf('\nSaved:\n');
fprintf('%s\n',figPath);
fprintf('%s\n',pngPath);
fprintf('%s\n',pdfPath);

end


%% =========================================================================
% HELPERS
% =========================================================================

function pos = local_relpos(panelPos,rel)

pos = [ ...
    panelPos(1)+rel(1)*panelPos(3), ...
    panelPos(2)+rel(2)*panelPos(4), ...
    rel(3)*panelPos(3), ...
    rel(4)*panelPos(4)];

end


function local_panel_border(ax,pos,color,lineWidth)

rectangle( ...
    ax, ...
    'Position',pos, ...
    'FaceColor','none', ...
    'EdgeColor',color, ...
    'LineWidth',lineWidth);

end


function local_panel_header( ...
    ax,letter,titleText,x,y,color,fontName,fsLetter,fsTitle)

text( ...
    ax,x,y,letter, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsLetter, ...
    'FontWeight','bold', ...
    'Color',color);

text( ...
    ax,x+0.060,y,titleText, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontName',fontName, ...
    'FontSize',fsTitle, ...
    'FontWeight','bold', ...
    'Color',color);

end


function local_summary_box( ...
    ax,pos,color,lines,fontName,fontSize)

rectangle( ...
    ax, ...
    'Position',pos, ...
    'FaceColor','w', ...
    'EdgeColor',color, ...
    'LineWidth',0.85);

if ischar(lines) || isstring(lines)
    lines = cellstr(lines);
end

text( ...
    ax, ...
    pos(1)+pos(3)/2, ...
    pos(2)+pos(4)/2, ...
    lines, ...
    'Interpreter','tex', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',fontName, ...
    'FontSize',fontSize, ...
    'FontWeight','bold', ...
    'Color',color);

end


function local_require_vars(T,vars,sourceName)

missing = strings(0,1);

for i = 1:numel(vars)

    if ~ismember(vars{i},T.Properties.VariableNames)
        missing(end+1,1) = string(vars{i}); %#ok<AGROW>
    end

end

if ~isempty(missing)

    error( ...
        '%s missing variables: %s', ...
        sourceName, ...
        strjoin(cellstr(missing),', '));

end

end


function c = local_mix(c1,c2,alpha)

c = (1-alpha).*c1 + alpha.*c2;

end


function v = local_nanmean(x)

x = double(x(:));
x = x(isfinite(x));

if isempty(x)
    v = NaN;
else
    v = mean(x);
end

end


function v = local_nanmin(x)

x = double(x(:));
x = x(isfinite(x));

if isempty(x)
    v = NaN;
else
    v = min(x);
end

end


function v = local_nanmax(x)

x = double(x(:));
x = x(isfinite(x));

if isempty(x)
    v = NaN;
else
    v = max(x);
end

end


function repoRoot = local_find_cmdo_repo(scriptDir)

repoRoot = '';

starts = {scriptDir,pwd};

for s = 1:numel(starts)

    p = starts{s};

    for k = 1:8

        if isempty(p)
            break;
        end

        if ...
                isfolder(fullfile(p,'source_data')) && ...
                isfolder(fullfile(p,'U10_Prospective_ECG'))

            repoRoot = p;
            return;

        end

        parent = fileparts(p);

        if strcmp(parent,p)
            break;
        end

        p = parent;

    end

end

userHome = strtrim(getenv('USERPROFILE'));

if isempty(userHome)
    userHome = strtrim(getenv('HOME'));
end

if ~isempty(userHome)

    candidates = { ...
        fullfile(userHome,'CMDO-Reproducibility'), ...
        fullfile(userHome,'Documents','CMDO-Reproducibility'), ...
        fullfile(userHome,'Desktop','CMDO-Reproducibility')};

    for i = 1:numel(candidates)

        p = candidates{i};

        if ...
                isfolder(fullfile(p,'source_data')) && ...
                isfolder(fullfile(p,'U10_Prospective_ECG'))

            repoRoot = p;
            return;

        end

    end

end

end