function Figure4(outputDir)
%FIGURE4 Frozen observer confirmation across cross-domain and clinical transitions
% Compact revision of v5:
%   - smaller figure canvas and slightly smaller fonts
%   - panel e summary boxes moved to the right of each sub-panel
%   - panel f no longer stretched visually; main profile plot is narrower,
%     with summary box and legend separated on the right
%   - panel c uses an in-panel family legend; panel d keeps the outside group legend

close all;
rng(20260728,'twister');

%% Project and canonical records
scriptDir = fileparts(mfilename('fullpath'));
if ~isempty(scriptDir)
    addpath(genpath(scriptDir));
end

cfg = cmdo_config('Figure4');
D = cmdo_load_all(cfg);

%% ========================================================================
% Unified output path
% Same convention as the other new main-figure scripts:
% <folder containing Figure4.m>\output\
% ========================================================================

reviewerRoot = strtrim(getenv('CMDO_OUTPUT_ROOT'));

if nargin < 1 || isempty(outputDir)
    if ~isempty(reviewerRoot)
        outputDir = fullfile(reviewerRoot,'figures','main');
    else
        outputDir = cfg.outputDir;
    end
end

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

%% ========================================================================
% Shared U6 target-level data
% ========================================================================
U6raw = D.u6_target;

familyOrder = [ ...
    "ACS_PUBLIC_COVERAGE_2024", ...
    "MEDICAL_DERMOSCOPY", ...
    "NATURAL_IMAGE"];

familyLabels = { ...
    'Population transfer', ...
    'Medical acquisition shifts', ...
    'Natural-image shifts'};

familyColors = [ ...
    0.1216 0.4667 0.7059; ...
    1.0000 0.4980 0.0549; ...
    0.8392 0.1529 0.1569];

U6 = U6raw([],:);
for f = 1:numel(familyOrder)
    Tf = U6raw(string(U6raw.family)==familyOrder(f),:);
    rg = 100 .* double(Tf.gain_vs_full_direct) ./ double(Tf.direct_mae);
    [~,ord] = sort(rg,'descend');
    U6 = [U6; Tf(ord,:)]; %#ok<AGROW>
end

u6Names = strings(height(U6),1);
u6Colors = zeros(height(U6),3);
for i = 1:height(U6)
    u6Names(i) = f4f_short_target(string(U6.target(i)));
    fi = find(familyOrder==string(U6.family(i)),1,'first');
    u6Colors(i,:) = familyColors(fi,:);
end

u6Observer = double(U6.mae);
u6Direct = double(U6.direct_mae);
u6RelGain = 100 .* double(U6.gain_vs_full_direct) ./ u6Direct;

u6PooledObserver = mean(double(D.u6_state.mae),'omitnan');
u6PooledDirect = mean(double(D.u6_state.direct_mae),'omitnan');
u6PooledGain = 100 .* (u6PooledDirect-u6PooledObserver) ./ u6PooledDirect;

u6WorstState = max(double(D.u6_state.mae_regret_vs_full_direct),[],'omitnan');
u6MeanWeight = mean(double(D.u6_state.mean_weight),'omitnan');
u6MaxIdentity = max(double(D.u6_state.maximum_identity_residual),[],'omitnan');

familyNames = unique(string(U6raw.family),'stable');
familyRegret = nan(numel(familyNames),1);
for f = 1:numel(familyNames)
    m = string(U6raw.family)==familyNames(f);
    familyRegret(f) = mean(double(U6raw.mae(m)),'omitnan') ...
        - mean(double(U6raw.direct_mae(m)),'omitnan');
end
u6WorstFamily = max(familyRegret,[],'omitnan');

%% ========================================================================
% Shared U7 AUC / metric data
% ========================================================================
U7 = D.u7_target(string(D.u7_target.metric)=="AUC",:);
u7RelGain = 100 .* double(U7.gain) ./ double(U7.direct_mae);
[~,ord7] = sort(u7RelGain,'descend');
U7 = U7(ord7,:);
u7RelGain = u7RelGain(ord7);

u7Names = strings(height(U7),1);
for i = 1:height(U7)
    u7Names(i) = f4f_pretty_stratum(string(U7.stratum(i)));
end

u7Observer = double(U7.mae);
u7Direct = double(U7.direct_mae);

U7M = D.u7_metric;
mAUC = find(string(U7M.metric)=="AUC",1,'first');
if isempty(mAUC)
    error('Figure4Full:MissingU7AUC','AUC row absent in D.u7_metric.');
end

u7AUC = U7M(mAUC,:);
u7PooledGain = 100 .* double(u7AUC.relative_gain);
u7WorstState = double(u7AUC.worst_regret);
u7Coverage = double(u7AUC.coverage);
u7NoHarm = double(u7AUC.no_harm);

S7AUC = D.u7_state(string(D.u7_state.metric)=="AUC",:);
u7Weights = f4f_try_get_weight(S7AUC);
u7MeanWeight = mean(u7Weights,'omitnan');

stratumGroupNames = { ...
    'All eligible', ...
    'Race', ...
    'Sex', ...
    'Age', ...
    'Prior utilization', ...
    'Insulin', ...
    'Length of stay', ...
    'Diagnoses'};

stratumGroupColors = [ ...
    0.15 0.15 0.15; ...
    0.12 0.47 0.71; ...
    0.84 0.15 0.16; ...
    0.20 0.63 0.17; ...
    0.58 0.40 0.74; ...
    1.00 0.50 0.05; ...
    0.09 0.75 0.81; ...
    0.55 0.34 0.29];

%% ========================================================================
% Figure layout
% ========================================================================
fig = figure( ...
    'Position',[40 0 800 950], ...
    'Color','w', ...
    'Renderer','painters', ...
    'Name','CMDO Figure 4 - Frozen observer confirmation', ...
    'NumberTitle','off');

tl = tiledlayout(fig,4,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

title(tl, ...
    'Frozen observer confirmation across cross-domain and clinical transitions', ...
    'FontWeight','bold', ...
    'FontSize',15.2);

axA = nexttile(tl,1);
axB = nexttile(tl,2);
axC = nexttile(tl,3);
axD = nexttile(tl,4);
axEcontainer = nexttile(tl,5,[1 2]);
axFcontainer = nexttile(tl,7,[1 2]);

drawnow;

%% ========================================================================
% a — U6 same-budget profiles + relative reductions
% ========================================================================
hold(axA,'on');

yA = 1:height(U6);

maxMAE6 = max([u6Direct;u6Observer]);
minMAE6 = min([u6Direct;u6Observer]);

span6 = maxMAE6-minMAE6;

if ~isfinite(span6) || span6<=0
    span6 = max(maxMAE6,0.01);
end

for i = 1:height(U6)

    plot( ...
        axA, ...
        [u6Observer(i) u6Direct(i)], ...
        [i i], ...
        '-', ...
        'Color',[0.74 0.74 0.74], ...
        'LineWidth',0.95, ...
        'HandleVisibility','off');

    scatter( ...
        axA, ...
        u6Direct(i), ...
        i, ...
        30, ...
        'o', ...
        'MarkerFaceColor','w', ...
        'MarkerEdgeColor',[0.32 0.32 0.32], ...
        'LineWidth',0.75, ...
        'HandleVisibility','off');

    scatter( ...
        axA, ...
        u6Observer(i), ...
        i, ...
        38, ...
        'o', ...
        'filled', ...
        'MarkerFaceColor',u6Colors(i,:), ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.50, ...
        'HandleVisibility','off');

    text( ...
        axA, ...
        maxMAE6+0.05*span6, ...
        i, ...
        sprintf('%.2f%%',u6RelGain(i)), ...
        'FontSize',6.6, ...
        'FontWeight','bold', ...
        'VerticalAlignment','middle');

end

set(axA,'YDir','reverse');

yticks(axA,yA);
yticklabels(axA,u6Names);

ylim(axA,[0.5,height(U6)+1.5]);

xlim( ...
    axA, ...
    [ ...
    minMAE6-0.08*span6, ...
    maxMAE6+0.36*span6]);

xlabel(axA,'Same-budget AUC MAE');

title( ...
    axA, ...
    sprintf( ...
    'U6: all 16 unseen targets improved (pooled %.2f%%)', ...
    u6PooledGain), ...
    'FontWeight','bold', ...
    'FontSize',9.8);


hDirect = scatter( ...
    axA,NaN,NaN,30,'o', ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor',[0.32 0.32 0.32], ...
    'LineWidth',0.75);

hPop = scatter( ...
    axA,NaN,NaN,38,'o','filled', ...
    'MarkerFaceColor',familyColors(1,:), ...
    'MarkerEdgeColor','w');

hMed = scatter( ...
    axA,NaN,NaN,38,'o','filled', ...
    'MarkerFaceColor',familyColors(2,:), ...
    'MarkerEdgeColor','w');

hNat = scatter( ...
    axA,NaN,NaN,38,'o','filled', ...
    'MarkerFaceColor',familyColors(3,:), ...
    'MarkerEdgeColor','w');


legend( ...
    axA, ...
    [hDirect hPop hMed hNat], ...
    { ...
    'Full direct', ...
    'Observer: population', ...
    'Observer: medical', ...
    'Observer: natural'}, ...
    'Location','southoutside', ...
    'NumColumns',2, ...
    'Box','off', ...
    'FontSize',6.6);


set(axA,'XGrid','on','YGrid','off');
axA.GridAlpha = 0.10;

cmdo_safe_apply_axes_style(axA);

axA.YAxis.TickLabelInterpreter = 'none';
axA.FontSize = 6.7;


%% ========================================================================
% b — U7 same-budget profiles + relative reductions
% ========================================================================
hold(axB,'on');

yB = 1:height(U7);

maxMAE7 = max([u7Direct;u7Observer]);
minMAE7 = min([u7Direct;u7Observer]);

span7 = maxMAE7-minMAE7;

if ~isfinite(span7) || span7<=0
    span7 = max(maxMAE7,0.01);
end


for i = 1:height(U7)

    plot( ...
        axB, ...
        [u7Observer(i) u7Direct(i)], ...
        [i i], ...
        '-', ...
        'Color',[0.74 0.74 0.74], ...
        'LineWidth',0.95, ...
        'HandleVisibility','off');

    scatter( ...
        axB, ...
        u7Direct(i), ...
        i, ...
        30, ...
        'o', ...
        'MarkerFaceColor','w', ...
        'MarkerEdgeColor',[0.32 0.32 0.32], ...
        'LineWidth',0.75, ...
        'HandleVisibility','off');

    scatter( ...
        axB, ...
        u7Observer(i), ...
        i, ...
        38, ...
        's', ...
        'filled', ...
        'MarkerFaceColor',[0.18 0.55 0.32], ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.50, ...
        'HandleVisibility','off');

    text( ...
        axB, ...
        maxMAE7+0.05*span7, ...
        i, ...
        sprintf('%.2f%%',u7RelGain(i)), ...
        'FontSize',6.6, ...
        'FontWeight','bold', ...
        'VerticalAlignment','middle');

end


set(axB,'YDir','reverse');

yticks(axB,yB);
yticklabels(axB,u7Names);

ylim(axB,[0.5,height(U7)+1.5]);

xlim( ...
    axB, ...
    [ ...
    minMAE7-0.08*span7, ...
    maxMAE7+0.36*span7]);

xlabel(axB,'Same-budget AUC MAE');

title( ...
    axB, ...
    sprintf( ...
    'U7: all 16 clinical strata improved (pooled %.2f%%)', ...
    u7PooledGain), ...
    'FontWeight','bold', ...
    'FontSize',9.8);


hDirect7 = scatter( ...
    axB,NaN,NaN,30,'o', ...
    'MarkerFaceColor','w', ...
    'MarkerEdgeColor',[0.32 0.32 0.32], ...
    'LineWidth',0.75);

hObs7 = scatter( ...
    axB,NaN,NaN,38,'s','filled', ...
    'MarkerFaceColor',[0.18 0.55 0.32], ...
    'MarkerEdgeColor','w');


legend( ...
    axB, ...
    [hDirect7 hObs7], ...
    {'Full direct','Frozen observer'}, ...
    'Location','southoutside', ...
    'NumColumns',2, ...
    'Box','off', ...
    'FontSize',6.8);


set(axB,'XGrid','on','YGrid','off');
axB.GridAlpha = 0.10;

cmdo_safe_apply_axes_style(axB);

axB.YAxis.TickLabelInterpreter = 'none';
axB.FontSize = 6.7;


%% ========================================================================
% c — U6 bias observability
% ========================================================================
hold(axC,'on');


posC = axC.Position;

axC.Position = [ ...
    posC(1), ...
    posC(2), ...
    0.88*posC(3), ...
    posC(4)];


maxBudget6 = max(D.u6_state.budget);

M6 = D.u6_state( ...
    D.u6_state.budget==maxBudget6,:);


x6 = double(M6.mean_sensor_abs_gap);
y6 = double(M6.transport_abs_error);

fam6 = string(M6.family);


rho6 = f4f_spearman(x6,y6);
p6 = f4f_spearman_pvalue(rho6,numel(x6));


f4f_fit_band(axC,x6,y6);


hFam = gobjects(3,1);


for f = 1:3

    m = fam6==familyOrder(f);

    hFam(f) = scatter( ...
        axC, ...
        x6(m), ...
        y6(m), ...
        48, ...
        'o', ...
        'filled', ...
        'MarkerFaceColor',familyColors(f,:), ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.55, ...
        'DisplayName',familyLabels{f});

end


xlabel(axC,'Paired-sensor discrepancy');

ylabel(axC,'True transport absolute error');


title( ...
    axC, ...
    sprintf( ...
    'U6 bias observability (\\rho = %.3f)', ...
    rho6), ...
    'FontWeight','bold', ...
    'FontSize',9.7);


legend( ...
    axC, ...
    hFam, ...
    familyLabels, ...
    'Location','northwest', ...
    'Box','off', ...
    'FontSize',6.5);


set(axC,'XGrid','on','YGrid','on');

axC.GridAlpha = 0.10;

cmdo_safe_apply_axes_style(axC);

axC.FontSize = 6.8;


text( ...
    axC, ...
    0.98, ...
    0.05, ...
    sprintf( ...
    '\\rho = %.3f; nominal P = %.2g', ...
    rho6,p6), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',6.8, ...
    'FontWeight','bold', ...
    'BackgroundColor','w', ...
    'Margin',1.1);


%% ========================================================================
% d — U7 bias observability
% ========================================================================
hold(axD,'on');


posD = axD.Position;

axD.Position = [ ...
    posD(1), ...
    posD(2), ...
    0.71*posD(3), ...
    posD(4)];


maxBudget7 = max(S7AUC.budget);

M7 = S7AUC( ...
    S7AUC.budget==maxBudget7,:);


x7 = double(M7.mean_sensor_gap);
y7 = double(M7.transport_abs_error);

strata7 = string(M7.stratum);


rho7 = f4f_spearman(x7,y7);
p7 = f4f_spearman_pvalue(rho7,numel(x7));


f4f_fit_band(axD,x7,y7);


grp7 = zeros(numel(strata7),1);

for i = 1:numel(strata7)
    grp7(i) = f4f_stratum_group(strata7(i));
end


hG = gobjects(numel(stratumGroupNames),1);


for g = 1:numel(stratumGroupNames)

    m = grp7==g;

    hG(g) = scatter( ...
        axD, ...
        x7(m), ...
        y7(m), ...
        44, ...
        'o', ...
        'filled', ...
        'MarkerFaceColor',stratumGroupColors(g,:), ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.50, ...
        'DisplayName',stratumGroupNames{g});

end


xlabel(axD,'Paired-sensor discrepancy');

ylabel(axD,'Transport absolute error');


title( ...
    axD, ...
    sprintf( ...
    'U7 bias observability (\\rho = %.3f)', ...
    rho7), ...
    'FontWeight','bold', ...
    'FontSize',9.7);


lgdD = legend( ...
    axD, ...
    hG, ...
    stratumGroupNames, ...
    'Location','northwest', ...
    'Box','off', ...
    'FontSize',6.3);


drawnow;


lgdPos = lgdD.Position;

lgdD.Position = [ ...
    lgdPos(1), ...
    lgdPos(2)+0.018, ...
    lgdPos(3), ...
    lgdPos(4)];


set(axD,'XGrid','on','YGrid','on');

axD.GridAlpha = 0.10;

cmdo_safe_apply_axes_style(axD);

axD.FontSize = 6.8;


text( ...
    axD, ...
    0.98, ...
    0.05, ...
    sprintf( ...
    '\\rho = %.3f; nominal P = %.2g', ...
    rho7,p7), ...
    'Units','normalized', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',6.8, ...
    'FontWeight','bold', ...
    'BackgroundColor','w', ...
    'Margin',1.1);


%% ========================================================================
% e — two safety panels with each summary on its right
% ========================================================================
hold(axEcontainer,'on');

axis(axEcontainer,'off');


title( ...
    axEcontainer, ...
    'Safety and integrity across complete outcome-budget trajectories', ...
    'FontWeight','bold', ...
    'FontSize',10.6);


pE = axEcontainer.Position;


axE1 = axes( ...
    fig, ...
    'Position',[ ...
    pE(1)+0.05*pE(3), ...
    pE(2)+0.20*pE(4), ...
    0.29*pE(3), ...
    0.58*pE(4)], ...
    'Color','w');


axE2 = axes( ...
    fig, ...
    'Position',[ ...
    pE(1)+0.56*pE(3), ...
    pE(2)+0.20*pE(4), ...
    0.21*pE(3), ...
    0.58*pE(4)], ...
    'Color','w');


% ------------------------------------------------------------------------
% U6 safety
% ------------------------------------------------------------------------
hold(axE1,'on');


bud6 = sort(unique(double(D.u6_state.budget)))';


for j = 1:numel(bud6)

    b = bud6(j);

    v = double( ...
        D.u6_state.mae_regret_vs_full_direct( ...
        D.u6_state.budget==b));

    v = v(isfinite(v));


    f4f_violin( ...
        axE1, ...
        j, ...
        v, ...
        [1.00 0.62 0.20], ...
        0.32);


    scatter( ...
        axE1, ...
        j+0.035*randn(size(v)), ...
        v, ...
        12, ...
        'MarkerFaceColor',[0.96 0.52 0.06], ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.28);


    med = median(v,'omitnan');


    plot( ...
        axE1, ...
        [j-0.16 j+0.16], ...
        [med med], ...
        'k-', ...
        'LineWidth',1.5);

end


yline( ...
    axE1, ...
    0, ...
    '--', ...
    'Color',[0.15 0.45 0.95], ...
    'LineWidth',0.85);


xticks(axE1,1:numel(bud6));

xticklabels(axE1,string(bud6));


xlabel(axE1,'U6 verified-outcome budget');

ylabel(axE1,'Target-level AUC regret');


title( ...
    axE1, ...
    'U6 cross-domain reserve', ...
    'FontWeight','bold', ...
    'FontSize',8.6);


u6Min = min( ...
    double(D.u6_state.mae_regret_vs_full_direct), ...
    [], ...
    'omitnan');


ylim( ...
    axE1, ...
    [ ...
    min(-0.010,1.05*u6Min), ...
    0.0004]);


set(axE1,'XGrid','off','YGrid','on');

axE1.GridAlpha = 0.10;

cmdo_safe_apply_axes_style(axE1);

axE1.FontSize = 6.7;


summary6 = sprintf( ...
    ['Worst state  %.6f\n' ...
     'Worst family  %.6f\n' ...
     'Mean weight  %.4f\n' ...
     'Exact fallback residual  %.0g'], ...
    u6WorstState, ...
    u6WorstFamily, ...
    u6MeanWeight, ...
    u6MaxIdentity);


annotation( ...
    fig, ...
    'textbox', ...
    [ ...
    pE(1)+0.36*pE(3), ...
    pE(2)+0.30*pE(4), ...
    0.11*pE(3), ...
    0.16*pE(4)], ...
    'String',summary6, ...
    'FitBoxToText','on', ...
    'BackgroundColor','none', ...
    'EdgeColor','none', ...
    'LineStyle','none', ...
    'Margin',0, ...
    'FontSize',6.8, ...
    'Interpreter','none');


% ------------------------------------------------------------------------
% U7 safety
% ------------------------------------------------------------------------
hold(axE2,'on');


bud7 = sort(unique(double(S7AUC.budget)))';

meanWByBudget = nan(numel(bud7),1);


for j = 1:numel(bud7)

    b = bud7(j);


    v = double( ...
        S7AUC.regret( ...
        S7AUC.budget==b));

    v = v(isfinite(v));


    f4f_violin( ...
        axE2, ...
        j, ...
        v, ...
        [1.00 0.62 0.20], ...
        0.32);


    scatter( ...
        axE2, ...
        j+0.035*randn(size(v)), ...
        v, ...
        12, ...
        'MarkerFaceColor',[0.96 0.52 0.06], ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.28);


    med = median(v,'omitnan');


    plot( ...
        axE2, ...
        [j-0.16 j+0.16], ...
        [med med], ...
        'k-', ...
        'LineWidth',1.5);


    if ~isempty(u7Weights)

        meanWByBudget(j) = mean( ...
            u7Weights(S7AUC.budget==b), ...
            'omitnan');

    end

end


yline( ...
    axE2, ...
    0, ...
    '--', ...
    'Color',[0.15 0.45 0.95], ...
    'LineWidth',0.85);


xticks(axE2,1:numel(bud7));

xticklabels(axE2,string(bud7));


xlabel(axE2,'U7 verified-outcome budget');

ylabel(axE2,'Stratum-level AUC regret');


title( ...
    axE2, ...
    'U7 clinical transition', ...
    'FontWeight','bold', ...
    'FontSize',8.6);


u7Min = min( ...
    double(S7AUC.regret), ...
    [], ...
    'omitnan');


ylim( ...
    axE2, ...
    [ ...
    min(-0.006,1.05*u7Min), ...
    0.0004]);


set(axE2,'XGrid','off','YGrid','on');

axE2.GridAlpha = 0.10;

cmdo_safe_apply_axes_style(axE2);

axE2.FontSize = 6.7;


% ------------------------------------------------------------------------
% U7 mean-weight inset
% ------------------------------------------------------------------------
axE2Inset = axes( ...
    fig, ...
    'Position',[ ...
    pE(1)+0.82*pE(3), ...
    pE(2)+0.53*pE(4), ...
    0.14*pE(3), ...
    0.18*pE(4)], ...
    'Color','w');


hold(axE2Inset,'on');


plot( ...
    axE2Inset, ...
    1:numel(bud7), ...
    meanWByBudget, ...
    '-o', ...
    'Color',[0.45 0.25 0.75], ...
    'MarkerFaceColor',[0.45 0.25 0.75], ...
    'LineWidth',1.0, ...
    'MarkerSize',3.2);


xticks(axE2Inset,1:numel(bud7));

xticklabels( ...
    axE2Inset, ...
    compose('2^{%d}',round(log2(bud7))));


title( ...
    axE2Inset, ...
    'Mean transport weight', ...
    'FontWeight','bold', ...
    'FontSize',6.1);


set( ...
    axE2Inset, ...
    'FontName','Arial', ...
    'FontSize',5.4, ...
    'Box','on', ...
    'XGrid','on', ...
    'YGrid','on');


summary7 = sprintf( ...
    ['Worst state  %.6f\n' ...
     'Coverage / geometry  %.3f / %.3f\n' ...
     'Mean weight  %.4f'], ...
    u7WorstState, ...
    u7Coverage, ...
    u7NoHarm, ...
    u7MeanWeight);


annotation( ...
    fig, ...
    'textbox', ...
    [ ...
    pE(1)+0.80*pE(3), ...
    pE(2)+0.26*pE(4), ...
    0.14*pE(3), ...
    0.15*pE(4)], ...
    'String',summary7, ...
    'FitBoxToText','on', ...
    'BackgroundColor','none', ...
    'EdgeColor','none', ...
    'LineStyle','none', ...
    'Margin',0, ...
    'FontSize',6.8, ...
    'Interpreter','none');


%% ========================================================================
% f — narrower main profile plot with right-side summary and legend
% ========================================================================
hold(axFcontainer,'on');

axis(axFcontainer,'off');


title( ...
    axFcontainer, ...
    'Cross-reserve and bounded-metric performance profile', ...
    'FontWeight','bold', ...
    'FontSize',10.6);


pF = axFcontainer.Position;


axF = axes( ...
    fig, ...
    'Position',[ ...
    pF(1)+0.05*pF(3), ...
    pF(2)+0.4*pF(4), ...
    0.44*pF(3), ...
    0.60*pF(4)], ...
    'Color','w');


hold(axF,'on');


metricOrder = [ ...
    "SENSITIVITY", ...
    "SPECIFICITY", ...
    "AUC", ...
    "BALANCED_ACCURACY", ...
    "BRIER_UTILITY"];


labelsF = { ...
    'U6 AUC', ...
    'U7 sensitivity', ...
    'U7 specificity', ...
    'U7 AUC', ...
    'U7 balanced accuracy', ...
    'U7 Brier utility'};


gainF = nan(6,1);
worstF = nan(6,1);


gainF(1) = u6PooledGain;
worstF(1) = u6WorstState;


for k = 1:numel(metricOrder)

    idx = find( ...
        string(U7M.metric)==metricOrder(k), ...
        1, ...
        'first');


    if isempty(idx)

        error( ...
            'Figure4Full:MissingMetric', ...
            'Missing U7 metric: %s', ...
            char(metricOrder(k)));

    end


    gainF(k+1) = ...
        100 .* double(U7M.relative_gain(idx));


    worstF(k+1) = ...
        double(U7M.worst_regret(idx));

end


safeColor = [0.20 0.68 0.38];
tailColor = [0.97 0.58 0.15];


yF = 1:6;


for k = 1:6

    plot( ...
        axF, ...
        [0 gainF(k)], ...
        [k k], ...
        '-', ...
        'Color',[0.74 0.74 0.74], ...
        'LineWidth',1.10, ...
        'HandleVisibility','off');


    c = tailColor;

    if worstF(k)<=0
        c = safeColor;
    end


    mk = 's';
    mks = 66;


    if k==1
        mk = 'o';
        mks = 72;
    end


    scatter( ...
        axF, ...
        gainF(k), ...
        k, ...
        mks, ...
        mk, ...
        'filled', ...
        'MarkerFaceColor',c, ...
        'MarkerEdgeColor','w', ...
        'LineWidth',0.65, ...
        'HandleVisibility','off');


    text( ...
        axF, ...
        gainF(k)+0.09, ...
        k, ...
        sprintf('%.2f%%',gainF(k)), ...
        'FontWeight','bold', ...
        'FontSize',7.6, ...
        'VerticalAlignment','middle');


    text( ...
        axF, ...
        5.9, ...
        k, ...
        sprintf( ...
        'worst regret %s', ...
        f4f_fmt_regret(worstF(k))), ...
        'FontSize',7.0, ...
        'VerticalAlignment','middle');

end


set(axF,'YDir','reverse');


yticks(axF,yF);

yticklabels(axF,labelsF);


xlabel( ...
    axF, ...
    'Relative pooled MAE reduction (%)');


xlim(axF,[0,8.0]);

ylim(axF,[0.4,6.6]);


set(axF,'XGrid','on','YGrid','off');

axF.GridAlpha = 0.10;


cmdo_safe_apply_axes_style(axF);


axF.YAxis.TickLabelInterpreter = 'none';

axF.FontSize = 6.9;


% ------------------------------------------------------------------------
% Right-side summary text
% ------------------------------------------------------------------------

nSafe = nnz(worstF<=0);
nPositive = nnz(worstF>0);


profileText = sprintf( ...
    ['Profiles evaluated: %d\n' ...
     'Positive pooled gain: %d/%d\n' ...
     'Non-positive observed worst regret: %d/%d\n' ...
     'Positive worst-regret profiles: %d/%d\n' ...
     'Gain range: %.2f%% to %.2f%%'], ...
    numel(gainF), ...
    nnz(gainF>0), ...
    numel(gainF), ...
    nSafe, ...
    numel(gainF), ...
    nPositive, ...
    numel(gainF), ...
    min(gainF), ...
    max(gainF));


annotation( ...
    fig, ...
    'textbox', ...
    [ ...
    pF(1)+0.54*pF(3), ...
    pF(2)+0.6*pF(4), ...
    0.17*pF(3), ...
    0.22*pF(4)], ...
    'String',profileText, ...
    'FitBoxToText','on', ...
    'BackgroundColor','none', ...
    'EdgeColor','none', ...
    'LineStyle','none', ...
    'Margin',0, ...
    'FontSize',6.9, ...
    'Interpreter','none');


% ------------------------------------------------------------------------
% Right-side legend
% ------------------------------------------------------------------------

hSafe = plot( ...
    axF,NaN,NaN,'s', ...
    'MarkerSize',7, ...
    'MarkerFaceColor',safeColor, ...
    'MarkerEdgeColor',safeColor);


hTail = plot( ...
    axF,NaN,NaN,'s', ...
    'MarkerSize',7, ...
    'MarkerFaceColor',tailColor, ...
    'MarkerEdgeColor',tailColor);


hU6 = plot( ...
    axF,NaN,NaN,'o', ...
    'MarkerSize',6.8, ...
    'MarkerFaceColor',[0.30 0.30 0.30], ...
    'MarkerEdgeColor',[0.30 0.30 0.30]);


hU7 = plot( ...
    axF,NaN,NaN,'s', ...
    'MarkerSize',6.8, ...
    'MarkerFaceColor',[0.30 0.30 0.30], ...
    'MarkerEdgeColor',[0.30 0.30 0.30]);


legend( ...
    axF, ...
    [hSafe hTail hU6 hU7], ...
    { ...
    'Worst regret \le 0', ...
    'Positive worst regret', ...
    'U6 AUC', ...
    'U7 metric'}, ...
    'Position',[ ...
    pF(1)+0.80*pF(3), ...
    pF(2)+0.6*pF(4), ...
    0.15*pF(3), ...
    0.18*pF(4)], ...
    'Box','off', ...
    'FontSize',6.5);


%% ========================================================================
% Audit prints
% ========================================================================

fprintf('\nFigure 4 frozen-observer confirmation audit:\n');

fprintf( ...
    '  U6 targets / improved = %d / %d\n', ...
    height(U6), ...
    nnz(u6RelGain>0));

fprintf( ...
    '  U7 strata / improved = %d / %d\n', ...
    height(U7), ...
    nnz(u7RelGain>0));

fprintf( ...
    '  U6 pooled observer/direct/gain = %.9f / %.9f / %.6f%%\n', ...
    u6PooledObserver, ...
    u6PooledDirect, ...
    u6PooledGain);

fprintf( ...
    '  U7 pooled AUC gain = %.6f%%\n', ...
    u7PooledGain);

fprintf( ...
    '  U6 rho / nominal p = %.9f / %.6g\n', ...
    rho6,p6);

fprintf( ...
    '  U7 rho / nominal p = %.9f / %.6g\n', ...
    rho7,p7);

fprintf( ...
    '  U6 worst state / family / mean weight / identity = %.9f / %.9f / %.9f / %.3g\n', ...
    u6WorstState, ...
    u6WorstFamily, ...
    u6MeanWeight, ...
    u6MaxIdentity);

fprintf( ...
    '  U7 worst state / coverage / geometry / mean weight = %.9f / %.6f / %.6f / %.9f\n', ...
    u7WorstState, ...
    u7Coverage, ...
    u7NoHarm, ...
    u7MeanWeight);

fprintf( ...
    '  Profile gains = %s\n', ...
    sprintf('%.3f%% ',gainF));

fprintf( ...
    '  Profile worst regrets = %s\n', ...
    sprintf('%.6g ',worstF));


%% ========================================================================
% Unified panel labels
% ========================================================================

drawnow;


f4f_panel_label( ...
    fig,axA,'a',-0.030,-0.008);

f4f_panel_label( ...
    fig,axB,'b',-0.030,-0.008);

f4f_panel_label( ...
    fig,axC,'c',-0.030,0.006);

f4f_panel_label( ...
    fig,axD,'d',-0.030,0.006);

f4f_panel_label( ...
    fig,axEcontainer,'e',-0.030,0.006);

f4f_panel_label( ...
    fig,axFcontainer,'f',-0.030,0.006);


drawnow;


%% ========================================================================
% Export using the same convention as the other new main figures
% ========================================================================

drawnow;

baseName = 'Figure4_Frozen_Observer_Confirmation';

exportgraphics( ...
    fig, ...
    fullfile(outputDir,[baseName '.png']), ...
    'Resolution',300, ...
    'BackgroundColor','white');

exportgraphics( ...
    fig, ...
    fullfile(outputDir,[baseName '.pdf']), ...
    'ContentType','vector', ...
    'BackgroundColor','white');

try
    exportgraphics( ...
        fig, ...
        fullfile(outputDir,[baseName '.svg']), ...
        'ContentType','vector', ...
        'BackgroundColor','white');
catch
end

savefig( ...
    fig, ...
    fullfile(outputDir,[baseName '.fig']));

fprintf('\nFinal Figure 4 written to:\n%s\n',outputDir);

end




%% ========================================================================
% Helpers
% ========================================================================

function label = f4f_short_target(target)

target = string(target);

switch target

    case "ACS_PUBLIC_COVERAGE_2024_FL"
        label = "ACS-FL";

    case "ACS_PUBLIC_COVERAGE_2024_IL"
        label = "ACS-IL";

    case "ACS_PUBLIC_COVERAGE_2024_OH"
        label = "ACS-OH";

    case "ACS_PUBLIC_COVERAGE_2024_PA"
        label = "ACS-PA";

    case "ACS_PUBLIC_COVERAGE_2024_TX"
        label = "ACS-TX";

    case "DERMA_CLEAN"
        label = "Derma clean";

    case "DERMA_NOISE_0_08"
        label = "Derma noise";

    case "DERMA_BLUR_1_0"
        label = "Derma blur";

    case "DERMA_GAMMA_1_4"
        label = "Derma gamma";

    case "DERMA_JPEG_35"
        label = "Derma JPEG";

    case "DERMA_DOWNSAMPLE_14"
        label = "Derma downsample";

    case "CIFAR_CAT_DOG_CLEAN"
        label = "CIFAR clean";

    case "CIFAR_CAT_DOG_GRAYSCALE"
        label = "CIFAR grayscale";

    case "CIFAR_CAT_DOG_NOISE_0_10"
        label = "CIFAR noise";

    case "CIFAR_CAT_DOG_BLUR_1_2"
        label = "CIFAR blur";

    case "CIFAR_CAT_DOG_JPEG_30"
        label = "CIFAR JPEG";

    otherwise
        label = replace(target,"_"," ");

end

end


function out = f4f_pretty_stratum(s)

s = upper(string(s));

switch s

    case "ALL"
        out = "All eligible";

    case "ER_RACE_AFRICAN_AMERICAN"
        out = "African American";

    case "ER_RACE_CAUCASIAN"
        out = "Caucasian";

    case "ER_FEMALE"
        out = "Female";

    case "ER_MALE"
        out = "Male";

    case "ER_INSULIN_ACTIVE"
        out = "Insulin active";

    case "ER_INSULIN_NONE"
        out = "No insulin";

    case "ER_PRIOR_UTILIZATION_POSITIVE"
        out = "Prior use +";

    case "ER_PRIOR_UTILIZATION_ZERO"
        out = "Prior use 0";

    case "ER_AGE_LT50"
        out = "Age <50";

    case "ER_AGE_GE50"
        out = "Age 50-69";

    case "ER_AGE_GE70"
        out = "Age >=70";

    case "ER_SHORT_STAY_LE4"
        out = "Stay <=4 d";

    case "ER_LONG_STAY_GE5"
        out = "Stay >=5 d";

    case "ER_DIAGNOSES_GE7"
        out = "Diagnoses >=7";

    case "ER_DIAGNOSES_LE6"
        out = "Diagnoses <=6";

    otherwise
        out = replace(string(s),"_"," ");

end

end


function g = f4f_stratum_group(s)

s = upper(string(s));


if s == "ALL"

    g = 1;

elseif contains(s,"RACE")

    g = 2;

elseif any(s == ["ER_FEMALE","ER_MALE"])

    g = 3;

elseif contains(s,"AGE")

    g = 4;

elseif contains(s,"PRIOR_UTILIZATION")

    g = 5;

elseif contains(s,"INSULIN")

    g = 6;

elseif contains(s,"STAY")

    g = 7;

elseif contains(s,"DIAGNOSES")

    g = 8;

else

    g = 1;

end

end


function rho = f4f_spearman(x,y)

x = double(x(:));
y = double(y(:));


m = isfinite(x) & isfinite(y);

x = x(m);
y = y(m);


rx = f4f_tied_rank(x);
ry = f4f_tied_rank(y);


rx = rx-mean(rx);
ry = ry-mean(ry);


den = sqrt(sum(rx.^2).*sum(ry.^2));


if den<=0

    rho = NaN;

else

    rho = sum(rx.*ry)./den;

end

end


function p = f4f_spearman_pvalue(rho,n)

if n<=2 || ~isfinite(rho)

    p = NaN;
    return;

end


rho = max(min(rho,1-eps),-1+eps);

df = n-2;


t = abs(rho).*sqrt( ...
    df./(1-rho.^2));


z = df./(df+t.^2);


p = betainc( ...
    z, ...
    df/2, ...
    0.5);

end


function r = f4f_tied_rank(v)

v = double(v(:));

n = numel(v);


[sv,ord] = sort(v,'ascend');


r = zeros(n,1);


i = 1;


while i<=n

    j = i;

    while j<n && sv(j+1)==sv(i)
        j = j+1;
    end


    r(ord(i:j)) = 0.5*(i+j);

    i = j+1;

end

end


function f4f_fit_band(ax,x,y)

x = double(x(:));
y = double(y(:));


m = isfinite(x) & isfinite(y);

x = x(m);
y = y(m);


n = numel(x);


if n<3
    return;
end


X = [ones(n,1),x];

beta = X\y;


xg = linspace(min(x),max(x),220)';

yg = beta(1)+beta(2).*xg;


res = y-X*beta;


df = max(n-2,1);


s2 = sum(res.^2)./df;


xm = mean(x);

sxx = sum((x-xm).^2);


if ~isfinite(sxx) || sxx<=0
    sxx = eps;
end


se = sqrt( ...
    s2 .* ...
    (1/n+(xg-xm).^2./sxx));


tc = f4f_tcritical95(df);


lo = yg-tc.*se;

hi = yg+tc.*se;


fill( ...
    ax, ...
    [xg;flipud(xg)], ...
    [lo;flipud(hi)], ...
    [0.72 0.72 0.72], ...
    'FaceAlpha',0.22, ...
    'EdgeColor','none', ...
    'HandleVisibility','off');


plot( ...
    ax, ...
    xg, ...
    yg, ...
    'k-', ...
    'LineWidth',1.35, ...
    'HandleVisibility','off');

end


function tcrit = f4f_tcritical95(df)

if df<=0

    tcrit = 1.96;
    return;

end


b = betaincinv( ...
    0.05, ...
    df/2, ...
    0.5);


tcrit = sqrt( ...
    df.*(1-b)./b);

end


function f4f_violin(ax,x0,v,faceColor,halfWidth)

v = double(v(:));

v = v(isfinite(v));


if numel(v)<2
    return;
end


vmin = min(v);
vmax = max(v);


if vmax<=vmin

    vmin = vmin-1e-6;
    vmax = vmax+1e-6;

end


gridY = linspace(vmin,vmax,180)';


sigma = std(v,0);


bw = ...
    1.06 ...
    * sigma ...
    * numel(v)^(-1/5);


if ~isfinite(bw) || bw<=0

    bw = max( ...
        (vmax-vmin)/20, ...
        eps);

end


z = ...
    (gridY-v') ...
    ./ bw;


density = ...
    mean(exp(-0.5*z.^2),2) ...
    ./ (bw*sqrt(2*pi));


m = max(density);


if ~isfinite(m) || m<=0
    return;
end


w = halfWidth*density./m;


patch( ...
    ax, ...
    [x0-w;flipud(x0+w)], ...
    [gridY;flipud(gridY)], ...
    faceColor, ...
    'FaceAlpha',0.24, ...
    'EdgeColor',faceColor*0.82, ...
    'LineWidth',0.50, ...
    'HandleVisibility','off');

end


function w = f4f_try_get_weight(T)

cands = { ...
    'mean_weight', ...
    'transport_weight', ...
    'weight', ...
    'w', ...
    'mean_transport_weight'};


w = [];


for i = 1:numel(cands)

    if ismember( ...
            cands{i}, ...
            T.Properties.VariableNames)

        w = double(T.(cands{i}));
        return;

    end

end

end


function s = f4f_fmt_regret(v)

if ~isfinite(v)

    s = 'NaN';

elseif abs(v)>=1e-3

    s = sprintf('%+.4f',v);

elseif abs(v)>=1e-5

    s = sprintf('%+.2g',v);

else

    s = sprintf('%+.1e',v);

end

end


function f4f_panel_label(fig,ax,letter,dx,dy)

if nargin < 4 || isempty(dx)
    dx = -0.030;
end


if nargin < 5 || isempty(dy)
    dy = 0.006;
end


pos = ax.Position;


annotation( ...
    fig, ...
    'textbox', ...
    [ ...
    pos(1)+dx, ...
    pos(2)+pos(4)+dy+0.005, ...
    0.028, ...
    0.028], ...
    'String',letter, ...
    'LineStyle','none', ...
    'FitBoxToText','off', ...
    'Margin',0, ...
    'FontWeight','bold', ...
    'FontSize',17, ...
    'Interpreter','none', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top');

end
